README.md
start.py
tracee/container_event_monitor_ebpf.c
tracee/container_tracer.py

Trace system events by choosing system mode (the new default),
or container events by choosing container mode

Add system tracing mode

---

Dockerfile
entrypoint.sh

assuming linux headers are present on the host and mounted in as well as debugfs
related: #20

add dockerfile

---

tracee/tracer.py

fix: https://github.com/aquasecurity/tracee/pull/27#discussion_r361160871

catch keyboard interrupt

---

main.go
tracee/consts.go
tracee/tracee.go

migration of https://github.com/aquasecurity/tracee/pull/42 to go

implement show-exec-env in go

---

tracee/consts.go
tracee/tracee.go

migration of https://github.com/aquasecurity/tracee/pull/46 to go

add bprm_check event

---

tracee/printer.go
tracee/tracee.go

see: https://github.com/aquasecurity/tracee/issues/49

show stats in table epilogue

---

tracee/consts.go

https://github.com/aquasecurity/tracee/pull/56 added some sys events to trace but didn't update the table size

fix list command to show recent additions

---

Dockerfile

update the docker file to build and use the go version of tracee
also, find a better solution to install bcc in the container, since the packages are out of date and doesn't work with latest gobpf
closes: https://github.com/aquasecurity/tracee/issues/20

update dockerfile to go

---

README.md
main.go
start.py

and touch up the relevant readme section

rename events-to-trace flag to event

---

tracee/printer.go

change printed time resolution from seconds to microseconds

---

tracee/tracee.go

don't show raw_syscalls by default

---

tracee/printer.go
tracee/tracee.go

in a future PR I will add a second "output" file for tracee to communicate errors and meta information, this will be required to report stats in gob

refactor stats collection and printing

---

tracee/tracee.go

fix: https://github.com/aquasecurity/tracee/issues/128

fix lost event counter

---

tracee/tracee.go

fix: https://github.com/aquasecurity/tracee/issues/141

don't capture same exec twice

---

tracee/argprinters.go

Fix chmod invalid file

---

main.go
tracee/consts.go
tracee/tracee.go

Remove global EventNameToID map

---

tracee/pipeline.go
tracee/tracee.go

In order to achieve better performance, and as a preparation for the
addition of plugins, handle events in a pipeline

Handle events in a pipeline

---

tracee/pipeline.go
tracee/tracee.go

Don't print raw_syscall if event exists

---

tracee/printer.go

instead of 2 arrays: names and values which are linked using the index, have 1 array with a name/value pair for each arg

improve output of args

---

tracee/event_monitor_ebpf.c

Save container pids in the container pid namespace when in host mode

Save host and container pids in host mode

---

tracee/tracee.go

This PR fixes "capture exec" when used with containers.
As conatiners mount ns is different, we reach the path using /proc/pid/ns
In order to avoid race conditions when a process dies before we copy the executable, we use the first ancestor of the process with the same mount namespace
Note: this solution doesn't work when another unshare namespace happens (for example, when cloning another process with NEW_NS). This may be fixed in a future PR
resolves #179

Fix capture exec for containers

---

README.md
tracee/printer.go
tracee/tracee.go

add host pids to container mode, remove unneeded columns from non-verbose, improve width of pid columns

improve table output

---

tracee/consts.go
tracee/event_monitor_ebpf.c
tracee/tracee.go

Add 32bit syscalls support

---

main.go
tracee/tracee.go

add flag to clear the output dir before running
(I think output dir is better name than output path)

clear output dir

---

README.md

Added below badges:
- Github release
- Go Report Card
- GitHub License
- Docker pulls count

chore(docs): Added badges in README.md file

---

tracee/event_monitor_ebpf.c

Verifier in 4.14 has some issues which were fixed in 4.15.
Satisfy 4.14 verifier to be happy...

Fix broken kernel 4.14 support

---

README.md
main.go
tracee/consts.go
tracee/event_monitor_ebpf.c
tracee/tracee.go

Replaces PR https://github.com/aquasecurity/tracee/pull/265 as  this was quicker than undoing that bad rebase.
Discussion: https://github.com/aquasecurity/tracee/issues/221

Additional tracing modes

---

tracee/tracee.go

fix https://github.com/aquasecurity/tracee/issues/258

fix sockaddr_in parsing

---

bpfwrap/libbpf_wrapper.go
tracee/tracee.go

we don't have use for this now but I already wrote this code for something else, and if we think of this library as a generic libbpf wrapper, why not add

add new module creation from buffer to bpfwrap

---

Makefile
main.go
tracee/tracee.bpf.c
tracee/tracee.go

search for bpf obj file in predefined locations, also customizable
built the obj file if it's not found, and install it in a permanent location in the system
This is still draft because I still need to embed the libbpf and extra header files instead of expecting to find them locally

bpf object build and discovery

---

Makefile

`cp` doesn't touch the `mtime` on `BPF_BUNDLE_DIR` therefore `make` didn't detect a change in `tracee.bpf.c`. I think having this `BPF_BUNDLE_DIR` as a top level artifact is not needed anyway so made it an implementation detail of `BPF_BUNDLE` which also fixes that issue

fix makefile dependency

---

Makefile

1. in some cases the `/lib/modules/$version/build will be a symlink which is useless in docker, so try to follow it. for example on ubuntu it's a symlink to `/usr/src/$version` and on manjaro it's not a symlink. so we follow the symlink if needed.
2. in some cases the kernel headers will symlink to a directories outside it's tree, which is not reachable in docker if not mounted, so we mount the parent directory. for example, on ubuntu `/usr/src/linux-headers-5.3.0-40-generic/include/` has links to `/usr/src/liunx-headers-5.3.0-40/...` so we mount `/usr/src`.
this is NOT fail proof but good enough for most common cases. otherwise, user can override these vars with their values value, or just mount `/` and adjust `KERN_SRC` accordingly

fix kernel headers defaults in other distros

---

README.md
main.go
tracee/consts.go
tracee/tracee.bpf.c

Add host only mode

---

Makefile
README.md
main.go

Split kernel headers to source and build

---

main.go

Use more informative error when making bpf object fails

---

go.sum
main.go
main_test.go
tracee/consts.go
tracee/tracee.bpf.c
tracee/tracee.go

- Add filter comparison operators (still just UIDs supported)
- Add tests in main_test.go
Relevant issue: #328

Add the ability to specify filters (such as by UID) using comparison operators (=, !=, >, <).

---

libbpfgo/libbpfgo.go
main.go
main_test.go
tracee/consts.go
tracee/tracee.bpf.c
tracee/tracee.go

Add UTS and COMM filters

---

tracee/tracee.bpf.c

Fix execve pointer errors

---

README.md
main.go

Set TRACEE_BPF_FILE to point to a file instead of a dir

---

main.go
main_test.go
tracee/consts.go
tracee/tracee.bpf.c
tracee/tracee.go

Move trace specific pids to filter flag

---

main.go
tracee/consts.go
tracee/tracee.go

Fix event listing

---

Makefile

test files are included in `GO_SRC`

remove redundant var

---

tracee-rules/signatures/golang/anti_debugging_ptraceme.go
tracee-rules/signatures/golang/code_injection.go
tracee-rules/signatures/golang/code_injection_test.go
tracee-rules/signatures/golang/helpers.go

add code injection signature

---

tracee-rules/signatures/golang/code_injection.go
tracee-rules/signatures/golang/example.go
tracee-rules/types/types.go

simplify finding data

---

main.go
tracee/consts.go

This commit provides the ability to display the system calls arguments when tracee runs with --list flag. #398

Issue-398 add arguments to events

---

main.go
main_test.go
tracee/tracee.go

Add support for filtering an event by its argument

---

libbpfgo/libbpfgo.go

As Discussed in https://github.com/aquasecurity/tracee/pull/375#issuecomment-760721374

added 'DeleteKey' and 'GetValue' to 'libbpfgo'

---

main.go
main_test.go
tracee/tracee.bpf.c
tracee/tracee.go

Change capture ux

---

main.go

Make '--capture clear-dir' safer

---

main.go
main_test.go
tracee/consts.go
tracee/tracee.go

Add return value filter

---

libbpfgo/libbpfgo.go

Addid pinning for maps in libbpfgo

Add pin, unpin and setpinpath for maps in libbpfgo

---

tracee-rules/input.go

regression introduced in https://github.com/aquasecurity/tracee/pull/455

Fix tracee-rules build

---

libbpfgo/libbpfgo.go
tracee-ebpf/main.go
tracee-ebpf/tracee/pipeline.go
tracee-ebpf/tracee/tracee.go
tracee-ebpf/tracee/tracee_test.go
tracee-rules/signatures/rego/regosig/traceerego.go

lint: Address a few idiomatic Go improvements

---

tracee-rules/signature.go
tracee-rules/signatures/rego/example1_test.rego
tracee-rules/signatures/rego/example2_test.rego

feat: add rego tests

---

tracee-rules/engine/engine.go
tracee-rules/go.mod
tracee-rules/go.sum
tracee-rules/input.go
tracee-rules/output.go
tracee-rules/signatures/golang/code_injection.go
tracee-rules/signatures/golang/code_injection_test.go
tracee-rules/signatures/golang/example.go
tracee-rules/signatures/golang/helpers.go
tracee-rules/signatures/rego/regosig/traceerego.go
tracee-rules/signatures/rego/regosig/traceerego_test.go
tracee-rules/types/types.go

refactor: tracee-rules to use Event type from tracee-ebpf

---

tracee-ebpf/Readme.md
tracee-ebpf/main.go
tracee-ebpf/main_test.go
tracee-ebpf/tracee/printer.go
tracee-ebpf/tracee/tracee.go

Remove the notion of an EOT event signaling end of transmission

---

tracee-rules/input_test.go

Have to more tests cases but here's scaffold for testing these two functions
Closes #517

Unit tests for input source setup functions

---

Dockerfile
Makefile
Readme.md
entrypoint.sh
tracee-rules/Makefile

close #463 
close #464
close #466

add general container and entrypoint

---

Makefile

The release tried to build artifact first and then create the release.
This made sense before the restructure, but now creating a problem:
the build of tracee-rules will fail to find the new version on github
(because it wasn't released yet)
the fix is to change the order:
first tag and push, then build everything (which will work this time),
and finally create the release

fix release as monorepo

---

Makefile

the previous PR #558 almost got it right, but broke something else in the release process. the best approach would be to disconnect the release into 2 phases, first build docker images, second builds github "assets", with clearing dirs between the phases to avoid libc compatibility issues.

fix release

---

tracee-rules/main.go
tracee-rules/output.go
tracee-rules/output_test.go

feat: Better formatted output for detected events.

---

tracee-ebpf/tracee/tracee.bpf.c

As we moved to minimal kernel 4.18, these WA are not required anymore

tracee-ebpf: remove validator workarounds

---

tracee-rules/signature_test.go
tracee-rules/signatures/golang/examples/example.go
tracee-rules/signatures/golang/stdio_over_socket.go
tracee-rules/signatures/rego/anti_debugging_ptraceme.rego
tracee-rules/signatures/rego/code_injection.rego
tracee-rules/signatures/rego/dynamic_code_loading.rego
tracee-rules/signatures/rego/fileless_execution.rego
tracee-rules/signatures/rego/kernel_module_loading.rego
tracee-rules/signatures/rego/ld_preload.rego
tracee-rules/types/types.go

Fixes: https://github.com/aquasecurity/tracee/issues/530

feat: Add signature versioning

---

libbpfgo/selftest/ringbuffers/main.go
libbpfgo/selftest/ringbuffers/self.bpf.c

fix: Make self test for ringbuffer verify the data sent from kernel space

---

.github/workflows/mkdocs-dev.yaml
.github/workflows/mkdocs-latest.yaml

apparently `mike` checks got git config and errors if not set

fix mkdocs generation

---

Readme.md
docs/index.md
docs/install/prerequisites.md

(also fix https://github.com/aquasecurity/tracee/pull/657#discussion_r604822908)

add a quick video intro

---

tracee-ebpf/tracee/pipeline.go
tracee-ebpf/tracee/tracee.go

tracee-ebpf: Fix type mismatch of event arguments

---

Dockerfile
docs/integrations.md
docs/tracee-ebpf/index.md
tracee-ebpf/Readme.md

1. add important gotemplates to the container
2. better documentation of integrations page, including reference to 1

integrate and document gotemplate

---

libbpfgo/libbpfgo.go

fix: https://github.com/aquasecurity/tracee/issues/686

Fix build with libbpfgo

---

tracee-rules/Makefile

add build in docker to tracee-rules

---

.github/workflows/mkdocs-latest.yaml

add manual trigger to docs workflow

---

.github/workflows/ebpf-selfhosted.yaml
.github/workflows/libbpfgo-selfhosted.yaml
.github/workflows/pr-ebpf-selfhosted.yaml
.github/workflows/pr-libbpfgo-selfhosted.yaml

Run libbpfgo self tests on self hosted github action runner

---

.github/workflows/mkdocs-dev.yaml
.github/workflows/mkdocs-latest.yaml

this should allow us to trigger the "latest" docs build manually with a previous tag
close: #704

add manual parameter to docs workflow

---

tracee-ebpf/tracee/consts.go
tracee-ebpf/tracee/tracee.bpf.c

Add security_sb_mount as tracee event

Add security_sb_mount lsm hook

---

tracee-rules/signatures/golang/stdio_over_socket.go
tracee-rules/signatures/golang/stdio_over_socket_test.go

using security_socket_connect with the sockfd arg.
added more details to the detection data.
add detection for a connect directly on standard I/O/E.

work with new form of security_socket_connect

---

tracee-ebpf/tracee/tracee.bpf.c

tracee-ebpf: fix bpf compilation error

---

tracee-ebpf/tracee/printer.go
tracee-rules/go.mod
tracee-rules/go.sum
tracee-rules/input.go

fix gob type declaration

---

tracee-ebpf/tracee/consts.go
tracee-ebpf/tracee/external/external.go
tracee-ebpf/tracee/printer.go
tracee-ebpf/tracee/tracee.bpf.c
tracee-ebpf/tracee/tracee.go

tracee-ebpf: add container id to context

---

tracee-ebpf/tracee/tracee.bpf.c

tracee-ebpf: move fork logic into sched_process_fork

---

tracee-ebpf/tracee/tracee.bpf.c

tracee-ebpf: fix instruction count on kernels < 5.2

---

tracee-rules/Makefile
tracee-rules/benchmark/README.md
tracee-rules/benchmark/benchmark_test.go
tracee-rules/benchmark/helpers_test.go
tracee-rules/benchmark/signature/golang/anti_debugging.go
tracee-rules/benchmark/signature/golang/code_injection.go
tracee-rules/benchmark/signature/rego/anti_debugging_ptraceme.rego
tracee-rules/benchmark/signature/rego/code_injection.rego
tracee-rules/benchmark/signature/rego/helpers.rego
tracee-rules/benchmark/signature/rego/signatures.go

test: Benchmark tracee-rules

---

docs/install/kubernetes.md

fix broken link

---

tracee-rules/benchmark/benchmark_test.go
tracee-rules/benchmark/helpers_test.go

test: Benchmark rules engine based on number of signatures

---

tracee-rules/engine/engine.go

fix: Unsynchronized send and close operations on signature channels

---

tracee-rules/benchmark/benchmark_test.go
tracee-rules/engine/engine.go
tracee-rules/engine/engine_test.go
tracee-rules/main.go

fix(benchmark): Use uniquely identifiable sigs in BenchmarkEngineWithNSignatures

---

tracee-rules/benchmark/signature/golang/anti_debugging.go
tracee-rules/benchmark/signature/golang/code_injection.go
tracee-rules/benchmark/signature/wasm/signatures.go
tracee-rules/engine/engine.go
tracee-rules/engine/engine_test.go
tracee-rules/signatures/golang/stdio_over_socket.go
tracee-rules/signatures/rego/regosig/traceerego.go
tracee-rules/types/types.go

dynamic load/unload signature capability (#797)

---

tracee-rules/benchmark/README.md
tracee-rules/benchmark/benchmark_test.go
tracee-rules/benchmark/signature/golang/noop.go
tracee-rules/benchmark/signature/wasm/signatures.go

test: Describe benchmarks for tracee-rules

---

tracee-ebpf/tracee/tracee.bpf.c

Hi @yanivagman thanks for your reply to my issue ( #806 ), I have created a PR to record timestamp at syscall entry. My approach is to add another bpf map to keep the records in order to affect least range of bpf code.

tracee-ebpf: record context timestamp at sys_enter

---

tracee-ebpf/tracee/tracee.go

skip printing out if library mode

---

tracee-ebpf/external/external_test.go
tracee-ebpf/go.mod
tracee-ebpf/go.sum
tracee-rules/benchmark/helpers_test.go
tracee-rules/go.mod
tracee-rules/go.sum

PR #837 changed the external module files.
Update go.mod to point to the updated module.

tracee-ebpf: update external module

---

tracee-ebpf/tracee/consts.go
tracee-ebpf/tracee/tracee.bpf.c

Fix 4th syscall param

---

tracee-rules/engine/engine.go
tracee-rules/engine/engine_test.go
tracee-rules/signatures/rego/regosig/traceerego.go
tracee-rules/signatures/rego/regosig/traceerego_test.go

With OPA Go SDK we can significantly improve performance by passing
rego.EvalParsedInput instead of rego.EvalInput option to rego.Eval()
method.
Co-authored-by: Simar <simar@linux.com>

tracee-rules: evaluate parsed input with OPA

---

tracee-ebpf/tracee/tracee.bpf.c

Possibly address #817 (needs verification)

tracee-ebpf: security_sb_mount: send exact argnum

---

Readme.md
docs/index.md
docs/install/ebpf-compilation.md
docs/install/headers.md
docs/install/prerequisites.md
docs/tracee-ebpf/index.md
tracee-ebpf/Dockerfile
tracee-ebpf/Readme.md

Update docs to take into account CO:RE default

---

Readme.md
docs/index.md
docs/install/ebpf-compilation.md
docs/install/prerequisites.md

Continues the conversation from #868

Update docs to be more targeted at users, rather than developers

---

Readme.md
docs/index.md

Change quickstart one liner to just make note of mounting Kconfig

---

tracee-ebpf/main.go

Fixes https://github.com/aquasecurity/tracee/issues/888
Testing:
```
sudo setcap cap_ipc_lock,cap_sys_admin=pe tracee-ebpf
./tracee-ebpf # without sudo
docker run --cap-add CAP_SYS_ADMIN --cap-add CAP_IPC_LOCK  --rm -it tracee-ebpf:latest
```
I have not changed any documentation, I would prefer to show examples using capabilities than `--privileged`, but perhaps before fixing the documentation I could before fix issue https://github.com/aquasecurity/tracee/issues/747

tracee-ebpf: fix capabilities minimum requirements

---

tracee-rules/signature.go
tracee-rules/signature_test.go

Fixes https://github.com/aquasecurity/tracee/issues/780

tracee-ebpf: add support to custom rego helpers

---

tracee-rules/engine/engine.go
tracee-rules/input.go
tracee-rules/main.go
tracee-rules/output.go
tracee-rules/signature.go

Minor fixes for error logging consistency.

tracee-rules: improve error logging

---

tracee-ebpf/tracee/tracee.bpf.c

tested on manjaro kernels 4.19, 5.4, 5.10

tracee-ebpf: simplify save_xxx_to_buf logic

---

docs/tracee-ebpf/output.md
tracee-ebpf/main.go
tracee-ebpf/tracee/printer.go
tracee-ebpf/tracee/tracee.go

Fixes https://github.com/aquasecurity/tracee/issues/876

tracee-ebpf: add --capture ignore

---

tracee-rules/signature.go
tracee-rules/signature_test.go

Fixes https://github.com/aquasecurity/tracee/issues/904

tracee-rules: fix rego signature loading

---

tracee-ebpf/go.mod
tracee-ebpf/go.sum
tracee-ebpf/tracee/pipeline.go
tracee-ebpf/tracee/tracee.go

bdcf9b9 tracee-ebpf: improve error handling and add missing ones
e48e515 tracee-ebpf: Change libbpfgo map methods to use unsafe.Pointer
9e867b4 tracee-ebpf: update libbpf to sync with libbpfgo
c8d2f99 tracee-ebpf: update to libbpfgo v0.2.0-libbpf_0.4.0

Update tracee-ebpf to libbpfgo v0.2.0-libbpf_0.4.0

---

tracee-ebpf/test/gob/Readme.md
tracee-ebpf/test/gob/gob.go

Fixes https://github.com/aquasecurity/tracee/issues/762
testing:
```
cd tracee-ebpf
make
sudo ./dist/tracee-ebpf -o gob | go run test/gob/gob.go
```

tracee-ebpf: fix gob test

---

tracee-ebpf/tracee/tracee.go

After merging #836 , tracee-ebpf doesn't work without using the tree filter (always-on).
This PR fixes it.

tracee-ebpf: fix process tree disabled

---

tracee-rules/engine/engine.go
tracee-rules/engine/engine_test.go

tracee-rules: add GetSelectedEvents

---

tracee-ebpf/external/external.go
tracee-ebpf/external/external_test.go

fix json unmarshaling nil

---

tracee-ebpf/go.mod
tracee-ebpf/go.sum
tracee-ebpf/main.go
tracee-ebpf/tracee/consts.go
tracee-ebpf/tracee/tracee.bpf.c
tracee-ebpf/tracee/tracee.go

Reference: https://github.com/aquasecurity/libbpfgo/issues/60
Needs https://github.com/aquasecurity/libbpfgo/pull/67 merged first.

helpers/btfinfo: renamed to osinfo and improved, syncing

---

tracee-ebpf/go.mod
tracee-ebpf/go.sum

Add replace directive back to go.mod

---

tracee-ebpf/tracee/consts.go
tracee-ebpf/tracee/tracee.bpf.c

tracee-ebpf: add sched_switch event

---

.gitignore
tracee-rules/signatures/rego/regosig/traceerego.go
tracee-rules/signatures/rego/regosig/traceerego_test.go

tracee-rules(test): rewrite tests for RegoSignature

---

tracee-ebpf/tracee/tracee.bpf.c

Today we call `init_context()` twice per event: in `should_trace()` and in `init_and_save_context()`. In addition to this, we call other helpers to get the pid/tid/comm/etc, while this data was already fetched in `init_context()`. This is redundant, and adds some extra instructions which we can save.
This patch calls `init_context()` once, and uses the returned struct where needed.

tracee-ebpf: init context once

---

tracee-ebpf/tracee/tracee.bpf.c

`save_args_from_regs()` is not used anymore for tracing syscalls. Remove it.

tracee-ebpf: remove save_args_from_regs

---

tracee-ebpf/main.go

Improve error message of being unable to find kernel headers

---

tracee-rules/signatures/rego/k8s_service_account_token.rego

add more process names to the allowlist so the signature will be less noisy. #1085

add more process names to allowlist

---

tracee-ebpf/main_test.go

feat: Add tests for fetchFormattedEventParams

---

tracee-ebpf/printer.go
tracee-ebpf/tracee/argprinters.go
tracee-rules/benchmark/helpers_test.go
tracee-rules/input.go
tracee-rules/signatures/golang/kubernetes_api_connection.go
tracee-rules/signatures/golang/kubernetes_api_connection_test.go
tracee-rules/signatures/golang/stdio_over_socket.go
tracee-rules/signatures/golang/stdio_over_socket_test.go
tracee-rules/signatures/helpers/helpers.go

there is no need to convert addr argument to string of json. now using it as it comes: map[string]string

use plain addr argument

---

docs/Dockerfile
docs/install/ebpf-compilation.md

docs: fix formatting on eBPF Compilation page

---

Dockerfile

fix: install the tini package in the tracee:slim container image

---

.github/workflows/mkdocs-dev.yaml
.github/workflows/mkdocs-latest.yaml
docs/Dockerfile
mkdocs.yml

to support https://github.com/aquasecurity/tracee/pull/1164

add semver variable to mkdocs

---

Dockerfile
tracee-ebpf/Dockerfile

fix: use alpine:3.15 as base image to build tracee

---

Readme.md

Fix linux headers broken link in readme

---

tracee-ebpf/tracee/containers.go

tracee-ebpf: keep deleted containers

---

tracee-ebpf/tracee/co-re/vmlinux.h
tracee-ebpf/tracee/events_decoder.go

fix reading sockaddr_in struct

---

tracee-ebpf/go.mod
tracee-ebpf/main.go

checking /proc/sys/kernel/ftrace_enabled

---

docs/install/docker-mac.md
docs/install/headers.md

Fixes: https://github.com/aquasecurity/tracee/issues/1127
Re-adds: https://github.com/aquasecurity/tracee/pull/571

docs: Re-add section for MacOS

---

Vagrantfile

To check things out (e.g. make docker or make docker-slim) I always install Docker in the VM.

chore: install docker in the Vagrant vm

---

tracee-ebpf/tracee/co-re/vmlinux.h

tracee-ebpf: fix pid 0 with CO-RE

---

tracee-ebpf/tracee/co-re/missing_definitions.h
tracee-ebpf/tracee/events_processor.go
tracee-ebpf/tracee/tracee.bpf.c
tracee-ebpf/tracee/tracee.go

use the i_mode field to check if socket dup

get file types from inode struct instead of file_operations

---

.github/actions/build-dependencies/action.yaml
.github/workflows/pr.yaml
tracee-ebpf/tracee/user_mode_events_test.go

chore: run critical Make targets in the PR checker workflow

---

.github/workflows/mkdocs-dev.yaml
.github/workflows/mkdocs-latest.yaml
builder/Dockerfile.mkdocs
docs/index.md
docs/install/docker-mac.md
docs/install/ebpf-compilation.md
docs/install/kubernetes.md
docs/install/prerequisites.md
docs/integrations.md
docs/rules-authoring.md
docs/tracee-ebpf/index.md
mkdocs.yml

docs: use git.tag macro instead of git_tag_version

---

cmd/tracee-ebpf/main_test.go

tracee-ebpf: fix arm64 tests

---

.gitignore
3rdparty/btfhub.sh
Makefile.one
builder/Dockerfile.alpine-tracee-make
builder/Dockerfile.ubuntu-tracee-make
builder/Makefile.docker
builder/Makefile.mkdocs

bbf7da2 Makefile.one: build dependencies fixes
a8b8507 btfhub.sh: improvement and fixes
bcf796e tracee-make: fix dockerfiles sudoers and dependencies
6ffbad3 Makefile.one: default parallel jobs for libbpf build only

Adjusting Makefile.one and btfhub.sh with fixes and improvements.

---

tracee-ebpf/tracee/events_definitions.go

due a refactor ( i guess) the parameter of Hidden_Inodes was deleted.
i just add it again (:

added parameter to the HiddenInodes event

---

pkg/containers/containers.go
tracee-ebpf/tracee/events_processor.go

This commit was made after a careful read of the containers logic. Changes proposed here are for better understanding of the logic for a first time reader.

containers: improve comments and function documentation

---

tracee-ebpf/tracee/tracee.go

tracee-ebpf: increase event count on init event

---

tracee-ebpf/tracee/events_pipeline.go

events_pipeline: Fixed bug of counting events twice

---

tracee-ebpf/tracee/tracee.bpf.c

Commit e252c46 introduced a minor regression in non CO-RE eBPF object loading in kernels v5.4. The kernel verifier complains:
```
; bpf_map_update_elem(&process_context_map, &process->host_tid, &process, BPF_ANY);
394: (18) r1 = 0xffffa0b8aa8f8400
396: (b7) r4 = 0
397: (85) call bpf_map_update_elem#2
invalid indirect read from stack off -240+0 size 56
processed 358 insns (limit 1000000) max_states_per_insn 0 total_states
21 peak_states 21 mark_read 21
```
Copying (struct process_context_t *) &data.context to function's stack seems to solve the issue.
Fixes: e252c46 ("Process context map  (#1300)")

tracee-ebpf: fix eBPF load regression for v5.4 kernel

---

types/go.mod
types/types.go

Copy the types folder in preparation to the module separation.
Needed to resolve #1312

Types module separation preparation

---

Vagrantfile

chore: install bpftool in Vagrant vm

---

cmd/tracee-ebpf/main.go
tracee-ebpf/tracee/events_pipeline.go
tracee-ebpf/tracee/tracee.go

Resolves #975
Other projects that wish to use tracee-ebpf as a library can now use the package with a `context.Context` to stop running: `Run() error` is now `Run(ctx context.Context) error`. Previously the `Run()` method could only be stopped using `SIGINT`/`SIGTERM`.
The tracee-ebpf binary now creates a context that is cancelled by these interrupts and passes it to the tracee-ebpf package so existing behaviour is preserved.
NOTE: I've imported `"context"` using the `gocontext` alias as `context` is already used elsewhere in the same package for another import. 
NOTE 2: This is my first tracee PR and I'm pretty unfamiliar with things atm, so feel free to rip this apart if necessary :)

Move signal handing out of tracee-ebpf package

---

tracee-ebpf/tracee/events_processor.go
tracee-ebpf/tracee/net_events.go
tracee-ebpf/tracee/write_capture.go

add stats printing to stderr in case of lost events

---

.github/workflows/pr.yaml
tests/Makefile
tests/tracee_test.go

Run signatures tests as sanity check on each PR.

chore(ci): e2e signatures tests

---

.github/workflows/pr.yaml
.github/workflows/scheduled-signatures-test.yaml
tests/tracee_test.go

Resolves: #1234
Resolves: #1191

test: parameterize e2e signatures test and use it as sanity check

---

signatures/rego/disk_mount.rego
signatures/rego/disk_mount_test.rego

changed the signature to alert on every device mount from within the container.
changed the description accordingly.
related #1332.

disk_mount signature alert on every device mount

---

tracee-ebpf/test/gob/gob.go
tracee-ebpf/tracee/events_pipeline.go
tracee-ebpf/tracee/events_processor.go
tracee-ebpf/tracee/tracee.go

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Misc typo fixes

---

tests/tracee_test.go

We have a new parameterized TestTraceeSignatures that does
the same thing (and more) and is actually run in the CI
pipeline.

test: remove obsolete TestLaunchTracee test

---

tracee-ebpf/tracee/events_pipeline.go
tracee-ebpf/tracee/tracee.bpf.c

bpf & pipeline: changed ProcessorID size in Context

---

pkg/containers/containers.go
tracee-ebpf/tracee/co-re/vmlinux.h
tracee-ebpf/tracee/events_definitions.go
tracee-ebpf/tracee/events_processor.go
tracee-ebpf/tracee/tracee.bpf.c

tracee-ebpf: fix cgroup v1 multiple container_create event

---

cmd/tracee-ebpf/main.go

tracee-ebpf: fix dir permissions

---

.github/workflows/pr.yaml
.github/workflows/scheduled-signatures-test.yaml

Remove deprecated workflow steps

---

types/trace/network_trace.go

Add network_trace to types module, Copied from external/network_external as a fix to #1454 and preparation to #1455

update types module

---

types/detect/detect.go
types/protocol/protocol.go
types/trace/trace.go
types/trace/trace_test.go

Adds event headers to `detect`.
Adds new `protocol` package to convert between `trace.Event` and `detect.Event`

types: Add event headers

---

pkg/bufferdecoder/net_decoder.go
pkg/ebpf/net_events.go

capture pcap with correct packet data

---

pkg/ebpf/events_definitions.go
pkg/ebpf/user_mode_events.go

this commit fixes Tracee compilation.
FYI @yanivagman

fix compilation, using trace instead of external package

---

mkdocs.yml

Fix path for headers.md

---

Vagrantfile
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml

fix(deploy): update DaemonSet config to deploy tracee in K8s

---

cmd/tracee-ebpf/internal/flags/flags-filter.go
cmd/tracee-ebpf/main_test.go
pkg/ebpf/filters.go

ebpf: fix string filter

---

deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml

Update to v0.7.0 in prep for release

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
builder/Makefile.release

Substitute out 'v' in docker image tags

---

pkg/rules/engine/engine.go
pkg/rules/engine/engine_test.go

This refactor unifies the signature loading logic.
`NewEngine` and `LoadSignature` both implemented their own internal signature map storing logic, with the difference being that `LoadSignature` would immediately start the signature and `NewEngine` wouldn't (Start does that instead).
This refactor adds a new internal `loadSignature` function which is used both by `NewEngine` and the exported `LoadSignature`.
This also solves the bug where signatures stat wasn't incremented on the initial load from `NewEngine`.

engine: unify signature loading logic

---

.github/workflows/pr.yaml
.github/workflows/release-snapshot.yaml

chore(ci): build unversioned release snapshot on schedule (nightly)

---

.github/workflows/release-snapshot.yaml
.github/workflows/test-signatures.yaml
Readme.md

chore: add status badge for release snapshot workflow

---

.github/workflows/release-snapshot.yaml

chore: publish release snapshot images to DockerHub

---

pkg/ebpf/argprinters.go
pkg/ebpf/c/missing_definitions.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/ebpf/events_definitions.go

This is a rebase of https://github.com/aquasecurity/tracee/pull/1580.

Pipe write event review

---

cmd/tracee-rules/output_test.go
cmd/tracee-rules/signature_test.go

fix(test): data race in Test_setupOutput

---

pkg/events/sorting/sorting_test.go

fix(test): data race in TestEventsChronologicalSorter_Start

---

types/trace/trace.go

This is in preparation for #1572
Also a good opportunity to discuss the new enrichment fields and if more are required for initial implementation.

trace: add container and pod data to event

---

pkg/ebpf/tracee.go

Commit 82b4ec3e ("fix empty process context for net_packet event
(#1692)") checks if InterfacesToTrace is not null but it should check
for length being bigger than 0 instead.
./dist/tracee-ebpf --trace net=<interface> --trace event=net_packet

network: InterfacesToTrace should be checked by length

---

.github/workflows/pr.yaml
.github/workflows/test-noncore-daily.yaml
.github/workflows/test-noncore-weekly.yaml

workflows: add non CO-RE tests for multiple kernels
Following the recent addition of CO-RE tests for PR workflow, this
commit adds non CO-RE tests to our GitHub workflows.
This is a test =).

workflows: add non CO-RE tests for multiple kernels

---

.github/workflows/pr.yaml
.github/workflows/test-core-daily.yaml
.github/workflows/test-core-weekly.yaml
.github/workflows/test-noncore-daily.yaml
.github/workflows/test-noncore-weekly.yaml

workflows: use a single image for core and non-core
- add amzn2 kernel images to test
- minor job name fix (non CO-RE)
These are tests.

workflows: use a single image for core and non-core

---

Readme.md

docs: fix image ref in README

---

types/trace/trace.go

This allows rules to use the `HookedSymbolData` struct in order to write rules for hooking detection.
commit 3b2024a47a6394cf352e148015e039ac2587d5b0 (HEAD -> symbol_type, origin/symbol_type)
Date:   Wed Apr 27 18:13:20 2022 +0300
Add HookedSymbolData to type/trace
This allows rules to use the struct
Fixes: #1709

add HookedSymbolData to types/trace

---

pkg/ebpf/tracee.go

Fixes: #1710 
Manually, with adding prints to the appropriate places.

Fix events shouldSubmit configuration overriding

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/ebpf/events_definitions.go

This event indicates a device creation - often used by rootkits as a communication method to their userland malware.
Fixes: replaces #1682 to solve #1613 
- New feature (non-breaking change which adds functionality)

add device_add event

---

types/trace/trace.go

Adds CgroupID field to trace.Event. This is done to pass cgroupId down the event pipeline in tracee-ebpf for #1572.
No tests needed, some tests will need to be modified once this is merged and used.

trace: add cgroupId to event

---

.github/workflows/pr.yaml

workflows: PR: core and non-core use same kernels

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_definitions.go

This is a rebase of https://github.com/aquasecurity/tracee/pull/1693 so I can get it merged.

pkg/ebpf: add register_chrdev_region event

---

pkg/ebpf/events_pipeline.go

Events previously didn't go through the emit check in the pipeline's sink stage. This PR fixes that.
Fixes: #1735
Manually through reproduction with the `container_create` event (as described by the issue)
- `sudo ./dist/tracee-ebpf -t event=container_create`
- `docker run --rm redis`

pipeline: fix events not going through emit check in sink

---

.github/workflows/pr.yaml
cmd/tracee-ebpf/internal/flags/flags-output.go
cmd/tracee-ebpf/main.go
cmd/tracee-ebpf/main_test.go
cmd/tracee-ebpf/printer.go
cmd/tracee-rules/input_test.go
pkg/bufferdecoder/decoder_test.go
pkg/bufferdecoder/eventsreader.go
pkg/ebpf/events_derived.go
pkg/ebpf/events_processor.go
pkg/ebpf/initialization/kconfig.go
pkg/ebpf/tracee.go
pkg/ebpf/user_mode_events_test.go
pkg/ebpf/write_capture.go
pkg/events/sorting/cpu_queue.go
pkg/events/sorting/pool.go
pkg/events/sorting/sorting.go
pkg/events/sorting/sorting_test.go
signatures/golang/examples/example.go

5c0693bb workflow: add go vet to PR workflow
2fe4cadd workflows: add golang static checker to each PR
efd75d17 chore: gomft fix
c4f9e039 chore: static checker fixes
Fixes: #1733
This is the result of a test AND a test implementation.
```
$ staticcheck -tags ebpf,core ./...
```

Static checker

---

.github/PULL_REQUEST_TEMPLATE.md

Add code refactoring and/or deletion option in the PR template.
N/A
N/A

template: add option to PR template

---

pkg/ebpf/argprinters.go
pkg/ebpf/events_definitions.go
pkg/ebpf/tracee.go

We used to have a "fake" sysCall attach probe to identify syscall
probes. This is no longer needed (since we moved using raw syscall
tracepoints, and instead we can simply tell if an event is a syscall or
not.
We used to have a "fake" sysCall attach probe to identify syscall probes. This is no longer needed (since we moved using raw syscall tracepoints, and instead we can simply tell if an event is a syscall or not.
- command 01
- command 02

tracee-ebpf: remove syscall probes

---

pkg/bufferdecoder/net_decoder.go
pkg/ebpf/net_events.go

process name for network events was not trimmed properly.
Fixes: #1740
locally
- command 01: `./dist/tracee-ebpf -t e=net_packet -t net=enp0s3 -o format:json`

fix: trim net events process name

---

pkg/bufferdecoder/decoder.go
pkg/bufferdecoder/net_decoder.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_definitions.go
pkg/ebpf/events_derived.go
pkg/ebpf/net_events.go
pkg/ebpf/net_proto.go
pkg/ebpf/net_proto_handlers.go
pkg/ebpf/tracee.go

This is just a rebase of https://github.com/aquasecurity/tracee/pull/1698 so I can merge it.

Dns events review

---

pkg/ebpf/events_definitions.go
pkg/ebpf/tracee.go

Build a generic mechanism to declare the required tail-call for the proper functionality of an event.
In addition, Introudce capture events to take care of capture dependencies (probes and tail-calls) automatically.
New feature (non-breaking change adding functionality).
Manually run and verified the proper functionality of the following events:
- exexcve
- execveat
- socket_dup
Manually run and verified the proper functionality of the following capture features:
- capture write
- capture mem

tracee-ebpf: add tail calls to event dependencies

---

.github/actions/build-dependencies/action.yaml
.github/workflows/test-os-packaging-daily.yaml
Readme.md

We should test the packaging process of tracee to make it reliable.
Fixes: #1597 
This is a test AND has been tested at: https://github.com/rafaeldtinoco/tracee/actions/runs/2304817227

Test OS packaging

---

.github/workflows/test-noncore-daily.yaml
.github/workflows/test-noncore-weekly.yaml
Readme.md

This is just a complement to https://github.com/aquasecurity/tracee/pull/1747 (it adds a badge into Readme and fixes a job name).

Workflow fixes

---

.github/workflows/pr.yaml
.github/workflows/test-core-daily.yaml
.github/workflows/test-core-weekly.yaml
.github/workflows/test-noncore-daily.yaml
.github/workflows/test-noncore-weekly.yaml
tests/distro-tester/.dockerignore
tests/distro-tester/.gitignore
tests/distro-tester/00-config
tests/distro-tester/00-readme
tests/distro-tester/01-copy-images.sh
tests/distro-tester/02-extract-images.sh
tests/distro-tester/03-run-qemu.sh
tests/distro-tester/04-compress-images.sh
tests/distro-tester/05-create-docker.sh
tests/distro-tester/99-uncompress-images.sh
tests/distro-tester/Dockerfile
tests/distro-tester/README.md
tests/distro-tester/files/docker-entrypoint.sh
tests/distro-tester/files/qemu-entrypoint.sh

commit 27d8ee1c
Date:   Sun May 15 02:08:43 2022
workflows: update CORE tests to distro tests
commit 46821282
Date:   Sun May 15 01:04:09 2022
tests: linux distributions and kernels tester
Through github actions within my own repository:
https://github.com/rafaeldtinoco/tracee/actions/runs/2326227282
> I failed Jammy test on purpose (the image did not exist yet in docker hub) so I could test if the failed test would also be detected.
> Some tests took more than 10min because I did not cache go modules in those images, I'm fixing it but it does not block this PR.

Tracee distro tester

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/ebpf/events_definitions.go

expose new event to user that indicated kernel module load.
expose new event to user that indicated kernel module load.
Fixes: #1706
- command 01: ./dist/tracee-ebpf -t e=do_init_module

event: do_init_module

---

types/trace/network_trace.go

add packet length and the network interface from which it comes.
adding `PacketLen` and `Iface` fields to the `trace.PktMeta` struct.
this is the first PR to solve the issue.
after it will be merged, we can use this change to complete the feature.
Fixes: #1761
- command 01
- command 02

network events: more values in metadata

---

.clang-format
.github/actions/build-dependencies/action.yaml
.github/workflows/pr.yaml
Makefile
Vagrantfile
builder/Makefile.checkers
docs/contributing/guidelines.md
mkdocs.yml
pkg/ebpf/c/missing_definitions.h
pkg/ebpf/c/struct_flavors.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h

Introduce clang-format and makefile targets to manage code formatting (C and Go) and static checking (go).
No logical changes were made.

[MAINT] C style

---

pkg/ebpf/events_definitions.go

When listing available events in tracee-ebpf, no parameters where shown.
Fix this by adding the missing sets field.
- command 01
- command 02

tracee-ebpf: fix socket_accept print

---

signatures/rego/k8s_service_account_token.rego
signatures/rego/k8s_service_account_token_test.rego

add 'kubectl' process name to allowlist

---

pkg/bufferdecoder/eventsreader.go
pkg/ebpf/c/missing_definitions.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/ebpf/events_definitions.go
pkg/ebpf/events_processor.go

commit a582a3e357aa149c8decf117fb5c7903f849af42 (HEAD -> rootkits/fops, origin/rootkits/fops)
Date:   Sun May 1 12:04:04 2022 +0300
fix: update types and bug fixes
commit eecd3ab4abe7400538fa995501b5772a2bcc40ce
Author: itamar maouda <itamarmaouda101@gmail.com>
Date:   Wed Jan 26 17:27:40 2022 +0200
events: create fops hooking on /proc event
File operation hooking is done by replacing function pointers in the fops struct
This can be used to hide files and processes.
This commit adds a detection to detect such efforts.
EPIC: #1703
Fixes: #1560 
- running tracee with the event filter `detect_hooked_proc_fops`
- running the `phide` kernel module from here -> https://github.com/nisay759/linux-rootkits
- running `ps` …

create new event - file operations hooking under /proc detection

---

signatures/rego/syscall_table_hooking.rego

This is a fix for wrong severity in syscall hooking signature.

signatures: fix syscall hooking detection signature severity

---

Vagrantfile

[MAINT] cd to /vagrant when you ssh to Vagrant vm

---

signatures/rego/anti_debugging_ptraceme.rego
signatures/rego/anti_debugging_ptraceme_test.rego
signatures/rego/cgroup_release_agent_modification.rego
signatures/rego/cgroup_release_agent_modification_test.rego
signatures/rego/code_injection.rego
signatures/rego/code_injection_test.rego
signatures/rego/disk_mount.rego
signatures/rego/disk_mount_test.rego
signatures/rego/dropped_executable.rego
signatures/rego/dropped_executable_test.rego
signatures/rego/dynamic_code_loading.rego
signatures/rego/dynamic_code_loading_test.rego
signatures/rego/fileless_execution.rego
signatures/rego/fileless_execution_test.rego
signatures/rego/helpers.rego
signatures/rego/illegitimate_shell.rego
signatures/rego/illegitimate_shell_test.rego
signatures/rego/k8s_service_account_token.rego
signatures/rego/k8s_service_account_token_test.rego
signatures/rego/kernel_module_loading.rego
signatures/rego/kernel_module_loading_test.rego
signatures/rego/kubernetes_certificate_theft_attempt.rego
signatures/rego/kubernetes_certificate_theft_attempt_test.rego
signatures/rego/ld_preload.rego
signatures/rego/ld_preload_test.rego
signatures/rego/syscall_table_hooking.rego
signatures/rego/syscall_table_hooking_test.rego

[MAINT] Format OPA Rego code with opa fmt

---

Readme.md

[MAINT] README: fix badges for daily workflows

---

pkg/containers/runtime/docker.go

```
Date:   Mon Jun 20 08:21:25 2022 +0000
enrichment: remove leading slash from docker container names
Docker container names include a leading slash if the containers are
local if fetched from it's API or checked in inspect.
This is hardly documented by docker and can cause some confusion.
```
Fixes: #1825
Run tracee as such:
`sudo ./dist/tracee-ebpf -t e=container_create`
Start a container like so
`docker run --rm alpine`
Confirm the container name has no leading slash.

enrichment: remove leading slash from docker container names

---

.github/workflows/publish-helm.yaml
.gitignore
RELEASING.md
Vagrantfile
deploy/helm/tracee/.helmignore
deploy/helm/tracee/Chart.lock
deploy/helm/tracee/Chart.yaml
deploy/helm/tracee/templates/NOTES.txt
deploy/helm/tracee/templates/_helpers.tpl
deploy/helm/tracee/templates/daemonset.yaml
deploy/helm/tracee/templates/serviceaccount.yaml
deploy/helm/tracee/values.yaml
docs/install/kubernetes.md
docs/tutorials/setup-development-machine-with-vagrant.md

This patch adds basic Helm chart templates to install Tracee
as a DaemonSet in a Kubernetes cluster.
You can install tracee Helm release with the following command:
git clone https://github.com/aquasecurity/tracee.git
cd tracee
helm repo add aqua-charts https://aquasecurity.github.io/helm-charts
helm dependency update ./deploy/helm/tracee
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace
When you want to test the template rendering, but not actually
installing anything, you can use:
helm install --debug --dry-run tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace
By default, Tracee is installed with Postee. You can disable Postee
with the `postee.enabled=false` value:
helm install tracee ./deploy/helm/tracee \
--namespace …

feat: add Helm chart to install Tracee with Postee

---

pkg/ebpf/events_derived.go

```
Date:   Wed Jun 22 13:41:56 2022 +0000
fix: submit flag enables derivation
An enabled flag was recently added to the derivation table struct
in order to determine wether a derive function should run at all.
In tracee's derivation table, the Enabled flag was set through the emit
flag of the derived event.
However events should really be derived if submitted to userspace
and not if emitted through it.
This should fix some derived events (for example HookedSyscalls #1844)
not being derived.
```
Fixes: #1844
- `sudo ./dist/tracee-ebpf -t e=hooked_syscalls` 
Confirm the event is emitted.

fix: submit flag enables derivation

---

pkg/bufferdecoder/decoder.go
pkg/bufferdecoder/protocol.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/tracee.go

This PR introduces two changes that improve the bpf programs performance.
The first change avoids performing scope caclculations (should_trace) on every event, by caching the last result of should_trace() in a new per-task map called task_info_map.
In addition, it adds task's start_time into the event context of every event so we can identify a specific task even when a pid is being reused (due to wrapping).
The second change reduces the amount of map lookups required for the different events by removing new_pids, trace_pids and syscall_data maps and introducing the matching fields in task_info map.
Tested manually with the different filters that exist in tracee to verify nothing was broken.
- command 01 …

Cache should trace and introduce task_info map

---

cmd/tracee-rules/output_test.go
go.mod
pkg/ebpf/events_pipeline.go
types/trace/trace.go

Pids in linux can be re-used. To uniquely identify a thread, expose thread's start time as part of the context.
Note: This commit only updates the types package. A future commit should initialize this field with the matching value from ctx.
- command 01
- command 02

types: add thread start time

---

docs/events/format.md
docs/events/security_alerts/magic_write.md
pkg/events/events.go

Created field in event's definition for documentation.
Added magic_write event doc for example of how events documentations
should look like.
Fixes: #1398 

pkg/ebpf: created events documentation

---

pkg/procinfo/procinfo.go

Fixes: #1856
- command 01
- command 02

deferring close of dir

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/tracee.go

We perform multiple lookups in the config map to get different config values which consume cpu cycles.
Perform only one lookup instead by grouping all the config values into one map element.
Manually tested the different configurations work as expected
- command 01
- command 02

One config value

---

pkg/ebpf/c/tracee.bpf.c

The hash map macros we use in Tracee today don't let us define exact
sizes for specific maps. Add the option to do that.
- command 01
- command 02

tracee-ebpf: define map size per each map

---

pkg/events/derive/derive.go
pkg/events/derive/derive_test.go

Fix bug that if derive event function does not need to derive event it
generates an error that it failed.
The reason is that there was no given way to not derive function.
Fixes: #1852 
- pkg/events/derive/derive_test - No derivation test for `singleEventDeriveFunc`.

Bugfix: pkg/events/derive: add support to no derivation

---

cmd/tracee-ebpf/internal/flags/flags-containers.go

Fixes: #1872
Run `sudo ./dist/tracee-ebpf --crs help`

flags: fix help text for --crs

---

pkg/ebpf/c/tracee.bpf.c
pkg/events/events.go

pkg/ebpf: add syscall pathname to security_file_open
Often, only security_file_open is monitored without the open syscalls.
From seeing the resolved path it's hard to tell to which action it's
related especially when referring symbolic links.
- command 01
- command 02

pkg/ebpf: add syscall pathname to security_file_open

---

builder/entrypoint.sh
cmd/tracee-ebpf/main.go
pkg/ebpf/events_pipeline.go
pkg/ebpf/tracee.go

Put the container enrichment behind a feature flag. This was done due to multiple bugs in the feature cropping up.
```
Date:   Tue Jun 28 17:10:44 2022 +0000
tracee-ebpf: add feature flag to enrichment
The feature may either be enabled through the --containers flag in
tracee-ebpf or through the CONTAINERS_ENRICHMENT environment flag in
the image entrypoint.
```
Run tracee as such:
`sudo ./dist/tracee-ebpf -trace container -o format:json -o option:parse-arguments -o option:detect-syscall --containers`
Start a container as such:
`docker run --rm alpine`
Confirm events are enriched.
Then run tracee without `--containers` and confirm no enrichment data was added.
Pick "Bug Fix" or "Feature", delete the other and mark appropriate …

tracee-ebpf: add feature flag to enrichment

---

cmd/tracee-ebpf/internal/printer/printer.go
cmd/tracee-rules/input.go
pkg/ebpf/net_proto_handlers.go
pkg/events/events.go
types/trace/network_trace.go

move DNS struct into trace package, so signatures can use it
i've moved `DnsResponseData`, `DnsAnswer`, `DnsQueryData` structs into package 'trace' to be used in signatures.
Fixes: #1867
locally. added mock signature to verify these struct can indeed be used.
- command 01: `./dist/tracee-ebpf -t e=dns_request,dns_response -t net=enp0s3 -o format:gob | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:gob`

DNS events: export DNS struct

---

docs/events/lsm_hooks/security_socket_setsockopt.md
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/probes/probes.go
pkg/events/events.go
pkg/events/parse_args.go

Created new event for the lsm-hook of 'security_socket_setsockopt'.
Fixes: #1858 

pkg/ebpf: new security_socket_setsockopt event

---

go.mod
go.sum

```
Date:   Thu Jun 30 08:59:03 2022 +0000
go.mod: revert types back to static commit
While it helped with development ease, switching the types to a local
replace caused plugin signatures not to work due to version mismatch
issues.
As such, this commit reverts that change.
```
Simple build and run to ensure nothing broke + workflows. Since this is how the repo was before, shouldn't be an issue.

go.mod: revert types back to static commit

---

pkg/ebpf/events_derived.go
pkg/events/derive/container_remove.go

```
Date:   Thu Jun 30 12:28:50 2022 +0000
derive: fix bugs in container_remove function
There were two bugs:
1. Incorrect arguments were returned from the arg function.
2. When no arguments were found an empty args array was returned instead
of nil.
```
Also renamed the functions from removed to remove like the event.
Run tracee as such:
`sudo ./dist/tracee-ebpf -t event=container_create,container_remove`
Run a container as such:
`docker run --rm alpine`
Ensure the container_remove event is derived correctly with no errors.

derive: fix bugs in container_remove function

---

pkg/ebpf/c/tracee.bpf.c

Change the `SYS_SETSOCKOPT` to not collide with kernel constant, to avoid
non-CORE compilation warning.
Fixes: #1894

Bugfix: pkg/ebpf: fix non-CORE SYS_SETSOCKOPT redefinition warning

---

tests/distro-tester/02-extract-images.sh
tests/distro-tester/files/docker-entrypoint.sh
tests/distro-tester/files/qemu-entrypoint.sh

[skip ci]
PR holder for fixes being landed to distro tester for this release.

[MAINT] tests/distro-tester: fixes needed for daily tests

---

.dockerignore

[MAIN] docker: ignore temporary distro tester files

---

pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/events.go

probes: refactor tc and network probes
- unify probes package for different probes types
- allow probes be attached/detached during runtime
- allow tc probes to be attached/detached from specific interface
This work will help in the future when dynamic attachment/detachment is
neded, but the current focus is to cleanup tracee.go initialization as
well (going forward with probes refactoring).
Commit adds:
- Probes interface:
- Using a traceProbe Handle (types: rawTracepoint, kprobe, kretprobe)
Syntax: Attach(EventHandle)
Syntax: Detach(EventHandle)
- Using a tcProbe Handle:
Syntax: Attach(EventHandle, *net.Interface)
Syntax: Detach(EventHandle, *net.Interface)
- to detach all probes:
DetachAll()
- Probe interface:
- traceProbe (attach/detach/autoload)
- tcProbe (attach/detach/autoload) …

tc and net probes refactoring

---

docs/index.md
docs/integrations.md

Added link from index.md to the integrations section
of container enrichment.
Also improved the existing documentation's formatting and examples.
Fixes #1884 

docs: improve enrichment documentation

---

pkg/ebpf/c/tracee.bpf.c

dropping support of DNS over TCP beacuse of #1834. this is to avoid errors in RC1.
meanwhile - working on a better design for an holistic solution to the problem.
Fixes: #1834
- command 01
- command 02

DNS: drop support of DNS over TCP

---

types/trace/trace.go

fix: bug #1907 add umode_t to UnmarshalJSON

---

go.mod
go.sum

Fixes: #1907
Use the commit in the types package to resolve the bug

update: types package to fix #1907

---

cmd/tracee-ebpf/main.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/tracee.go
pkg/events/amd64.go
pkg/events/arm64.go
pkg/events/events.go

To reduce the number of map lookups in every event, remove the use of events_to_submit map. Instead, create an events bitmap shared between the userspace and bpf code through the configuration map.
Manually
- command 01
- command 02

ebpf: remove events_to_submit map

---

pkg/containers/containers.go
pkg/ebpf/tracee.go
pkg/events/events.go
pkg/events/usermode.go

```
Date:   Tue Jul 5 15:11:09 2022 +0000
usermode: add enrichment to existing_continer
Enrichment will happen on init time and not as part of the pipeline.
This was chosen due to simplicity and was tested with
230 initial containers.
Since it's a single action done before the pipeline starts,
it shouldn't overload the enrichment queues or runtimes.
```
Fixes: #1920
Create a file `many_containers.sh`:
```
#!/bin/bash
for i in {1..200}
do
docker run -d --name test$i --rm redis
done
```
Run tracee with:
`tracee-ebpf -t event=existing_container -o json --containers > dump`
Confirm dump file has all events enriched.
Clean up your containers with:
`docker stop $(docker ps -aq)` …

usermode: add enrichment to existing_continer

---

pkg/ebpf/c/tracee.bpf.c

A recent libbpf version introduced syscall param macros.
Use them.
A recent libbpf version introduced syscall param macros. Use them.
- command 01
- command 02

ebpf: use new libbpf syscall macros

---

pkg/ebpf/c/tracee.bpf.c

Avoid passing the binary currently executed as ELF if there is no interpreter.
Fixes: #1927 
Manual check with static compiled file and normal ELF file.

Bugfix: pkg/ebpf: avoid passing interpreter for static ELF

---

pkg/ebpf/events_enrich.go

```
events_enrich: a new atomic approach with single lock
Producer:
Each cgroupId gets its own channel of events. Events are enqueued and only
de-dequed once the cgroupId was enriched OR has failed enrichment.
[cgroupId #0]: queue of trace events for the host
[cgroupId #1]: queue of trace events for container described by cgroupId #1
[cgroupId #2]: queue of trace events for container described by cgroupId #2
[cgroupId #3]: queue of trace events for container described by cgroupId #3
...
If the cgroupId channel does not exist it is created and an enrichment phase
is triggered for that cgroupId. If the cgroup channel is not used after a
specific period, it is removed.
Consumer:
In order to de-queue an event from its queue there is a scheduled operation
to each queued event.
queueReady: it …
```

events_enrich: a new atomic approach with single lock

---

pkg/containers/containers.go
pkg/containers/utils.go

This was done in order to add a search string to the function.
This search string is used in cgroup v1 envs to find the
cpuset controller.
```
Date:   Wed Jul 6 15:49:17 2022 +0000
containers: change findMountpoint to searchMountpoint
This was done in order to add a search string to the function.
This search string is used in cgroup v1 envs to find the
cpuset controller.
```
Fixes: #1934 
1. `docker run -d --rm redis`
2. `sudo ./dist/tracee-ebpf -t c`
Confirm redis container generates events

containers: change findMountpoint to searchMountpoint

---

pkg/ebpf/events_enrich.go

```
Date:   Wed Jul 6 17:12:20 2022 +0000
enrich: fix enrichment skipping cgroup events
Some conditions were missing checks that the eventID wasn't a
cgroup event.
Because of that two things would happen:
1. Lifecycle cleaning from cgroup_rmdir wouldn't happen
2. cgroup_mkdir wouldn't trigger enrichment causing a race condition
for enrichment data in container_create
3. Another condition was missing which would falsley add enrichment data
to the cgroup events.
```
Fixes: #1936
As shown in #1936

enrich: fix enrichment skipping cgroup events

---

pkg/ebpf/c/tracee.bpf.c

Reverts aquasecurity/tracee#1928
Build fails on arm64 platforms after this change

Revert "ebpf: use new libbpf syscall macros"

---

pkg/events/parse_args.go

fix syscall argument not parsed on security_mmap_file
- command 01
- command 02

fix: add security_mmap_file syscall argument parsing

---

pkg/ebpf/events_enrich.go

Similar bug to the previous version of enrichment:
When cleaning the queue one last time on a cgroup_rmdir event
the range loop would run forever because the channel isn't closed yet.
As such an explicit length check is required before and in the loop.
In addition, the channel is now closed before being deleted.
```
Date:   Mon Jul 11 10:13:55 2022 +0000
enrich: fix lock in cleanup logic (cgroup_rmdir)
Similar bug to the previous version of enrichment:
When cleaning the queue one last time on a cgroup_rmdir event
the range loop would run forever because the channel isn't closed yet.
As such an explicit length check is required before and in the loop.
In addition, the channel is now closed before being deleted.
```
Fixes: #1953 …

enrich: fix lock in cleanup logic (cgroup_rmdir)

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h

We currently use pid_ns_for_children to resolve task's pid in the pid namespace it is in, which is wrong. 
Fix this and simplify logic to get task's ns pid.
Fixes: #1950
- command 01
- command 02
- [] I have made corresponding changes to the documentation.

ebpf: fix namespace pid resolution

---

mkdocs.yml

[MAINT] mkdocs: expand menu by default

---

Readme.md
docs/architecture.md
docs/building/containers.md
docs/building/macosx.md
docs/index.md
docs/installing/distros/fedora.md
docs/installing/distros/ubuntu.md
docs/installing/headers.md
docs/installing/kubernetes.md
docs/installing/prerequisites.md
docs/integrating/container-engines.md
docs/integrating/postee.md
docs/integrating/prometheus.md
docs/tracing/index.md
docs/tracing/output-options.md
docs/tutorials/deploy-grafana-dashboard.md

[MAINT] docs: fixes for the v0.8.0 release

---

pkg/ebpf/c/tracee.bpf.c

Signed-off-by: xjas <pdxzdc@foxmail.com>
when switch namespaces, use task->nsproxy to get the right old pid_ns_id
Fixes: #1972
- command 01
- command 02

ebpf: fix old pid_ns resolution when switch namespaces

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/kustomization.yaml
deploy/kubernetes/tracee-postee/tracee.yaml

helm: fix tracee version to latest release v0.8.0
Fixes: #1974

helm: fix tracee version to latest release v0.8.0

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/filters.go
pkg/ebpf/tracee.go

Refactor the filtering logic and make it simpler.
Avoid unnecessary map lookups where possible.
Manually, running all filters
- command 01
- command 02
- [ x New and existing unit tests pass locally with my changes.

ebpf: simplify filters logic

---

pkg/ebpf/c/tracee.bpf.c
pkg/events/events.go

Pass the ELF interpreter ctime upon execution similar to the executed
file.
Fixes: #1976 

pkg/ebpf: add interpreter ctime

---

pkg/ebpf/events_pipeline.go

When using container mode, container_create and container_remove events
were not emitted. Fix this.
Fix #1664
Manually 
- command 01
- command 02

pipeline: fix container lifecycle events

---

cmd/tracee-ebpf/capabilities.go
cmd/tracee-ebpf/main.go
pkg/ebpf/tracee.go

```
tracee: split new between new and init
This is done in order to allow extracting information from tracee before
it performs certain initializing operations which may require system
side effects (file reads, writes, service connections and so on).
```
Fixes: #1989 
Manual sanity tests (run with comm=ls, uid=0, etc.)

tracee: split new between new and init

---

pkg/containers/containers.go
pkg/ebpf/events_processor.go
pkg/ebpf/tracee.go

There is no need to have the containers_map bpf name given as argument.
Rely in PR workflows.

containers: containers_map set by package initialization

---

types/trace/trace.go
types/trace/trace_test.go

Flags will enable to pass Boolean information about the context from
the kernel.
Add the container context from the kernel in the new flags.
Type change for #1984 
Added to UTs.

types: add context flags with container flag to event

---

cmd/tracee-rules/output_test.go
go.mod
go.sum
pkg/bufferdecoder/decoder.go
pkg/bufferdecoder/protocol.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_pipeline.go
pkg/rules/engine/engine_test.go
types/trace/trace_test.go

Add a flag to all events marking whether the process is a part of a
started container.
This way tracee-rules will be able to use the logic of tracee-ebpf to
determine the origin of the event.
Fixes: #1967

Bugfix: container created flag

---

.github/workflows/pr.yaml

Disable the fail-fast strategy on the CORE and NONCORE matrix tests.
Fixes: #2020 
With this PR.

tests: disable fail-fast on pr workflow

---

pkg/ebpf/c/tracee.bpf.c

```
fix: verifier error on arm due to register reuse
```
Fixes: #2023
- tracee-ebpf on ARM

fix: verifier error on arm due to register reuse

---

cmd/tracee-rules/output_test.go
go.mod
go.sum
pkg/bufferdecoder/decoder.go
pkg/bufferdecoder/protocol.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_pipeline.go
pkg/rules/engine/engine_test.go
tests/kerneltest.sh
types/trace/trace.go
types/trace/trace_test.go

Attempt of clearing up the functional tests.

Cleanup tests

---

pkg/ebpf/probes/probes.go

There is an error in comment.
There is no need for testing.

pkg/probes: typo fix in comment

---

docs/events/security_alerts/symbols_loaded.md
pkg/ebpf/events_derived.go
pkg/events/derive/symbols_loaded.go
pkg/events/derive/symbols_loaded_test.go
pkg/events/events.go

Add event to monitor when loading an SO to a process, if it export
some symbols.
This event will add more functionality to shared objects monitoring,
and will help to monitor more dependency injections and hooks.
Fixes: #2013

pkg/ebpf: add event to monitor SOs exported symbols

---

.github/actions/build-dependencies/action.yaml
.github/workflows/pr.yaml
Makefile
pkg/ebpf/tracee.go
tests/integration/integration_test.go
tests/integration/tracee.go

```
integration: recomission the tests
Integration tests were  previously skipped and as such unmaintained
and were broken over time.
Fix the tests by redesigning them to locally run tracee.
```
Fixes: #2005 
Run tests locally by running:
`sudo env "PATH=$PATH" make test-integration`

recomission integration tests

---

Readme.md

fix prerequisite broken link in ReadMe file

---

pkg/ebpf/c/tracee.bpf.c

Fix false value upon execution of the first process in the container.
Also fixed saved task_info flags values, even though it currently not
used.
Fixes: #2043

Bugfix: pkg/ebpf: fix container started flag value

---

Makefile
cmd/tracee-bench/main.go
cmd/tracee-bench/main_test.go
cmd/tracee-bench/prometheus.sh
cmd/tracee-bench/prometheus.yml
cmd/tracee-bench/readme.md
go.mod
go.sum

```
Date:   Wed Jun 29 13:04:59 2022 +0000
add tracee-bench
tracee-bench is a cli tool to track performance information of
tracee based apps exported through prometheus.
Will be used as a performance probe as part of EPIC #1986.
```
Fixes: #1987
Test files were added in `tracee-perf`.
This will later be used in a performance gate as a PoC.

tracee-bench: benchmark tracee's performance through prometheus

---

cmd/tracee-ebpf/capabilities.go
docs/installing/prerequisites.md

Capabilities required by Tracee depend on the `perf_event_paranoid` kernel value.
Before this commit, Tracee required the `CAP_SYS_ADMIN` capability to be certain
to run on every configuration. This commit checks the `perf_event_paranoid` to ensure that
Tracee is running with required capabilities only, therefore reducing the exposition to security
issues.
Fixes: #1815

Add `perf_event_paranoid` dependent capability support

---

pkg/events/derive/symbols_loaded.go

Add whitelist for architectures libraries directories.
Fixes: #2047

pkg/events/derive: fix libs whitelist of symbols_loaded

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_processor.go
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/derive/hooked_seq_ops.go
pkg/events/events.go

commit 17b4c94551824780e6213d7bf7eacc82506324f6 (HEAD -> uprobe, origin/uprobe)
Date:   Sat Jul 30 15:57:10 2022 +0300
events: add context of triggering event to the triggered event
Retains the event context of the triggering event (e.g. hooked_syscall gets the context of the insmod that preceded it)
commit c62d19cfb0055ea1adac9abf4fdf4bb9e2fe3fdb
Date:   Mon Jun 6 16:00:37 2022 +0300
events: convert trigger events to uprobe
Change the way tracee-ebpf is triggering events.
Solves #2019
Fixes: #2019
Tested both on x86 and ARM.
`tracee-ebpf -t e=hooked_syscalls,hooked_seq_ops` and load a rootkit like diamorphine that hooks syscalls or seq ops.
Pick "Bug Fix" or "Feature", …

convert trigger events from ioctl syscall to a uprobe

---

docs/integrating/container-engines.md

docs: fix `docker run` command

---

pkg/ebpf/tracee.go

Signed-off-by: cdelzotti <elk1ns@outlook.fr>
Fixes: #2066 

fix : fix net filter pointer error

---

.github/workflows/test-daily.yaml
Makefile
Readme.md
tests/libbpfgo.sh

```
commit 42cada28d84ee98867899f81e17352447de63988 (HEAD -> daily-test, origin/daily-test)
Author: Geyslan Gregório <geyslan@gmail.com>
Date:   Thu Aug 11 15:01:49 2022 -0300
doc: add Tests (DAILY) badge to Readme.md
commit cd7d448056ea9132be924eb197df00be01e10c26
Author: Geyslan Gregório <geyslan@gmail.com>
Date:   Thu Aug 11 15:00:48 2022 -0300
workflows: add test-daily.yaml and libbpfgo.sh
Keep dependency (libbpfgo) tests inside tracee.
Create test-upstream-libbpfgo Makefile rule.
```
https://github.com/geyslan/tracee/runs/7862082846?check_suite_focus=true&ts=8#step:4:44
https://github.com/geyslan/tracee/runs/7797021090?check_suite_focus=true
Remote:
https://github.com/geyslan/tracee/actions/workflows/test-daily.yaml
Local:
make test-upstream-libbpfgo …

Add daily tests workflow and respective badge

---

pkg/ebpf/c/tracee.bpf.c

To save map lookups and space, remove bufs_off map
Manually
- command 01
- command 02

ebpf: remove bufs_off map

---

cmd/tracee-ebpf/flags/output.go
docs/tracing/output-options.md
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_pipeline.go
pkg/ebpf/tracee.go
pkg/events/parse_args.go

This is a rebase for PR: #1971 , squashing 2 commits and solving minor conflicts.

[REBASE ONLY] for the PR: #1971

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/probes/probes.go
pkg/events/events.go

This is a rebase of PR: #2045, solving Issue: #2042 because the online (github) interface conflict resolution made a mess in that PR.
@roikol FYI

[REBASE] events: add security_inode_rename event (rebase of PR: #2045)

---

pkg/ebpf/events_enrich.go

```
Date:   Sun Aug 21 14:15:37 2022 +0000
enrich: add queue cleaner goroutine
Instead of running cgroup_rmdir cleanup logic right away, cleanup logic
is queued similar to the scheduled enrichment tick.
If the queue is not ready to be cleaned yet (was not fully enriched)
cleanup will be rescheduled.
```
Fixes: #2083 
Quick test with running alpine container.
Also stress tested as in #1904.

enrich: add queue cleaner goroutine

---

pkg/ebpf/events_processor.go
pkg/events/trigger/context_test.go

```
Date:   Tue Aug 23 14:57:35 2022 +0000
trigger: fix context apply
Fixes applying the context from triggering event.
Previously the invoking context was applied with a reference assignment
however when the value went out of scope the reference popped back
to the previous value.
Also adds ContainerID and ProcessName to happy path tests as they are
critical fields.
```
Fixes: #2089
Described in #2089, ProcessName should now be `insmod`.

trigger: fix context apply

---

deploy/kubernetes/tracee-postee/kustomization.yaml

it should apply the local image name when using `kubectl -k`
- [] If part of an EPIC, PR git log contains EPIC number.
```
commit 4f39c8db41c15aa5fc67c75c6ea34ba00e72beb3 (HEAD -> k8s-fix-kustomization, origin/k8s-fix-kustomization)
Date:   Thu Aug 25 16:53:54 2022 -0300
k8s: fix kustomization.yaml
it should apply the local image name when using `kubectl -k`
```
Fixes: #2100
```
kubectl kustomize deploy/kubernetes/tracee-postee/ | grep image
image: tracee:latest
```

k8s: fix kustomization.yaml

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml

Fixes: #2097 
chore: updating tracee on helm/k8s 
```
helm install tracee ./deploy/helm/tracee     --namespace tracee-system --create-namespace     --set hostPID=true
```

k8s: fix tracee version to latest release v0.8.1

---

Readme.md

[MAINT] README: remove badge for removed workflow

---

pkg/ebpf/tracee.go
pkg/metrics/stats.go

refactor: style fixes

---

cmd/tracee-ebpf/flags/containers.go
pkg/containers/runtime/runtime.go
pkg/containers/runtime/sockets.go

```
Date:   Sun Aug 21 12:36:09 2022 +0000
containers/runtime: move autodiscover to package
This is done to in order to export the current autodiscover logic to
consuming applications.
```
Fixes: #1898 
Sanity testing container enrichment

containers/runtime: move autodiscover to package

---

pkg/events/events.go

change some events arguments types to `void*` so that they will be printed as hex values rather than decimal.
```
events: change addr arguments to type pointer
change arguments types of addresses to be pointers -
so they would be printed correctly
```
Fixes: #2127 
locally.
- command 01: `./dist/tracee-ebpf -t e=proc_create,kprobe_attach,debugfs_create_file,do_init_module`

events: change addr arguments to type pointer

---

pkg/ebpf/tracee.go
pkg/events/usermode.go

```
commit fcabd62f4fd4daf5af5e9769203cec3603678c99 (HEAD -> refactor-init-namespaces-event, origin/refactor-init-namespaces-event)
Date:   Tue Aug 30 16:22:03 2022 -0300
refactor: remove not used return argument
```
- [] Separate subject from body with a blank line.

refactor: remove not used return argument

---

deploy/kubernetes/tracee-falcosidekick/tracee.yaml

Add missing env var to falcosidekiq k8s deployment.
- [z] There is an issue describing the need for this PR.
- [z] Git log contains summary of the change.
- [z] Git log contains motivation and context of the change.
```
commit 3335b1c407d6c081858c62634afe1af2136e7620 (HEAD -> add-libbpf-env-var-falco-ds, origin/add-libbpf-env-var-falco-ds)
Date:   Wed Aug 31 22:02:00 2022 -0300
bug: add LIBBPFGO_OSRELEASE_FILE to falcosidekiq
Add missing env var to falcosidekiq k8s deployment
```
Fixes: #2141 
```
kubectl apply -f  deploy/kubernetes/tracee-falcosidekick/tracee.yaml 
```
Pick "Bug Fix" or "Feature", delete the other and mark appropriate …

bug: add LIBBPFGO_OSRELEASE_FILE to falcosidekiq

---

Makefile
builder/Makefile.checkers
cmd/tracee-ebpf/capabilities.go
cmd/tracee-ebpf/capabilities_test.go
docs/building/building.md
go.mod
go.sum
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/parse_args.go

Replacing: https://github.com/aquasecurity/tracee/pull/2095
with a few agreed changes.

v0.8.2 MILESTONE RELEASE FIXES

---

docs/tracing/output-options.md

docs/tracing: fix typo

---

signatures/rego/proc_fops_hooking.rego
signatures/rego/proc_fops_hooking_test.rego

commit 52d0a848f9ec0385e0c0c15a0d609626adad63a2 (HEAD -> fops_sig, origin/fops_sig)
Date:   Tue Sep 6 18:25:49 2022 +0300
signatures: add file_operations hooking signature
- clone https://github.com/nisay759/linux-rootkits/tree/master/phide
- compile
- load kernel module
- run tracee-ebpf with tracee-rules
- run ps

add file_operations hooking signature

---

go.mod
go.sum

Fix running tracee-ebpf compiled with go 1.19 by updating net.af/netaddr package, which cause the following error:
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.
Fix #2094 
- command 01
- command 02

tracee-ebpf: fix compilation with go 1.19

---

deploy/helm/tracee/Chart.lock
deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml

Fixes: #2161
- [] I have made corresponding changes to the documentation.

k8s: fix tracee version to latest release v0.8.2

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/events/events.go

Add unlinked file info to the event.
This way more hermetic rules could be written over it.
Fixes: #2135

pkg/ebpf: enrich security_inode_unlink

---

pkg/events/events.go

Device arguments are referenced as "dev" in other events. This PR renames "device" to "dev".
Device arguments are called `dev` in tracee - this renames `device` to `dev` in `security_inode_unlink`

events: rename security_inode_unlink device arg

---

cmd/tracee-ebpf/capabilities.go
cmd/tracee-ebpf/capabilities_test.go
go.mod
go.sum
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/parse_args.go
pkg/events/parse_args_test.go

Let's try to bump to libbpfgo v0.4.0 and libbpf 1.0.0 one more time, earlier in the milestone this time. Note that I'm bumping to a specific commit of libbpfgo because we needed the CGO fixes made by the following commit of that project:
commit 14c6bc9 (HEAD -> main, origin/main, origin/HEAD)
Author: rotscale <grantseltzer@gmail.com>
Date:   Fri Sep 16 13:44:11 2022
Move logic into C code via cgo
Quick change in test recently added by @AlonZivony at commit:
commit 03f9221d
Date:   Tue Sep 20 15:35:47 2022
parse_args: fix {get,set}sockopt new parse option
Because of needed changes (newer API).

[MAINT] Bump libbpfgo again

---

pkg/ebpf/c/tracee.bpf.c

bpf-nocore: remove compilation warnings and unused variables
Run:
```
make bpf-nocore
```
before and after the fixes.

[MAINT] bpf-nocore: remove compilation warnings and unused variables

---

Readme.md
docs/index.md
docs/tracing/index.md

Small documentation fixes
- command 01
- command 02

docs: small fixes

---

Readme.md

```
README: fix indention of "docker run" blocks
```
No issue, but was broken by: c0d24c74b42baeba8d489ce63ff58fd818fa1a63
Reading: https://github.com/Nirusu/tracee/tree/fix/readme

README: fix indention of "docker run" blocks

---

pkg/ebpf/tracee_test.go

Possible failure could happen because of mismatching MapIndexes order. This caused the elements to not match.
```
Date:   Thu Sep 22 13:05:06 2022 +0000
Test_getTailCalls: fix intermittent failure
Possible failure could happen because of mismatching MapIndexes order.
This caused the elements to not match.
```
Fixes: #2191
Changes in `tracee_test.go:Test_getTailCalls`

Test_getTailCalls: fix intermittent failure

---

deploy/helm/tracee/Chart.lock
deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml

- [] I have commented all functions/methods created explaining what they do.
- [] I have commented my code, particularly in hard-to-understand areas.

fix: change k8s version to 0.8.3

---

pkg/events/parse/params_test.go

Added unit tests for the argument parsing in tracee-rules:
[pkg/events/parse/params.go](https://github.com/aquasecurity/tracee/blob/main/pkg/events/parse/params.go)
Fixes: #2196 
```sh
cd pkg/events/parse
go test -v
```
- cd pkg/events/parse
- go test -v

Test: Add Unit tests for params under event parsing

---

types/trace/trace.go
types/trace/trace_test.go

Add support to all pointers types in the `UnmarshalJson` function.
Fixes: #1619

types/trace: support arbitrary pointers in json

---

pkg/ebpf/c/tracee.bpf.c

```
Date:   Wed Sep 28 13:35:12 2022 +0000
tracee.bpf.c: fix submit of shared_object_loaded
Event was implicitly dependent on Mmap syscall.
Since only the ID check was necessary for the event, the
get_task_syscall_id helper is used to resolve the issue.
```
Running `tracee-ebpf -t e=shared_object_loaded` and confirming output is emitted.

tracee.bpf.c: fix submit of shared_object_loaded

---

pkg/ebpf/c/tracee.bpf.c

Make sure that all save_args paths call in the end to the del_args function to clean up the args_map BPF map.
Fixes: #2173
Using the same test that I found the bug with - great load of events and check if the `register_chrdev` is passed.

pkg/ebpf: quick fix for args_map memory leak

---

cmd/tracee-ebpf/main.go
cmd/tracee-rules/main.go
pkg/logger/logger.go

commit 37e3bce1e70b27645d71dcf80e0a4c37b3db89ab (HEAD -> 2206-api-change, origin/2206-api-change, main)
Author: Geyslan Gregório <geyslan@gmail.com>
Date:   Thu Sep 29 11:38:38 2022 -0300
logger: use new logger API
commit bd2998e8b68ffbf1e0f1bbc6655bb74903632e8d
Author: Geyslan Gregório <geyslan@gmail.com>
Date:   Thu Sep 29 11:21:40 2022 -0300
logger: change public API
Get rid of 'w' suffix in the public API.
Private functions remained with their suffix, making it clear
what do they mean for the wrapped zap logger and avoiding naming
override (e.g. panicw vs panic)
Fixes: #2206

[REFAC] Change logger API function names

---

pkg/ebpf/events_enrich.go

`enrichment: skip enriched events`
Added a "skipped" internally for testing if skipping occurs and running
`sudo ./dist/tracee-ebpf --containers -t c -o json`
`docker run --rm redis`
and confirming events were properly enriched and "skipped" was outputted".
In addition ran the stress test from #1873 

enrichment: skip enriched events

---

docs/events/kprobes/do_sigaction.md
pkg/bufferdecoder/eventsreader.go
pkg/ebpf/c/missing_definitions.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/ebpf/probes/probes.go
pkg/events/events.go

Created a new event for the case that a user change signal handler (aka sigaction operation).
Fixes: #2185 

[Feature] Signal handling change event

---

.github/workflows/publish-helm.yaml

Fixes https://github.com/aquasecurity/tracee/issues/2244

k8s: fix helm publishing

---

.github/workflows/publish-helm.yaml
deploy/helm/tracee/Chart.lock

A quick fix to be able to publish helm.

Fix helm publishing

---

cmd/tracee-ebpf/flags/cache.go
cmd/tracee-ebpf/flags/capabilities.go
cmd/tracee-ebpf/flags/capture.go
cmd/tracee-ebpf/flags/containers.go
cmd/tracee-ebpf/flags/filter.go
cmd/tracee-ebpf/flags/help.go
cmd/tracee-ebpf/flags/help_test.go
cmd/tracee-ebpf/flags/output.go
cmd/tracee-ebpf/main.go
cmd/tracee-ebpf/main_test.go

Fix https://github.com/aquasecurity/tracee/issues/2240

refactor: improve help handling

---

tests/integration/integration_test.go

This is a mitigation until https://github.com/aquasecurity/tracee/issues/2073 is solved.

[MAINT] integration: fix integration tests

---

docs/events/kprobes/kallsyms_lookup_name.md
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/probes/probes.go
pkg/events/events.go
pkg/events/parse_args.go

This is just a rebased version of https://github.com/aquasecurity/tracee/pull/2122

events: add kallsyms_lookup_name event

---

cmd/tracee-bench/main.go
cmd/tracee-rules/input.go
cmd/tracee-rules/main.go
cmd/tracee-rules/output.go
cmd/tracee-rules/signature.go
pkg/rules/benchmark/benchmark_test.go
pkg/rules/engine/engine.go
pkg/rules/engine/engine_test.go

All the places where the "log" package was being used has now been migrated to our own logger
```sh
commit 3fc1ef9112422157ceb822b6a7f307387952d274 (HEAD -> shubhamm/implement-new-logger, myfork/shubhamm/implement-new-logger, shubham/refactor-logger)
Author: ShubhamPalriwala <spalriwalau@gmail.com>
Date:   Tue Oct 11 18:16:56 2022 +0530
feat: migrate to aqua logger in pkg/rules/engine
commit 52bd6f15d170aa583a28775345e894a5deae35be
Author: ShubhamPalriwala <spalriwalau@gmail.com>
Date:   Sat Oct 8 14:31:13 2022 +0530
feat: migrate to aqua logger in cmd/tracee-rules/signature
commit a62d5c66c2e298f0dd6cdb428fbe2d1487adc3ed
Author: ShubhamPalriwala <spalriwalau@gmail.com>
Date:   Sat Oct 8 14:23:41 2022 +0530
feat: migrate to aqua logger in …
```

Migrate log calls to our own logger package

---

.github/workflows/publish-helm.yaml

Fixes: https://github.com/aquasecurity/tracee/issues/2262

k8s: add kind to helm publishing for testing

---

RELEASING.md

Fix https://github.com/aquasecurity/tracee/issues/2269

docs: update RELEASING.md to publish helm

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

This updates the git tag for tracee in the deployment scripts in advance of us cutting tracee v0.8.4. This will allow for the correct version to be part of the release and fix helm installations.

Update tracee tags in deployments

---

Readme.md
docs/getting-started/docker-quickstart.md
docs/getting-started/kubernetes-quickstart.md
docs/index.md
mkdocs.yml

commit aa17da2236668782d49351a894a79daef7f4d492 (HEAD -> k8s-quickstart, pfork/k8s-quickstart)
Date:   Thu Oct 20 17:01:08 2022 -0400
Add quickstart guide to using tracee in k8s
This creates a quickstart guide that uses minikube to demonstrate
how to install, and run tracee with the goal of explaining its
value as well.

Add quickstart guide to using tracee in k8s

---

docs/getting-started/installing/kubernetes.md

Fix for https://github.com/aquasecurity/tracee/issues/2219

docs: fix helm install

---

docs/getting-started/docker-quickstart.md
docs/getting-started/installing/docker.md
docs/getting-started/kubernetes-quickstart.md
docs/index.md

docs: fix broken links

---

pkg/ebpf/tracee.go

After the change in the filters, we can no longer assume the arguments filters are always initialized.
Fix a bug that caused using nil pointer of a filter.
#2285

pkg/ebpf: fix symbols_loaded initialization crash

---

cmd/tracee-rules/main.go
pkg/capabilities/capabilities.go
pkg/containers/path_resolver.go
pkg/containers/path_resolver_test.go
pkg/ebpf/events_processor.go
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/derive/symbols_loaded.go
pkg/utils/sharedobjs/host_symbols_loader.go

This is needed for the next release and I need asap, so I'm merging without further reviews. Both, local and e2e tests have passed with this version (and that is why I will merge asap).

Raise capabilities for privileged operations. DO not drop by default.

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

Fix k8s tags for upcoming release.

k8s: update image tag to latest

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

Preparing for release 0.9.2, updating k8s files to  tag 0.9.2

k8s: update version to 0.9.2

---

signatures/golang/export.go

FIx for https://github.com/aquasecurity/tracee/issues/2296

k8s: disable signature TRC-108

---

cmd/tracee-ebpf/flags/capabilities.go
cmd/tracee-rules/main.go
go.mod
go.sum
pkg/capabilities/capabilities.go
pkg/containers/path_resolver.go
pkg/containers/path_resolver_test.go
pkg/ebpf/events_processor.go
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/utils/sharedobjs/host_symbols_loader.go

libbpf was mistakenly moved to another version during a rushed release.

Last touches before v0.9.2 (kubecon)

---

pkg/ebpf/tracee.go
pkg/events/events.go

```
tracee: remove invalid events from tailcalls
On some architecture the default tail calls may include events that do
not exist, for example in ARM64 the "open" syscall is missing but
security_file_open requires it as a traced syscall in "sys_enter_init_tails".
As such when extracting tail calls during initialization we remove the
invalid event ids from tail calls.
In addition, when getting a direct tracing request for a syscall event
which does not exist, we skip adding it's index to the syscall tracing
tail call maps.
```
Fixes: #2309
In `amd64.go` change `Open` ID to `10000`.
Then run tracee-ebpf with no arguments.
It should not break.

tracee: remove invalid events from tailcalls

---

cmd/tracee-ebpf/flags/filter.go
cmd/tracee-ebpf/flags/filter_test.go
pkg/events/events.go

```
Date:   Sun Oct 30 12:27:29 2022 +0000
filter: fix wildcard not working for events
Preparing events to trace uses the filter's package StringFilter object.
However this logic doesn't actually need full "filter" logic as such
a simpler data structure similar to the old string filter is used
for this logic (sets and events parsing).
```
Fixes: #2306 
Do `tracee-ebpf -t e=sched_proc*`

filter: fix wildcard not working for events

---

.github/workflows/pr.yaml

workflows: change pr to new runners

---

pkg/ebpf/c/tracee.bpf.c

In cases where both security_file_mprotect and mem_prot_alert events were chosen by the user, mem_prot_alert could have failed to decode or have invalid arguments. This was caused by the fact we submitted those two events one after the other without reinitializing the submit buffer.
Fix mem_prot_alert event by initializing the submit buffer as required.
While at it, also remove redundant buffer initialization at sys_enter and sys_exit.
- command 01
- command 02

ebpf: fix mem_prot_alert invalid args

---

.github/workflows/pr.yaml

workflows: add stream8 back

---

3rdparty/btfhub.sh

[MAINT] btfhub: adjust ol7 path after btfhub change

---

.github/workflows/publish-helm.yaml
deploy/helm/tracee/Chart.lock
deploy/helm/tracee/Chart.yaml
docs/getting-started/installing/kubernetes.md
docs/tutorials/setup-development-machine-with-vagrant.md

Fixes: #2287 
```
$ helm repo add aqua https://aquasecurity.github.io/helm-charts
$ helm dependency update ./deploy/helm/tracee
$ helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true
```

k8s: fix postee dependency

---

docs/contributing/events/lsm_hooks/security_file_mprotect.md
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/tracee_test.go
pkg/events/events.go
pkg/events/parse_args.go

Add missing information in the security_file_mprotect, like address and len of operation.
Add support to the `pkey_mprotect` syscall too.
Fixes: #2334 
Ran the event with the `mprotect` and `pkey_mprotect` to check that the event works well.

pkg/ebpf: add syscalls arguments to security_file_mprotect

---

pkg/ebpf/c/tracee.bpf.c
pkg/events/events.go

add stdin_path argument to sched_process_exec event
add `stdin_path` argument to the `sched_process_exec` event.
Fixes: #2215
locally.
- command 01: `./dist/tracee-ebpf -t e=sched_process_exec`

feature: add stdin path to sched_process_exec

---

pkg/ebpf/events_enrich.go

Cleanup logic on cgroup_rmdir was missing sending the event out, causing the event to be "lost".
```
Date:   Tue Nov 15 09:21:39 2022 +0000
events_enrich: fix missing container_remove event
Cleanup logic on cgroup_rmdir was missing sending the event out, causing
the event to be "lost".
```
Fixes: #2347 
1. `tracee-ebpf --containers -t e=container_remove`
2. `docker run --rm ubuntu`

[FIX] events_enrich: fix missing container_remove event

---

docs/contributing/events/security_alerts/mem_prot_alert.md
pkg/ebpf/c/tracee.bpf.c
pkg/events/events.go
pkg/events/parse_args.go

The `mem_prot_alert` event currently only pass the alert, but not the context for it.
By passing more arguments a more in-detailed analysis can be taken. Also, event was missing documentation so created new one with new args.
Fixes: #2338
Manual tests

pkg/ebpf: add arguments and doc to mem_prot_alert

---

pkg/ebpf/tracee.go
pkg/events/events.go

When an event has a missing symbols dependency which it defines as crucial for its operation, it will be canceled with matching error message.
Fixes: #2367

pkg/ebpf: cancel event with missing symbols dependency

---

pkg/ebpf/tracee.go
pkg/events/derive/symbols_loaded.go
pkg/events/derive/symbols_loaded_test.go
pkg/utils/proc/ns.go
pkg/utils/proc/ns_test.go

Tracee access containers files using the procfs, accessing the root directory of a process in the mount namespace from its /proc directory. Until now tracee did not get existing mount namespaces upon initialization, causing many errors.
Now we get processes from all existing mount namespaces using iteration on the procfs.
Fixes: #2062 

pkg/ebpf: process existing mount ns upon initialization

---

pkg/capabilities/capabilities.go
pkg/ebpf/tracee.go
pkg/procinfo/procinfo.go
pkg/utils/proc/ns.go

commit c7733ca2
Date:   Fri Nov 25 16:31:41 2022
pkg/ebpf/tracee: raise capabilities for procfs reads
Fixes: #2379
commit e311d81f
Date:   Fri Nov 25 14:19:15 2022
pkg/capabilities: logger already includes pkgname
commit 4761ea88
Date:   Fri Nov 25 14:17:56 2022
pkg/procinfo: add debug warnings for errors
Without those, the package was failing silently because of missing
capabilities when capabilities were being dropped.
commit 4514ef8a
Date:   Fri Nov 25 14:15:55 2022
proc/ns: fix logger calls missing var names
```
$ sudo TRACEE_LOGGER_LVL=debug ./dist/tracee-ebpf --trace …
```

Fix capabilities initialization

---

.github/workflows/pr.yaml

- Add an Ubuntu with upstream v6.0 kernel
- Add an Ubuntu Focal with upstream v4.19 kernel (non-core)

[MAINT] workflows/pr: add kinetic60 and focal419

---

types/trace/network_trace.go

There are the types used for the new network code at https://github.com/aquasecurity/tracee/pull/2200

types: add network protocol events types

---

pkg/ebpf/events_processor.go

The thread start time of the `sched_process_fork` was in monotonic time until now. Change it to time since epoch, so it will be comparable to other times, like what is done for the event timestamp.
Fixes: #2386

pkg/ebpf: change fork thread start time to be since epoch

---

cmd/tracee-rules/main.go
cmd/tracee-rules/testdata/signatures/anti_debugging_ptraceme.rego
cmd/tracee-rules/testdata/signatures/code_injection.rego
cmd/tracee-rules/testdata/signatures/helpers.rego
pkg/rules/signature/signature.go
pkg/rules/signature/signature_test.go
pkg/rules/signature/testdata/signatures/anti_debugging_ptraceme.rego
pkg/rules/signature/testdata/signatures/code_injection.rego
pkg/rules/signature/testdata/signatures/helpers.rego

Fix https://github.com/aquasecurity/tracee/issues/2414

tracee-rules: extract getSignatures

---

pkg/ebpf/tracee.go

In cases where net features are disabled or the blob perf buffer is set to 0, disable their respective perf buffers and event processing logic.
This will help reduce kernel memory footprint of tracee in some workloads, and increase the chance of available memory for the main event perf buffer.
```
Date:   Thu Dec 1 13:57:14 2022 +0000
tracee: make some perf buffers optional
In cases where net features are disabled or the blob perf buffer is
set to 0, disable their respective perf buffers and event processing
logic.
```
Fixes: #2422
Run `tracee-ebpf --blob-perf-buffer-size 0`
Run `tracee-ebpf --trace net=docker0 --trace event=dns_request` then in a container `apt-get update` …

tracee: make some perf buffers optional

---

pkg/counter/counter.go
pkg/counter/counter_test.go
pkg/ebpf/events_processor.go
pkg/ebpf/net_events.go
pkg/ebpf/write_capture.go
pkg/events/trigger/context.go

3a4a95a
pkg/counter: change Counter type
- change count type to uint64
- encapsulate the count avoiding non-atomic override
- atomic override can be done with Set()
- Increment() and Decrement() now return error if wrap occurs
Fixes: #2410 #2428

pkg/counter: change Counter type

---

tests/integration/integration_test.go

commit 8d589709e4215c0942c5819a5f25e0e8c354a3a5 (HEAD -> integration-test-script-fixes, pfork/integration-test-script-fixes)
Date:   Fri Nov 18 11:09:11 2022 -0500
Embed test script and import environment variable
Fixes: #2330 #2331
Compile integration tests and run

Embed test script and import environment variable

---

pkg/ebpf/c/tracee.bpf.c

Change the `security_file_mprotect` kprobe so it will compile to less instructions, also achieving performance improvement at the same time. This is done to bypass the verifier of kernel 4.19.
Fixes: #2420
Compiled and ran both `security_file_mprotect` and `mem_prot_alert` without issues.

pkg/ebpf: reduce security_file_mprotect instructions

---

docs/docs/tracing/output-formats.md
pkg/cmd/flags/flags_test.go
pkg/cmd/flags/output.go
pkg/cmd/printer/printer.go
pkg/cmd/printer/printer_test.go
pkg/cmd/tracee.go
pkg/cmd/urfave/urfave.go
pkg/containers/runtime/sockets.go
pkg/ebpf/events_pipeline.go
pkg/ebpf/events_processor.go
pkg/ebpf/net_events.go
pkg/ebpf/tracee.go
pkg/ebpf/write_capture.go
pkg/events/sorting/sorting.go
pkg/logger/logger.go
tests/integration/tracee.go
types/detect/detect.go
types/protocol/protocol.go

commit 4fcc4735089633ae623a3115aa0f9b3bcb6026b1
```
tracee-ebpf: enable log redirection
Change the err-file flag to log-file, which handles redirecting
tracee-ebpf's log output.
```
commit 94efde27687d7eadc7b3b0653feb5e368557f85d
```
errors: remove error channel and printer
tracee.handleError redirects errors to the logger instead of an error
channel.
Additionally, the printer's error method is also removed, using the
logger for printing errors too.
```
Fixes: #2404
tracee-ebpf -o log-file:test

Streamline error logging

---

cmd/tracee-rules/main.go
pkg/rules/benchmark/benchmark_test.go
pkg/rules/engine/engine.go
pkg/rules/engine/engine_test.go

Fix for https://github.com/aquasecurity/tracee/issues/2437
Context: https://github.com/aquasecurity/tracee/pull/2374#discussion_r1033326102

rules: refactor engine.New to receive sigs via Cfg

---

docs/docs/detecting/avd.md
docs/docs/detecting/index.md
docs/docs/detecting/rules.md
mkdocs.yml

Add AVD links to rules page
- command 01
- command 02

Add AVD link from detection docs

---

pkg/cmd/printer/printer.go

Fixes https://github.com/aquasecurity/tracee/issues/2430

tracee: trim event name for table output

---

pkg/capabilities/capabilities.go
pkg/ebpf/tracee.go

74e0c517 caps: log errors from caps Requested and cb func
Fixes: #2458

caps: log errors from caps Requested and cb func

---

tests/e2e-net-test.sh

... or else the v419 non CORE tests will fail.
Fixes: commit 8c67067b
Fixes: PR: #2456 (it had a bug)

network: e2e-net-test v419 skip should return 0

---

pkg/events/sorting/sorting.go

In multiple places in the sorting feature, there was an assumption that the queues don't change between atomic operations. There are also places that doesn't check call success at all. Now we check before usage in found problematic places the integrity of queue operations results.
Fixes: #2449

sorting: add race condition checks for queues usage

---

Makefile
docs/getting-started/docker-quickstart.md
docs/getting-started/kubernetes-quickstart.md

Quick start update & adding commands to create docs previous to Makefile

---

pkg/events/events.go

debugfs_create_file event has CAP_NET_ADMIN dependency which is not actually required. Remove this dependency.
- command 01
- command 02

events: remove unused dependency

---

pkg/ebpf/events_enrich.go
pkg/ebpf/events_processor.go
pkg/events/derive/container_create.go
pkg/events/derive/container_remove.go
pkg/events/derive/detect_hooked_syscall.go
pkg/events/derive/hooked_seq_ops.go
pkg/events/derive/symbols_loaded.go
pkg/events/parse/params.go
pkg/events/parse/params_test.go
pkg/events/trigger/context.go

All of the argument parsing functions were duplicates except for the type.
Change them to be one generic function.

pkg/events/parse: use generic function to parse args

---

docs/docs/tracing/network-events.md
mkdocs.yml

Execute:
```
make -f builder/Makefile.mkdocs mkdocs-serve
```
To read and test it.

docs: add network events documentation to mkdocs

---

builder/entrypoint.sh

commit ca346d16e273f8cdc53e24034a02718c2d8d82ab
builder: add custom-rules arg opt to entrypoint.sh
For docker must be used like
docker run -v /your/custom/rules/dir:/custom-rules:ro ... custom-rules
Context: #2402
Fixes: #2402

[FEAT] builder: add custom-rules arg opt to entrypoint.sh

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

bump kubernetes tags for next release!

k8s: bump tag to 0.10.0

---

docs/docs/tracing/event-filtering.md
pkg/cmd/flags/filter.go
pkg/cmd/flags/filter_test.go
pkg/ebpf/bpf_error.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/filters.go
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/events.go
pkg/filters/string.go

Fixes: #2405 
- command 01
- command 02

Binary filter

---

docs/docs/tracing/event-filtering.md
pkg/ebpf/c/tracee.bpf.c

Currently the pid filter actually filters for tid. This is not the desired behavior since the user may want to trace the different threads of the same process. Fix this by looking at the host pid while keeping support for tracing specific threads using their tid.
- command 01
- command 02

ebpf: fix pid filter

---

docs/contributing/events/security_alerts/bpf_attach.md
pkg/ebpf/c/tracee.bpf.c
pkg/events/events.go

```
Date:   Thu Dec 15 14:46:18 2022 +0200
docs/bpf_attach: add documentation for bpf_attach event
```
Fixes: #2308
- command 01
- command 02

docs/bpf_attach: add documentation for bpf_attach event

---

go.mod
go.sum

Update to include the latest update to the types package, so will have more precise error messages from the `UnmarshalJson` function.
- command 01
- command 02

go.mod: update types to have more precise UnmarshalJson error

---

pkg/cmd/flags/filter_test.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/tracee.go
pkg/events/events.go

The sched_process_free event caused buffer corruptions on event buffers which belong to other CPUs. Further investigation is required to understand why this happend. Until then, remove this event.
- command 01
- command 02

ebpf: remove sched_process_free event

---

pkg/ebpf/c/tracee.bpf.c

interpreter_map is used to save interpreter file info per process. Now that we have the proc_info_map, we can save it there and remove the interpreter map.

ebpf: remove interpreter map

---

pkg/ebpf/c/tracee.bpf.c

Instead of using the submit buffer to initialize task and proc info maps, use dedicated scratch maps. Also take the opportunity to generalize the scratch concept by having a dedicated scratch map. The scratch map contains a union of types which we use in various places to avoid consuming stack space.
- command 01
- command 02

ebpf: use scratch map for task and proc info maps

---

pkg/ebpf/c/tracee.bpf.c

ebpf: refactor init_task_info

---

pkg/ebpf/c/tracee.bpf.c

Whenever we call init_task_info we already did a map lookup in task_info_map. Remove the extra redundant lookup in the function.
- command 01
- command 02

remove redundant task info lookup

---

docs/contributing/events/security_alerts/symbols_loaded.md

We changed the API for using events args filters, but didn't update the events docs.
- command 01
- command 02

docs: Change symbols_loaded doc to use new arg filters API

---

types/trace/network_trace.go

add HTTP request and HTTP response types for future HTTP events.
```
Date:   Thu Dec 29 17:57:03 2022 +0200
trace: add types of HTTP events
add HTTP request and HTTP response types for future HTTP events
```
this PR is the first part to solve this issue: #1385.
(next part will be the actual HTTP events).
- command 01
- command 02

trace: add types of HTTP events

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/probes/probes.go
pkg/events/events.go
pkg/events/parse_args.go

Create internal mmap flow event which has access to both mapped file
and its mapped address.
Fixes: #2469

pkg/ebpf: create `do_mmap` event

---

pkg/ebpf/c/tracee.bpf.c

After merging #2517 and #2537 one after the other build fails. Fix this.
- command 01
- command 02

fix: build

---

pkg/ebpf/events_pipeline.go
pkg/ebpf/events_processor.go
pkg/ebpf/tracee.go

```
Date:   Wed Dec 21 14:00:32 2022 +0000
pipeline: change event processing to be map based
The event processing part of the pipeline's mechanism is changed from a
hard coded switch statement to use a map which registers for each event
id it's processing functions.
By using this mechanism we can expose a function to register such a
processor programatically, which will be useful later for future tracee
event plugins.
```
Did a manual sanity check with `hooked_proc_fops` and the `phide` rootkit which is an event going through processing.

pipeline: change event processing to be map based

---

deploy/helm/tracee/Chart.lock
deploy/helm/tracee/templates/daemonset.yaml
deploy/helm/tracee/values.yaml

Fixes: #2505
I ran the following command to get the Helm Chart as the Kubernetes resources like they would be deployed:
`helm install --dry-run tracee ./deploy/helm/tracee`
- check out my brach and run: `helm dependency update /deploy/helm/tracee` and then `helm dependency build /deploy/helm/tracee`
- and then above command

modifying webhook in tracee Helm Chart

---

go.mod
go.sum
pkg/ebpf/ksymbols.go
pkg/ebpf/tracee.go
pkg/events/derive/detect_hooked_syscall.go
pkg/events/derive/hooked_seq_ops.go
pkg/utils/utils.go

use new libbpgo kernel symbols Refresh method so that kernel symbols will be up-to-date throughout all components
```
Date:   Tue Jan 3 19:47:02 2023 +0200
ebpf: use new kernel symbols from libbpfgo
use new libbpgo kernel symbols Refresh method so that
kernel symbols will be up-to-date throughout all components
```
Fixes: #2526
using POC of seq_ops hooks (can be provided).
now we get the correct values for `hooked_seq_ops` event:
`19:19:35:747254  0      insmod           49240   49240   0                hooked_seq_ops       hooked_seq_ops: map[tcp4_seq_ops_show:{hook_tcp4_seq_show main}]`

ebpf: use new kernel symbols from libbpfgo

---

docs/docs/capturing/index.md
pkg/bufferdecoder/eventsreader.go
pkg/cmd/flags/capture.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_pipeline.go
pkg/ebpf/net_capture.go
pkg/ebpf/tracee.go
pkg/events/derive/net_packet_icmp.go
pkg/events/derive/net_packet_icmpv6.go
pkg/events/derive/net_packet_ipv4.go
pkg/events/derive/net_packet_ipv6.go
pkg/events/derive/net_packet_tcp.go
pkg/events/derive/net_packet_udp.go
pkg/events/events.go
pkg/metrics/stats.go
pkg/pcaps/cache.go
pkg/pcaps/common.go
pkg/pcaps/pcap.go
pkg/pcaps/pcaps.go
pkg/utils/utils.go

**network: add cgroup based pcap capture code**
The new cgroup based pcap capture code is able to capture ANY TCP, UDP or ICMP packet for both IPv4 and IPv6 protocols from any physical (L1) and link (L2) layers.
Differently than the current existing pcap capture code, this new approach allows tracee to capture packets from any process on the host or in a container, independently of the interfaces they are using to communicate. There is no need to bind a tc hook program to a specific interface now.
```
$ tracee-ebpf --capture network
```
There is also a mid layer code responsible for managing opened pcap files using a LRU cache (so tracee has a limit on amount of opened files being used).
Another feature is the capability of selecting one or multiple pcap file types to have captured:
- per …

network: add cgroup based pcap capture code

---

go.mod
go.sum
pkg/ebpf/events_processor.go
pkg/events/parse_args.go

Related #2177
1. Run `tracee-ebpf -t e=security_kernel_read_file -o json`
2. Install a kernel module
3. Confirm that the `type` argument is 2
4. Run the same with table printer, confirm the `type` argument is `kernel-module`

Normalize kernel read type

---

signatures/helpers/helpers.go
tests/e2e-net-rules/e2e-http.go
tests/e2e-net-rules/export.go
tests/e2e-net-rules/scripts/http.sh

```
Date:   Thu Jan 12 16:00:55 2023 +0200
add e2e test for http events
```
Fixes: #1385
- command 01
- command 02

add e2e test for http events

---

pkg/ebpf/bpf_log.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/events_pipeline.go
pkg/ebpf/events_processor.go
pkg/ebpf/ksymbols.go
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/events.go
pkg/filters/args.go

The event is used to dump the content of memory addresses or symbols.
The symbol or address to be dumped is provided via the event filter:
provide it via `-t print_mem_dump.args.address=<hex address>`, `-t print_mem_dump.args.symbol_name=<owner>:<symbol>` or `-t print_mem_dump.args.symbol_name=<symbol>` if specifying a system owned symbol
commit 7685dd1ea6afb5c52ef7191eb7ad71b241301dd1 (HEAD -> mem_dump, origin/mem_dump)
Date:   Sun Dec 4 17:59:45 2022 +0200
events: add print_mem_dump event
The event is used to dump the content of memory addresses or symbols.
Fixes: #2481
dumping both address and symbols based values from the memory and viewing as it printed after kernel module loading. …

events: add print_mem_dump event

---

pkg/ebpf/events_enrich.go

```
Date:   Sun Jan 15 11:19:10 2023 +0000
enrich: fix remove and create ordering
container_remove will arrive before container_create and other events
from the container because it is immediately sent out before the enrich
queue is fully emptied.
Fix this by making the notification channel for cleaning triggered by
the cgroup_rmdir event itself, thus guaranteeing that it is the final
event from the cgroup being sent out.
```
Fixes: #2583
Test by doing the procedure from #2583 but noting that `container_create` arrives first.

enrich: fix remove and create ordering

---

cmd/tracee-rules/output_test.go
go.mod
go.sum
pkg/containers/runtime/containerd.go
pkg/containers/runtime/crio.go
pkg/containers/runtime/docker.go
pkg/containers/runtime/runtime.go
pkg/ebpf/events_pipeline.go
pkg/events/derive/container_create.go
pkg/events/events.go
pkg/events/usermode.go

containers: add sandbox container awareness
Add a new argument "pod_sandbox" and event field to container events to
indicate the container's type in its pod.

Enrich pod sandbox

---

docs/docs/integrating/container-engines.md
pkg/cmd/flags/containers.go
pkg/containers/containers.go

```
Date:   Mon Jan 16 14:52:07 2023 +0000
containers: register DockerEnricher for podman
Docker and Podman use a compatible HTTP api which the docker client sdk
uses in the backend.
Therefore, using the docker's enricher for podman runtime will fully
work to support the latter.
```
Run `tracee-ebpf -t e=container_create --containers`
Run `sudo podman run --rm ubuntu` OR `podman run --rm ubuntu`
`container_create` event should be correctly enriched.

containers: register DockerEnricher for podman

---

cmd/tracee-rules/input.go
cmd/tracee-rules/main.go
pkg/rules/celsig/config.go
pkg/rules/signature/signature.go

Until now, after dropping the effective capabilities, tracee-rules wouldn't raise privileges when needed, always erroring when executed as root (instead of doing the correct: dropping all privileges).
This patch fixes this issue.
Run tracee-rules with "sudo" and see permission issues when trying to read ./dist/rules directory, for example. After the patch you can run the same command and it will be able to read the directory because of added CAP_DAC_OVERRIDE capability that was raised when needed.

rules: raise privileges when needed if user root

---

docs/contributing/events/kprobes/vfs_read.md
docs/contributing/events/kprobes/vfs_readv.md
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/probes/probes.go
pkg/events/events.go

Create new events for reading files from the file system using buffer or a vector.
This feature will enable to handle read operations, in the hope to develop it like was done for writing.
Fixes: #2320

pkg/ebpf: add vfs_read and vfs_readv events

---

docs/docs/capturing/index.md
pkg/cmd/flags/capture.go
pkg/cmd/flags/flags_test.go
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/net_capture.go
pkg/pcaps/common.go
pkg/pcaps/pcap.go
pkg/pcaps/pcaps.go

network: pcap default cap mode to a single file
Fixes: #2587

network: pcap default cap mode to a single file

---

pkg/ebpf/c/tracee.bpf.c

In some cases, uts name may have some extra characters which are wrong. This is caused because we didn't properly initialize it with zeros, required since we move event_context to a map.
This commit fixes this problem.
- command 01
- command 02

fix: bad uts name

---

pkg/ebpf/c/tracee.bpf.c

commit 4ef3b231
Date:   Tue Jan 24 01:23:28 2023
ebpf: fix network events corruption
Do not share scratch buffer (from array maps) between network and regular
probes. This solves problems such as:
{"level":"error","ts":1674523484.3078973,"msg":"tracee encountered an
error","error":"failed to read argument 0 of event net_packet_capture: error
reading byte array: can't read context from buffer: buffer too short"}
{"level":"debug","ts":1674523484.3081043,"msg":"network capture: no payload
packet","pkg":"ebpf","file":"net_capture.go","line":89}
Note: This change also allows init_program_data() to use event_data and scratch
area from the stack of the caller, not only from an array item from a global
map.
Note: It is not clear yet why this …

ebpf: fix progs from kthread ctx might preempt work

---

builder/Makefile.tracee-container

- replace #2451 leftover debug flag
- remove an unintentional single quote mark (... follow')
Fix: #2622

docs: fix Makefile help rule (--log debug)

---

docs/docs/tracing/event-filtering.md
docs/docs/tracing/scopes.md
mkdocs.yml

- Add scopes.md file.
- Add reference to scopes.md in event-filtering.md.
- Updates mkdocs.yml
Complementary of:
- #2238
- #2626

docs: introduce scopes documentation

---

.github/workflows/test-os-packaging-daily.yaml
.gitignore
builder/Makefile.packaging
docs/contributing/building/packaging.md
packaging/Dockerfile.ubuntu-packaging
packaging/fedora/tracee.spec
packaging/ubuntu/control
packaging/ubuntu/rules

- update releases in both fedora and ubuntu
- include tracee single binary in both package types
- update documentation about this change

packages: update distro packaging files

---

pkg/ebpf/events_pipeline.go
pkg/ebpf/tracee.go
pkg/events/derive/container_create.go
pkg/events/derive/container_remove.go
pkg/events/derive/derive.go
pkg/events/derive/derive_test.go
pkg/events/derive/detect_hooked_syscall.go
pkg/events/derive/errors.go
pkg/events/derive/hooked_seq_ops.go
pkg/events/derive/net_packet_dns.go
pkg/events/derive/net_packet_http.go
pkg/events/derive/net_packet_icmp.go
pkg/events/derive/net_packet_icmpv6.go
pkg/events/derive/net_packet_ipv4.go
pkg/events/derive/net_packet_ipv6.go
pkg/events/derive/net_packet_tcp.go
pkg/events/derive/net_packet_udp.go
pkg/events/derive/symbols_loaded.go

tracee: add event derivation registering

---

pkg/cmd/tracee.go

cli: fix: event list table header alignment

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

bump kubernetes tags for next release!

k8s: bump tracee version

---

RELEASING.md
docs/docs/capturing/index.md
docs/docs/tracing/event-filtering.md
pkg/cmd/flags/capabilities.go
pkg/cmd/flags/filter.go

Quote cli option values with single quotation mark when required.

docs: cli: general fixes and cosmetics

---

types/trace/trace.go

Add a flag that signifies if the process is running in 32bit compatibility mode for each event.
This will help to understand better process context and improve other features in the future.
This is a pre-step for #2614 
- command 01
- command 02

types: add compatibility mode context flag

---

Readme.md
docs/index.md

(also removed the explanation about tracee-rules/tracee-ebpf as it's not that interesting going forward)

docs: add tracee-action

---

pkg/cmd/flags/capture.go
pkg/cmd/flags/flags_test.go
pkg/ebpf/events_processor.go
pkg/ebpf/tracee.go
pkg/ebpf/tracee_test.go
pkg/events/events.go

remove capture profile feature

---

pkg/events/events.go

7f860ae2 chore: new default set of events
Fixes:
- #2631

chore: new default set of events

---

pkg/ebpf/c/tracee.bpf.c

ebpf: initialize scopes in trigger events
Addendum to #2644

ebpf: initialize scopes in trigger events

---

pkg/events/events.go

chore: remove mount dup from default evts

---

pkg/ebpf/probes/cgroup.go
pkg/events/events.go

events: remove new network events from default set

---

go.mod
go.sum
pkg/events/events.go

Fix network attach

---

pkg/ebpf/c/common/buffer.h
pkg/ebpf/c/tracee.bpf.c

removed some unused constants and moved some other definitions closer to where they are being used.
- command 01
- command 02

refactor: small fixes after ebpf code split

---

docs/getting-started/installing/kubernetes.md

Fixes: #2619 
- command 01
- command 02

Remove $ from code examples

---

docs/getting-started/installing/kubernetes.md
mkdocs.yml

https://github.com/aquasecurity/tracee/issues/2686
- command 01
- command 02

Expose events documentation

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

bump tags for the upcoming bugfix release

k8s: bump tag to 0.11.1

---

cmd/tracee-ebpf/main.go
cmd/tracee-rules/main.go
cmd/tracee/main.go

Minor fixes for `--help` to make it more consistent, and simplify some text.

chore: improves to commands --help

---

cmd/tracee-ebpf/main.go

change log flag to be a string slice
`sudo ./dist/tracee -t comm=uname -log debug`
`sudo ./dist/tracee-ebpf -t comm=uname -log debug`

fix: change log flag to be a string slice

---

pkg/ebpf/events_pipeline.go

Currently, if one event derives multiple event types, like:
```go
events.NetPacketDNSBase: {
events.NetPacketDNS: {
Enabled:...
DeriveFunction:...
},
events.NetPacketDNSRequest: {
Enabled:...
DeriveFunction:...
},
events.NetPacketDNSResponse: {
Enabled:...
DeriveFunction:...
},
},
```
And more than 1 type of derived event is being filtered:
--trace event=net_packet_dns,net_packet_dns_request
Then only the last one of them will be printed (and twice in this case).
This patch fixes that behavior by giving the correct pointer to the *trace.Event channel (instead of giving one pointer that gets *overwritten).
Fixes: #2705
```
$ sudo ./dist/tracee --install-path /tmp/tracee --output option:parse-arguments --capabilities bypass=false --trace binary=/usr/bin/dig --output format:json --trace …
```

pipeline: fix multiple derived events logic

---

pkg/logger/logger.go

feat: add more info to logger debug level
This removes the pkg, file and line fields from log entry, replacing
them with origin which has the format:
"origin":"pkg:relative/path/to/file:line"
e.g.:
"origin":"proc:pkg/utils/proc/ns.go:40"
The file path is now clickable in most editors and terminals.
This also introduces to debug level "calls" field, which is a custom
call trace back to the logger call.
e.g.:
"calls":"GetMountNSFirstProcesses() < (*Tracee).Init.func1() <
(*Capabilities).Requested() < (*Tracee).Init() < Runner.Run() <
main.func1() < (*App).RunContext() < (*App).Run() < main()"
Fixes: #2568
```shell
sudo ./dist/tracee -t comm=uname -log debug               
{"L":"DEBUG","T":"2023-02-09T13:59:32.585-0300","M":"osinfo","ID_LIKE":"arch","BUILD_ID":"rolling","KERNEL_RELEASE":"5.15 …
```

feat: add more info to logger debug level

---

types/go.mod
types/go.sum

upgrade go-yaml minor version due to CVE:
```
┌──────────────────┬────────────────┬──────────┬───────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │         Installed Version         │           Fixed Version           │                          Title                          │
├──────────────────┼────────────────┼──────────┼───────────────────────────────────┼───────────────────────────────────┼─────────────────────────────────────────────────────────┤
│ gopkg.in/yaml.v3 │ CVE-2022-28948 │ HIGH     │ 3.0.0-20200313102051-9f266ea9e77c │ 3.0.0-20220521103104-8f96da9f5d5e │ golang-gopkg-yaml: crash when attempting to deserialize │
│                  │                │ …
```

types: upgrade go-yaml

---

go.mod
go.sum

This PR update the types depedencies which was changed on the PR -> https://github.com/aquasecurity/tracee/pull/2719

dep: update githuhub.com/aquasecrity/tracee/types

---

pkg/ebpf/events_processor.go

log when not a container cgroup instead of err
Fixes: #2734
- #2734

log when not a container cgroup instead of err

---

docs/contributing/events/security_alerts/symbols_collision.md
docs/contributing/events/security_alerts/symbols_loaded.md
pkg/ebpf/tracee.go
pkg/events/derive/symbols_collision.go
pkg/events/derive/symbols_collision_test.go
pkg/events/derive/symbols_loaded_test.go
pkg/events/events.go

This is https://github.com/aquasecurity/tracee/pull/2053 rebased and with a minor fix.

pkg/ebpf: add derived events for ld SO symbols collision (rebase)

---

types/trace/trace.go

Adds the struct definition of the hidden kernel module event in type package.
Just definition - the test is in PRs using this struct

trace: add hidden kernel module struct

---

pkg/ebpf/c/common/filesystem.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/types.h
pkg/ebpf/probes/probes.go
pkg/events/events.go

add event to indicate utimes change of a file
```
Date:   Wed Feb 8 13:58:11 2023 +0200
events: add vfs_utimes event
add event to indicate utimes change of a file
```
Fixes: #2666
- command 01: `./dist/tracee-ebpf -t e=vfs_utimes`
- command 02: `touch -d "2020-01-01 12:00:00" utimes_test`

events: add vfs_utimes event

---

.github/workflows/pr.yaml
Makefile
tests/e2e-instrumentation-signatures/e2e-vfs_write.go
tests/e2e-instrumentation-signatures/export.go
tests/e2e-instrumentation-signatures/scripts/vfs_write.sh
tests/e2e-instrumentation-test.sh

issue: #2765
```
Date:   Thu Feb 23 12:35:22 2023 +0200
chore (tests): add e2e instrumentation tests
support for e2e instrumentation tests. as first test, add test 
for vfs_write event
```

chore (tests): add e2e instrumentation tests

---

go.sum
pkg/cmd/flags/output.go

Refactor https://github.com/aquasecurity/tracee/pull/2155

Refactor output forward flag

---

pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/types.h
pkg/ebpf/probes/probes.go
pkg/events/events.go

issue: #2748
```
Date:   Mon Feb 20 14:48:00 2023 +0200
feat: add do_truncate event
add event indicating a file truncate.
```
command 1: `./dist/tracee-ebpf -t e=do_truncate`
command 2: `echo test >> test.txt && truncate -s 1 test.txt`

feat: add do_truncate event

---

pkg/ebpf/tracee.go
tests/integration/integration_test.go
tests/integration/tracee.go

tests: fix integration pkg race conditions
```diff
diff --git a/Makefile b/Makefile
-       $(CMD_GO) test \
+       $(CMD_GO) test -race \
```
`sudo make test-integration`
Fixes: #2762
- #2762 
First step to:
- #2688.

tests: fix integration pkg race conditions

---

.github/workflows/pr.yaml

workflow: move runners to jenkins.

workflow: move runners to jenkins

---

cmd/tracee/main.go
cmd/tracee/main_test.go

Signatures are loaded by default. This is part of https://github.com/aquasecurity/tracee/issues/2355
Try triggering a simple signature like`anti_debugging`

signatures: load sigs as default events

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/kustomize/base/tracee.yaml
deploy/kubernetes/tracee-falcosidekick/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

Bump version on k8s templates for the upcoming release.

k8s: bump version

---

.github/workflows/pr.yaml

USING THIS TO TEST ARM64 RUNNERS

[ARM64 TESTS] workflow: add arm64 runners and tests

---

.github/workflows/pr.yaml

commit 08d5aa04 (HEAD -> workflow-paths, rafaeldtinoco/workflow-paths, main)
Date:   Wed Mar 8 03:41:17 2023
workflow: do not run PR workflow for some changes
commit e8e98feb
Date:   Wed Mar 8 03:33:07 2023
workflow: cancel running tests when a new PR update happens

Workflow paths

---

index.html

Fix https://github.com/aquasecurity/tracee/issues/2834
Adds index.html to gh-pages so it redirects if anyone access docs without a version.

docs: add index.html to root gh-pages

---

Readme.md

Fix docs links. Depends on https://github.com/aquasecurity/tracee/pull/2836

docs: fix readme docs links

---

pkg/ebpf/finding.go

Fix  https://github.com/aquasecurity/tracee/issues/2838
```
15:09:47:171891  1000   strace           2480802 2480802 0                anti_debugging
```

events: fix signature event name

---

.github/workflows/pr.yaml

workflow: test other tools builds as well

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

workflow: change release AMI IDs to latest

---

signatures/golang/ptrace_code_injection.go
signatures/golang/ptrace_code_injection_test.go

issue: #2841
```
Date:   Sun Mar 12 12:11:58 2023 +0200
feat: add PTRACE_POKEDATA to ptrace_code_injection
detect PTRACE_POKEDATA in ptrace_code_injection.go sig
```

feat: add PTRACE_POKEDATA to ptrace_code_injection

---

3rdparty/btfhub.sh
Readme.md
builder/Makefile.release
docs/contributing/building/building.md
docs/contributing/building/containers.md

- update documentation about the new container images

chore: enable btfhub after arm64 changes

---

.github/workflows/pr.yaml
.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml
tests/e2e-instrumentation-test.sh
tests/e2e-net-test.sh
tests/kerneltest.sh

- release & snapshot workflows, use AMIs with 80GB:
- x86_64:  ami-0f66f3ab4856ffc3f
- aarch64: ami-0226a47b9804ee055
- pr workflow, use a single AMI for core and non-core.

workflow: update AMI IDs

---

.github/workflows/pr.yaml

workflow: add amzn2 5.10 kernel AMIs to tests
Fixes: #2882

workflow: add amzn2 5.10 kernel AMIs to tests

---

docs/classic-docs/docs/capturing/index.md
pkg/bufferdecoder/decoder.go
pkg/bufferdecoder/decoder_test.go
pkg/bufferdecoder/protocol.go
pkg/bufferdecoder/protocol_test.go
pkg/cmd/flags/capture.go
pkg/cmd/flags/flags_test.go
pkg/ebpf/c/common/bpf_prog.h
pkg/ebpf/c/common/consts.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/vmlinux.h
pkg/ebpf/tracee.go
pkg/ebpf/write_capture.go
pkg/events/events.go

fix #1274
Adds BPF programs bytecode (JIT) capture.
`tracee-ebpf -c bpf`

add bpf byte code capture

---

docs/docs/events/builtin/extra/bpf_attach.md
docs/docs/events/builtin/extra/security_bpf_prog.md
pkg/ebpf/c/maps.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/types.h
pkg/ebpf/probes/probes.go
pkg/events/events.go
pkg/events/parse_args.go

issue: #2854
```
Date:   Wed Mar 15 17:01:14 2023 +0200
feat: add security_bpf_prog event
add security_bpf_prog event with details about the program
Date:   Mon Mar 13 14:57:11 2023 +0200
feat: add helpers list to bpf_attach
add full list of helpers used in the bpf program to the bpf_attach 
event instead of prog_write_user and prog_override_return explicit args
```
command: `./dist/tracee-ebpf -f e=bpf_attach`

feat: add helpers list to bpf_attach

---

pkg/cmd/flags/flags_test.go
pkg/cmd/flags/logger.go
pkg/cmd/flags/logger_test.go
pkg/cmd/flags/output.go
pkg/cmd/flags/tracee_ebpf_output.go
pkg/cmd/urfave/urfave.go

Fix https://github.com/aquasecurity/tracee/issues/2908
```
tracee --log file:/tmp/test.log
cat /tmp/test.log
```
This refactoring is done now, because it simplifies the implementation of actions per events for the policies task: https://github.com/aquasecurity/tracee/issues/2665

refactor: move log-file to be under --log

---

pkg/cmd/flags/errors.go
pkg/cmd/flags/filter.go
pkg/cmd/flags/filter_map.go
pkg/cmd/flags/flags_test.go
pkg/cmd/flags/policy.go
pkg/cmd/printer/printer.go
tests/integration/integration_test.go

Removes policy number CLI in favor of policy files mechanism #2892.
This will be rebased once #2892 is merged.
Fixes: #2918

Policy number CLI removal

---

examples/container_dns_events.yaml
pkg/cmd/flags/policy.go
pkg/cmd/flags/policy_test.go

The `container` scope was not working.
```
./dist/tracee -p examples/container_dns_events.yaml
```

policies: fix container scope

---

docs/docs/policies/index.md

Fix policy docs newline

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml
builder/Makefile.release

- also: include static and non-static binaries in .tar.gz

workflows: make release like the snapshot logic

---

.github/workflows/release.yaml
.gitignore
builder/Makefile.release

release: fix release_notes.txt placement

---

docs/docs/forensics/index.md

#2874 added the documentation under the old classic-docs section.
Add this documentation under the new forensics section as well.

docs: add bpf capture documentation

---

docs/docs/outputs/logging.md
docs/docs/outputs/output-formats.md
mkdocs.yml

Fix https://github.com/aquasecurity/tracee/issues/2966
```
make -f builder/Makefile.mkdocs mkdocs
```

docs: fix logging documentation

---

docs/docs/outputs/logging.md
docs/docs/policies/scopes.md

Fix mnt docs

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/kustomize/base/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

Bump tag for the bugfix release

k8s: bump tag to 0.13.1

---

.github/workflows/release.yaml

fix: strip v from docker images tags

---

deploy/helm/tracee/Chart.lock
deploy/helm/tracee/Chart.yaml

Fix https://github.com/aquasecurity/tracee/issues/2980
Bumps postee to latest.
```
helm install  tracee ./deploy/helm/tracee --create-namespace --namespace tracee-system --set postee.enabled=true 
```
Lastest postee allows customizations of the configfile through helm:
```
helm install --dry-run tracee ./deploy/helm/tracee --create-namespace --namespace tracee-system --set postee.enabled=true --set-file postee.posteeConfig=postee.cfg
```

chore: bump postee to 2.9.0

---

Readme.md

docs: remove tracee-action metion

---

.github/workflows/debug-shell.yaml

workflow: raise timeout limit for debug shell jobs

---

types/trace/trace.go

the idea is to unmarshal types from the `trace` package to the correct type, instead of `interface` (which is the case now).
it'll make writing signatures easier as there will be no need to parse types in the signature itself (or in the helpers).
in practice, i moved the parsing logic from `helpers.go` (https://github.com/aquasecurity/tracee/blob/main/signatures/helpers/helpers.go) to the `UnmarshalJSON()` func in the `trace` package.
in the future, after this PR merges, any new types in the `trace` package should be parsed there as well.
this PR has the same purpose as #2937 which didn't solve the problem.
```
Date:   Sun Apr 2 17:50:23 2023 +0300
feat: unmarshall trace types correctly
unmarshal trace types to their real types instead of interface
```

feat: unmarshall trace types correctly

---

go.mod
go.sum
signatures/helpers/helpers.go

Recent types added to Tracee from:
https://github.com/aquasecurity/tracee/pull/2996/
https://github.com/aquasecurity/tracee/pull/2937/
Make now this change to be possible.
This is just a rebase of:
https://github.com/aquasecurity/tracee/pull/2941
by @roikol. I wanted to rush things and test the new types and signature changes, and, if the tests work, I'm +1 on that PR and can merge this one.

feat: use new types in signatures

---

pkg/events/derive/hidden_kernel_module.go

- missed a lockup in capabilities ring raising during review, fix it
- fixed logger errors (needs key/value) and used correct error func

events: fix hidden_kernel_module derivation

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/kustomize/base/tracee.yaml
deploy/kubernetes/tracee-postee/tracee.yaml
deploy/kubernetes/tracee/tracee.yaml

k8s: bump to 0.14.0

---

.github/workflows/release.yaml

release: fix workflow to push tracee:${TAG}

---

.github/workflows/debug-shell.yaml
.github/workflows/pr.yaml
.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

- move all AMIs to an aquasec account

workflow: move workflows to aqua infrastructure

---

.github/ISSUE_TEMPLATE/BUG.md
.github/PULL_REQUEST_TEMPLATE.md

fix: update github bug and PR templates

---

types/trace/trace.go

prepare types package for #3062
alert name change due to logic change

change mem_prot_alert alert from W+E to W

---

pkg/cmd/tracee.go
pkg/ebpf/events_processor.go
pkg/ebpf/tracee.go
pkg/ebpf/write_capture.go
pkg/utils/files.go

tracee: remove pid file on exit
This also does some cosmetic changes to the code.
```
$ sudo ./dist/tracee --filter event=ptrace_code_injection
```
then
```
ctrl+c
```
and watch:
```
$ find /tmp/tracee
/tmp/tracee
/tmp/tracee/out
```
Fix: #3074

remove pid file on exit

---

cmd/tracee/cmd/root.go
pkg/cmd/cobra/cobra.go
pkg/cmd/tracee.go

The logger should be the first thing to initialize, as we have packages using it already, like: https://github.com/aquasecurity/tracee/blob/main/pkg/signatures/signature/signature.go#L23
There is also two simple commits to remove an old TODO, and clean up an `if` not used.

Fix logger

---

.github/workflows/release-snapshot.yaml

Add cosign installer to release-snapshot

workflow: add cosign to release snapshot

---

.github/workflows/release-snapshot.yaml

workflow: sign aquasec/tracee:x86_64-dev

---

.github/workflows/release.yaml

Fix https://github.com/aquasecurity/tracee/issues/2804
Fix https://github.com/aquasecurity/tracee/issues/2907
Sign release images. 
This was implemented on the [`release-snapshot`](https://github.com/aquasecurity/tracee/blob/main/.github/workflows/release-snapshot.yaml) workflow to validate it works.
You can check the signed dev image with:
```
cosign verify aquasec/tracee:aarch64-dev \
--certificate-identity=https://github.com/aquasecurity/tracee/.github/workflows/release-snapshot.yaml@refs/heads/main \
--certificate-oidc-issuer=https://token.actions.githubusercontent.com | jq
```

workflow: sign release images

---

pkg/cmd/tracee.go
pkg/ebpf/tracee.go

The ready callback is executed once tracee is fully initialized, and ready to receive events. This feature will be used for the `/healthz` endpoint, which will only start to respond "OK" once tracee is ready.
Fix for https://github.com/aquasecurity/tracee/issues/3116
```
commit 4b3fef7a5e747f512eabb88c4bd9094a473d442a (HEAD -> add-ready-callback, origin/add-ready-callback)
Date:   Thu May 18 14:45:28 2023 -0300
tracee: add ready callback
The ready callback is executed once tracee is fully initialized,
and ready to receive events. This feature will be used for the
`/healthz` endpoint, which will only start to respond "OK" once
tracee is ready.
```
```
sudo tracee --healthz
```
```
curl localhost:3366/healthz
```
This is important for the …

tracee: add ready callback

---

deploy/helm/tracee/templates/daemonset.yaml
deploy/helm/tracee/values.yaml
deploy/kubernetes/tracee/tracee.yaml
docs/docs/config/kubernetes.md
mkdocs.yml

Fix for https://github.com/aquasecurity/tracee/issues/3118
```
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true
kubectl get pods # pod should be running
kubectl get cm # a configmap should exist named tracee
kubect edit cm/tracee # check the content
```
if you want to customize:
```
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true \
--set config.perfBufferSize=1000
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true \
--set config.output[0]=table
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true \
--set-file traceeConfig=<path/to/config/file>
```

Add k8s configmap

---

deploy/helm/tracee/templates/daemonset.yaml
deploy/helm/tracee/values.yaml
deploy/kubernetes/tracee/tracee.yaml

Fix https://github.com/aquasecurity/tracee/issues/2114
The readiness probe will be useful once we create services for the metrics endpoint and also the API which is upcoming.

k8s: add readiness probe

---

deploy/helm/tracee/templates/daemonset.yaml
deploy/helm/tracee/templates/tracee-config.yaml
deploy/helm/tracee/templates/tracee-policies.yaml
deploy/kubernetes/tracee/tracee.yaml
docs/tutorials/k8s-policies.md
mkdocs.yml

Fix https://github.com/aquasecurity/tracee/issues/3129
This PR adds a default policy for signatures events on kubernetes. It introduces a configmap that can be extended with newer policies, or changes to the default policy depending on the user needs. It also includes a tutorial on how to add a new policy.

k8s: add default signatures policy

---

docs/getting-started/installing/kubernetes.md
docs/getting-started/kubernetes-quickstart.md

Fix helm docs:
1 - no need to set `hostPID=true` as it is the default https://github.com/aquasecurity/tracee/blob/main/deploy/helm/tracee/values.yaml#L30
2 - no need to update dependency, as we removed it https://github.com/aquasecurity/tracee/pull/3089

k8s: fix helm installation

---

docs/getting-started/installing/kubernetes.md

Fix https://github.com/aquasecurity/tracee/issues/3135 
```
make -f builder/Makefile.mkdocs
```

k8s: fix k8s installation docs

---

.github/workflows/test-helm-chart.yaml
deploy/helm/chart_schema.yaml
deploy/helm/ct.yaml
deploy/helm/lintconf.yaml

Fix https://github.com/aquasecurity/tracee/issues/3119
Add github workflow to `lint` and test the `installation` fo the tracee chart into a kubernetes cluster when a PR is created to update it. 
As the configfile for `chart-testing` are under `deploy/helm` the workflow was triggered with this PR, you can see the result here https://github.com/aquasecurity/tracee/actions/runs/5069056125/jobs/9102140783?pr=3138

k8s: add helm test workflow

---

types/detect/detect.go

This is the types for https://github.com/aquasecurity/tracee/pull/3026
@NDStrahilevitz FYI

types: add DataSource type for signatures

---

pkg/policy/policy_file.go
pkg/policy/policy_file_test.go

Fix https://github.com/aquasecurity/tracee/issues/3143
Fixes validation for filter `args` and `retval` on policies.
create file p.yaml with policy below 
```
name: openat_args_pathname
description: traces openat under /tmp/*
scope:
- global
defaultAction: log
rules:
- event: openat
filter:
- args.pathname=/tmp*
```
Pass policy to tracee
```
sudo tracee -p p.yaml
```

policy: fix validation of args and retval

---

pkg/ebpf/c/maps.h
pkg/ebpf/c/tracee.bpf.c
pkg/ebpf/c/types.h
pkg/ebpf/hidden_kernel_module.go
pkg/ebpf/probes/probes.go
pkg/ebpf/tracee.go
pkg/events/derive/hidden_kernel_module.go
pkg/events/events.go

Add improvements:
- Run after a kernel module was loaded (in addition to periodically)
- Address possible race condition that my cause false-positive
./tracee -f e=hidden_kernel_module

events: improve hidden_kernel_module

---

types/trace/trace.go

types: add ContainerID field back

---

pkg/cmd/printer/benchmarks/printer_test.go
pkg/cmd/printer/policy.go

Fix https://github.com/aquasecurity/tracee/issues/3169

printer: fix policy printer

---

pkg/ebpf/hidden_kernel_module.go

Fix a bug in hidden_kernel_module event that was triggered every 2 seconds constantly.
./tracee -f e=hidden_kernel_module

events: fix hidden_kernel_module trigger time

---

pkg/cmd/cobra/cobra.go

Fix https://github.com/aquasecurity/tracee/issues/3186
The `c.Flags()` opinion should only be used for command line only arguments, anything else must use `viper` because that is how we process the config file https://github.com/aquasecurity/tracee/blob/main/cmd/tracee/cmd/root.go#L313
create the cfg.yaml below
```
blob-perf-buffer-size: 1024
install-path: /tmp/tracee
cache:
- cache-type=mem
- mem-cache-size=1024
capabilities: []
containers: true
crs: []
log:
- info
output:
- json
perf-buffer-size: 1024
pyroscope: false
rego: []
signatures-dir: ""
metrics: true
healthz: true
pprof: true
listen-addr: :3366
```
start tracee
```
sudo ./dist/tracee --config cfg.yaml 
```

tracee: fix output configuration via configfile

---

pkg/containers/path_resolver.go

Fixing linting on top of  https://github.com/aquasecurity/tracee/pull/3200

Fix path check multiple pids

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

Prepare tags for the upcoming release.

k8s: bump release tag to 0.15.0

---

.github/workflows/release.yaml

Cosign is missing env vars for finishing the signing.

workflow: fix cosign signing

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

k8s: bump release tag to 0.15.1

---

Vagrantfile

Fix simple typo in Vagrantfile's comments: `sing` -> `sign`.
It's not necessary since I have changed only a comment.
Related to [this issue](https://github.com/aquasecurity/tracee/issues/3258).

Fix typo in Vagrantfile's comment

---

.github/workflows/release-snapshot.yaml

Now that we have cosign for our release, we should remove it from the snapshot. The snapshot is generated daily, which generates a lot of signatures not used in our docker hub.

build: remove signing from snapshot

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

release: bump release tag to 0.16.0

---

pkg/counter/counter.go
pkg/counter/counter_test.go
pkg/ebpf/bpf_log.go
pkg/ebpf/capture.go
pkg/ebpf/events_pipeline.go
pkg/ebpf/events_processor.go
pkg/ebpf/net_capture.go
pkg/ebpf/signature_engine.go
pkg/ebpf/tracee.go
pkg/events/trigger/context.go
pkg/events/trigger/context_test.go
pkg/events/trigger/errors.go
pkg/signatures/engine/engine.go

commit 0c41d9bc9 (HEAD -> counter-fixes, rafaeldtinoco/counter-fixes)
Date:   Sun Jun 25 05:26:41 2023
pkg/events/trigger: fix context concurrency issues
Fixes: #3264
Fixes: #3264
commit 3147f27be
Date:   Sun Jun 25 05:26:01 2023
pkg/counter: method for increase and read atomically
commit a1bf09c4d
Date:   Sun Jun 25 03:15:56 2023
pkg/counter: fix concurrency issues with atomics
Fixes: #3263
Rename increment/decrement to increase/decrease: Terms increment &/
ecrement are technicaly more correct terms, but increase and decrease
are more widely used, and more common terms, to most audiences.
Fixes: #3263

thread-safety issues fix

---

docs/docs/events/custom/analyze.md
mkdocs.yml

Add docs to `tracee analyze`. 
```
make -f builder/Makefile.mkdocs
```

docs: add analyze documentation

---

docs/tutorials/verify-tracee-signature.md

Fix https://github.com/aquasecurity/tracee/issues/3122
Add a simple tutorial on how to verify the tracee image signature with cosign.

doc: add tutorial to verify tracee signature

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

Bump k8s tag to 0.16.1 so we can backport and publish helm.

chore: bump k8s tag to 0.16.1

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

chore bump 0.16.2

---

builder/Dockerfile.alpine-tracee-container

deadea426 **fix(build): btfhub's bpftool in alpine container (#3349)**
commit deadea426
```
Install bpftool in alpine container from btfhub's submodule.
commit: 41ea796 (main), cherry-pick
```

fix(build): btfhub's bpftool in alpine container (#3349)

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

chore: bump k8s tags to 0.17.1

---

cmd/tracee/cmd/root.go

1814cc75a **fix(config): loading config file**
```
commit: 7e58610 (main), cherry-pick
```

[v0.17.1] fix(config): loading config file

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

ca7aaa952 **chore: bump k8s tags to 0.17.1 (#3374)**
```
commit: a8ddb7e (main), cherry-pick
```

[v0.17.1] chore: bump k8s tags to 0.17.1 (#3374)

---

docs/tutorials/additional-resources.md
mkdocs.yml

docs: additional resources for the docs

---

docs/tutorials/k8s-policies.md

Fix https://github.com/aquasecurity/tracee/issues/3368
```
make -f builder/Makefile.mkdocs
```

fix: k8s policies tutorial

---

docs/contributing/guidelines.md

fix: committing typo

---

pkg/ebpf/c/tracee.bpf.c

fix: fix section name for vfs_readv

fix: fix section name for vfs_readv

---

pkg/ebpf/c/common/filesystem.h

Force the verifier to use the right registers for read, avoiding verifier errors about reading of possible negative value with bpf_probe_read.

Fix(capture): fix verifier issue with elf capture

---

pkg/cmd/cobra/cobra.go
pkg/cmd/tracee.go
pkg/cmd/urfave/urfave.go
pkg/config/config.go
pkg/ebpf/events_pipeline.go
pkg/ebpf/tracee.go
pkg/policy/errors.go
pkg/policy/policies.go
pkg/policy/policy.go
pkg/streams/streams.go
pkg/streams/streams_test.go
tests/integration/event_filters_test.go

This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208). It adds Streams support, streams represent a subscriber of tracee events, the subscriber can specific which policies to receive events from. Streams will be used by grpc, where each grpc client can create multiple streams for tracee to consume events.
The GRPC endpoint will later be implemented like:
```
func (s *TraceeService) StreamEvents(in *pb.StreamEventsRequest, grpcStream pb.TraceeService_StreamEventsServer) error {
stream, err := s.tracee.Subscribe(in.Policies)
if err != nil {
return err
}
defer s.tracee.Unsubscribe(stream)
mask := fmutils.NestedMaskFromPaths(in.GetMask().GetPaths())
for e := range stream.ReceiveEvents() {
eventProto := convertTraceeEventToProto(e) …
```

feat: add streams

---

docs/docs/events/builtin/extra/security_bprm_check.md
mkdocs.yml
pkg/ebpf/c/tracee.bpf.c
pkg/events/core.go

To allow deeper analysis of the executed program before the execution, a new field for the argv given is added.
fix: #3441

feat: add argv to security_bprm_check

---

tests/integration/event_filters_test.go

4c7959d13 **chore(tests): comment out init sighup test**
```
This test is the one that fails the most in CI. Comment it out for now,
and we'll revisit it later.
Context: #3440
```
Context: #3440

chore(tests): comment out init sighup test

---

types/api/v1beta1/event.pb.go
types/api/v1beta1/event.proto

Fix user stack address, the addresses must have the symbol name.

fix: stackaddress needs to have symbol name

---

docs/docs/events/builtin/extra/ftrace_hook.md
pkg/ebpf/hidden_kernel_module.go
pkg/ebpf/probes/probe_group.go
pkg/ebpf/probes/trace.go
pkg/ebpf/tracee.go
pkg/events/core.go
pkg/events/ftrace.go
pkg/events/ftrace_test.go
pkg/utils/utils.go

add ftrace_hook event
tracee -e=ftrace_hook
Closes #3439

events: add ftrace_hook event

---

types/datasource/proctree.go

This is the types changes for the PR of the proctree datasource #3054

feat(types): add proctree datasource

---

Vagrantfile

Close: #3458 
4207fbfe3c807fc914ef26d97aa2fe29d4c1370c **chore(vagrant): add support to arm64 architecture**
```
Whether the Vagrantfile will work depends on the availability of online
boxes and compatibility of architecture and providers (vbox, parallels).
Tested in Darwin (M1) and Linux (amd64).
```
On an arm64 (i.e. macOS on M1, requires [parallels](https://github.com/aquasecurity/libbpfgo/blob/bd31ff0bdba11491d7d31df7675274e6829b769f/docs/Vagrantfile.md#darwin)):
```
vagrant up
vagrant ssh
docker run \
--name tracee --rm -it \
--pid=host --cgroupns=host --privileged \
-v /etc/os-release:/etc/os-release-host:ro \
-v /boot/config-$(uname -r):/boot/config-$(uname -r):ro \
aquasec/tracee:aarch64
```
It's an env ready for development on arm64.

chore(vagrant): add support to arm64 architecture

---

Vagrantfile

Fix a wrong var reference in the Vagrantfile.

fix(Vagrantfile): wrong var reference

---

pkg/ebpf/signature_engine.go
pkg/proctree/datasource.go
pkg/proctree/proctree_output.go
pkg/proctree/taskinfo.go

commit 3b5d5d71f (HEAD -> pr3488-rebase, rafaeldtinoco/pr3488-rebase)
Author: Alon Zivony <alon.zivony@aquasec.com>
Date:   Tue Sep 19 10:07:00 2023
feat(proctree): create process tree data source
Expose the process tree to the signatures using a datasource.
This way a signatures can use the process tree to have state, instead
of using multiple events and saving the state internally.

feat(proctree): create process tree data source

---

types/trace/trace.go

Add to event an executable member, to enable enrichment using process tree.

feat(types): add executable to event

---

cmd/tracee-rules/output_test.go
go.mod
go.sum
pkg/ebpf/events_pipeline.go
pkg/ebpf/processor.go
pkg/ebpf/processor_proctree.go

Rebase of https://github.com/aquasecurity/tracee/pull/3511

feature(proctree): enrich events with executable from proctree

---

types/trace/trace.go

Context: #3305
e5bc488d5 **feat(types): add PoliciesVersion field to Event**

feat(types): add PoliciesVersion field to Event

---

docs/docs/data-sources/containers.md
docs/docs/data-sources/overview.md
docs/docs/data-sources/process-tree.md
mkdocs.yml

- add containers data source documentation
- add process tree data source documentation

docs(datasources): make datasource docs more complete

---

deploy/helm/tracee/templates/tracee-config.yaml
deploy/helm/tracee/values.yaml
deploy/kubernetes/tracee/tracee.yaml
examples/config/global_config.json
examples/config/global_config.yaml

This PR removes the `containers` config from the kubernertes files, the flag was removed after the PR https://github.com/aquasecurity/tracee/pull/3610

chore(k8s): remove containers config option

---

deploy/helm/tracee/templates/tracee-policies.yaml
deploy/kubernetes/tracee/tracee.yaml

Fix https://github.com/aquasecurity/tracee/issues/3323
This PR adds the default events to the kubernetes default policy, so users have the same experience if they are using k8s or the tracee binary.

feature(k8s): add default events to k8s policies

---

tests/integration/tracee.go

f6c990576 **chore: disable cri enrich on tests**

chore: disable cri enrich on tests

---

deploy/helm/tracee/templates/tracee-config.yaml
deploy/helm/tracee/values.yaml

Fix k8s config file. The PR isn't adding all options but the most common ones, if a user needs to optmize all options he can use the option to inject a full config file, I'll create an issue to add the remaining options in the next release.

fix: structured k8s config

---

docs/docs/advanced/data-sources/containers.md
docs/docs/advanced/data-sources/process-tree.md
docs/docs/flags/config.1.md
docs/docs/install/docker.md
mkdocs.yml

https://github.com/aquasecurity/tracee/issues/3658

docs: fix broken links #3658

---

builder/entrypoint.sh

- all signatures enabled by default
- container creation and removal events only
- json output just like k8s deployment
anything else only if explicitly asked by user.

chore(container): same default events as k8s deployment

---

types/trace/network_trace.go
types/trace/trace.go

feature(types): add packet metadata type

---

types/datasource/proctree.go

Add a time relevant info object for proctree queries. This will give the query answer the time context it is relevant for.
This is a type change for #3691

feat(types): time relevant info for proctree

---

.github/workflows/pr.yaml

bdb65cc74 **chore(ci): bump changed-files to v40.2.0**

chore(ci): bump changed-files to v40.2.0

---

builder/Dockerfile.alpine-tracee-make
builder/Dockerfile.ubuntu-tracee-make

chore(release): use go1.20 for releasing

---

Makefile

chore(makefile): fix doube-quoted version string

---

api/v1beta1/datasource.pb.go
api/v1beta1/event.pb.go
api/v1beta1/event_data.pb.go
api/v1beta1/tracee.pb.go

main should have those types always updated -> "make protoc"

chore: update proto types

---

tests/e2e-inst-test.sh
types/detect/detect.go
types/detect/finding.go

Types protected finding

---

.github/workflows/pr.yaml

commit 55308b6a594c9ac9be0be698116f19dcbaa29b9e
chore(ci): add mantic 6.6 AMIs

chore(ci): add mantic 6.6 AMIs

---

go.mod
go.sum

Use signatures helpers module directly instead of replace.

chore: remove replace of signatures helpers

---

pkg/server/grpc/event_data.go

Fixes https://github.com/aquasecurity/tracee/issues/3821

grpc: fix nil arguments

---

Vagrantfile

commit 33d6d124e7c55c22a385eb9b7844aab62f964eb2
chore: increase vb resources

chore: increase vb resources

---

pkg/ebpf/processor_proctree.go
pkg/events/derive/derive.go
pkg/events/ftrace.go
pkg/events/trigger/context.go

1324bc4d3 **fix: invoking.ArgsNum assignment**
8af3e2443 **fix: update Event.ArgsNum**
1324bc4d3 **fix: invoking.ArgsNum assignment**
```
Assign the actual length of the arguments to the ArgsNum field.
```

Fix ArgsNum

---

docs/docs/install/kubernetes.md

af3c6a1f7 **Fix typo in kubernetes install guide**
Verify that the install guide for Kubernetes mentions "Grafana" instead of "Graphana".

Fix typo in kubernetes install guide

---

docs/docs/policies/index.md

It will fix the typo under the Policies section. 
Issue raised - #3857 
Not sure about the test, but you can check the changes in the following link - [f5c5ece](https://github.com/aquasecurity/tracee/commit/f5c5eceebadc7f5271dd7767821dd37062a340f2)
N/A

Docs: fixed the typo

---

.github/workflows/debug-shell.yaml
.github/workflows/pr.yaml
.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

Also use short label name 'graas' instead of 'github-self-hosted'

Use EXECUTION_TYPE label for github self host runner

---

tests/e2e-inst-signatures/scripts/bpf_attach.sh
tests/e2e-inst-test.sh
tests/e2e-install-deps.sh
tests/e2e-kernel-test.sh
tests/e2e-net-test.sh

2f00d1812 **chore(tests): -f for names greater than 15 chars**
92d7f06cf **chore(tests): use signal name instead of numbering**
b8d1d74c7 **fix(tests): unattended upgrades still running sometimes**

fix(tests): unattended upgrades still running sometimes

---

docs/docs/install/config/kubernetes.md

d1cb1e6ef **fix(docs): kubectl configmap command**

fix(docs): kubectl configmap command

---

pkg/ebpf/c/tracee.bpf.c

ebpf: don't send magic_write with zero bytes

---

tests/e2e-install-deps.sh

Close: #3911
b2c2c02da **fix(tests): e2e-install-deps.sh wait for unlock**

fix(tests): e2e-install-deps.sh wait for unlock

---

.github/workflows/auto-author-assign.yml
.github/workflows/debug-shell.yaml
.github/workflows/labeler.yml
.github/workflows/mkdocs-dev.yaml
.github/workflows/mkdocs-latest.yaml
.github/workflows/pr.yaml
.github/workflows/publish-helm.yaml
.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml
.github/workflows/test-daily.yaml
.github/workflows/test-helm-chart.yaml

55992ee7b **chore(ci): bump actions versions**
```
```

chore(ci): bump actions versions

---

pkg/ebpf/tracee.go

Avoid errors about missing print_mem_dump args filters when the policy does not choose the event.
This was caused when one policy chose it, but others didn't.
Fix #3781

fix: wrong print_mem_dump errors about args filter

---

Vagrantfile

168db5457 **fix: vagrantfile url for opa download**

fix: vagrantfile url for opa download

---

go.mod
go.sum
pkg/server/grpc/tracee.go

Fix https://github.com/aquasecurity/tracee/issues/4005

grpc: update definitions api

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

chore(k8s): prepare v0.21.0 release

---

.github/workflows/performance.yaml

1. Downgrade AWS authentication v3 (see https://github.com/aws-actions/configure-aws-credentials/issues/862)
2. Add missing needs label to the benchmark job

fix: performance yaml

---

.github/workflows/performance.yaml

Add workflow_dispatch trigger for performance gate.
Also add temporary PR trigger.

chore: add workflow_disptach to perf gate

---

.github/workflows/performance.yaml

chore(perf): upgrade aws-auth back to v4.0.2

---

.github/workflows/performance.yaml

fix(perf): add missing cluser name env var

---

.github/workflows/performance.yaml

1. Move into benchmark folder before executing script
2. Remove internal cache (use gh pages commits instead)

fix(perf): various changes and fixes

---

tests/integration/capture_test.go
tests/perftests/metrics_test.go
tests/testutils/exec.go
tests/testutils/tracee.go

Fix tests so they will make sure to close channels properly and clean goroutines.
This is a cherry pick of #4047

0.21.0/fix(tests): fix goroutines leakage in integration tests

---

deploy/helm/tracee/templates/tracee-config.yaml
deploy/helm/tracee/values.yaml
docs/docs/install/config/kubernetes.md

fix: #3885 
799c68b3f **docs(helm): rename helm field config file**
e86f9f425 **chore(helm): rename helm field config file**

chore(helm): rename helm field config file

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

3891d3abb **Revert "chore(k8s): prepare v0.21.0 release (#4007)"**
```
This reverts commit 7d630788701a1e4a538564b03fac463eea5f6f5e.
commit: 70abe5e (main), cherry-pick
```

[v0.21.0] Revert "chore(k8s): prepare v0.21.0 release (#4007)"

---

deploy/helm/tracee/templates/tracee-config.yaml
deploy/helm/tracee/values.yaml
docs/docs/install/config/kubernetes.md

0688a01a3 **chore(helm): rename helm field config file (#4018)**
```
commit: a458fa9f (main), cherry-pick
```

chore(helm): rename helm field config file (#4018)

---

docs/docs/install/config/kubernetes.md

083221b49 **chore(docs): fix helm field in kubernets doc**

chore(docs): fix helm field in kubernets doc

---

.github/workflows/performance.yaml

Removed in 49e792c for no good reason.

fix(performance.yaml): add aws authentication back

---

.github/workflows/performance.yaml

fix(performance.yaml): logout after image publish

---

.github/workflows/performance.yaml

smallerIsBetter fixed to customSmallerIsBetter.

fix(performance.yaml): bench tool typo

---

.github/workflows/performance.yaml

Images were previously uncleaned, causing disk storage buildup on the runner. Prevent this by cleaning the image after publishing.

feat(performance.yaml): clean up images post build

---

pkg/changelog/changelog.go
pkg/changelog/changelog_test.go
pkg/proctree/process.go
pkg/proctree/proctree.go
pkg/proctree/proctree_feed.go
pkg/proctree/thread.go
pkg/utils/time.go
tests/e2e-inst-signatures/e2e-proctree_data_source.go

Fix multiple bugs in the pursuit to fix the issue that thread name received from proctree was incorrect.
Fix #4103
Updated all tests to the new use-cases

fix(changelog): fix bugs with indexes

---

pkg/ebpf/hidden_kernel_module.go

remove throttle timer in hidden_kernel_module
./tracee -e=hidden_kernel_module

feat(events): remove throttle timer in hidden_kernel_module

---

pkg/ebpf/hidden_kernel_module.go

remove throttle timer in hidden_kernel_module
./tracee -e=hidden_kernel_module

[backport v0.21.0] feat(events): remove throttle timer in hidden_kernel_module

---

tests/e2e-inst-test.sh

Uncomment hooked_syscall e2e for kernel v6.5

fix(e2e): run hooked_syscall e2e in all envs

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

85468787c **chore(k8s): prepare v0.21.0 release (#4134)**
```
commit: ad285fe (main), cherry-pick
```

[v0.21.0] chore(k8s): prepare v0.21.0 release (#4134)

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

e1d0e3cc1 **chore(ci): update image reference**
b642e723b **fix(ci): bump cosign to 2.2.4**

Fix release action

---

.github/workflows/release-snapshot.yaml

fix(ci): dev tag is the latest snapshot

---

builder/Dockerfile.alpine-tracee-container
builder/Dockerfile.ubuntu-tracee-make

ce2fd2b28 **chore: install last version of golang**

chore: install last version of golang

---

Makefile

577ac311d8f40504e6c5f7a4402a753f97090b27 **chore(build): create format-pr rule for speeding up**

Create Makefile format-pr rule

---

go.mod

970d94f66 **fix(build): bump go to fix cve-2024-24790**
```
commit: 18311aa (main), backport
[backport]
- go mod tidy executed
```

[v0.21.0] fix(build): bump go to fix cve-2024-24790

---

builder/Makefile.release

55f6eb2c8 **fix(build): mv gh release logic to release rule**
```
Continuation of #4141.
```

fix(build): mv gh release logic to release rule

---

builder/Makefile.release

ae7208392 **fix(build): fix release build**
```
This fixes issues that arose after applying the previous fix #4141.
```

fix(build): fix release build

---

builder/Makefile.release

0845b8e53 **fix(build): fix release build (#4150)**
```
This fixes issues that arose after applying the previous fix #4141.
commit: d83c07b (main), cherry-pick
```

[v0.21.0] fix(build): fix release build (#4150)

---

pkg/logger/logger.go

baa97d3fa **chore(logger): safe guard before locking**

chore(logger): safe guard before locking

---

pkg/utils/environment/amount_cpus.go
pkg/utils/environment/amount_mem.go
pkg/utils/environment/kernel_config.go
pkg/utils/environment/kernel_symbols.go
pkg/utils/environment/osinfo.go

Close: #4111
1d8278c95 **chore: rem logger and errfmt as dependencies**
```
Remove logger and errfmt as dependencies from the environment package.
```

chore: rem logger and errfmt as deps from env pkg

---

docs/docs/events/builtin/extra/tracee_info.md
pkg/ebpf/tracee.go
pkg/events/core.go
pkg/events/usermode.go

Part of #3520
5c02ebf4e **feat(events): create tracee_info event**
```
Create an event that export Tracee's data upon startup.
Co-authored-by: Alon Zivony <alon.zivony@aquasec.com>
```
Credits to @AlonZivony, who did the work.

feat(events): create tracee_info event

---

pkg/capabilities/capabilities.go
pkg/capabilities/capabilities_test.go
pkg/cmd/flags/output_test.go

Close: #4176
8cd08ed0a **fix: cleanup test tmp files**
e2bd31f41 **fix: turn Capabilities thread-safe**
8cd08ed0a **fix: cleanup test tmp files**
```
It was detected during random test runs that the test was leaving
temporary files behind and failing in the next run.
```

Caps concurrency fix

---

Makefile

b1e17b7a6 **fix(build): include libbpf during libbpfgo compilation**
```
An issue appears when we try to compile libbpfgo on an older kernel that
doesn't have the XDP_FLAGS_REPLACE defined in
/usr/include/linux/if_link.h. To overcome this, it is necessary to
include the directory of libbpf under 3rdparty during the compilation,
since install_uapi_headers doesn't install if_link.h.
```
Thank you @geyslan for the guidance through this issue.

fix(build): add the include to 3rdparty libbpf during libbpfgo compilation

---

.github/workflows/pr.yaml

2c15a5eaa **chore(build): trigger tracee tests on Makefile changes**

chore(build): trigger tracee tests on Makefile changes

---

go.mod
go.sum
pkg/ebpf/tracee.go

ee975c0eb **chore: use libbpfgo to check bpf helper func**
```
Instead of checking kernel symbols, determine if the helper is available
based on the BPF program type. To achieve this, use the
BPFHelperIsSupported() function from libbpfgo.
```

chore: use libbpfgo to check bpf helper func

---

pkg/ebpf/tracee.go

0ac18e3e4 **fix: inner error inside check for ebpf func**

fix: inner error inside check for ebpf func

---

pkg/ebpf/c/tracee.bpf.c
pkg/events/core.go

add prev_comm for sched_process_exec
./tracee -e=sched_process_exec
Closes #4207

feat(ebpf): add prev_comm for sched_process_exec

---

pkg/signatures/benchmark/benchmark_test.go

814993d43 **fix: necessary to Init engine before Start**

fix: necessary to Init engine before Start

---

pkg/ebpf/c/common/task.h

use correct syscall id for compat
./tracee

fix(ebpf): use correct syscall id for compat

---

pkg/ebpf/c/tracee.bpf.c
pkg/events/core.go

make security_file_open not rely on sys_enter/exit
./tracee -e=security_file_open

feat(ebpf): make security_file_open not rely on sys_enter/exit

---

Makefile
builder/Dockerfile.alpine-tracee-container
builder/Dockerfile.alpine-tracee-make
builder/Dockerfile.ubuntu-tracee-make
builder/Makefile.man
builder/Makefile.release

Close: #4153 
9e1dd40ba **fix: add docs for release archive/image**
4db34bf4f **chore: silence Dockerfile warnings**

Provide manual files in release image/archive

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

7d11f0dd3 **chore(k8s): prepare v0.22.0 release**

chore(k8s): prepare v0.22.0 release

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

2444cf6dc **chore: update release amis**

chore(ci): update release amis

---

builder/Dockerfile.alpine-tracee-container
builder/Dockerfile.alpine-tracee-make

0e019b598 **fix: release snapshot target arch**

fix: release snapshot target arch

---

builder/Dockerfile.alpine-tracee-container
builder/Dockerfile.alpine-tracee-make

0eeb12958 **fix: release snapshot target arch**
```
commit: 5583089 (main), cherry-pick
```

[v0.22.1] fix: release snapshot target arch

---

go.mod
go.sum
pkg/server/grpc/tracee.go

update go.sum and go.mod with grpc change

---

Vagrantfile

7897408cb **chore: use 6.2.0-1018-aws kernel**

chore: use 6.2.0-1018-aws kernel

---

pkg/events/derive/process_execute_failed.go

36a1a07d5 **fix: process_execute_failed use correct lru**
```
- use the correct LRU (base events)
- remove unused LRU
commit: 5ba9087 (main), cherry-pick
```

[v0.22.1] fix: process_execute_failed use correct lru

---

pkg/ebpf/processor.go
pkg/ebpf/processor_funcs.go

19f0f556a **Remove irrelevant context from uprobe based events**
```
commit: df0aa69 (main), cherry-pick
```

[v0.22.1] Remove irrelevant context from uprobe based events

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

489df306e **chore(k8s): prepare v0.22.1 release**

chore(k8s): prepare v0.22.1 release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

c82be293e **chore(k8s): prepare v0.22.1 release**
```
commit: 20a90dc (main), cherry-pick
```

[v0.22.1] chore(k8s): prepare v0.22.1 release

---

.github/workflows/performance.yaml

eBPF changes kept triggering the defunct performance gate so comment it out for now.

chore: deactive performance gate

---

signatures/helpers/helpers.go

a03470771 **chore: sig helper clone metadata**

chore: sig helper clone metadata

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

486b5ae37 **chore(k8s): prepare v0.22.2 release**

chore(k8s): prepare v0.22.2 release

---

signatures/helpers/arguments_helpers.go

- changes argv to args and close issue 4302
Fixes #4302

 change argv to args

---

pkg/proctree/proctree.go
pkg/proctree/proctree_procfs.go

Close: #3872 
97dc77af6 **fix(proctree): possible sync.Once data race**

fix(proctree): possible sync.Once data race

---

.github/workflows/fast-forward.yaml
.github/workflows/pr-ff.yaml

5871d3980 **chore(ci): add possibility of ff merging via ui**
https://github.com/sequoia-pgp/fast-forward

chore(ci): add possibility of ff merging via ui

---

docs/docs/install/config/index.md

- remove policy and capture from the documention section about config file
acording to the help and the issue i opend config file does not support those flags 
#4342

remove policy and capture form docs

---

types/trace/trace.go

e7ced10f7 **chore(types): add Zero field to ArgMeta**
```
This is field for internal use which holds the zero value
of ArgMeta.Type.
commit: d40bc1f (main), cherry-pick
```

[v0.22.3] chore(types): add Zero field to ArgMeta

---

go.mod
go.sum
pkg/bufferdecoder/decoder.go
pkg/events/core.go
pkg/events/definition_group.go
pkg/events/parse/params.go
signatures/helpers/go.mod
signatures/helpers/go.sum

f92bedd21 **fix(events): setuid16 arg name typo**
e9a66d8ef **fix: handle zero-value types for unavailable fields**
92de007e5 **chore(go.mod): bump types to latest version**
f92bedd21 **fix(events): setuid16 arg name typo**
```
'git log --grep old_old_uid_t' in Linux kernel code didn't return any
results.
commit: 2f31471 (main), cherry-pick
```
e9a66d8ef **fix: handle zero-value types for unavailable fields**
```
Some event arguments, such as "interpreter_*" from sched_process_exec,
were not being populated because the kernel might not always provide
them. This was causing errors during the gRPC proto conversion, as
the values couldn't be asserted - they were nil.
With this change, ArgMeta now holds the Zero value of the type, ensuring
that assignment is always possible without requiring …
```

[v0.22.3] Handle zero-value types for unavailable fields - ArgMeta

---

pkg/ebpf/c/tracee.bpf.c

restrict set_fs_pwd to (f)chdir syscall
./tracee -e=set_fs_pwd

feat(ebpf): restrict set_fs_pwd to (f)chdir syscall

---

pkg/mount/mount.go

Cherry-pick of https://github.com/aquasecurity/tracee/pull/4328

[v0.22.3] fix(mount): reintroduce root path requirement

---

pkg/ebpf/hooked_syscall_table.go
pkg/events/derive/hidden_kernel_module.go

Backport v0.22.0

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

f880fad77 **chore(k8s): prepare v0.22.3 release**

chore(k8s): prepare v0.22.3 release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

a57a59d52 **chore(k8s): prepare v0.22.3 release**

[v0.22.3] chore(k8s): prepare v0.22.3 release

---

pkg/events/derive/hidden_kernel_module.go

fix(events): fix slice out of bounds in hidden_kernel_module

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

f3b116cc7 **chore(k8s): prepare v0.22.4 release**

chore(k8s): prepare v0.22.4 release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

1b688f00e **chore(k8s): prepare v0.22.4 release**
```
commit: f3b116cc (main), cherry-pick
```

[v0.22.4] chore(k8s): prepare v0.22.4 release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

637d14047e9d9ff62fdf0840898af3c9fefd4243 **chore(k8s): prepare v0.22.5 release**

chore(k8s): prepare v0.22.5 release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

f5b33a16a **chore(k8s): prepare v0.22.5 release**

[v0.22.5] chore(k8s): prepare v0.22.5 release

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

Close: #4435 
113203301 **fix(ci): add runner type to release workflows**
```
Set INSTANCE_TYPE=LARGE for release workflows as
release demands a runner with higher specs.
```

fix(ci): add runner type to release workflows

---

pkg/ebpf/c/common/context.h

67aaa9582 **chore(ebpf): refactor reset_event_args_buf to mark entries as invalid**

chore(ebpf): refactor reset_event_args_buf to mark entries as invalid

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

Close: #4435 
b5d676c4d **fix(ci): set 2XLARGE runner type to x86_64**

fix(ci): set 2XLARGE runner type to x86_64

---

.github/dependabot.yaml

e5c4df45a **chore(ci): enable dependabot version updates**

chore(ci): enable dependabot version updates

---

performance/dashboard/provisioning/dashboards/tracee.json

142a4e02f **chore(performance): update tracee dashboard**
```
Add panels measuring Tracee's CPU time and updates Host ones.
```

chore(performance): update tracee dashboard

---

.github/workflows/pr.yaml

chore(ci): trigger pr workflow on release branches

---

go.mod
go.sum

8050eda94 **chore: api/types bump**

chore: api/types bump

---

pkg/analyze/analyze.go

Change the event field to Context to be backward compatible
tracee analyze --output legacy

legacy mode: align event field name in output

---

pkg/ebpf/c/tracee.bpf.c

Convert to 64bit syscall ID before checking if the syscall is selected.
Additionally, remove false positive of VDSO triggered syscalls being detected as suspicious.

fix(epbf): fix handling of compat tasks in syscall checkers

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

ffab7a045 **chore(k8s): prepare v0.22.6 release**

chore(k8s): prepare v0.22.6 release

---

builder/Makefile.release

**0db018d4f fix(build): update Makefile.release**

[v0.22.6] fix(build): update Makefile.release

---

builder/Makefile.release

095fcc66f **fix(build): update Makefile.release (#4599)**
```
Use the new RELEASE_VERSION variable to set the version in the
release build.
```

fix(build): update Makefile.release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

495927d19 **chore(k8s): prepare v0.23.0 release**

chore(k8s): prepare v0.23.0 release

---

.github/workflows/codeql.yaml

4d6de683f **fix(ci): CodeQL warning**
```
"An imported package is intended for a different OS or architecture."
```

fix(ci): CodeQL warning

---

.github/workflows/codeql.yaml

c87cd0c16 **fix(ci): CodeQL warning (2)**
```
"An imported package is intended for a different OS or architecture."
```

fix(ci): CodeQL warning (2)

---

.github/workflows/pr.yaml

chore(ci): disable action

---

go.mod
go.sum
pkg/server/grpc/tracee.go

chore(grpc): update translation table

---

.github/workflows/pr.yaml

e112d1c01 **PR #4657: chore(ci): disable action**
```
commit: fd0f3d8a5 (main), backport
```

Release v0.23.1 - 2

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

34a2000a3 **chore(k8s): prepare v0.23.1 release**

chore(k8s): prepare v0.23.1 release

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

9bb6aab34 **PR #4696: chore(k8s): prepare v0.23.1 release**
```
commit: f113bd0ca (main), cherry-pick
```

PR #4696: chore(k8s): prepare v0.23.1 release

---

.github/dependabot.yaml

bd610c8f3 **chore: add dependabot config for traceectl**

chore: add dependabot config for traceectl

---

go.mod
go.sum
pkg/server/grpc/event_data.go
pkg/server/grpc/event_data_test.go

Bump types to apply changes from #4733

chore(go.mod): bump types to 386881

---

.github/workflows/pr.yaml
Makefile
scripts/lib.sh
scripts/lib_test.sh
scripts/run_test_scripts.sh
scripts/verify_man_md_sync.sh

Close: #4690
a90d32866 **chore(ci): run scripts test units**
f7b6da0c3 **fix(ci): use verify_man_md_sync.sh**
07fcb8890 **chore(scripts): introduce scripts**
f7b6da0c3 **fix(ci): use verify_man_md_sync.sh**
```
tj-actions/changed-files has had security issues and is now being
replaced with our own logic.
```
07fcb8890 **chore(scripts): introduce scripts**
```
This folder must contain all the scripts that are used in the project
(testing, building, and other tasks). They must be POSIX compliant and
should not depend on any specific shell.
Initially, it contains the following scripts:
- `lib.sh`: a library of functions that can be used in other scripts.
- `lib_test.sh`: a unit test file for the `lib.sh` library.
- `run_test_scripts.sh`: a script that runs all the test scripts in
the …
```

Enable man/markdown pair changes check

---

signatures/golang/k8s_service_account_token.go
signatures/golang/k8s_service_account_token_test.go

46699a68b **fix(signatures): regex of K8SServiceAccountToken**

fix(signatures): regex of K8SServiceAccountToken

---

.github/workflows/codeql.yaml

1c6936d4902ec645e48783ffeb8c93b87aa61cac chore(ci): install Go for CodeQL

chore(ci): install Go for CodeQL

---

pkg/cmd/cobra/cobra.go
pkg/events/derive/symbols_loaded.go

8d8620c09 **fix(events): reduce LRU cache size which seems to...**
```
...  contain a typo. The reduction targets performance improvements.
```
0261793e2 **perf(cmd): reduce Signatures buffer size in 80%...**
```
... to meet performance improvements.
```

Memory profile improvements

---

.github/workflows/codeql.yaml

9622fcf4f **chore(ci): always run codeql**
```
The branch ruleset requires CodeQL to run on every PR and push.
```

Always run codeql

---

scripts/tracee_common.sh
scripts/tracee_start.sh
scripts/tracee_stop.sh

e39727d04 **chore: introduce tracee runtime scripts**

chore: introduce tracee runtime scripts

---

pkg/ebpf/c/common/consts.h

efe7e1f48 **Revert "chore(ebpf): update MAX_BYTES_ARR_SIZE const"**
```
This reverts commit 0605bd7ebc623f232251fb74abc2fc358250fe7b.
```

Revert "chore(ebpf): update MAX_BYTES_ARR_SIZE const"

---

.github/workflows/pr-sync.yaml

fe16bf8d1 **feat(ci): add pr-sync GitHub Action**

feat(ci): add pr-sync GitHub Action

---

.github/workflows/pr-sync.yaml

0cfaa9597 **fix(ci): pr-sync workflow**

fix(ci): pr-sync workflow

---

.github/workflows/pr-sync.yaml

4974abdb8 **chore(ci): curl max time configurable via env**

chore(ci): curl max time configurable via env

---

Makefile

It adds support to go tags in the makefile. It you make possible for example to make go vet skip some files.

chore(Makefile): add go tags to build signatures.

---

cmd/tracee-rules/main.go
pkg/analyze/analyze.go
pkg/cmd/cobra/cobra.go
pkg/ebpf/tracee.go
pkg/signatures/benchmark/benchmark_test.go
pkg/signatures/engine/engine.go
pkg/signatures/engine/engine_test.go

Fix signature loading v0.23

---

deploy/helm/tracee/Chart.yaml
deploy/kubernetes/tracee/tracee.yaml

310df5e34 **chore(k8s): prepare v0.23.2 release**

chore(k8s): prepare v0.23.2 release

---

pkg/ebpf/probes/probe_group.go
pkg/ebpf/tracee.go

Change the default autoload of probes to false. Now, only probes needed by events selected and their dependencies will be loaded to the kernel.
I tested this manually by adding a program which fails the kernel upon loading, and then checking if it crashes when the program is not used.
Future uses will by default check this change as well, so I deem the creation of a test right now as not necessary.

feat(events): load only used probes

---

.github/workflows/pr.yaml

tests: increase machine size

---

pkg/cgroup/cgroup.go
pkg/ebpf/c/common/cgroups.h

Add GetCgroupID() to extract cgroup ID from process PID and get_current_cgroup_id() BPF helper for unified cgroup access.
Supports both cgroupv1/v2 and uses existing mount detection infrastructure to avoid code duplication.

pkg/cgroup: add userspace cgroup ID extraction utilities

---

pkg/ebpf/probes/compatibility.go
pkg/ebpf/probes/compatibility_test.go

Introduce a requirement type to verify BPF program type support for probe compatibility checks.
Added unit tests

feat(ebpf): add prog type compatibility

---

.github/workflows/pr.yaml

Resolves 'Missing Base Commit' error by fetching recent git history.

fix: resolve Codecov 'missing base commit' issue

---

docs/contributing/adding-events.md

- Add section for adding events to protobuf schema (event.proto)
- Add section for updating gRPC translation table (tracee.go)
- Add section for generating protobuf files with 'make protoc'
- Add section for handling complex data type marshalling
- Enhance troubleshooting with protobuf/gRPC common issues
- Update overview to include protobuf/gRPC as main areas
- Renumber sections to accommodate new content
Addresses missing documentation for protobuf integration when adding new events to Tracee's gRPC API.

docs: add missing protobuf and gRPC sections to adding-events guide

---

.github/workflows/pr.yaml
.github/workflows/test-daily.yaml
Vagrantfile
builder/Dockerfile.alpine-tracee-container
builder/Dockerfile.alpine-tracee-make
scripts/installation/install-deps-alpine.sh
scripts/installation/install-deps-ubuntu.sh
scripts/installation/install-deps.sh

Migrates GitHub Actions to Alpine containers and consolidates dependency installation logic into OS-specific scripts for faster, more reliable builds.
- **GitHub Actions reliability issues** with Ubuntu runner dependencies  
- **Scattered installation logic** duplicated across Dockerfiles, Vagrant, and workflows
- **Inconsistent build environments** between different systems
- **6 GitHub Actions workflows** now use `container: image: alpine` 
- **Eliminates runner OS dependencies** and reduces build complexity
- **Faster builds** with lightweight Alpine containers
- **`install-deps-alpine.sh`** - Complete Alpine dependency installer
- **`install-deps-ubuntu.sh`** - Complete Ubuntu/Debian dependency installer
- **Consolidates scattered package installations** into proven, tested scripts
- …

Install deps

---

common/environment/lsm.go
common/environment/lsm_test.go

If the securityfs lsm file is missing, it is now interpreted as LSM is not supported.
Previously it was considered an error, but it is an expected behavior.
Also change the default behavior for error in analyzing the securityfs to checking the kconfig.

bugfix(lsm): interpret lsm file missing as not supported

---

pkg/server/grpc/event_data.go
pkg/server/grpc/tracee.go

This fix was originally created for ProcessLineage structure and now we are expanding to all string fields serialized to protobuf..

fix(grpc): sanitize invalid UTF-8 envent serilization to protobuf

---

pkg/ebpf/c/common/common.h

5dcc4aef8 **feat(ebpf): add min macro for comparing two values**

feat(ebpf): add min macro for comparing two values

---

pkg/ebpf/probes/compatibility.go
pkg/ebpf/probes/compatibility_test.go

Add a bpf helper compatibility requirement.
This will allow probes to use helpers only available for newer kernel versions.

feat(ebpf): add bpf helper compatibility

---

pkg/cmd/initialize/callbacks.go

3af071c35 **chore: add regex for uprobe warn**

chore: add regex for uprobe warn

---

pkg/ebpf/tracee.go

7cbf40026 **chore: refactor getSelfLoadedPrograms log other types**
```
- simplify the function getSelfLoadedPrograms, logging
all other types of probe's
```
Grep the output for `getSelfLoadedPrograms`:
```
sudo ./dist/tracee -e ftrace_hook,magic_write,hidden_kernel_module --log debug
```

chore: refactor getSelfLoadedPrograms log other types

---

common/elf/analyzer_test.go

- Removed flaky GetSymbolOffset assertion from TestSymbolFunctions_WithRealElf that was failing due to legitimate zero offsets at section boundaries
- Added TestSymbolOffsetCalculation to properly test offset calculation logic with controlled data, covering both zero and non-zero offset cases

tests: remove flaky GetSymbolOffset test and add dedicated unit test

---

pkg/ebpf/controlplane/controller.go
pkg/ebpf/controlplane/controller_test.go

9dcb01ff1 **chore: add helper function to register signal**
```
- Creates RegisterSignal, this way an extension can register a
signal
```

chore: add helper function to register signal

---

pkg/ebpf/extension.go
pkg/ebpf/extension_test.go
pkg/ebpf/tracee.go

3c22bea1b **feat(ebpf): add extension to Tracee**
```
Introduce an extension framework for modular functionality:
- Extension interface with lifecycle methods (Init, Run and Close)
- Global extension registry for automatic discovery and management
- Unit tests
This foundation enables future development of extensions while maintaining
Tracee's core stability.
```

feat(ebpf): add extension to Tracee

---

pkg/cmd/initialize/callbacks.go
pkg/cmd/initialize/callbacks_test.go

4b1c8eb04 **feat(initialize): refactor libbpf log logic**
```
- Add regex for missing BTF line
- Optimize libbpf regex patterns with anchors (^$) for better performance
- Use non-capturing groups (?:...) to reduce memory overhead
- Restructure complex alternations for improved efficiency
- Extract anonymous callback functions into named functions for testability
- Extract log level translation logic into separate function
- Add comprehensive test coverage for all regex pattern variations
- Add boundary tests to verify anchor optimizations work correctly
The optimized regexes now execute faster with proper anchoring and
non-capturing groups while maintaining identical matching behavior.
All regex patterns are thoroughly tested with edge cases and boundary
conditions to prevent regressions. …
```

feat(initialize): refactor libbpf log logic
