- cmd/tracee-rules/main.go
- pkg/ebpf/probes/cgroup.go
- pkg/signatures/celsig/config.go
- pkg/signatures/signature/signature.go
commit cb71563f (HEAD -> capabilities-fixes, origin/capabilities-fixes)
Date:   Wed Apr 19 04:01:45 2023
capabilities: fix legacy detachment for older kernels
Legacy attachments (for now: cgroupv2 prog attachments under older
kernels) might not be done using BpfLink logic. Without a file
descriptor for the link, tracee needs to raise its capabilities
in order to call bpf() syscall for the legacy detachment.
This fixes error happening in older kernels when exiting tracee:
{"level":"error","ts":1681876470.9877832,"msg":"failed to detach
probes when closing tracee","err":"probes.(*probes).DetachAll:
probes.(*cgroupProbe).detach: failed to detach program:
cgroup_skb_ingress (failed to detach (legacy) program
cgroup_skb_ingress from …
> Capabilities fixes

- pkg/ebpf/events_processor.go
in `security_kernel_read_file` parsing of the argument `type` has an error in one condition - making it never true. thus the parsing fails in some kernel versions.
```
Date:   Mon May 1 13:54:53 2023 +0300
fix: kernel version comparison
fix never-true if condition when comparing kernel versions
in initKernelReadFileTypes func
```
> fix: kernel version comparison

- pkg/containers/containers.go
Fix a bug related to detect container id when run docker on GitHub Action
run in Github Action `dist/tracee-ebpf -f e=container_create,existing_container,cgroup_mkdir -o json --containers`, run docker and check if the event contains the container id and other data.
> fix: detect container id from cgroup in  GitHub Action

- pkg/ebpf/signature_engine.go
- pkg/ebpf/tracee.go
- pkg/signatures/engine/engine.go
This change allows managing the signature engine directly from tracee when running in "everything is an event" mode.
This allows access to engine methods from tracee itself.
Due to the following change, the engine.PipelineStart method was removed as the encapsulation was no longer relevant to the purpose of this change.
Tested by:
1. Sanity checking anti_debugging_ptrace signature and making sure it still triggers
This change is necessary to resolve #3007, and will allow further future developments of direct interactions between tracee and the signature engine.
> tracee: add engine field to tracee object

- pkg/ebpf/c/tracee.bpf.c
issue: #3036
```
Date:   Wed May 3 17:33:53 2023 +0300
feat: support running tracee from pid ns
in triggered events, check the pid and host_pid of the triggering
process against tracee_pid to allow running tracee from non-host pid ns
```
run tracee inside WSL
command: `./dist/tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=security_bprm_check`
upon tracee startup you should get `print_mem_dump` event.
> feat: support running tracee from pid ns

- pkg/cmd/initialize/callbacks.go
After https://github.com/aquasecurity/libbpfgo/commit/6d17d1ac71918fcf13379ffecfbccff607204b9b, the libbpf message is passed as it is to the callback function. This causes the message to be printed with an additional newline.
So this commit trims the suffix newline from the message.
Fix: #2950
> libbpfgo: trim suffix newline from libbpf message

- cmd/tracee/cmd/root.go
After moving to cobra, flags are automatically sorted alphabetically. This, however, is not the desired behavior since we want the most useful flags to show first in the help message.
Disable this automatic sorting behavior.
`./dist/tracee -h`
> cli: don't sort flags in help/usage messages

- cmd/tracee/cmd/root.go
- cmd/tracee/main.go
While tracee doesn't reach the Run() function, we don't want to log anything, just print possible errors to stderr.
Fix: #3044
> cmd: log only after tracee.Run()

- pkg/cmd/tracee.go
- pkg/ebpf/signature_engine.go
- pkg/ebpf/tracee.go
Adds a new config field MetricsEnabled, which is used to register tracee and the rule engine's (in everything is an event) stats, instead of relying on doing in the runner when the flag is enabled from the server (which now informs the config field instead).
Fix #3007
> tracee: move metrics register to tracee

- cmd/tracee/cmd/root.go
- docs/docs/config/overview.md
- pkg/cmd/cobra/cobra.go
The previous implementation was making use of StringSlice which parses the input as a comma separated list. This is not what we want, we want to be able to pass multiple values to the same flag, letting the parsing of the values to the Prepare function.
```
❯ sudo ./dist/tracee --filter event=openat,close --filter comm=ls --filter comm=uname,who                                      
07:38:27:474415  1000   ls               830292  830292  3                openat                    dirfd: -100, pathname: /etc/ld.so.cache, flags: O_RDONLY|O_CLOEXEC, mode: 0
07:38:27:474447  1000   ls               830292  830292  0                close                     fd: 3
07:38:27:474479  1000   ls …
```
> cmd: cobra: fix parsing for multiple values

- .github/workflows/debug-shell.yaml
- .github/workflows/pr.yaml
@yanivagman FYI, IMO would be good to have those included (and any issue fixed, like https://github.com/aquasecurity/tracee/pull/3067, before the 0.14.1).
These are 6.1 and 6.3 kernels from the upstream stable tree, being used in Ubuntu Jammy, and using the same kconfig values as Ubuntu does for 5.19 kernels (this way we can test upstream trees before Ubuntu releases them).
> workflow: add 6.1 and 6.3 kernels

- pkg/cmd/printer/broadcast.go
- pkg/cmd/tracee.go
- pkg/ebpf/bpf_log.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/net_capture.go
- pkg/ebpf/tracee.go
- pkg/ebpf/write_capture.go
- pkg/server/server.go
commit 502db312fdb975e44d2e5419e6da8b1e4d33c581
cosmetics
commit 47399fff525a2a9d663e967ba84b879ea2dd3dcb
tracee: add done channel to Tracee struct
This is an end-stage channel that will be used to signal the last
processing goroutines to stop. This is needed to avoid a deadlock in
processLostEvents().
commit c94cbcd41cd47e496328fa8ff454a1cfcc62024a
add ctx to lkmSeekerRoutine
This make lkmSeekerRoutine goroutine safe by adding a context to it.
commit f9e442f19aa6ed6652bf54a6703e18cfc7c8fbac
tracee: add done channel to Broadcast struct
This add a done channel to Broadcast struct, and closes it by calling
Close() method. This way, the printer goroutine can be stopped by
closing the channel in a late stage of the program execution instead of
using the main ctx that is cancelled first.
Set a …
> fix deadlocks triggered by cancelled ctx

- pkg/ebpf/events_processor.go
- pkg/events/events.go
fix #3071
commit 6edd49a5041601c7c6ece7bc38ad13ceb2e804b0 (HEAD -> fix_print_mem, origin/fix_print_mem)
Date:   Wed May 3 14:09:55 2023 +0300
make print_mem_dump reprint on kernel module load
fix #3071
`sudo dist/tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=execve,kill`
load a kernel module and see 2 new events being printed.
> make print_mem_dump reprint on kernel module load

- .github/workflows/debug-shell.yaml
- .github/workflows/pr.yaml
- cmd/tracee-ebpf/main.go
- go.mod
- go.sum
- pkg/ebpf/c/common/capabilities.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/c/vmlinux_flavors.h
- tests/e2e-instrumentation-test.sh
- tests/e2e-net-test.sh
- tests/kerneltest.sh
commit cea89a66 (HEAD -> include-v6, rafaeldtinoco/include-v6)
Date:   Mon May 8 23:45:33 2023
workflow: enable v6.1 and v6.3 tests after fix
commit f45cc1ba
Date:   Mon May 8 23:42:07 2023
ebpf: CO-RE: deal with new kernel_cap_t type
commit 57520600
Date:   Mon May 8 12:54:31 2023
workflow: fix debug-shell job name
commit 6aee7293
Date:   Mon May 8 12:53:06 2023
tests: cleanup tracee.pid in case not cleaned
----
The only change that isn't chore is the change that fixes v6.3 kernels (commit f45cc1ba) and the way to test it:
```console
$ sudo ./dist/tracee --output json …
```
> fix for kernels v6.3 and mitigation for tracee.pid in tests

- go.mod
- go.sum
https://github.com/aquasecurity/libbpfgo/commit/80f41e18e690e279a1edc123a2382c3b16db2094 Fix double-free in NewModuleFromBufferArgs
> Bump libbpfgo to v0.4.8.1-libbpf-1.2.0

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
fixes: #3063
```
Date:   Sun May 7 14:39:10 2023 +0300
fix: correct list of bpf helpers
get correct kernel version when getting bpf helpers list for
bpf_attach and security_bpf_prog events
```
in kernel version >= 5.13 : 
terminal 1: `./dist/tracee-ebpf -f e=bpf_attach`
terminal 2: `./dist/tracee-ebpf -f e=security_socket_bind`
> fix: correct list of bpf helpers

- builder/entrypoint.sh
- deploy/helm/tracee/Chart.yaml
- deploy/kubernetes/kustomize/base/tracee.yaml
- deploy/kubernetes/tracee-postee/tracee.yaml
- deploy/kubernetes/tracee/tracee.yaml
commit 8564f2cd (HEAD -> about-to-be-released, rafaeldtinoco/about-to-be-released)
Date:   Tue May 9 23:46:27 2023
k8s: update tags for about to be released version
commit 62d8b3ac
Date:   Tue May 9 23:44:42 2023
types: update to latest types
commit 1c59f8a2
Date:   Tue May 9 23:33:34 2023
entrypoint: fix container image arguments
Currently the docker image given arguments were put at the end of an
already set cmdline with some arguments before. With that, it is
currently impossible to give a simple "help" or "list" argument to
the container image.
This commit fixes the issue by replacing ALL "tracee" command line
with a given …
> v0.14.1: about to be released

- .github/workflows/release-arm64-only.yaml
- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
The git checkout might be a shallow clone and not have all needed tags in order for "git describe" to work, knowing the exact version to be released.
> workflow: guarantee release has needed tags

- .dockerignore
- builder/Dockerfile.alpine-tracee-container
- pkg/cmd/initialize/bpfobject.go
Currently, after the single binary was added to the official container image, I believe BTFHUB support has not been included in the binaries of the docker images. This needs fixing asap as this is what allows tracee to be fully portable.
This is an important fix if you want to run tracee in older kernels.
@ShiraCohen33 FYI. I'll be merging this fix and doing a new release of v0.14 (to v0.14.3). You can cherry-pick/backport the fix if it solves your issue.
@josedonizetti FYIO, the single binary didn't have BTFHUB support, so I added.
> btfhub: fix tracee container image with btfhub

- deploy/helm/tracee/templates/daemonset.yaml
- deploy/kubernetes/kustomize/base/tracee.yaml
- deploy/kubernetes/tracee-postee/tracee.yaml
- deploy/kubernetes/tracee/tracee.yaml
Fix https://github.com/aquasecurity/tracee/issues/2731
The PR maps the paths for tracee runtime autodiscovery, and enables enrichment by default. This might not cover all cases, see https://github.com/aquasecurity/tracee/issues/1864, but it was tested and worked on kind, minikube, azure, digital ocean and google kubernetes engine, so it is a good start. 
```
kubectl apply -f deploy/kubernetes/tracee/tracee.yaml
helm repo add aqua https://aquasecurity.github.io/helm-charts/
helm dependency update ./deploy/helm/tracee
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true
kubectl run test --image=ubuntu:latest -- tail -f /dev/null
kubectl exec -ti test -- apt update -y && apt install -y strace  && strace ls
```
> k8s: enrichment enabled by default

- pkg/cmd/cobra/cobra.go
- pkg/cmd/printer/broadcast.go
- pkg/cmd/tracee.go
- pkg/cmd/urfave/urfave.go
This PR refactors the broadcast to be a printer. The idea of refactoring is to simplify the interface of the Runner, exposing only one printer to the outside, keeping the whole logic of printers creation inside the `pkg/cmd` and `flags`, with this refactor in place, a follow-up PR will be created to add a printer which is policy aware for policies' actions (webhook, and fluentd), the new printer will route events where it is appropriate instead of broadcast for all printers.
Part of -> https://github.com/aquasecurity/tracee/issues/2975
> refactor: add broadcast printer

- pkg/ebpf/c/tracee.bpf.c
fixes: #3077
```
Date:   Sun May 21 16:55:33 2023 +0300
fix: file_modification not triggered in newer kernels
file_modification event was not triggered properly in kernels 6.*
```
command: `./dist/tracee -f e=file_modification`
> fix: file_modification not triggered in newer kernels

- docs/docs/outputs/logging.md
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/logger_test.go
- pkg/cmd/initialize/callbacks.go
- pkg/logger/filter.go
- pkg/logger/logger.go
callbacks: print formatted libbpf verifier errors
This filters out logs originated from libbpf which are related to bpf
loading failure. It outputs that error message in a formatted way
via stderr.
logger: flags: add filter and filter-out
This commit adds two new options to log flag: filter and filter-out.
The filter option is used to filter out logs that do not match the
option values. The filter-out option is used to filter out logs that
match the option values.
The filter and filter-out flags can be used multiple times to filter
out or filter, and can be used together.
Filter options:
msg=<value,...>    | Filters logs that message contains a value.
regex=<value,...>  | Filters logs that a regex matches the message.
pkg=<value,...>    | Filters logs that originate from a package. …
> logger: flags: add filter and filter-out

- docs/docs/policies/actions.md
- pkg/cmd/cobra/cobra.go
- pkg/cmd/cobra/helper.go
- pkg/cmd/printer/broadcast.go
- pkg/cmd/printer/policy.go
- pkg/cmd/urfave/urfave.go
- pkg/policy/policy_file.go
Adds a printer for policy actions. The printer creates a map where a policy event can point to a specific printer, if it was overriding on the policy declaration, or if not, uses the default action. 
Fix https://github.com/aquasecurity/tracee/issues/2975
```
name: dig
description: traces dns events from the dig binary
scope:
- global
defaultAction: log
rules:
- event: ptrace
- event: net_packet_dns_request
action: webhook:http://localhost:8080
- event: net_packet_dns_response
action: webhook:http://localhost:8081
```
> Add policy printer

- cmd/tracee-rules/output_test.go
- go.mod
- go.sum
- pkg/ebpf/events_pipeline.go
- tests/integration/integration_test.go
The PR reintroduces the `ContainerID` field into the `trace.Event` type.
It should be equivalent to using the new `.Container.ID` field.
This was done because the field change back in v0.13 has broken some json consumers of tracee.
We've decided to duplicate this field in it's original format until we make the event type overhaul in v0.16 to let consumers have more time to prepare migrations.
Run `tracee -o json -f c`
Start a container `docker run --rm ubuntu`
Confirm that both the `"containerId"` field and `"container": "id"` field are populated the same way.
> chore: restore old ContainerID field

- pkg/ebpf/c/tracee.bpf.c
bpf: fix int truncation in address holder
Running `sudo ./dist/tracee -f comm=uname -o json | jq` on this PR, should not (falsely) detect syscall hooks.
Running on main:
`sudo ./dist/tracee -f comm=uname -o json | jq`
```json
{
"timestamp": 0,
"threadStartTime": 0,
"processorId": 0,
"processId": 0,
"cgroupId": 0,
"threadId": 0,
"parentProcessId": 0,
"hostProcessId": 0,
"hostThreadId": 0,
"hostParentProcessId": 0,
"userId": 0,
"mountNamespace": 0,
"pidNamespace": 0,
"processName": "",
"hostName": "",
"containerId": "",
"container": {},
"kubernetes": {},
"eventId": "6028",
"eventName": "syscall_hooking",
"matchedPolicies": [
""
],
"argsNum": 1,
"returnValue": 0,
"syscall": "",
"stackAddresses": [
0
],
"contextFlags": {
"containerStarted": false,
"isCompat": false
},
"args": [
{
"name": …
```
> bpf: fix int truncation in address holder

- pkg/ebpf/tracee.go
- pkg/policy/policies.go
ebpf: events: set policies for init events
This sets the policies for the init events, populating matchedPolicies
names in the event by using setMatchedPolicies().
`sudo ./dist/tracee -f e=init_namespaces -o json`
```json
{"timestamp":1685388723975242360,"threadStartTime":0,"processorId":0,"processId":0,"cgroupId":0,"threadId":0,"parentProcessId":0,"hostProcessId":0,"hostThreadId":0,"hostParentProcessId":0,"userId":0,"mountNamespace":0,"pidNamespace":0,"processName":"tracee-ebpf","hostName":"","containerId":"","container":{},"kubernetes":{},"eventId":"2013","eventName":"init_namespaces","matchedPolicies":[""],"argsNum":10,"returnValue":0,"syscall":"","stackAddresses":null,"contextFlags":{"containerStarted":false,"isCompat":false},"args":[{"name":"cgroup","type":"u32","value":4026531835},{" …
```
> ebpf: events: set policies for init events

- pkg/policy/policy_file.go
- pkg/policy/policy_file_test.go
policy: add not-equal operator parsing
This adds the not-equal operator check to the policy parser. It also
adds test cases for the not-equal operator.
`sudo ./dist/tracee -p ./not_equal.yaml`
```yaml
name: test policy
description: test symbols_loaded filter
scope:
- global
defaultAction: log
rules:
- event: symbols_loaded
filter:
- args.symbols=fopen
- args.library_path!=libc
```
Fix: #3166
> policy: add not-equal operator parsing

- docs/docs/events/builtin/extra/bpf_attach.md
address changes to the bpf_attach event in the .MD file
```
Date:   Wed May 31 11:22:02 2023 +0300
docs: update docs for bpf_attach event
additional probe and arguments names changes
```
> docs: update docs for bpf_attach event

- pkg/cmd/cobra/helper.go
- pkg/cmd/cobra/helper_test.go
Fix https://github.com/aquasecurity/tracee/issues/3191
`--output option*` were getting ignore when using policies.
```
name: test
description: test
scope:
- comm=ping
defaultAction: log
rules:
- event: sched_process_exec
```
```
sudo ./dist/tracee -p policy.yml --output option:exec-env --output json
```
env should not be empty
> policy: fix output options

- types/trace/trace.go
types: change Event fields
"MatchedPolicies" pass to be named "MatchedPoliciesKernel" and
propagated through the pipeline without being changed (internal).
"MatchedPoliciesUser" is a new bitmask of the policies that matched
after applying user land filters through the pipeline (internal).
"MatchedPoliciesNames" is now named "MatchedPolicies" (public).
Required by #3183
> types: change Event fields

- pkg/ebpf/c/tracee.bpf.c
commit 77cf072129e749139c7e1e2325a019d90ca98347 (HEAD -> 3184-net-return, origin/3184-net-return)
Author: Geyslan Gregório <geyslan@gmail.com>
Date:   Fri Jun 2 16:08:15 2023 -0300
ebpf: bitwise should_submit_net_event return
This is the continuation of #3184, fixing should_submit_net_event()
return.
> ebpf: bitwise should_submit_net_event return

- .github/workflows/release.yaml
Fix permission to write contents for the release workflow.
```
./dist/signatures/builtin.so
[7660](https://github.com/aquasecurity/tracee/actions/runs/5198242348/jobs/9374109061#step:6:7661)HTTP 403: Resource not accessible by integration (https://api.github.com/repos/aquasecurity/tracee/releases)
[7661](https://github.com/aquasecurity/tracee/actions/runs/5198242348/jobs/9374109061#step:6:7662)make: *** [builder/Makefile.release:161: release] Error 1
[7662](https://github.com/aquasecurity/tracee/actions/runs/5198242348/jobs/9374109061#step:6:7663)Error: Process completed with exit code 2.
```
> workflow: fix contents permissions

- tests/integration/event_filters_test.go
Fix: #3219
f393a556 **tests: fix event MatchedPoliciesUser check** _<sub>(2023/jun/08) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
For matched policies bitmap, it was wrongly checking for the
MatchedPolicies field, which is now the matched policies' names.
This commit fixes the check to use the MatchedPoliciesUser (bitmap)
field instead.
```
> tests: fix event MatchedPoliciesUser check

- pkg/ebpf/c/tracee.bpf.c
Anonymous files in `mmap` triggering `mem_prot_alert` got an incorrect file info, because it was not checked.
Fix it so there won't be file info in this case.
fix #3217
Ran it using the following script:
```
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
int main() {
size_t size = 4096; // Size of memory to allocate (in bytes)
void* addr = NULL;  // Address at which to create the mapping
// Allocate anonymous memory with write and execute permissions
void* ptr = mmap(addr, size, PROT_WRITE | PROT_EXEC, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
if (ptr == MAP_FAILED) {
perror("mmap");
exit(1);
}
if (munmap(ptr, size) == -1) {
perror("munmap");
exit(1);
}
return 0;
}
```c
> ebpf: fix mem_prot_alert anonymous file info

- Makefile
90217202 **makefile: add check-pr rule** _<sub>(2023/jun/07) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
This rule will run all code checks (not tests) and output a formatted
summary of all commits that are not yet in the main branch to be used
for pull requests head comments.
```
From your working branch, after commits created, run `make check-pr`.
Chore.
> makefile: add check-pr rule

- go.mod
- go.sum
- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
- pkg/events/derive/hidden_kernel_module.go
- pkg/events/derive/symbols_loaded.go
- pkg/pcaps/cache.go
- pkg/pcaps/common.go
Upgrade `hashicorp/golang-lru` to v2.
This includes generics and further optimizations and fixes.
TODO: add pcaps tests to make sure it doesn't break.
> chore: migrate to golang-lru v2

- pkg/containers/containers.go
This ensures that only the cgroup subpath is evaluated for a container id.
This resolves the case where container mounting the cgroup fs through kubernetes may have their container id as part of the mountpoint. Then, events on the host would be evaluated with respect to that mountpoint, including its container id.
> containers: trim mountpoint from stored paths

- docs/docs/integrating/container-engines.md
1eeeeb25 **docs: remove old trace subcommand** _<sub>(2023/jun/14) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
```
Mentioned in https://github.com/aquasecurity/tracee/pull/3226#discussion_r1229179145
Detected via regex search: `docker run[\s\S\n]+?trace`
> docs: remove old trace subcommand

- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/filters/containers.go
- pkg/filters/string.go
- pkg/filters/uint.go
- pkg/policy/policies.go
5bce4837 **policies: replace "userspace" with "userland"** _(2023/jun/08) <Geyslan Gregório>_
```
```
0a015810 **docs: change "bitmask" mentions to "bitmap"** _(2023/jun/07) <Geyslan Gregório>_
```
```
229ce1c9 **ebpf: pipeline: reduce iteration over policies** _(2023/jun/07) <Geyslan Gregório>_
```
This creates a policy bitmap with filters that need to be checked in the
userland. This bitmap is used to avoid iterating the entire map when
there is no policy match in the kernel that requires userland filtering.
When there is a policy that requires userland filtering, the iteration
must be done using FilterableInUserSpaceMap(), which returns a possible
reduced map of policies.
```
> ebpf: pipeline: reduce iteration over policies

- pkg/signatures/engine/engine.go
[Wait must be synchronized with the first Add.](https://go.dev/src/sync/waitgroup.go?s=1857:1892#L42) 
This seems to be the case here, as we call Add from inside the goroutine, for a short lived `tracee-rules` process there might  be a race between `checkCompletion` and `signatureStart` triggering the error reported on the issues https://github.com/aquasecurity/tracee/issues/3230 and https://github.com/aquasecurity/tracee/issues/3151
> engine: fix panic on waitgroup

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/events.go
commit a68570d2c97b
```
ebpf: simplify socket_accept tailcall
Use the existing sockaddr buffer submit helper, instead of manually
parsing and submitting.
```
commit 5d843b0c548bf8b0ed8a7c
```
ebpf: fix socket_accept event
1. Event definition was missing a tail call register for the accept
syscalls in the sys_exit_init program.
2. The sockfd argument was not saved into the argument buffer.
```
Fix #3229
> ebpf: fix socket_accept event

- pkg/signatures/signature/signature.go
Fix https://github.com/aquasecurity/tracee/issues/2778
If the binary is static, we will skip the golang signatures in order to avoid panics, so tracee-static can still be used for builtin events and rego signatures.
on main:
```
make clean && make
rm dist/tracee
BTFHUB=0 STATIC=1 make tracee
sudo ./dist/tracee # should trigger the error
```
on this PR, the same test print it is skipping the golang plugin.
> tracee: skip golang plugin for static binaries

- cmd/tracee-rules/main.go
- cmd/tracee/cmd/list.go
- cmd/tracee/cmd/root.go
- docs/docs/events/custom/overview.md
- pkg/cmd/cobra/cobra.go
- pkg/signatures/signature/signature.go
- pkg/signatures/signature/signature_test.go
Fix https://github.com/aquasecurity/tracee/issues/3179
```
Date:   Wed Jun 14 20:48:42 2023 -0300
feat: signatures-dir accept multiple values
```
The tracee-rules binary should be working as before:
```
mkdir /tmp/test
./dist/tracee-rules --help # should still only support one dir
./dist/tracee-rules --list 
./dist/tracee-rules --list --rules-dir=/tmp # should find no signatures
```
The unified binary should now support multiple directories:
```
mkdir /tmp/test
./dist/tracee list
./dist/tracee list --signatures-dir=/tmp/test # should not find any signatures
./dist/tracee list --signatures-dir=/tmp/test --signatures-dir=./dist/signatures # should find normal signatures
./dist/tracee --signatures-dir=/tmp/test -f e=anti_debugging # should fail …
```
> tracee: signatures-dir accept multiple values

- pkg/bufferdecoder/decoder.go
- pkg/bufferdecoder/decoder_test.go
- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_test.go
- pkg/bufferdecoder/protocol.go
- pkg/bufferdecoder/protocol_test.go
- pkg/containers/containers.go
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/common/signal.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/controlplane/signal.go
- pkg/ebpf/events_enrich.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
- pkg/events/derive/container_create.go
- pkg/events/derive/container_remove.go
- pkg/events/derive/hidden_kernel_module.go
- pkg/events/derive/hooked_seq_ops.go
- pkg/events/derive/hooked_syscall.go
- pkg/events/derive/symbols_collision_test.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/parse/params.go
- pkg/events/parse/params_test.go
- pkg/events/trigger/context.go
Add a control plane package which attaches specialized shorter eBPF probes to guarantee lifecycle events reach tracee.
Currently, only container lifecycle events are handled.
```
Date:   Sun Jun 4 09:04:16 2023 +0000
ebpf: refactor arg buffer to type
```
```
Date:   Wed Jun 7 12:14:55 2023 +0000
bufferdecoder: add DecodeArguments method
```
```
Date:   Wed Jun 7 12:29:37 2023 +0000
events/parse: refactor parse.ArgVal
Take arguments array directly instead of the entire event.
```
```
Date:   Wed Jun 7 12:31:05 2023 +0000
ebpf: add control plane
The …
```
> eBPF control plane signals

- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
Fix: #3267
218c6e04 **fix: send init events to pipeline** _<sub>(2023/jun/26) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
This commit fixes the issue where init events were sent to printer
directly instead of being sent to the pipeline.
```
`sudo ./dist/tracee -f e=init_namespaces -o json`
> fix: send init events to pipeline

- pkg/ebpf/tracee.go
- pkg/ebpf/tracee_test.go
- pkg/events/events.go
This was supposed to enter together with https://github.com/aquasecurity/tracee/pull/3252 (the full event definition instances) but, because of the release, this fix has to be applied before that can be merged.
This fixes race issues with the tailcall dependency instance (already merged into main before that PR).
NOTE: This code is fully tested against thread-safety but the tests will be merged altogether in that PR.
> fix(pkg/events): fix tailcall dependencies race issues

- .github/workflows/mkdocs-latest.yaml
- .github/workflows/release.yaml
Starting the version 0.16.0 we will branch out from the main 1 week before the release date, and then run the release workflow manually
```
Date:   Mon Jun 26 15:14:02 2023 -0300
build: remove release on tag push
Starting the version 0.16.0 we will branch out from the main 1 week
before the release date, and then run the release workflow manually
```
> build: remove release on tag push

- .gitignore
- Makefile
- tests/integration/event_filters_test.go
- tests/integration/integration_test.go
- tests/integration/tracee.go
dc068334 **chore: move syscaller to dist** _<sub>(2023/jun/26) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
This commit moves syscaller to dist.
This also makes integration tests don't fail if not run as root. Now,
they will just skip the tests that require root privileges.
```
`make integration-test`
`sudo make integration-test`
> chore: move syscaller to dist

- cmd/tracee/cmd/analyze.go
Fix https://github.com/aquasecurity/tracee/issues/2736
Adds analyze subcommand. The subcommand only accepts json as input, and only output json.
```
tracee --filter event=ptrace --output=json:events.json
tracee analyze events.json
tracee analyze --event=anti_debugging events.json
tracee analyze --event=dropped_executable events.json
```
This is marked as EXPERIMENT, because the implementation will later change to support datasources. For now this is equivalent to `tracee-rules`.
> tracee: add analyze cmd

- deploy/helm/tracee/templates/tracee-policies.yaml
- deploy/kubernetes/tracee/tracee.yaml
- docs/docs/events/overview.md
- docs/docs/policies/actions.md
- docs/docs/policies/index.md
- docs/docs/policies/rules.md
- docs/tutorials/k8s-policies.md
- examples/policies/container_dns_events.yaml
- examples/policies/context_comm.yaml
- examples/policies/dig.yaml
- examples/policies/new_containers.yaml
- examples/policies/new_pids.yaml
- examples/policies/not_containers.yaml
- examples/policies/openat_args_pahtname.yaml
- examples/policies/pid_equal.yaml
- examples/policies/scope_comm.yaml
- examples/policies/signature_events.yaml
- examples/policies/uid_higher_than_or_equal_to_zero.yaml
- pkg/cmd/cobra/helper.go
- pkg/cmd/cobra/helper_test.go
- pkg/cmd/flags/policy.go
- pkg/cmd/flags/policy_test.go
- pkg/cmd/printer/benchmarks/printer_test.go
- pkg/cmd/printer/policy.go
- pkg/policy/policy_file.go
- pkg/policy/policy_file_test.go
Fix https://github.com/aquasecurity/tracee/issues/3241
Fix https://github.com/aquasecurity/tracee/issues/3181
This PR does two things:
1 - renames a few fields of the policy, and fix the code where appropriate.
filter -> filters
action -> actions
2 - add support to multiple default actions
defaultAction -> defaultActions
This PR will break the internal tests, because of the policies change.
> policies: rename list fields to be plural

- pkg/counter/counter.go
- pkg/counter/counter_bench_test.go
- pkg/counter/counter_test.go
- pkg/ebpf/bpf_log.go
- pkg/ebpf/capture.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/net_capture.go
- pkg/ebpf/signature_engine.go
- pkg/ebpf/tracee.go
- pkg/events/trigger/context.go
- pkg/metrics/stats.go
- pkg/signatures/engine/engine.go
- pkg/signatures/engine/engine_test.go
- pkg/signatures/metrics/stats.go
a6817c18d **fix(pkg/counter): finish making counter atomic** _<sub>(2023/Jun/27) Rafael David Tinoco \<raf>
```
Last changes renamed Increment/Decrement to Increase/Decrease. This was
reverted after discussions.
With this new approach:
- Overflow is detected in both cases (and proved by test).
- Thread safety is guaranteed by atomic Add/Sub operations.
- Unit tests prove all assumptions and thread safety for all cases.
NOTE: The issue is now fully fixed...
Originally, the bug was only about reading counter value in parallel to
atomic operation (multiple LOAD/STORE simultaneously, and some not
protected by atomics).
Previous fix, made by commit 1e54ce292, fixed data race but overflow errors
could be reported more than once. It also had atomic operations for each
given argument (if multiple …
```
> fix(pkg/counter): finish making counter atomic

- pkg/ebpf/events_pipeline.go
Fix https://github.com/aquasecurity/tracee/issues/3279
The bug happens because we pass a different event to [`matchPolicies`](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L522) inside the for, instead of passing the [event that goes down the pipeline](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L531), so the logic of [changing the bitmap](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L366) is lost, because it happened on different events.
```
name: pol1
description: general policy
scope:
- global
defaultActions: 
- log
rules:
- event: cgroup_mkdir
filters:
- args.cgroup_path!=/system.slice*
- event: container_create
```
```
./dist/tracee -p policy.yaml
```
```
docker run ubuntu:latest ls
``` …
> fix: derived event not triggering if base filtered

- pkg/ebpf/events_pipeline.go
commit: 00f71ab (main), cherry-pick
The bug happens because we pass a different event to [`matchPolicies`](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L522) inside the for, instead of passing the [event that goes down the pipeline](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L531), so the logic of [changing the bitmap](https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L366) is lost, because it happened on different events.
```
name: pol1
description: general policy
scope:
- global
defaultActions: 
- log
rules:
- event: cgroup_mkdir
filters:
- args.cgroup_path!=/system.slice*
- event: container_create
```
```
./dist/tracee -p policy.yaml
```
```
docker run ubuntu:latest ls
```
The …
> [v0.16.0] fix: derived event not triggering if base filtered

- pkg/containers/containers.go
- pkg/containers/datasource.go
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/events_processor.go
The `container_create` argument enrichment was broken due to a race in context switching between the control plane and the ebpf event pipeline.
As such the control plane would trigger but a context switch could cause the pipeline continue instead. Then when enrichment for the `cgroup_mkdir` event would trigger, the cgroup info would be missing in the `Containers` struct, since now the control plane populates it.
The root cause is that the locking scheme in `Containers` is non transactional. Now that we have multiple pipelines writing to the `Containers` struct, locking should align with the situation. This PR does that.
```
containers: change locking scheme
Locks in the container package were as short as possible.
This caused transaction issues once a few actors interacted with it. …
```
> enrich: fixes post control plane

- pkg/containers/containers.go
- pkg/containers/datasource.go
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/events_processor.go
> fix: enrich post control plane (#3285)

- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/events.go
- pkg/filters/args.go
Fix https://github.com/aquasecurity/tracee/issues/3207
This PR builds a map between a base event and its signatures, allowing us to check after the `decode` stage if the event should be passed down the pipeline because there is a signature depending on it, or in case the userland filter out the event, ignore it and continue. 
```
name: signature_events
description: traces all signature events
defaultActions: 
- log
scope:
- global
rules:
- event: ptrace
filters:
- userId=1000
- event: anti_debugging
```
```
./dist/tracee -p policy.yaml
```
```
sudo strace ls
```
The `anti_debugging` signature should be triggered even though we are filtering the `ptrace` event for the uid 1000.
> fix: signature event not triggering if base filtered

- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_pipeline_bench_test.go
- pkg/ebpf/tracee.go
04bf8534f **perf:(pipeline) memory efficiency using pool** _<sub>(2023/jul/01) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
This commit employs sync.Pool to bolster memory performance in event
handling. The benchmarking file, events_pipeline_bench_test.go,
simulates the pipeline execution and measures sync.Pool's effectiveness.
Benchmark command:
go test \
-benchmem -benchtime=100x \
-run=^$ -bench ^(BenchmarkGetEventFromPool|BenchmarkNewEventObject)$ \
github.com/aquasecurity/tracee/pkg/ebpf
Findings:
Environment:
- OS: Linux
- Arch: amd64
- Package: github.com/aquasecurity/tracee/pkg/ebpf
- CPU: Intel Core i7-12700H
Benchmarking Results:
BenchmarkGetEventFromPool (with pooling):
- Time per Op: 1740.88 ms
- Memory per Op: 243.5 KB
- Allocations per Op: 543
BenchmarkNewEventObject …
```
> pipeline memory efficiency using pool

- pkg/ebpf/c/tracee.bpf.c
syscall_pathname was fetched only for open(at) syscalls, thus was empty for security_file_open originated from execve(at) syscall
./tracee -f e=security_file_open
> events: update syscall_pathname for security_file_open

- pkg/containers/containers.go
The write Lock() is not getting released because of the defer, blocking the read RLock(), and the pipeline.
Fix https://github.com/aquasecurity/tracee/issues/3310
We had a deadlock introduced on the last release on the PR https://github.com/aquasecurity/tracee/pull/3285
The write [`Lock()`](https://github.com/aquasecurity/tracee/blob/main/pkg/containers/containers.go#L383) isn't getting release due to the [`defer`](https://github.com/aquasecurity/tracee/blob/main/pkg/containers/containers.go#L384), which blocks the read [`RLock`](https://github.com/aquasecurity/tracee/blob/main/pkg/containers/containers.go#L398) and the pipeline.
To fix it, I remove the defer and did the lock() and unlock() on the critical path, also removed the `return`, we only update the cgroupMap inside the if logic, …
> pkg/containers: fix deadlock

- pkg/containers/containers.go
Cherry pick https://github.com/aquasecurity/tracee/pull/3311 to v0.16.0 branch (will release v0.16.1).
> [v0.16.0] pkg/containers: fix deadlock

- deploy/helm/tracee/Chart.yaml
- deploy/kubernetes/tracee/tracee.yaml
Cherry pick https://github.com/aquasecurity/tracee/pull/3316 to v0.16.0 branch (will publish the helm chart with 0.16.1).
> [v0.16.0]  chore: bump k8s tag to 0.16.1

- cmd/tracee-rules/readme.md
The tracee rules docs site in the repo is one of the links that shows up when searching for Tracee. I just want to make sure people then get easily to the right information.
> docs: updating link to tracee docs for search results

- pkg/cgroup/cgroup.go
- pkg/containers/containers.go
- pkg/ebpf/controlplane/controller.go
```
commit b3d043c558b50526fef1c7e65c8d89db8f984d28
Date:   Tue Jul 18 14:59:12 2023 +0000
fix (cgroups): already dead edge case
Certain kubernetes version make use of short lived cgroups for various
tasks (for example log rotation). These cgroups will generate events and
a very quick cgroup_rmdir event.
As such, many related events to the cgroup will attempt to query its
directory through the recursive path and not find it.
Commit adds a "Dead" field to the cgroup info to indicate a cgroup which
has already been removed. Various logical sections can refer to it if
its relevant to them, and more importantly, additional queries will not
be attempted.
Bonus: optimize away additional Stat syscall in containers by returning
the …
```
> fix (cgroups): already dead edge case

- pkg/cgroup/cgroup.go
- pkg/containers/containers.go
- pkg/ebpf/controlplane/controller.go
> [v0.16.0] backport: dead cgroups fix

- deploy/helm/tracee/Chart.yaml
- deploy/kubernetes/tracee/tracee.yaml
Backport https://github.com/aquasecurity/tracee/pull/3331
> [v0.16.0] chore: bump k8s tag to 0.16.2

- pkg/ebpf/c/common/filtering.h
- tests/integration/event_filters_test.go
- tests/integration/tracee.go
Close: #3327 
bb8c4c8ac **fix(ebpf): size of mntns/pidns filters key holders** _<sub>(2023/jul/25) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
Even though the namespace id is a 32-bit integer, the key size for the
mntns/pidns filters has been set to 64-bit. This caused these filters to
not work correctly as their key value was being read beyond limits.
Chore: Add integration tests for mntns/pidns filters.
```
See #3327.
> fix(ebpf): size of mntns/pidns filters key holders

- pkg/ebpf/c/common/filtering.h
- tests/integration/event_filters_test.go
- tests/integration/tracee.go
32ff32e26 **fix(ebpf): size of mntns/pidns filters key holders (#3337)** _<sub>(2023/jul/25) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
Even though the namespace id is a 32-bit integer, the key size for the
mntns/pidns filters has been set to 64-bit. This caused these filters to
not work correctly as their key value was being read beyond limits.
Chore: Add integration tests for mntns/pidns filters.
commit: bb8c4c8 (main), cherry-pick
```
> [v0.17.0] fix(ebpf): size of mntns/pidns filters key holders (#3337)

- deploy/helm/tracee/templates/tracee-policies.yaml
- deploy/kubernetes/tracee/tracee.yaml
- docs/docs/events/overview.md
- docs/docs/policies/index.md
- docs/docs/policies/rules.md
- docs/tutorials/k8s-policies.md
- examples/policies/container_dns_events.yaml
- examples/policies/context_comm.yaml
- examples/policies/new_containers.yaml
- examples/policies/new_pids.yaml
- examples/policies/not_containers.yaml
- examples/policies/openat_args_pahtname.yaml
- examples/policies/pid_equal.yaml
- examples/policies/scope_comm.yaml
- examples/policies/signature_events.yaml
- examples/policies/uid_higher_than_or_equal_to_zero.yaml
- go.mod
- pkg/cmd/flags/policy_test.go
- pkg/policy/v1beta1/policy_file.go
- pkg/policy/v1beta1/policy_file_test.go
- tests/integration/event_filters_test.go
Fix https://github.com/aquasecurity/tracee/issues/3333
Policy names must be k8s compatible, which means defined as [RFC 1123](https://tools.ietf.org/html/rfc1123). 
So the name must:
contain no more than 63 characters
contain only lowercase alphanumeric characters, '-' or '.'
start with an alphanumeric character
end with an alphanumeric character
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
> fix: validate policy names are rfc 1123

- deploy/helm/tracee/templates/tracee-policies.yaml
- deploy/kubernetes/tracee/tracee.yaml
- docs/docs/events/overview.md
- docs/docs/policies/index.md
- docs/docs/policies/rules.md
- docs/tutorials/k8s-policies.md
- examples/policies/container_dns_events.yaml
- examples/policies/context_comm.yaml
- examples/policies/new_containers.yaml
- examples/policies/new_pids.yaml
- examples/policies/not_containers.yaml
- examples/policies/openat_args_pahtname.yaml
- examples/policies/pid_equal.yaml
- examples/policies/scope_comm.yaml
- examples/policies/signature_events.yaml
- examples/policies/uid_higher_than_or_equal_to_zero.yaml
- go.mod
- pkg/cmd/flags/policy_test.go
- pkg/policy/v1beta1/policy_file.go
- pkg/policy/v1beta1/policy_file_test.go
- tests/integration/event_filters_test.go
d15609bc1 **fix: validate policy names are rfc 1123 (#3335)** _<sub>(2023/jul/27) Jose Donizetti \<jdbjunior@gmail.com\></sub>_
```
commit: 933301c (main), cherry-pick
```
> [v0.17.0] fix: validate policy names are rfc 1123 (#3335)

- cmd/tracee-ebpf/main.go
- cmd/tracee/cmd/analyze.go
- cmd/tracee/cmd/list.go
- cmd/tracee/cmd/root.go
- docs/docs/deep-dive/caching-events.md
- docs/docs/deep-dive/dropping-capabilities.md
- docs/docs/flags/cache.md
- docs/docs/flags/capabilities.md
- docs/docs/flags/capture.md
- docs/docs/flags/config.md
- docs/docs/flags/containers.md
- docs/docs/flags/events.md
- docs/docs/flags/log.md
- docs/docs/flags/output.md
- docs/docs/flags/rego.md
- docs/docs/flags/scope.md
- docs/docs/forensics/index.md
- docs/docs/outputs/output-formats.md
- docs/docs/outputs/output-options.md
- pkg/cmd/flags/capture.go
- pkg/cmd/flags/errors.go
- pkg/cmd/flags/help.go
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/output.go
- pkg/cmd/flags/rego.go
- pkg/cmd/flags/tracee_ebpf_output.go
Close #3299
5bac134c6 **fix(flags)!: del help cmd, add md files for flags** _<sub>(2023/jul/13) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
This removes the default cobra help command, leaving only the root
--help flag.
The remaining - in code - help flags strings are only used by the old
tracee-ebpf command.
With this, new binary flags help are inaccessible. To circumvent this,
the help flags are now documented in markdown files (not included to
online docs) to be used as source for man pages generation (next step).
BREAKING CHANGE: help command is gone, use --help flag instead.
```
`sudo ./dist/tracee --help`
```
Tracee uses eBPF technology to tap into your system and give you
access to hundreds of events that help you understand how your system behaves.
Usage:
tracee [flags] …
```
> remove help command, create flags markdown docs

- cmd/tracee-rules/main.go
- pkg/ebpf/signature_engine.go
- pkg/signatures/engine/engine.go
- pkg/signatures/engine/engine_test.go
```
Date:   Wed Jul 26 15:03:21 2023 +0000
chore (engine): split Init from NewEngine
Previously data sources could not be registered after the NewEngine call
call and be used in signatures, due to the Init calls being made in
NewEngine.
Fix by moving the loadSignature and initial data source registers to
a new Init method from NewEngine.
In addition, export a method in tracee to prepare the builtin data
sources provided out of the box.
```
Fix #3341
Needs backport into v0.16.0 and v0.17.0
> fix: data source registration after NewEngine

- cmd/tracee-rules/main.go
- pkg/ebpf/signature_engine.go
- pkg/signatures/engine/engine.go
- pkg/signatures/engine/engine_test.go
46266e12d **chore (engine): split Init from NewEngine (#3342)** _<sub>(2023/jul/27) Nadav Strahilevitz \<nadav.strahilevitz@aquasec.com\></sub>_
```
Previously data sources could not be registered after the NewEngine call
call and be used in signatures, due to the Init calls being made in
NewEngine.
Fix by moving the loadSignature and initial data source registers to
a new Init method from NewEngine.
In addition, export a method in tracee to prepare the builtin data
sources provided out of the box.
commit: efa0ec4 (main), cherry-pick
```
> [v0.17.0] chore (engine): split Init from NewEngine (#3342)

- builder/Dockerfile.alpine-tracee-container
Context: https://github.com/aquasecurity/tracee/actions/runs/5676715511/job/15383893531#step:7:1974
89dcf23ca **fix(build): btfhub's bpftool in alpine container** _<sub>(2023/jul/28) Geyslan Gregório \<geyslan@gmail.com\></sub>_
```
Install bpftool in alpine container from btfhub's submodule.
```
> fix(build): btfhub's bpftool in alpine container

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
cf7137649 **chore(build): add LOGFROM flag to check-pr rule**
commit cf7137649
```
With this flag, the git log output is filtered to only include commits
from the specified commit to the current HEAD.
make check-pr                # from main (default)
make check-pr LOGFROM=v0.1.0 # from tag/branch
make check-pr LOGFROM=HEAD~1 # from commit
make check-pr LOGFROM=f3a4b2 # from commit
This also changes check-pr output format and adds information for using
its output in the PULL_REQUEST_TEMPLATE.md file.
```
See commit above.
> chore(build): add LOGFROM flag to check-pr rule

- Makefile
4ef7356d6 **chore(build): change check-pr output format**
> chore(build): change check-pr output format

- pkg/cmd/flags/filter.go
709399bc9 **fix(filter): remove unneeded workaround**
commit 709399bc9
```
Since 4.19 support was dropped (non CORE) there is no need for this
workaround to exist anymore.
```
> fix(filter): remove unneeded workaround

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/c/vmlinux_flavors.h
The struct that kept the address of which the module resides has changed - we now use the correct field based on kernel version in runtime
close #3339
> events: adjust hidden kernel module event to v6.4

- cmd/tracee/cmd/root.go
Fix https://github.com/aquasecurity/tracee/issues/3369
By disabling argument parsing https://github.com/aquasecurity/tracee/blob/main/cmd/tracee/cmd/root.go#L28, we stopped loading the config file properly. 
```
tracee --config cfg.yaml
```
This needs to be backported to the 0.17.0 and we need a bugfix release.
> fix(config): loading config file

- pkg/cmd/flags/logger.go
- pkg/events/derive/symbols_loaded_test.go
- pkg/logger/logger.go
- pkg/signatures/engine/engine_test.go
This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208). It adds AtomicLevel to our logger, so we can change it safely in runtime. The GRPC server will have a DiagnosticService for debugging and diagnostic tracee. One of the endpoints will be a `ChangeLogLevel`.
> feat: add loggers atomic level

- cmd/tracee/cmd/root.go
Close: #3372
0611b6dae **chore(cmd): refactor config flag**
add405434 **fix(cmd): --help flag parsing**
**fix(cmd): --help flag parsing**
```
The --help flag was not being parsed correctly, i.e.
`sudo ./dist/tracee --help whatever` was not showing the help message.
This commit fixes the issue by using the `--help` flag as a boolean flag
and leaving the hard work to cobra.
```
`sudo ./dist/tracee --help`
`sudo ./dist/tracee --help --scope comm=who`
`sudo ./dist/tracee --scope comm=who --help`
Expected failing:
`sudo ./dist/tracee --scope --help`
`sudo ./dist/tracee --help whatever`
> `--help` flag parsing

- go.mod
- go.sum
- pkg/cmd/flags/logger.go
- pkg/cmd/tracee.go
- pkg/logger/logger.go
- pkg/server/grpc/diagnostic.go
- pkg/server/grpc/server.go
- pkg/server/grpc/server_test.go
This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208). This PR implements the diagnostic rpc service. I've tested with `-race` no data races were found here. 
The below clients can be used to test the GRPC API:
```go
import (
pb "github.com/aquasecurity/tracee/types/api/v1beta1"
)
```
```go
func main() {
var opts []grpc.DialOption
opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
conn, err := grpc.Dial(":4466", opts...)
if err != nil {
log.Fatalf("fail to dial: %v", err)
}
client := pb.NewDiagnosticServiceClient(conn)
changelog := &pb.ChangeLogLevelRequest{
Level: pb.LogLevel_Info,
}
_, err = client.ChangeLogLevel(context.Background(), changelog)
if err != nil {
log.Fatal(err)
}
fmt.Println("Log level changed …
```
> Add grpc diagnostic

- pkg/containers/containers.go
Fix https://github.com/aquasecurity/tracee/issues/3396
When running tracee on gke we see a lot of errors due to deletion of groups that don't exist (probably because they are not related to containers), on this PR we ignore this error, and add a debug logging for whenever it happens.
> fix: ignore error for cgroups that doesn't exist

- pkg/ebpf/events_pipeline.go
Minor refactor, `getStackAddresses` doesn't return na error.
> refactor: getStackAddresses doesn't return an err

- cmd/tracee-bench/main.go
Latest revive started giving a warning for redundancy. Mitigate the warning so all next builds start passing linting checks.
> chore(revive): mitigate redundant warning

- types/trace/trace.go
Type change for https://github.com/aquasecurity/tracee/pull/3364
> feature(types): add task identifier

- pkg/cmd/flags/policy.go
- pkg/cmd/flags/policy_test.go
Close: #3428
8a96bebbc8d1d59ca9b79ea1a738f83c0e3ec6fd **fix(flags): use scope flag parser for policy**
```
Make PrepareFilterMapsFromPolicies() use parseScopeFlag() instead of
parsing the scope flag manually.
```
`sudo ./dist/tracee -p examples/policies`
> fix(flags): use scope flag parser for policy

- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/tracee.bpf.c
this PR fixes capture write of `writev` syscalls.
issue: #3424
```
Date:   Tue Aug 22 19:07:25 2023 +0300
fix: capture of writev
handle io_vec correctly to fix capture of writev syscalls
```
`sudo ./dist/tracee -c write`
then write into a file using `writev`
> fix: capture of writev

- docs/docs/forensics/index.md
- pkg/cmd/flags/capture.go
- pkg/config/config.go
- pkg/ebpf/c/capture_filtering.h
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/tracee.h
- pkg/events/core.go
Add a filter for file IO capture filtering ELF files. ELF files are the most important files to capture in security research, so filtering according to ELF files is very effective to reduce noise.
fix #3359
> feat: filter file capture by ELF type

- pkg/ebpf/tracee.go
- pkg/events/definition_dependencies.go
Fix #3382
commit cbac4047cf596712a353542a0a9b6586c8cf3844
```
Date:   Sun Aug 13 12:38:37 2023 +0000
fix: non-nil empty ksymbols dependency
The events group refactor (commit aa3fd66) changed the semantics of
ksymbols dependency so that kernel symbols would only be loaded if a
specific list was set.
This broke several events which require kernel symbols in general, but
not any specifically (being set through argument "parameter" lists).
Fix this by bringing back previous semantics.
```
Fix #3383 
commit b57331706b726343af011af9a85c2711dd25c633
```
Date:   Sun Aug 13 12:41:05 2023 +0000
fix: print_mem_dump fail on missing symbol
print_mem_dump trigger currently fails when failing to query a symbol.
However print_mem_dump can potentially include many symbols in its
parameters, and shouldn't …
```
> fix: print_mem_dump fails on missing symbol

- pkg/ebpf/tracee.go
- pkg/events/definition_dependencies.go
This reverts commit 1a47a4e4e3b565d6e06169696c533c63d94c3c1f. This is done because the commit cause the "symbols_loaded" event to fail and also cause many error messages that weren't seen before.
> Revert "fix: print_mem_dump fails on missing symbol (#3384)"

- pkg/events/core.go
commit fad5fc043 (HEAD -> ksymboldepsregression, rafaeldtinoco/ksymboldepsregression)
Date:   Tue Sep 5 16:33:13 2023
fix(event): enable ksymbols engine for PrintMemDump
Commit 1a47a4e4e attempted to fix this issue by reverting some changes
made during the event definitions (and dependencies) refactor. That
change caused some regressions because of another fix made together,
but, since it was reverted, this commit fixes the same issue with a much
simpler approach (at least until the event definitions refactor work is
finished).
Fixes: #3382
> fix(definitions): ksymbols dependencies handled wrongly

- pkg/ebpf/bpf_log.go
- pkg/ebpf/capture.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/net_capture.go
- pkg/ebpf/tracee.go
Close: aquasecurity/libbpfgo#122
eebd7e714 **fix(ebpf): close perfbuf instead of just stop**
667a86315 **fix(ebpf): closed channel read**
eebd7e714 **fix(ebpf): close perfbuf instead of just stop**
```
This was an old TODO comment removed by https://github.com/aquasecurity/tracee/pull/296/files#diff-82aa2eb77c3ce782b8ebfb70eaba8a1a5a8a2dce9f3349352a3a3c0f909478f1L604
```
667a86315 **fix(ebpf): closed channel read**
```
This libbpfgo issue aquasecurity/libbpfgo#122
is actually a Tracee problem. It was caused by read attempts on a
closed channel (lostEvChannel), when libbpgo had already closed it.
```
Run tracee and kill it via `^C`.
> Fix closed chan read 2

- pkg/cmd/initialize/sigs.go
- pkg/cmd/initialize/sigs_test.go
- pkg/ebpf/finding_test.go
- pkg/events/core.go
- pkg/events/core_test.go
- pkg/events/definition.go
- pkg/events/definition_group_test.go
- pkg/events/definition_test.go
- pkg/events/derive/derive_test.go
- pkg/events/version.go
- pkg/policy/v1beta1/policy_file_test.go
This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208), and also the https://github.com/aquasecurity/tracee/issues/2870, because the new event structure won't have metadata, and instead static data from the event will come from the definition, so users will be able to query the grpc endpoint to get a definition, but there is two important fields missing from the definition:
- the event description
- the event version, which will be bumped if we change the Params, to inform users that the event schema changed
> feat: add version and description to definition

- pkg/ebpf/events_pipeline.go
- pkg/ebpf/policy_manager.go
- pkg/ebpf/policy_manager_test.go
- pkg/ebpf/tracee.go
This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208).  It adds support to enable/disable rules per policy globally. The GRPC endpoints will be implemented in a following PR. 
This is a temporary solution, the enable/disable rules in the future should by extensions code @rafaeldtinoco is currently creating/refactoring, and probably load and unload configuration from kernel layer. But to support a feature now, we are creating some code that handles it by dropping the events, instead of unloading it. Also I created a specific structure to handle it, to avoid mutex code scattered around the tracee struct.
> Add enable/disable rule

- .revive.toml
04b6639d1 **chore(revive): disable unchecked-type-assertion**
```
This probably should be re-enabled at some point.
```
After revive [update](https://github.com/mgechev/revive/commit/95acb880a1b545bdf74dc393a1b80a6df1176cda) `check-lint` outputs:
```
make check-lint                            
Linting golang code...
pkg/signatures/benchmark/signature/golang/code_injection.go:94:20: type cast result is unchecked in request.Value.(string) - type assertion will panic if not matched
pkg/signatures/celsig/wrapper/wrapper.go:113:8: type cast result is unchecked in source.Value.(string) - type assertion will panic if not matched
pkg/signatures/celsig/wrapper/wrapper.go:118:8: type cast result is unchecked in source.Value.([]string) - type assertion will panic if not matched …
```
> chore(revive): disable unchecked-type-assertion

- docs/docs/filters/filtering.md
- docs/docs/flags/scope.md
- docs/docs/policies/scopes.md
- examples/policies/dig.yaml
- examples/policies/not_containers.yaml
- pkg/cmd/flags/filter.go
- pkg/cmd/flags/policy.go
- pkg/cmd/flags/policy_test.go
- pkg/cmd/flags/scope.go
- pkg/cmd/flags/scope_test.go
- pkg/filters/bool.go
- pkg/filters/filters_test.go
- pkg/policy/v1beta1/policy_file.go
- tests/integration/event_filters_test.go
Close: #3446 
815a02db8 **chore(flags): add scope exec/executable option**
```
The exec/executable scope option is the same of bin/binary, but it is
now the default option among the two. The bin/binary option is now
an alias for exec/executable.
```
951506142 **chore(flags)!: rename !container to not-container**
```
BREAKING CHANGE: !container is now not-container
Rename the scope option !container to not-container, eliminating the
need of quoting the scope value.
```
`sudo ./dist/tracee -p examples/policies`
> Rename `!container` and `binary` scope filters

- go.mod
- go.sum
- pkg/server/grpc/tracee.go
This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208), it add the implementation to the `GetEventDefinition` rpc call.  
```
func main() {
var opts []grpc.DialOption
opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
conn, err := grpc.Dial(":4466", opts...)
if err != nil {
log.Fatalf("fail to dial: %v", err)
}
client := pb.NewTraceeServiceClient(conn)
definitions, err := client.GetEventDefinition(
context.Background(),
&pb.GetEventDefinitionRequest{Name: "openat"},
)
if err != nil {
log.Fatal(err)
}
for _, definition := range definitions.Definitions {
v := fmt.Sprintf("%d.%d.%d", definition.Version.Major, definition.Version.Minor, definition.Version.Patch)
fmt.Println("Id:", definition.Id)
fmt.Println("Name:", …
```
> Add definition grpc endpoint

- go.mod
- go.sum
9194c9fbe **chore(libbpfgo): bump to v0.5.0-libbpf-1.2**
```
This version brings in map of maps support.
```
> chore(libbpfgo): bump to v0.5.0-libbpf-1.2

- pkg/ebpf/ksymbols.go
- pkg/ebpf/tracee.go
Close: #3460 
7b76c016f **chore(ebpf): not fail if some ksymbol is not found**
```
Continue the execution even if some ksymbol is not found or valid.
```
> chore(ebpf): not fail if some ksymbol is not found

- types/api/v1beta1/definition.proto
Remove `params` from event defintion protobuf.
> fix: remove params from event definition proto

- pkg/ebpf/events_pipeline.go
- pkg/ebpf/policy_manager.go
- pkg/ebpf/policy_manager_test.go
- pkg/ebpf/tracee.go
The event manager manages the state (disabled/enabled) of events globably on tracee.
This PR is part of the work to support a [v1 for GRPC](https://github.com/aquasecurity/tracee/issues/3208), it adds an enable/disable method to the policyManager, with a state struct to hold the information about the event that is enable/disbale globally as well as per policy, this struct in the future can hold the event emit/submit mask and also a policyMask to enable/disable policies globally.
> feat: add event enable/disable

- types/api/v1beta1/definition.pb.go
forgot to regenerate definition.pb.go after the last merge removing params
> fix: regenerate definition.pb.go

- go.mod
- go.sum
- pkg/server/grpc/tracee.go
Update types and fix GetEventDefinition endpoint, because EventDefinition doesn't have params anymore.
> fix: GetEventDefinition doesn't have params

- deploy/helm/tracee/templates/tracee-policies.yaml
- deploy/kubernetes/tracee/tracee.yaml
- docs/docs/events/overview.md
- docs/docs/policies/index.md
- docs/docs/policies/rules.md
- docs/tutorials/k8s-policies.md
- examples/policies/container_dns_events.yaml
- examples/policies/context_comm.yaml
- examples/policies/dig.yaml
- examples/policies/new_containers.yaml
- examples/policies/new_pids.yaml
- examples/policies/not_containers.yaml
- examples/policies/openat_args_pahtname.yaml
- examples/policies/pid_equal.yaml
- examples/policies/scope_comm.yaml
- examples/policies/signature_events.yaml
- examples/policies/uid_higher_than_or_equal_to_zero.yaml
- pkg/policy/v1beta1/policy_file.go
- pkg/policy/v1beta1/policy_file_test.go
Fix https://github.com/aquasecurity/tracee/issues/3462
This PR renames policy apiVersion and kind to be:
```
apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
name: dig
annotations:
description: traces dns events from the dig executable
spec:
scope:
- executable=/usr/bin/dig
rules:
- event: net_packet_dns_request
- event: net_packet_dns_response
```
> fix: rename policy apiVersion and kind

- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_procfs.go
This is needed in order for https://github.com/aquasecurity/tracee/pull/3488 to work correctly.
> fix(proctree): include thread group leader in threads LRU map

- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
Close: #3383 
826d30f022b872fb5e02b6be1a2aff3a43fea4c2 **fix(ebpf): fix symbol name on error**
```
When not finding a symbol, the error message was showing the symbol name
prefixed with the last attempted symbol name. Now it shows all attempted
symbol names.
This also fixes a bug where it just returned after the first option
lookup failure, instead of trying all.
```
`sudo ./dist/tracee -e print_mem_dump.args.symbol_name=compat_filldir64,do_sys_open,bleh,proc_sys_open,compat_filldir`
```
{"level":"warn","ts":1695346496.5952117,"msg":"Memory dump","error":"ebpf.(*Tracee).triggerMemDump: policy 0: invalid symbols provided to print_mem_dump event: …
```
> fix(ebpf): fix symbol name on error

- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
Reverts aquasecurity/tracee#3497
After that, symbols_loader is failing in e2e. There is more info in the tests discussion. @yanivagman FYI.
> Revert "fix(ebpf): fix symbol name on error"

- go.mod
- go.sum
- pkg/ebpf/finding.go
- pkg/ebpf/finding_test.go
- pkg/server/grpc/tracee.go
- pkg/server/grpc/tracee_test.go
This PR adds the stream endpoint to the grpc server, which closes the implementation of the v1beta1 of the grpc API. The user needs pass which policies to create a stream, and optionally he can filter with fields to get as a response with the field mask. 
test streams:
```
func main() {
kk := keepalive.ClientParameters{
Time:                10 * time.Second, // send pings every 10 seconds if there is no activity
Timeout:             time.Second,      // wait 1 second for ping ack before considering the connection dead
PermitWithoutStream: true,             // send pings even without active streams
}
var opts []grpc.DialOption
opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
opts = append(opts, grpc.WithKeepaliveParams(kk))
conn, err := grpc.Dial(":4466", …
```
> Add streams endpoint

- .github/workflows/test-os-packaging-daily.yaml
- packaging/Dockerfile.fedora-packaging
- packaging/Dockerfile.ubuntu-packaging
- packaging/fedora/tracee.spec
- packaging/ubuntu/control
- ubuntu kinetic is EOL and build is failing.
- make ubuntu pkg builds to use clang14 from upstream.
- make fedora pkg builds to use clang14 from upstream.
> fix(packaging): adjust ubuntu and fedora packaging

- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
Close: https://github.com/aquasecurity/tracee/issues/3383
38060bbd2 **fix(ebpf): triggerMemDump check all filters**
```
Fixes a bug where it just returned after the first failure.
Now triggerMemDump checks all filters from all policies, returning a
slice of errors.
This also fixes the error message when a symbol is not found. The error
message was showing the symbol name prefixed with the last attempted
(prefixed) symbol name. Now it shows all attempted symbol names.
```
`sudo ./dist/tracee -e print_mem_dump.args.symbol_name=compat_filldir64,do_sys_open,bleh,proc_sys_open,compat_filldir`
```
{"level":"warn","ts":1695346496.5952117,"msg":"Memory …
```
> fix(ebpf): triggerMemDump check all filters

- mkdocs.yml
> fix: link cosign tutorial to mkdocs.yml

- pkg/cmd/flags/proctree.go
- pkg/ebpf/c/common/consts.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/controlplane/processes.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/processor.go
- pkg/ebpf/processor_funcs.go
- pkg/ebpf/processor_proctree.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/policy/policies.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_output.go
- tests/integration/tracee.go
commit 0ac586115 (HEAD -> proctreestuff, rafaeldtinoco/proctreestuff)
Date:   Thu Sep 21 23:37:10 2023
fix(proctree): allow regular events to create proctree nodes
It is not impossible, although it is unlikely, that a fork/exec/exit
event arrives first in the regular events pipeline. There is also a
possibility that the signal event is lost.
This change allows tracee to choose which source of events the process
tree should be fed with. Using the control plane (and the fork, exec and
exit signal events) is preferrable, but user can also opt to use regular
sched events OR even both.
There is also another need for this: the analyze mode. If the signatures
rely in data source entries to work, when running tracee analyze mode
there will be …
> fix(proctree): allow regular events to create proctree nodes

- docs/getting-started/docker-quickstart.md
Regarding the issue detailed in #3454
> docs: running tracee docker container on amd64 and arm64

- pkg/events/derive/net_packet_http.go
The net_packet_http and net_packet_http_response events are failing for empty replies (such as HTTP/1.x 200 OK replies, for example). Ignore if there is some EOF trying to parse response... it usually means there is a single code response with no body.
> fix(networking): fix net_packet_http errors on empty OK

- pkg/bufferdecoder/decoder.go
3d617243a **fix(decoder): read uint16 from buffer**
```
ProcessorId is uint16. This fixes the reading to 2 bytes instead of 4.
```
> fix(decoder): read uint16 from buffer

- go.mod
- go.sum
commit 544b2cdfe introduced a types replacement, removing it.
> fix(go.mod): remove types replacement leftover

- pkg/events/parse_args.go
When choosing output option parse-arguments, cap_capable event didn't show the capability string.
This PR fixes it.
> fix: cap_capable should parse arguments

- pkg/ebpf/tracee.go
- pkg/proctree/datasource.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_output.go
- pkg/proctree/proctree_procfs.go
- pkg/proctree/taskinfo.go
commit 559a649f8 (HEAD -> proctree-datasource-fixes, rafaeldtinoco/proctree-datasource-fixes)
Date:   Fri Oct 6 10:31:41 2023
fix(proctree): fix issues when updating from procfs
- raise channel buffer due to initialization needs (all pids)
- check if fields from stat and status are valid
- take care of PIDs 0 and 1 in the right manner
- only update nodes if they are incomplete in basic fields
commit 72d31d570
Date:   Fri Oct 6 10:28:43 2023
fix(proctree): remove unused capabilities change
The routing that is in charge of reading procfs is not the same as the
one being called for initialization. Capabilities were being raised for
no reason in the initialization.
The loop in charge …
> proctree + datasource fixes and adjustments

- pkg/events/derive/net_packet_dns.go
- pkg/events/derive/net_packet_helpers.go
Fixes: https://github.com/aquasecurity/tracee/issues/3547
> fix(events): fix dns events slice out of bounds issues

- go.mod
- go.sum
- https://github.com/aquasecurity/tracee/security/dependabot/50
> chore(golang): update types and api to latest for security

- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/task.h
Both, process tree AND the event context should have "parent" pointing to a real task and not a potential thread. Event context still had it pointing to the real parent and not what is being called "up parent".
> fix(event): make sure parent points to a real process

- embedded.go
- pkg/cgroup/errors.go
- pkg/counter/counter_bench_test.go
- pkg/filters/errors.go
- pkg/logger/logcounter.go
- pkg/mount/errors.go
- pkg/policy/errors.go
- pkg/proctree/thread.go
- pkg/utils/numbers.go
- tests/testutils/cpu.go
- types/datasource/proctree.go
cf69607fb **chore: goimports-reviser new version**
```
It demands new formatting.
Context: https://github.com/aquasecurity/tracee/actions/runs/6533411157/job/17738793205?pr=3562#step:6:28
```
> chore: goimports-reviser new formatting

- pkg/ebpf/c/common/context.h
Fix for a situation observed by Alon at:
https://github.com/aquasecurity/tracee/pull/3571#discussion_r1361217873
> fix(events): make ns parent pid exist only in same ns

- tests/integration/event_filters_test.go
- tests/integration/syscaller/cmd/syscall_test.go
- tests/integration/tracee.go
Close: #3440 
538e6be62 **chore(tests): re-enable 'trace events from pid 1'**
```
This re-enables 'pid 1 trace events' since it was unable to be
reproduced. If it happens again, hopefully with the use of a shuffle
seed it can be reproduced.
During analysis, another issue was detected with Test_changeOwnComm. The
raw fork is not safe at all, even with all the precautions taken, which
is why it was removed and the test takes place in the same thread now.
Additional measures were taken to prevent the goroutine from escaping
the OS thread: calling runtime.GOMAXPROCS(1) and changeOwnComm()
from init().
This also removes leftover code (eventOutput, waitForTraceeOutput).
```
> chore(tests): re-enable 'trace events from pid 1'

- .github/workflows/pr.yaml
- pkg/ebpf/c/tracee.bpf.c
commit 22374afc8 (HEAD -> add-mantic-to-workflow, rafaeldtinoco/add-mantic-t>
Date:   Thu Oct 19 14:44:09 2023
fix(events): fix hooked_proc_fops evt in v6.5+
Fixes: #3573
Reported-by: Jeff Wooldridge (provided patch suggestion)
Signed-off-by: Rafael David Tinoco <rafaeldtinoco@gmail.com>
commit 2eb2bf1d5
Date:   Thu Oct 19 11:27:50 2023
chore(workflow): add kernel v6.5 to kernel tests
> chore(workflow): add kernel v6.5 to kernel tests

- pkg/containers/containers.go
- pkg/containers/runtime/runtime.go
The regex should match the following patterns:
ca94fb1d-8d1e-42f9-529c-a8af
e660266c-de34-45e9-6102-d881
Fixes: #3584
> fix(containers): parse cont id of cloud-foundry garden apps

- pkg/events/core.go
After merging the syscall hooking changes, the E2E signature needs fixing (which Im providing) and then I realized the argument names contained "." (which isn't something used in any other event so far). I changed the names and I'm providing fixes to the e2e tests (with signature and signature test changes as well).
> chore(events): rename syscall hooking arguments

- builder/entrypoint.sh
- cmd/tracee-ebpf/main.go
- cmd/tracee/cmd/root.go
- docs/docs/data-sources/containers.md
- docs/docs/deep-dive/caching-events.md
- docs/docs/integrating/container-engines.md
- pkg/cmd/cobra/cobra.go
- pkg/cmd/tracee.go
- pkg/cmd/urfave/urfave.go
- pkg/config/config.go
- pkg/containers/containers.go
- pkg/ebpf/controlplane/cgroups.go
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/events_enrich.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/definition_group.go
- pkg/events/usermode.go
commit b39d88457 (HEAD -> no-containers-default, rafaeldtinoco/no-containers-default)
Date:   Wed Oct 25 12:09:09 2023
fix(definitions): debug shows wrong logs for sig events
commit b067fd385
Date:   Wed Oct 25 11:51:14 2023
chore(containers): make feature flag a safe guard
- make default behavior (--containers) to enrich containers
- keep a safeguard measure (change cmdline flag to --no-containers)
> chore(containers): make feature flag a safe guard

- deploy/helm/tracee/templates/daemonset.yaml
- deploy/kubernetes/tracee/tracee.yaml
- pkg/containers/containers.go
- pkg/k8s/k8s.go
fix https://github.com/aquasecurity/tracee/issues/3593
The PR https://github.com/aquasecurity/tracee/pull/3325 introduced an optimization to avoid querying CRI on short live cgroups, this works well for all bigger gke platforms I tested (aws, azure, gke, digital ocean), but it doesn't work for minikube/kind, because the cgroup path is not accessible to a container https://github.com/aquasecurity/tracee/blob/main/pkg/containers/containers.go#L365-L374
As this is a special case for development tools only, I did a hack to not validate this whenever it is running on minikube or kind, so enrichment works. 
The PR uses the downward API to know the name of the node, if the name of the node is either minikube or kind it ignores the cgroup dead valiation.
> fix: enrichment for kind and minikube

- pkg/cmd/printer/printer.go
Fix https://github.com/aquasecurity/tracee/issues/3448
This PR adds support to `gotemplate` and `contentType` to the webhook printer.
```
sudo ./dist/tracee -p examples/policies/dig.yaml -o webhook:"http://localhost:8081?gotemplate=/path/to/template/test.tmpl&contentType=application/json"
```
example tmpl:
```
{
"test": {{ .EventName }}
}
```
> feature(webhook): add template and content type

- deploy/helm/tracee/templates/tracee-policies.yaml
- deploy/helm/tracee/values.yaml
Fix https://github.com/aquasecurity/tracee/issues/3516
This PR adds a new option to helm to allow the customization of the default policy. The work on this PR is done in the commit https://github.com/aquasecurity/tracee/commit/8f97f471553b3c6a195540c1a96d89bcc3ee95ea the previous commit is from the PR https://github.com/aquasecurity/tracee/pull/3619, which is a depedency.
```
helm install tracee ./deploy/helm/tracee --set-file defaultPolicy=/path/to/policy
```
> Allow default policy customization

- pkg/ebpf/events_pipeline.go
Removing this debug, it is too noisy, really hard to test anything.
> fix: remove noisy debug log

- pkg/cmd/flags/policy.go
- pkg/ebpf/tracee.go
Close: #3397
Context: #3562
257f36ac47cb78550ddeed5379403b043aef6a43 **fix(ebpf): change error to debug level**
58504464e **fix(ebpf): cancel dependencies of the canceled one**
4db6a48ab **chore(flags): remove leftover**
257f36ac47cb78550ddeed5379403b043aef6a43 **fix(ebpf): change error to debug level**
```
Some GKE kernels lack the CONFIG_KALLSYMS_ALL enabled, so this level
change is to silence the error related to missing kernel symbols. This
is a workaround until the 'sys_call_table' address can be retrieved
from the kernel in a way other than using '/proc/kallsyms' (see #3397).
At that point, the level should be changed back to 'error' again.
```
58504464e **fix(ebpf): cancel dependencies of the canceled one**
```
Context: #3495 …
```
> Silence missing event

- cmd/tracee-ebpf/main.go
- cmd/tracee/cmd/man.go
- cmd/tracee/cmd/root.go
- deploy/helm/tracee/templates/tracee-config.yaml
- deploy/helm/tracee/values.yaml
- docs/docs/config/kubernetes.md
- docs/docs/config/overview.md
- docs/docs/deep-dive/caching-events.md
- docs/docs/flags/containers.1.md
- docs/man/containers.1
- examples/config/global_config.json
- examples/config/global_config.yaml
- examples/config/global_config_cli.yaml
- mkdocs.yml
- pkg/cmd/cobra/cobra.go
- pkg/cmd/cobra/config.go
- pkg/cmd/cobra/config_test.go
- pkg/cmd/flags/containers.go
- pkg/cmd/flags/help.go
- pkg/cmd/urfave/urfave.go
Close: #3182 
d3f9ba9fb **chore(config): add gotemplate and content-type**
86c120975 **chore!: change crs flag/key to cri**
d1532749d **feat(docs): update docs for structured config file**
9092b9941 **feat(cobra): add parser for structured config file**
d3f9ba9fb **chore(config): add gotemplate and content-type**
```
Since #3622, webhooks can be configured with a gotemplate and a
content-type. This commit adds these two fields to the config file.
```
86c120975 **chore!: change crs flag/key to cri**
```
BREAKING CHANGE: change crs flag to cri
```
d1532749d **feat(docs): update docs for structured config file**
```
This also changes the default config file to be a structured YAML file
and adds a new example config file 'global_config_cli.yaml'  that uses
the CLI format.
```
9092b9941 …
> Handle structured config file

- Readme.md
- docs/docs/deep-dive/mac.md
- docs/docs/install/docker.md
- docs/index.md
#3605
yes I asked you all to review, not by mistake :) just to be sure my understanding is correct.
I'm not 100% sure all these extra docs should be under deep-dive but we can go with the flow for now and perhaps rearrange as part of the docs reorg.
> docs: docker guide and mac

- docs/docs/deep-dive/os-info.md
- pkg/cmd/initialize/kernelconfig.go
Close: #3637 
8a45f7a95590a51f2104ba530e438fa9f5a65ee0 **fix(initialize): do not fail kconfig options**
```
When initializing, we should not fail if the kernel config options
are not found. Let it fail if the option is required further down
the line.
```
> fix(initialize): do not fail kconfig options

- docs/docs/policies/kubernetes.md
Adds docs for kubernetes section under policies. I didn't link it to mkdocs, because I'm not sure where it should go, considering we are changing the structure.
> docs: add kubernetes operator

- .github/workflows/pr.yaml
- Makefile
- pkg/ebpf/processor.go
- procTreeForkProcessor, procTreeExecProcessor and procTreeExitProcessor should be registered when source "events" (or "both") is picked.
- any proctree enriching processor should be registered if at least one source is available (which means the process tree is enabled).
- there is one (for now at least) processor that is always registered (cleanup).
> fix(proctree): register processors correctly

- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/processor_funcs.go
- pkg/events/parse_args.go
Close: #3609 
9588651fb **fix(ebpf): use ts as fd_arg_path_map key**
```
A race condition has been reported when sequential open/close calls
cause the same FD (part of the map key) to be reused, therefore causing
value corruption.
The fd_arg_path_map continues as BPF_LRU_HASH just to avoid the need to
delete entries in userland even though the map is not used as a LRU
anymore - just as "oldest inserted", since there are no subsequent
accesses to update the LRU status of any entry.
P.S.: Another solution would be to use the inode number as part of the
key, but this value would not be available in the event at decode stage.
```
`sudo ./dist/tracee -s comm=openclose -e 'openat,close' -o option:parse-arguments-fds --capabilities bypass=true`
```
sudo ./dist/tracee -s comm=openclose -e …
```
> fix(ebpf): use ts as fd_arg_path_map key

- pkg/ebpf/signature_engine.go
- tests/e2e-inst-signatures/e2e-signature_derivation.go
- tests/e2e-inst-signatures/export.go
- tests/e2e-inst-signatures/scripts/signature_derivation.sh
Feed the signatures engine with its own output instead of feeding it to the output channel.
This allows signatures to use other signatures as their selector.
cfa2e5dae **refactor(engine): feed engine with signatures events**
fix #3680
> refactor(engine): feed engine with signatures events

- signatures/helpers/proctree.go
I donate this signatures helper code in the hope that it will help other people to use the process tree datasource.
07371088b **feat(signatures): add simple proctree datasource envelope**
> feat(signatures): add simple proctree datasource envelope

- pkg/logger/logcounter.go
- pkg/logger/logger.go
Close: #3665
7f0209914 **fix(logger): ensure full lock when flushing**
b73303103 **chore(logger): reuse caller info**
45974c877 **feat(logger): make filtered aggregation possible**
Insert a `logger.Debugw("raw")` in a hotpath and run:
`sudo ./dist/tracee -l debug -l filter:msg=raw -l aggregate -o none`
> Make filtered aggregation possible

- pkg/ebpf/probes/cgroup.go
- pkg/ebpf/probes/uprobe.go
- pkg/ebpf/tracee.go
One may debug self loaded function by using:
```
$ sudo ./dist/tracee --log debug --log filter:'msg=self loaded program' --output json --output option:parse-arguments --events do_init_module,ftrace_hook
```
For example:
```json
{"L":"DEBUG","T":"2023-11-27T02:18:44.440-0300","M":"self loaded program","event":"do_init_module","program":"trace_do_init_module","origin":"ebpf:pkg/ebpf/tracee.go:1569","calls":"(*Tracee).getSelfLoadedPrograms.func1() < (*Tracee).getSelfLoadedPrograms() < (*Tracee).invokeInitEvents() < (*Tracee).processEvents()"}
{"L":"DEBUG","T":"2023-11-27T02:18:44.440-0300","M":"self loaded program","event":"do_init_module","program":"trace_ret_do_init_module","origin":"ebpf:pkg/ebpf/tracee.go:1569","calls":"(*Tracee).getSelfLoadedPrograms.func1() < …
```
> probes: improve probes by having specific getters

- pkg/bufferdecoder/decoder.go
- pkg/bufferdecoder/decoder_test.go
- pkg/bufferdecoder/protocol.go
- pkg/bufferdecoder/protocol_test.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_pipeline_bench_test.go
00ffa33 **chore: rename Context to EventContext**
```
It aligns with the name of the type in the ebpf land, `event_context`
avoiding confusion with the `context.Context` type.
It also updates the respective comments.
```
> chore: rename Context to EventContext

- .github/workflows/pr.yaml
- builder/Dockerfile.man
ced448eb7 **chore(ci): improve 'how to fix man' steps**
71d1269e7 **chore(builder): pin pandoc to 3.1.2**
> Pin pandoc version to 3.1.2

- go.mod
- go.sum
df94a6c6b **chore: bump libbpfgo to v0.6.0-libbpf-1.3**
3367625dd **chore: bump 3rdparty/libbpf to v1.3.0**
Bring new features and fixes: https://github.com/libbpf/libbpf/releases/tag/v1.3.0
> libbpfgo bump to v0.6.0-libbpf-1.3

- pkg/containers/path_resolver.go
- pkg/ebpf/processor_funcs.go
Avoid creating errors upon errors in hash calculations from known reasons.
This includes memfd files, and race conditions in container FS access
Fix #3732
> bugfix(ebpf): avoid errors upon hash calc fail

- pkg/cmd/printer/printer.go
Fix https://github.com/aquasecurity/tracee/issues/3717
This PR adds support to Sprig's funcs for webhook templates.
create a `test.tmpl` with:
```
{
"hostname": "{{ .HostName }}",
"message": "Signature name: \"{{ .Metadata.Properties.signatureName }}\" description:\n{{ .Metadata.Description }}",
"severity": "{{ .Metadata.Properties.Severity }}",
"time": "{{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" }}",
"tags": {
"category": "{{ .Metadata.Properties.Category }}",
"external_id": "{{ .Metadata.Properties.external_id }}",
"signature_id": "{{ .Metadata.Properties.signatureId }}"
}
}
```
```
sudo ./dist/tracee -e anti_debugging -o webhook:http://localhost:8080?gotemplate=test.tmpl
```
Tracee wouldn't boot if the parse failed before.
> fix: webhook template should support sprig funcs

- pkg/containers/datasource.go
Add ctime of container's cgroup in data source schema and output.
TODO
> feature: add ctime to containers data source

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/events/derive/net_tcp.go
- pkg/events/parse_args.go
commit c3bb180a4 (HEAD -> network-connection)
Date:   Wed Dec 6 23:34:58 2023
feature(event): make net_tcp_connect report only TCP
commit 8d476c907
Date:   Tue Dec 5 23:43:18 2023
feature(event): add net_tcp_connect event with dns support
- create new set called "flows" to represent network flows.
commit cb3525fdf
Date:   Tue Dec 5 23:39:30 2023
chore(ebpf): improve readability for security_socket_connect
Opportunistic code change with no logic changes.
commit 8f40dc58e
Date:   Tue Dec 5 16:09:29 2023
fix(network): important fix to how header pointers are calculated
The …
> Network: add net_tcp_connect event with DNS support

- docs/docs/advanced/caching-events.md
- docs/docs/advanced/dropping-capabilities.md
- docs/docs/advanced/forensics.md
- pkg/cmd/flags/capture.go
- pkg/cmd/flags/errors.go
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/output.go
d63110ae4 **chore: refer to man pages**
> chore: refer to man pages

- cmd/tracee-rules/main.go
- cmd/tracee/cmd/analyze.go
- cmd/tracee/cmd/list.go
- pkg/cmd/cobra/cobra.go
- pkg/ebpf/signature_engine.go
- pkg/signatures/signature/signature.go
- pkg/signatures/signature/signature_test.go
- signatures/golang/export.go
- tests/e2e-inst-signatures/export.go
- tests/e2e-net-signatures/export.go
Fix https://github.com/aquasecurity/tracee/issues/3705
> feature: pluggable datasources

- pkg/cmd/flags/grpc.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/server/grpc/server.go
- types/detect/detect.go
Add types for PR #3725
Fix #3757 (opportunistically)
dfa6fe56a **feature(types): add WritableDatasource interface**
ef3bcd602 **feat(ebpf): synchronize ready callback to pipeline**
c831127db **fix(grpc): cleanup listen address**
For the bugfix: run tracee with `--grpc-listen-addr` set to something (tested with both unix and tcp) close tracee and run again. Note that tracee will not fail anymore.
> Writeable datasource types

- pkg/ebpf/c/tracee.bpf.c
9f90b1d70 **feat(ebpf): optimize sendmsg/recvmsg kprobes**
```
Move the socket validation section in these eBPF programs from the map
updating functions to the initial stage of the eBPF program.   
This is better because it is much quicker to validate the socket, than
initally checking `should_trace` and doing `init_program_data`.
It is also consistent with another networking kprobe of the packet logic
`trace_sock_alloc_file`.
Old version benchmark:
PROGRAM: security_socket_recvmsg (runtime: 569255060 ns, amount: 90974 times, average: 6257 ns)
PROGRAM: security_socket_sendmsg (runtime: 603516073 ns, amount: 109182 times, average: 5527 ns)
New version benchmark:
PROGRAM: security_socket_recvmsg (runtime: 613052965 ns, amount: 134066 times, average: 4572 ns)
PROGRAM: security_socket_sendmsg …
```
> feat(ebpf): optimize sendmsg/recvmsg kprobes

- pkg/events/derive/net_packet.go
The recent refactoring in the network derivation functions made HTTP request and HTTP response events to start failing due to wrong error being reported.
> fix(network): fix http request/response events

- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/c/vmlinux_flavors.h
18127c2b6 **fix(ebpf): adjust inode struct to kernel v6.6**
Fix #3768 
Tested on a coreos-fedora39 VM.
> fix(ebpf): adjust inode struct to kernel v6.6

- types/detect/detect.go
for #3725 - improve the write api making batch write implementations more convenient for users.
> feat(types): improve datasource write api

- cmd/tracee/cmd/analyze.go
- pkg/cmd/cobra/cobra.go
- pkg/cmd/initialize/sigs.go
- pkg/cmd/initialize/sigs_test.go
- pkg/ebpf/signature_engine.go
- pkg/signatures/engine/engine.go
1840ee1d540 **fix: clean up untraced signatures**
See the linked below issue.
Fix #3656
> fix: filter dispatching to signatures

- deploy/helm/tracee/values.yaml
- deploy/kubernetes/tracee/tracee.yaml
- docs/docs/flags/output.1.md
- docs/docs/install/config/index.md
- docs/docs/outputs/output-options.md
- docs/docs/policies/usage/cli.md
- docs/man/output.1
- examples/config/global_config.yaml
- go.mod
- go.sum
- pkg/bucketscache/bucketscache.go
- pkg/bucketscache/bucketscache_bench_test.go
- pkg/cmd/cobra/config.go
- pkg/cmd/cobra/config_test.go
- pkg/cmd/flags/output.go
- pkg/cmd/flags/output_test.go
- pkg/cmd/flags/tracee_ebpf_output_test.go
- pkg/config/config.go
- pkg/ebpf/processor_funcs.go
- pkg/ebpf/tracee.go
- pkg/ebpf/tracee_bench_test.go
- pkg/filehash/cache.go
- pkg/filehash/hash.go
- pkg/filehash/hash_bench_test.go
- pkg/filehash/hash_test.go
- pkg/filehash/key.go
c2ebbb290 **feat(exechash): optimize hash by reusing buffer**
9f9e5a44d **feat(ebpf): expand exec-hash output option**
eb17fc6fc **feat(ebpf): optimize computeFileHash**
db51e0b0e **fix(ebpf): fix getFileHash()**
c469486e5 **fix(bucketscache): GetBucket was not thread safe**
041bcff5e **chore(bucketscache): add benchmark**
Added tests to confirm parity with previous hash functionality.
Can be manually tested by using:
`tracee -o option:exec-hash={inode|dev-inode|digest-inode}`
where you may choose which hash option you want, with varying degrees of accuracy and performance.
Close #3734
Close #3745
> Improve performance of exec-hash

- pkg/cmd/cobra/cobra.go
- pkg/cmd/tracee.go
- pkg/cmd/urfave/urfave.go
- tests/e2e-inst-test.sh
- tests/e2e-kernel-test.sh
- tests/e2e-net-test.sh
5ca4667f4 **fix: create pid file under install-path**
Fix #3756
Run `tracee --install-path /tmp/blah/hehe`
Confirm with `ls /tmp/blah/hehe/tracee.pid` that tracee.pid will be under that path.
> fix: create pid file under install-path

- pkg/events/derive/net_packet.go
Deriving a net packet event for HTTP when given a malformed request/response would previously return an error. This error is useless for users as there always exists a chance for packet corruption when passing through the eBPF perf buffer. As such, log in WARN level instead.
Before `net_packet_helpers.go:632` add the following line:
Then compile and note the logs working.
`tracee --events net_packet_http_request`
`{"level":"warn","ts":1703593308.6970172,"msg":"attempted to derive net_packet_http_request event from malformed packet, event will be skipped","error":"invalid method \"G\\x00T\""}`
> chore(derive/http): change log level when packets are malformed

- pkg/ebpf/ksymbols.go
- pkg/utils/ksyms/safe_ksym_table.go
commit 2ad320e15435f1055ecff477e2fd28b42d2bf667
```
Date:   Sun Dec 31 13:42:23 2023 +0000
fix: use thread safe wrapper for ksyms table
Original implementations in libbpfgo helpers aren't thread safe, they
include golang maps which may are accessed without a thread safety
mechanism.
Provide a wrapper in the utils package which adds a mutex on top of
calling the original methods.
```
Fix #3785 
No regressions in relevant e2es, should work the same as before.
> fix: use thread safe wrapper for ksyms table

- pkg/cmd/printer/printer.go
Fix https://github.com/aquasecurity/tracee/issues/3790
```
14:36:15:580419  1000   strace           3450532 3450532 0                anti_debugging            triggeredBy: ptrace
```
instead of
```
14:38:21:840737  1000   strace           3452247 3452247 0                anti_debugging            triggeredBy: map[args:[{{request string} PTRACE_TRACEME} {{pid pid_t} 0} {{addr void*} 0x0} {{data void*} 0x0}] id:101 name:ptrace returnValue:0]
```
> fix: triggeredBy should print event on table output

- Readme.md
This PR fixes the contribution link in the Readme.md page. 
Before it was redirecting to the wrong location throwing 404 error.
Since it's documentation fix so there is no need for test.
So I have found another documentation for contributing but it's for whole aquasecurity. [Here](https://github.com/aquasecurity/.github/blob/master/CONTRIBUTING.md)
kind/documentation
> fix(doc): contribution document link

- pkg/ebpf/c/tracee.bpf.c
On some kernels, while iterating module_kset, we need to check if we've encountered the first module we iterated on, marking we iterated over all modules instead of continuing iterating indefinitely (max amount of iterations - causing a BPF_LOG_ID_UNSPEC error message)
On some kernels, while iterating module_kset, we need to check if we've encountered the first module we iterated on, marking we iterated over all modules instead of continuing iterating indefinitely.
/tracee -e=hidden_kernel_module
> fix(ebpf): fix hidden_kernel_module error in some kernels

- pkg/events/core.go
629883533:
```
fix(events): restore dependency in hooked_syscall
The event dependency for do_init_module in the hooked_syscall event was
removed in commit 43a3eac. As a result, installing a kernel module did
not immediately trigger a syscall table integrity check.
```
Fix #3783
See issue.
> fix(events): restore dependency in hooked_syscall

- pkg/ebpf/c/capture_filtering.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
Close #3731
0e1786b0a **chore: remove bpf map macros**
```
Define the bpf maps manually, instead of using the macros.
Context: #3731
It also does some renaming and changes filter comments.
```
> Remove BPF map macros

- pkg/ebpf/capture.go
- pkg/ebpf/net_capture.go
- pkg/ebpf/processor.go
- pkg/ebpf/tracee.go
1763cd440 **fix(capture): restore absolute time in pcap frames**
Use the normal process events step in the pipeline for the network capture buffer pipeline as well.
This fixes the issue that the conversion of the monotonic time to absolute time moved from the decode step to the process step, leaving the network capture events timestamp monotonic.
Fix #3799
> fix(capture): restore absolute time in pcap frames

- go.mod
- go.sum
- pkg/server/grpc/event_data.go
- pkg/server/grpc/event_data_test.go
- pkg/server/grpc/tracee.go
Fix https://github.com/aquasecurity/tracee/issues/3811
This PR update the api types, and fixes the parsing issues related to the changes. Also, it fixes a error on the creation of protobuf timestamps.
> Update api types

- go.mod
- go.sum
- signatures/helpers/go.mod
To allow users the option to use the up-to-date helpers for Go signatures, the helpers were exported to be an external Go module.
f9a60e590 **feat(signatures): expose signatures helpers as Go module**
> feat(signatures): expose signatures helpers as Go module

- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/config.go
- pkg/ebpf/tracee.go
- pkg/policy/ebpf.go
Close: #3805 
Part of #3239.
172f53367122d979cd2e41334ed69b475bd52c5e **chore: make policies config versioned**
```
This extracts the policy-related fields from config_entry_t into a new,
separate struct (policies_config_t), which continues to be stored in the
config_entry_t struct, as well as in the versioned policies_config_map.
This is required to enable access to the appropriate policies_config_t
based on the policy version.
```
> Make policies config versioned

- Makefile
f771010c65d3f3df0a3807bdc3fd8c52aaa7e929 chore: remove clang march flag
clang versions ~16 and above do not support the march flag.
- 16.0.6:
clang: warning: argument unused during compilation: '-march=bpf' [-Wunused-command-line-argument]
- 17.0.2:
clang: error: unsupported option '-march=' for target 'bpf'
> chore: remove clang march flag

- pkg/ebpf/processor_funcs.go
**a78e7c129e**: fix: skip timestamp normalizing in derived events
1. `tracee --events container_create`
2. `docker run --rm ubuntu`
3. Timestamp should make sense
Fix #3828
> fix: skip timestamp normalizing in derived events

- pkg/cgroup/cgroup.go
- pkg/changelog/changelog.go
- pkg/containers/containers.go
- pkg/ebpf/controlplane/cgroups.go
- pkg/ebpf/events_enrich.go
- pkg/ebpf/tracee.go
- pkg/events/derive/container_create.go
- pkg/events/usermode.go
- pkg/mount/mount.go
ae406df9c **optimize(enrich): skip non hid mkdir events**
9d97d239c **chore: improve logging in container related code**
96f0c9042 **fix: existing_container bad output**
04331580b **feat(mount): use mountinfo instead of /proc/mounts**
9d2206c4a **feat(cgroup): always switch to root cgroupns**
1. Deploy an EKS environment (v1.27+)
2. Deploy tracee with a rule for tracking container_create
3. Deploy a new pod
4. The two container_create events should be enriched (barring some race conditions)
I've found that we have some race conditions right now where enrichment will finish but a container event will be sent before. This is another bug which should be tackled separately (either by fixing the condition itself, or changing how a container_create event is triggered).
Resolve #3826
Fix #3689 …
> Various cgroup and mounting fixes and optimizations

- pkg/ebpf/processor_funcs.go
- pkg/events/parse_args.go
Change all places that change args values in processors to find arguments by their names instead of index.
This way the order of the arguments received from the kernel shall not cause bugs.
> fix(processors): change args values by name

- docs/docs/flags/output.1.md
- docs/man/output.1
- pkg/cmd/flags/output.go
- pkg/cmd/flags/output_test.go
- pkg/filehash/cache.go
Close: #3817 
354c152ff **fix: typo**
e481dbba9 **fix(flags): rollback exechash cli api**
e481dbba9 **fix(flags): rollback exechash cli api**
```
exechash can be set again as 'option:exec-hash' which will set it now as
'dev-inode' as default.
```
> Set exec-hash default option

- pkg/events/derive/net_packet.go
- tests/e2e-kernel-test.sh
- tests/e2e-net-signatures/e2e-dns.go
- tests/e2e-net-signatures/e2e-http.go
- tests/e2e-net-signatures/e2e-icmp.go
- tests/e2e-net-signatures/e2e-icmpv6.go
- tests/e2e-net-signatures/e2e-ipv4.go
- tests/e2e-net-signatures/e2e-ipv6.go
- tests/e2e-net-signatures/e2e-tcp.go
- tests/e2e-net-signatures/e2e-udp.go
- tests/e2e-net-test.sh
Fixing e2e tests to use the `tracee` binary instead of `tracee-rules` and `tracee-ebpf`.
> fix: e2e-net-tests should use unified binary

- .github/workflows/debug-shell.yaml
- .github/workflows/mkdocs-dev.yaml
- .github/workflows/mkdocs-latest.yaml
- .github/workflows/pr.yaml
- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/test-daily.yaml
e871343ee3a6d5d8b1e6a607c3155b9a558d66c0 chore(ci): remove deprecating set-output
set-output is deprecated and will be removed in the future.
More info: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
ef9514377bec843f89a544cf0005e309158885df chore(ci): bump checkout action to v4
Due to the transition from Node 16 to Node 20, the checkout action
needs to be updated to v4.
More info: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> GitHub actions chore

- docs/docs/flags/output.1.md
- docs/docs/install/config/index.md
- docs/docs/outputs/output-formats.md
- docs/man/output.1
- examples/config/global_config.yaml
- pkg/cmd/cobra/config.go
- pkg/cmd/cobra/config_test.go
- pkg/cmd/flags/output.go
- pkg/cmd/flags/output_test.go
- pkg/cmd/flags/tracee_ebpf_output.go
- pkg/cmd/flags/tracee_ebpf_output_test.go
- pkg/cmd/printer/printer.go
- pkg/cmd/printer/printer_test.go
- pkg/signatures/benchmark/helpers_test.go
Remove the gob printer. This is a legacy printer which was used by `tracee-rules` and `tracee-ebpf`, which are no longer supported and will be soon removed from the repo.
> chore: remove gob printer

- deploy/helm/tracee/templates/tracee-config.yaml
- deploy/helm/tracee/values.yaml
903fb1188 **chore: bump chart version to 0.19.1**
32a892a26 **feat: allow webhook configuration via helm values**
the webhook section of the tracee config map can not be configured anymore since the refactoring in version 0.19.0 of the Helm chart. This PR allows to configure the webhook. Choice has been made to map the webhook keys (instead of just dumping the values as is in the config map), similarly to what already exists for other portions of this configmap's values file content.
```
helm template tracee ./deploy/helm/tracee --show-only templates/tracee-config.yaml
```
output doesn't include the webhook configuration (no reg).
```
cat > ci.yaml <<EOF
config:
output:
webhook:
- name: "named-webhook"
protocol: http
host: localhost
port: 8080
timeout: 3s
goTemplate: …
```
> feat: allow webhook configuration via helm values

- builder/Dockerfile.alpine-tracee-container
Forgot to fix a spot, context -> https://github.com/aquasecurity/tracee/issues/3867
> fix: bump opa to v0.61.0

- pkg/ebpf/tracee.go
`symbols_collisions` event use two events to operate. Fix the issue of initializing an object for each event, resulting broken event.
Fix #3882
> fix(derive): keep symbols_collision state between events

- deploy/helm/tracee/templates/tracee-config.yaml
if we pass an empty go template it breaks the config file, as it doesn't have a default we only configure it if we pass a template
> helm: config go template only if passed

- pkg/ebpf/processor_funcs.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/events/ftrace.go
We need to count how many ftrace based hooks will be placed on each symbol. eventsState may contain duplicate events due to dependencies. To get the real count, we consider the program name and the prob type. Furthermore, added logic that addresses the situation where there may be multiple k[ret]probes from a single probe request (due to multiple symbols at different locations).
./tracee -e=ftrace_hook
> fix(events): fix ftrace_hook

- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
fix: always initialize proc_info map
In environments with a high amount of CPUs the current proc_info map
size of 10240 entries might not be enough, and gets filled quickly.
In these cases we got an error of missing proc_info entry.
A quick mitigation then will be to set a bigger map size.
The root cause of this issue is that we assume that if task_info exists
for some task in the task_info_map, then also the proc_info of the
process to which the task belongs to also has an entry in the map,
but that is not the case.
To fix this issue, add proc_info lookup and initialization in
init_program_data() function. In addition, init proc_info of the
relevant pid in case it was not found in other places.
Fix: #3914
To test, I changed proc_info_map size to 50, then reproduced the issue.
Then see …
> Fix proc info lru

- pkg/ebpf/c/tracee.bpf.c
Currently we use the stack to initialize task_info in the sched_process_fork program. Since task_info_t has a size of ~200 bytes, we should opt to put it on a map, and not on the stack.
> chore: use map instead of stack to store task_info

- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
f1b2d39e **chore: reduce bpf map lookups for policies config**
```
Instead of always retrieving the policies config map version in the
outer and inner maps, create a holder in the event_data and update it
only when config entry version changes.
```
> Improve bpf policies config access

- cmd/tracee/cmd/analyze.go
- pkg/signatures/engine/engine.go
fix: #3903
fix: #3905 
Instead of terminating the program upon reaching the EOF (after all events have been read), ensure the program concludes only after all events have been fully processed.
> Concurrency issue at analyze

- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/common/probes.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/events/core.go
perf: use lazy program data initialization
We currently initialize all task context related fields on the beginning
of our BPF programs. Reading all the relevant fields takes some CPU
cycles although these fields are not always used. In many cases, for
example when filters are applied, the event is not sent to userspace and
is just dropped without any side effects.
Reading only the essential fields and leaving all other fields
initialization to the submit stage will avoid wasting these cycles, and
will also allow us to perform some of the event enrichment in userspace
instead (not part of this PR).
To do this change, we have to remove the matched_policies which were
cached in task_info since we can't check if "context changed" anymore.
Considering that the average user will only use one …
> Optimize init program

- Makefile
Close: #3928
ea5e6f445 **fix: make check-pr compliant with different shells**
```
It also now deals with trailing newlines in the commit bodies, printing
them following the same pattern.
```
> fix: make check-pr compliant with different shells

- tests/e2e-install-deps.sh
8959a2e62 **chore: ensure unattended-upgrades killing**
Issue:
https://github.com/aquasecurity/tracee/actions/runs/8440398742/job/23117187309
```
Run ./tests/e2e-install-deps.sh
Synchronizing state of unattended-upgrades.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable unattended-upgrades
Removed /etc/systemd/system/multi-user.target.wants/unattended-upgrades.service.
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1551 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1551 (apt-get)
E: Unable to acquire the dpkg frontend lock …
```
> chore: ensure unattended-upgrades killing

- cmd/tracee-rules/input.go
- cmd/tracee-rules/input_test.go
ec644981c **chore!: remove gob support from tracee-rules**
```
This finishes the removal of gob support after #3841.
```
> chore!: remove gob support from tracee-rules

- pkg/cmd/initialize/sigs.go
Give each signature an event ID before loading it. This allows signatures to select each other when loaded together.
Fix #3935
> fix: preallocate ids for signatures upon load

- api/go.mod
- api/go.sum
- go.mod
- go.sum
Fix for [CVE-2024-24786](https://pkg.go.dev/vuln/GO-2024-2611)
> chore(deps): bump google.golang.org/protobuf to v1.33.0

- pkg/ebpf/c/tracee.bpf.c
The security_scoket_connect event sent the wrong fd number. This was due to using a wrong way to check if the binary is a 32bit binary.
Fix: #3950
> fix: security_socket_connect wrong fd

- pkg/cmd/tracee.go
- pkg/config/config.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_loaded.go
- pkg/policy/ebpf.go
- pkg/policy/errors.go
- pkg/policy/policies.go
- pkg/policy/policies_test.go
- tests/integration/event_filters_test.go
9d2a1c59b **chore(policy): remove PolicyAlreadyExists**
```
Remove wrong logic from set method to check if a policy already exists.
If it exists, the method should always overwrite the policy.
```
bace1d126 **chore(policy): change Policies inner maps key pair**
```
Invert the key pair of the Policies inner maps to make it easier to
do reflection (tests).
```
> Invert Policies inner maps key pair

- tests/e2e-install-deps.sh
> chore: set xtrace on e2e-install-deps.sh script

- signatures/helpers/arguments_helpers.go
Add `ArgVal` signature helper to extract a generic type from event arguments.
This function is simply copied from `pkg/events/parse/params.go` so it is now available for signatures.
This PR is needed for https://github.com/aquasecurity/tracee/pull/3953
> Add `ArgVal` signature helper

- pkg/policy/errors.go
- pkg/policy/policies.go
- pkg/policy/policies_test.go
043d0310d **chore(policy): add policiesMapByName to Policies**
```
- Introduce policiesMapByName to speed up LookupByName() and support
Add(), Set() and Remove().
- Reintroduce PolicyAlreadyExistsError with different signature.
- Add() now checks against already existing policy name.
- Set() now only overwrites if name and ID of the given policy are
identical.
- Add count() to be used internally.
```
> chore(policy): add policiesMapByName to Policies

- pkg/ebpf/ksymbols.go
- pkg/ebpf/tracee.go
- pkg/events/dependencies/event.go
- pkg/events/dependencies/manager.go
- pkg/events/dependencies/manager_test.go
Create a manager object for the dependencies between event.
It helps to follow what events are really used, and will enable to effectively cancel and add events and probes.
This is a first step towards my current goal of having fallbacks for dependencies, to have a proper solution for the `process_execute_failed` event.
I will create another PR after this one that support the fallback of dependencies, and afterwards work with it on the event.
The work on this PR exposed multiple problems or I might even call them bugs in our current code:
1. When an event fails, we just cancel all of its dependencies events even though they might be chosen or a dependency of another event. However, we don't cancel events that depend on it. **This PR address this issue** - Fix #3932
2. We don't cancel …
> Dependencies tree manager

- pkg/ebpf/c/common/cgroups.h
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/tracee.bpf.c
This PR changes a few `bpf_probe_read` which did not use the correct core/kernel helpers.
> chore: various co-re fixes

- pkg/ebpf/tracee.go
- pkg/events/dependencies/manager.go
- pkg/events/dependencies/manager_test.go
Fix a bug of nil pointer reference when removing an event node from the dependencies after it was already removed.
> fix(dependencies): allow multiple removes of same event

- deploy/helm/tracee/templates/deploy.yaml
- deploy/helm/tracee/values.yaml
Allow options to schedule the tracee operator when deploying with the Helm chart
* fix: add missing nodeSelector and tolerations to tracee-operator deployment
* fix: add missing imagePullSecrets for tracee-operator
```
cat > test.yaml <<EOF
operator:
nodeSelector:
kubernetes.io/os: linux
tolerations:
- key: "workload"
operator: "Equal"
value: "security"
effect: "NoSchedule"
EOF
helm template tracee ./deploy/helm/tracee --show-only templates/deploy.yaml
helm template tracee ./deploy/helm/tracee --show-only templates/deploy.yaml -f test.yaml
```
> fix: add missing nodeSelector and tolerations to tracee-operator

- pkg/cmd/tracee.go
- pkg/config/config.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_loaded.go
- pkg/policy/ebpf.go
- pkg/policy/policies.go
- pkg/policy/policies_iterator.go
- pkg/utils/utils.go
- tests/integration/event_filters_test.go
5dc0a1bbc **chore: add CreateAllIterator**
688c30403 **chore: add CreateUserlandIterator**
7de062cbd **chore: introduce PoliciesIterator**
faef01c64 **chore: introduce Iterator generic interface**
5dc0a1bbc **chore: add CreateAllIterator**
```
Use CreateAllIterator instead of directly accessing the policies map,
which is a private field.
This also removes a stale Policies validation from the Config struct
method.
```
688c30403 **chore: add CreateUserlandIterator**
```
Use CreateUserlandIterator instead of directly accessing userland
policies slice, which is a private field.
```
faef01c64 **chore: introduce Iterator generic interface**
```
The Iterator pattern can be used to traverse a …
```
> Add Iterator generic interface, debut it in Policies

- .github/workflows/release-snapshot.yaml
I don't think the aarch64 build depends on the x86_64 build after a cursory look. This should reduce build time by over and hour and let me have new builds at 11PM instead of 1AM in my timezone 😁
> Run x86_64 & aarch64 builds in parallel

- .github/workflows/release.yaml
02a61c04 **chore(ci): run x86_64 & aarch64 builds in parallel**
```
See: #3962
```
> chore(ci): run x86_64 & aarch64 builds in parallel

- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_loaded.go
- pkg/filters/args.go
- pkg/filters/args_test.go
- pkg/filters/binary.go
- pkg/filters/bool.go
- pkg/filters/bool_test.go
- pkg/filters/context.go
- pkg/filters/context_test.go
- pkg/filters/filters.go
- pkg/filters/int.go
- pkg/filters/int_test.go
- pkg/filters/processtree.go
- pkg/filters/retval.go
- pkg/filters/sets/prefixset.go
- pkg/filters/sets/suffixset.go
- pkg/filters/string.go
- pkg/filters/string_test.go
- pkg/filters/uint.go
- pkg/filters/uint_test.go
- pkg/policy/policies.go
- pkg/policy/policies_test.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
- pkg/utils/utils.go
64ac6e62 **chore: make Cloner generic**
```
This simplifies the Cloner interface usage since it is not necessary to
assert the Clone return to the specific type.
This also includes compile-time checks to ensure that the Clone method
is implemented for all types that should be cloned.
```
> chore: make Cloner generic

- pkg/ebpf/c/tracee.bpf.c
commit c3fc330 accidentally deleted vfs_read/write arguments which are also used by the capture tail call. Let's restore them.
> fix: capture io

- pkg/ebpf/c/common/consts.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/tracee.go
OPT_PROCESS_INFO is not used anymore and can't be selected by the user. Remove old code that still uses it.
> chore: remove OPT_PROCESS_INFO

- Vagrantfile
The current commands to download kubectl are outdated. Seems that the repository is not available anymore.
Update to kubectl v1.29.
> fix: update vagrant file to download kubectl

- pkg/filters/args_test.go
- pkg/filters/bool_test.go
- pkg/filters/context_test.go
- pkg/filters/int_test.go
- pkg/filters/processtree_test.go
- pkg/filters/sets/sets_test.go
- pkg/filters/string.go
- pkg/filters/string_test.go
- pkg/filters/uint_test.go
- pkg/policy/ebpf.go
- pkg/policy/policies.go
- pkg/policy/policies_test.go
- pkg/policy/policy_test.go
6185bdcda **chore: improve Clone tests by using google/go-cmp**
227367504 **chore(filters): add ValueHandler function type**
02e4a1238 **chore(policy): add inner methods for iteration**
392535aea **fix(policy): iterate array to preserve order**
239087aca **fix(policy): Policies Clone method**
227367504 **chore(filters): add ValueHandler function type**
```
It is a function type that can be used to handle the value of a filter
when it is parsed.
This also removes a dead code.
```
02e4a1238 **chore(policy): add inner methods for iteration**
```
Depending o the use case, the iteration of the policies can be done
by allFromArray() or allFromMap().
```
392535aea **fix(policy): iterate array to preserve order**
```
To fill userlandPolicies, we need to iterate over the array of policies
to …
```
> Fix Policies Cloning

- .github/workflows/release-snapshot.yaml
There is no way to currently use an architecture agnostic dev image for a specific build. This enables that use case.
> Add timestamp docker tag for dev image

- Makefile
- go.mod
- go.sum
fa8adfb15 **chore: bump 3rdparty/libbpf to v1.4.0**
82bdf24d6 **chore: bump libbpfgo to v0.7.0-libbpf-1.4**
68c1fcdc4 **chore(build): remove pre-requisites from Makefile**
68c1fcdc4 **chore(build): remove pre-requisites from Makefile**
```
For test-upstream-libbpfgo target, the libbpf.a is built from calling
./tests/libbpfgo.sh.
```
> Libbpfgo bump

- cmd/tracee/cmd/analyze.go
Restore the binding of the analyze mode flags with viper. This should fix the issue that they weren't usable since they were commented out.
Fix #3980
> fix(analyze): bind flags with viper

- deploy/helm/tracee/templates/daemonset.yaml
- docs/contributing/setup-development-machine-with-vagrant.md
37fd48037 **docs: helm add repo is not necessary from local installation**
58824a3c5 **fix: option webhook value on helm**
58824a3c5 **fix: option webhook value on helm**
```
If uses helm chart to install Tracee, the '--output' key need to be
separeted from value 'webhook' in order to work as excepted.
```
Follow this [tutorial](https://aquasecurity.github.io/tracee/latest/contributing/setup-development-machine-with-vagrant/#deploy-tracee-with-postee-on-kubernetes), the issue raises during `helm install tracee` step.
> Fix helm install option webhook

- pkg/ebpf/tracee.go
d621c3644 **fix(ebpf): use log debug level instead of error...**
```
... for internal requirements.
Considering that if GetLast() failed t.config.Policies is nil, this also
removes the use of t.config.Policies. Furthermore, the goal is to
concetrate all Policies access in the PolicyManager.
```
> fix(ebpf): use debug error level instead of error

- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/common/signal.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/policy/ebpf.go
As preparation for migrating event scope filters into the kernel and matching filters by event id, we now save the event id in the program_data_t structure during initialization instead of when submitting the event to userspace.
By knowing the event id during program init, we can also retrieve the bitmap of the policies that requested this event, removing the need to call should_submit() within the program.
Next, should_trace() is renamed to evaluate_context_filters() to better represent its function and accommodate potential future argument filters. This function considers both event submit bits and matched context filters. Its return value is now boolean to hide the internal policy matching mechanism, ensuring future-proofing against changes in bitmap size or implementation.
For …
> refactor: Improve API used by ebpf programs

- pkg/ebpf/signature_engine.go
Close: #3993
873599b17 **fix(ebpf): check if engineOutput is closed**
> fix(ebpf): check if engineOutput is closed

- pkg/policy/ebpf.go
- pkg/policy/equality.go
405b8bedf **chore: refactor equality computation**
```
This moves the equality logic to equality.go, and uses Generics to
deduplicate the code.
This also changes procTreeEqualities map key to uint32, the right type
for the key.
```
> chore: refactor equality computation

- pkg/cmd/cobra/cobra.go
- pkg/cmd/flags/policy.go
- pkg/cmd/tracee.go
- pkg/cmd/urfave/urfave.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/policy_manager_test.go
- pkg/ebpf/tracee.go
- pkg/policy/ebpf.go
- pkg/policy/errors.go
- pkg/policy/policies.go
- pkg/policy/policies_compute.go
- pkg/policy/policy.go
- pkg/policy/snapshots.go
- pkg/policy/snapshots_test.go
c5f3f8d5a **chore(policy): move logic into policies_compute.go**
13977144b **chore(cmd): reuse already computed policies value**
1d17a5065 **chore(policy): align policy and polices API**
3faa9b88c **chore(policy): rename consts and add PolicyNone**
78305a90b **chore(policy): remove SetVersion()**
e8f4545e8 **chore(policy): remove useless code**
ea3998ee6 **chore: remove dead/duplicate code**
c5f3f8d5a **chore(policy): move logic into policies_compute.go**
```
This new file contains the logic for policies computation.
```
13977144b **chore(cmd): reuse already computed policies value**
```
GetContainerMode() can make use of the already computed policies
information (container filters) via ContainerFilterEnabled().
```
1d17a5065 **chore(policy): align policy and polices API**
```
Both policy …
```
> Chore at large

- tests/e2e-install-deps.sh
d4a0dfa0a **fix(tests): address shellcheck SC1091**
```
Silence shellcheck SC1091 in e2e-install-deps.sh.
```
95ea66abd **fix(tests): address shellcheck SC2001**
```
- SC2001: See if you can use ${variable//search/replace} instead.
In this was used % (shortest match - suffix) since it's more appropriate
for the use case.
```
3700b4018 **fix(tests): address shellcheck SC2005**
```
- SC2005: Useless echo? Instead of 'cmd; echo $?' just use 'cmd'.
```
d06ef237f **fix(tests): address shellcheck SC2086**
```
- SC2086: Double quote to prevent globbing and word splitting.
```
a4475b83a **fix(tests): call wait_for_apt_locks before apt-get**
```
Reduce the window of opportunity for apt-get to fail due to locks by
calling wait_for_apt_locks before each apt-get command.
```
> Wait for apt locks

- docs/docs/flags/events.1.md
- docs/docs/policies/rules.md
- docs/man/events.1
- pkg/cmd/flags/capture.go
- pkg/cmd/flags/event.go
- pkg/cmd/flags/event_test.go
- pkg/cmd/flags/filter.go
- pkg/cmd/flags/policy.go
- pkg/cmd/flags/policy_test.go
- pkg/ebpf/events_pipeline.go
- pkg/filters/errors.go
- pkg/filters/scope.go
- pkg/filters/scope_test.go
- pkg/policy/policies.go
- pkg/policy/policies_compute.go
- pkg/policy/policies_iterator.go
- pkg/policy/policies_test.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
This commit updates the terminology within the Tracee codebase, replacing occurrences of "context filters" with "scope filters". By doing so, it enhances the clarity and intuitiveness of the user interface and documentation.
Fix: #3996
> Rename context filters to scope filters

- deploy/helm/tracee/templates/daemonset.yaml
- deploy/helm/tracee/templates/tracee-config.yaml
- deploy/helm/tracee/templates/tracee-templates.yaml
- deploy/helm/tracee/values.yaml
- feat: go templates for tracee webhooks (fixes #3886)
- fix: make only goTemplate mandatory in webhook config (temporary workaround for #3866)
```
➜ cat > test.yaml <<EOF
extraWebhookTemplates:
- name: custom.tmpl
goTemplate: |-
{
"event": "{{ .Event }}"
}
config:
output:
webhook:
name: local
protocol: http
host: localhost
port: 8080
goTemplate: /tracee/templates/custom.tmpl
EOF
➜ helm template tracee ./deploy/helm/tracee --show-only templates/tracee-templates.yaml -f test.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: tracee-templates
labels:
helm.sh/chart: tracee-0.20.0
app.kubernetes.io/name: tracee
app.kubernetes.io/instance: tracee
app.kubernetes.io/version: "0.20.0"
app.kubernetes.io/managed-by: Helm
data:
custom.tmpl: |
{
"event": "{{ .Event }}"
}
➜ helm template tracee …
```
> Helm webhook custom templates

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/derive/hidden_kernel_module.go
The MAX_NUM_MODULES was recently decreased from 600 to 450 and is anyway relatively small. In case there are more modules to iterate on than the number of the iterations done, it will report the rest as false positives. To mitigate that, an LRU holds the suspected events and waits until the scan finishes: if the scan finished successfully, sends the events and otherwise deletes them.
This was introduced in kernels 6.5 where the mod_tree contains duplicate nodes, and 450 iterations may not be enough.
When it's possible to use bpf_loop (currently RHEL verifier fails if the helper exists in the code; specific program loading might solve it), this patch needs to be reverted and the patch that uses bpf_loop needs to be used instead.
./tracee -e=hidden_kernel_module
> fix(events): hidden_kernel_module - change history scan behaviour

- docs/docs/advanced/data-sources/builtin/process-tree.md
- pkg/cmd/flags/proctree.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_feed.go
Allow the procfs scanning and querying to be configured by the user. For now Tracee only enable to disable the procfs querying upon lost events. This should help to improve performance on high-load systems.
Fix #3988
> feat(proctree): control procfs query by config

- Makefile
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/tracee.bpf.c
- tests/e2e-inst-signatures/e2e-vfs_writev.go
- tests/e2e-inst-signatures/export.go
- tests/e2e-inst-signatures/scripts/vfs_writev.sh
- tests/e2e-inst-signatures/scripts/writev_tester/writev.c
- tests/e2e-inst-test.sh
- tests/integration/capture_test.go
- tests/perftests/metrics_test.go
- tests/testutils/tracee.go
d92f13f43 **tests(integration): add capture tests**
8ad9959a4 **tests(inst): add vfs_writev test**
bb7cd569e **fix: restore io capture output**
bb7cd569e **fix: restore io capture output**
```
Commit 3ddf73d changed various probe_read calls to probe_read_kernel.
However, io capture relies on reading userspace buffers, as such the
pointers being read are userspace pointers. Therefore the relevant calls
in some of these changes, affecting IO capture, were changed to
probe_read_user.
```
1. With the new integration test
OR
1. Run tracee with `tracee -c read=/home/ubuntu/output* -c write=/home/ubuntu/output*`
2. `echo Hello > /home/ubuntu/output.txt`
3. `cat /home/ubuntu/output.txt`
4. Check `/tmp/tracee/out/host` for the relevant files and confirm their content (both should be `Hello`) …
> capture: fixes and tests

- Makefile
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/tracee.bpf.c
- tests/e2e-inst-signatures/e2e-vfs_writev.go
- tests/e2e-inst-signatures/export.go
- tests/e2e-inst-signatures/scripts/vfs_writev.sh
- tests/e2e-inst-signatures/scripts/writev_tester/writev.c
- tests/e2e-inst-test.sh
- tests/integration/capture_test.go
- tests/perftests/metrics_test.go
- tests/testutils/tracee.go
Waiting to merge #4016 so that the mainline commits can be specified in the commit messages.
> [v0.21.0] capture: fixes and tests

- pkg/ebpf/c/tracee.bpf.c
- tests/e2e-net-signatures/e2e-dns.go
- tests/e2e-net-signatures/e2e-http.go
- tests/e2e-net-signatures/e2e-icmp.go
- tests/e2e-net-signatures/e2e-icmpv6.go
- tests/e2e-net-signatures/e2e-ipv4.go
- tests/e2e-net-signatures/e2e-ipv6.go
- tests/e2e-net-signatures/e2e-tcp.go
- tests/e2e-net-signatures/e2e-udp.go
714777811 **fix(ebpf): initialize network event task context**
```
Commit f806cb4b changed context initialization to occur in the submit
stage. However, network events do not have access to that context during
their submit stage (since they happen in a cgroup_skb program).
Therefore, add a call to init_task_context in the pre cgroup bpf program
(cgroup_bpf_run_filter_skb).
```
37716feb2 **tests(network): add task context validation**
```
Since network events have a different eBPF program architecture, they
can't initialize the task context the standard way.
Therefore, add a validation in the e2e tests so that task context
initialization doesn't break.
```
Added validation in existing e2e network tests.
Manually test by running `tracee --events net_packet_http` and then `curl …
> fix: network event context

- pkg/ebpf/c/tracee.bpf.c
- tests/e2e-net-signatures/e2e-dns.go
- tests/e2e-net-signatures/e2e-http.go
- tests/e2e-net-signatures/e2e-icmp.go
- tests/e2e-net-signatures/e2e-icmpv6.go
- tests/e2e-net-signatures/e2e-ipv4.go
- tests/e2e-net-signatures/e2e-ipv6.go
- tests/e2e-net-signatures/e2e-tcp.go
- tests/e2e-net-signatures/e2e-udp.go
> [v0.21.0] fix: network event context

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/probes/probe_group.go
- pkg/ebpf/probes/probes.go
- pkg/events/core.go
Recently, the process_execute_failed event implementation had been changed to use the new inner execute_finished event. This event has used syscall tracepoints in its implementation. However, tracepoints rely on debugfs, which was not a requirement of tracee until now. To remove this requirement (at least for now), move to use architecture-specific kprobes instead.
Fix #4026
> fix(ebpf): use kprobes for execute_finished

- pkg/events/derive/symbols_collision_test.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/symbols_loaded_test.go
- pkg/utils/sharedobjs/host_symbols_loader.go
- pkg/utils/sharedobjs/host_symbols_loader_test.go
- pkg/utils/sharedobjs/shared_object.go
The symbols_loaded event currently log all errors received in its logic.
However, there is a case that an object is loaded to a process which is not ELF (for example, jsa files of Java).
As the event is not meant to parse such files, avoid logging errors in parsing them.
Fix #4033
> fix: avoid logging warnings for non-ELF so loading

- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/symbols_loaded_test.go
Errors from the SO loader are pretty frequent because of race conditions. As the user has nothing to do with it, the log level should be lowered from WARN.
> chore(events): decrease SO loader error log level to debug

- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/symbols_loaded_test.go
Errors from the SO loader are pretty frequent because of race conditions.
As the user has nothing to do with it, the log level should be lowered from WARN.
> v0.21.0:chore(events): decrease SO loader error log level to debug

- mkdocs.yml
Fix #4012
The documentation sports a "Format" security event: https://aquasecurity.github.io/tracee/latest/docs/events/builtin/signatures/format/ This is some error with how the documentation got created by AI.
Remove this "event" from docs.
> fix: remove invalid "format" event from docs

- tests/integration/capture_test.go
- tests/perftests/metrics_test.go
- tests/testutils/exec.go
- tests/testutils/tracee.go
Fix tests so they will make sure to close channels properly and clean goroutines.
Fix #4044
> fix(tests): fix goroutines leakage in integration tests

- deploy/helm/tracee/Chart.yaml
- deploy/kubernetes/tracee/tracee.yaml
Reverts aquasecurity/tracee#4007 due to https://github.com/aquasecurity/tracee/pull/4018#issuecomment-2106928157
> Revert "chore(k8s): prepare v0.21.0 release"

- pkg/changelog/changelog.go
- pkg/changelog/changelog_test.go
- pkg/proctree/fileinfo.go
- pkg/proctree/process.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/taskinfo.go
This PR add limitation on the changelog objects sizes, and reduces drastically the memory usage of the tree by not saving the interpreter and interp information in the tree.
This should reduce the chance for memory leakage.
By rough calculation, before the PR the process tree would take around 150MB of memory on average.
After this change, it should be reduced by at least 60MB on average.
> fix(proctree): limit tree memory usage and reduce it

- .github/workflows/performance.yaml
- Makefile
- performance/benchmark/network/bench.sh
Benchmark output was previously uncoordinated between yaml and script. Commit adds an output location parameter to the script and corresponding make arguments, which are then used in the yaml.
> fix(performance.yaml): benchmark output location

- pkg/changelog/changelog.go
- pkg/changelog/changelog_test.go
- pkg/proctree/fileinfo.go
- pkg/proctree/process.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/taskinfo.go
The PR is backporting of #4058 to v0.21.0
> 0.21.0/fix(proctree): limit tree memory usage and reduce it

- .github/actions/build-dependencies/action.yaml
- Makefile
- Vagrantfile
- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- docs/contributing/building/building.md
- tests/e2e-install-deps.sh
Close: https://github.com/aquasecurity/tracee/issues/4060
ac9bdb162 **chore: temp fix for install libzstd on AMIs**
656df9ac8 **chore: install required bpftool from btfhub**
e40109f69 **fix(build): static build might require zstd lib**
ac9bdb162 **chore: temp fix for install libzstd on AMIs**
```
AMIs have to be updated and installations like this commented out.
```
e40109f69 **fix(build): static build might require zstd lib**
```
libelf might be built with zstd support in some environments, so for
static builds (mainly) it is necessary to ensure that the zstd library
is available.
https://sourceware.org/git/?p=elfutils.git;a=commit;h=ed688a59b4d4f5ccf6ef15244e5a9139f71769a3
```
> fix(build): static build might require zstd lib

- .github/actions/build-dependencies/action.yaml
- Makefile
- Vagrantfile
- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- docs/contributing/building/building.md
- tests/e2e-install-deps.sh
6660bd6d7 **chore: temp fix for install libzstd on AMIs**
```
AMIs have to be updated and installations like this commented out.
commit: ba4db8b (main), cherry-pick
```
216ebc055 **chore: install required bpftool from btfhub**
```
commit: d2cd2c3 (main), cherry-pick
```
6e9edd1d6 **fix(build): static build might require zstd lib**
```
libelf might be built with zstd support in some environments, so for
static builds (mainly) it is necessary to ensure that the zstd library
is available.
https://sourceware.org/git/?p=elfutils.git;a=commit;h=ed688a59b4d4f5ccf6ef15244e5a9139f71769a3
commit: 5e42f2c (main), cherry-pick
```
> [v0.21.0] fix(build): static build might require zstd lib

- .revive.toml
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_pipeline_bench_test.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_collision_test.go
- pkg/events/ftrace.go
- pkg/server/grpc/tracee.go
- pkg/signatures/benchmark/signature/golang/anti_debugging.go
- pkg/signatures/benchmark/signature/golang/code_injection.go
- pkg/utils/sharedobjs/host_symbols_loader.go
- tests/integration/capture_test.go
- tests/integration/event_filters_test.go
- types/trace/trace.go
fix: #3475 
3645eaa16 **chore: code refactor to add assertion**
e1ec4b2a8 **chore: enable unchecked-type-assertion**
3645eaa16 **chore: code refactor to add assertion**
```
Refactored code to fix the unchecked type cast issue by
incorporating error handling after the type assertion.
```
> chore: code refactor to add assertion

- pkg/cgroup/cgroup.go
- pkg/mount/mount.go
When running Tracee from within a container, multiple mount points of the cgroup filesystem may exist. In such cases, we need to ensure that we select the mountpoint from the host cgroup namespace. By checking for an inode equal to 1, we can identify the cgroupfs mountpoint belonging to the host cgroup namespace. This ensures that Tracee can discover preexisting containers using the host cgroup filesystem.
Additionally, a warning log is emitted if the cgroup mountpoint does not have an inode of 1, indicating that it might not be part of the host cgroup namespace.
> [v0.21.0] fix: select cgroup mountpoint with the smallest inode number

- pkg/cgroup/cgroup.go
- pkg/mount/mount.go
When running Tracee from within a container, multiple mount points of the cgroup filesystem may exist. In such cases, we need to ensure that we select the mountpoint from the host cgroup namespace. By checking for an inode equal to 1, we can identify the cgroupfs mountpoint belonging to the host cgroup namespace. This ensures that Tracee can discover preexisting containers using the host cgroup filesystem.
Additionally, a warning log is emitted if the cgroup mountpoint does not have an inode of 1, indicating that it might not be part of the host cgroup namespace.
> fix: select cgroup mountpoint with the smallest inode number

- pkg/cgroup/cgroup.go
The GetCgroupPath function previously used recursion for directory traversal, which could consume excessive memory for deep directory structures. This commit refactors the function to use an iterative approach, reducing memory usage and improving performance. Additionally, the comments and error handling in the function have been updated for clarity and consistency.
> Refactor: Optimize GetCgroupPath() memory utilization

- pkg/cgroup/cgroup.go
Refactor: Optimize GetCgroupPath() memory utilization
The GetCgroupPath function previously used recursion for directory traversal,
which could consume excessive memory for deep directory structures. This commit
refactors the function to use an iterative approach, reducing memory usage and
improving performance. Additionally, the comments and error handling in the
function have been updated for clarity and consistency.
> [v0.21.0]Refactor: Optimize GetCgroupPath() memory utilization

- docs/docs/events/builtin/extra/symbols_collision.md
- docs/docs/events/builtin/extra/symbols_loaded.md
- docs/docs/policies/rules.md
- pkg/ebpf/events_pipeline.go
5662d5891 **chore(docs): rename args filter to data filter**
> chore(docs): rename args filter to data filter

- pkg/changelog/changelog.go
Fix bug with changelog max size enforcement that caused the remove of wrong entries from the timestamps cache, corrupting it.
> fix(changelog): size enforcement corrupted cache

- pkg/changelog/changelog.go
Fix bug with changelog max size enforcement that caused the remove of wrong entries from the timestamps cache, corrupting it.
> 0.21.0/fix(changelog): size enforcement corrupted cache 

- pkg/ebpf/probes/probe_group.go
- pkg/ebpf/probes/trace.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/utils/environment/kernel_symbols.go
- pkg/utils/environment/kernel_symbols_test.go
```
fix: add missing dependency for hooked_syscalls event
The hooked_syscalls event requires CAP_SYSLOG in order to
refresh its symbol table when reading /proc/kallsyms.
Add this missing dependency.
```
```
feat(ksymbols): restore lazy ksyms implementation
Use modified ksymbols implementation. The new implementation may take
a list of required symbols and addresses to track. If the list is given,
symbol scanning will only save those symbols or addresses which were
given in the list. If a new symbol is queried, then a rescan is needed.
Refactor tracee initialization to find all necessary symbols to track
ahead of runtime.
```
> Fix ksymbols mem consumption

- pkg/ebpf/probes/probe_group.go
- pkg/ebpf/probes/trace.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/utils/environment/kernel_symbols.go
- pkg/utils/environment/kernel_symbols_test.go
Backport #4095 to v0.21.0 branch
> [backport 0.21.0] Fix ksymbols mem consumption backport

- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux_missing.h
115610859 **chore(ebpf): replace sizeof with bpf type helpers**
```
When using sizeof on kernel structs, false results may happen due to the
sizeof builtin not being designed to take into account btf relocations.
Use the libbpf helpers bpf_core_type_size and bpf_core_field_size where
relevant.
```
cfd849e5c **chore(ebpf): remove get_type_size macro**
```
Use the builtin libbpf core helper instead, which
the macro was an alias of.
```
Resolve #3774
> chore(ebpf): use core type size checks

- pkg/ebpf/c/common/common.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/probes/probe_group.go
- pkg/ebpf/probes/probes.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/events/definition_dependencies.go
- pkg/events/dependencies/actions.go
- pkg/events/dependencies/errors.go
- pkg/events/dependencies/event.go
- pkg/events/dependencies/manager.go
- pkg/events/dependencies/manager_test.go
- pkg/events/dependencies/probes.go
- pkg/logger/logger.go
- pkg/policy/v1beta1/policy_file_test.go
- tests/integration/dependencies_test.go
- tests/integration/event_filters_test.go
- tests/testutils/logger.go
- tests/testutils/policies.go
This PR expands and uses the dependencies API introduced in #3931 for other events dependencies handling.
It adds the probes dependencies to the dependencies manager, and use it to manage probes cancelling.
This PR also add the dependencies watchers for adding and removing the probes, and use the dependencies to cancel events with missing ksymbols.
Fix #3933
> feat(dependencies): further adopt dependencies API to ksymbols and probes

- pkg/bufferdecoder/decoder.go
- pkg/ebpf/controlplane/signal.go
- pkg/ebpf/events_pipeline.go
Refactor the event decoding stage in the Tracee pipeline to fetch event parameters and related data (e.g., event name) from the event definition only once. Previously, the `GetParams` function was called multiple times within `DecodeArguments`, leading to unnecessary overhead.
This optimization improves the efficiency of event processing, particularly for events with a large number of parameters or frequent occurrences.
> perf: Optmize event parameter decoding in pipeline

- Makefile
Close #4075
6da260d22 **fix(build): set order-only prerequisites correctly**
a403b7111 **fix(build): ldflags settings**
6da260d22 **fix(build): set order-only prerequisites correctly**
```
Move "order-only prerequisites" from "dependencies" to the right place -
after the pipe symbol.
```
> fix(build): ldflags setting

- builder/Makefile.release
- builder/Makefile.tracee-container
This is a continuation of https://github.com/aquasecurity/tracee/pull/4137.
89dd6d0af **chore(ci): use dev tag for docker image building**
```
When SNAPSHOT=1, the local docker image will be tagged with dev tag to
differentiate it from the official release which is tagged with the
latest tag.
```
> chore(ci): use dev tag for docker image building

- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.ubuntu-tracee-make
d739e9e65 **chore: golang binary move to tmp**
4435515e4 **fix: arm64 clang issue**
> chore: golang binary move to tmp

- builder/Makefile.release
82336fef5 **fix(ci): make release rule to have prerequisites**
```
These changes ensure that the 'release' rule will require the other
rules to be executed (splitting the commands into different rules). This
way, if any some of the rules fail, the build will be aborted right away.
```
> fix(ci): make release rule to have prerequisites

- builder/Dockerfile.alpine-tracee-container
- go.mod
0841d4497 **fix(build): extract OPA 0.66 from OPA dev image**
66b7b5e43 **fix(build): bump go to fix cve-2024-24790**
0841d4497 **fix(build): extract OPA 0.66 from OPA dev image**
```
This workaround is required since OPA 0.65.0 (latest published release)
has cve-2024-24790.
After solved we can rollback to the previouw installation method.
```
> Bumps to fix cve-2024-24790

- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.ubuntu-tracee-make
- builder/Makefile.release
- builder/Makefile.tracee-container
2195c5ee4 **fix(build): mv gh release logic to release rule (#4145)**
2101b63b8 **fix(build): extract OPA 0.66 from OPA dev image**
ce88fbb09 **fix(ci): make release rule to have prerequisites (#4141)**
432fb25fc **fix: arm64 clang issue**
9bff2616b **chore: golang binary move to tmp**
657a88d59 **chore: install last version of golang**
fba6c4409 **chore(ci): use dev tag for docker image building (#4138)**
> [v0.21.0] release build fix

- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/events/core.go
Add event containing the full payload of all network packets.
Closes #4121 
Run with the `net_packet_raw` event enabled.
> Added event containing full payload for all packets

- pkg/logger/logger.go
- tests/integration/capture_test.go
- tests/integration/dependencies_test.go
- tests/testutils/logger.go
Close: #4156 
74bfd7d41 **fix(tests): refactor Test_TraceeCapture**
4e1f89918 **fix(tests): Test_EventsDependencies**
f493e2890 **chore: turn logger thread-safe**
74bfd7d41 **fix(tests): refactor Test_TraceeCapture**
```
This test was failing when other tests were run before it and failed,
tracee running was not stopped and some garbage was left in the system.
Two major changes were made:
1. Do not fail the test before stopping tracee.
2. Always remove capture files after the test (do cleanup).
```
4e1f89918 **fix(tests): Test_EventsDependencies**
```
Test_EventsDependencies overrides the default logger to capture the logs
and check them as part of the test.
Before it was synced to pass in the github actions, what wasn't
happening locally or in a different environment.
Since the logger …
```
> Fix Integration Tests

- pkg/ebpf/ksymbols.go
- pkg/ebpf/tracee.go
- pkg/events/dependencies/manager.go
- pkg/events/dependencies/manager_test.go
- tests/integration/dependencies_test.go
- tests/integration/event_filters_test.go
83c39cf83 **chore: mv dependencies tests to same pkg**
5b6c9fce4 **chore: make dependencies manager a singleton (temp)**
5b6c9fce4 **chore: make dependencies manager a singleton (temp)**
```
This tidies up the dependencies manager by making it a singleton,
temporarily. It's a necessary step to decouple the manager from the
Tracee object without touching much code, allowing it to be accessed
from other parts of the codebase and be detached from other logic.
It introduces an also temporary ResetManagerFromTests() to reset the
manager state between tests.
When elements are decoupled and redesign, the manager will not be a
singleton anymore, but it will be accessed via dependency injection.
NOTE: It continues being not thread-safe. This will be addressed in a
future PR.
```
> chore: make dependencies manager a singleton

- pkg/containers/containers.go
1eb711c85: **fix: generic kubernetes containerd path pattern**
```
Some containerd+k8s distribution create containers in cgroup paths with
the format of:
kubepods/<besteffort|burstable>/podXXXX/<container_id>
This pattern is unrecognizable and on its face indistinguishable between
container runtimes. Since it has so far only been observed in containerd
distributions, detect it as such (for now).
```
Test on a GKE env.
Fix #3003
> fix: generic kubernetes containerd path pattern

- pkg/cmd/cobra/cobra.go
- pkg/cmd/urfave/urfave.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_collision_test.go
- pkg/events/derive/symbols_loaded.go
- pkg/policy/policies.go
- pkg/policy/policy_manager.go
- pkg/policy/policy_manager_test.go
- tests/integration/dependencies_test.go
- tests/integration/event_filters_test.go
93aaaf98a **chore: tidy up policy manager and related code**
857d8ed16 **chore(policy): change manager mutex type to rw**
209a44f9e **chore: move policy manager into policy pkg**
9341d3510 **chore: tidy up policy manager and related code**
```
- Remove Snapshot() use. In the future it could be managed by the policy
manager itself.
- After PolicyManager initialization (first stages), Policies are not
accessed directly anymore, but through the PolicyManager.
- t.config.Policies is now only transient and used for PolicyManager
initialization.
- Policy version is deprecated and to be removed soon.
```
209a44f9e **chore: move policy manager into policy pkg**
```
Place PolicyManager in its proper home, the policy package.
```
> Tidying Policy Manager

- pkg/events/ftrace.go
ftrace_hook: address tabs in input lines
./tracee -e=ftrace_hook
closes #4170
> fix(events): ftrace_hook: address tabs in input lines

- pkg/ebpf/events_pipeline.go
36f4eb123 **fix(pipeline): add ebpf caps in stack addres query**
1. `tracee -o option:stack-addresses -o json`
2. Confirm stack addresses field is filled with a non-empty array
Fix #3964
> fix(pipeline): add ebpf caps in stack addres query

- tests/integration/capture_test.go
0d4e979bc **fix(tests): remove named pipe if it exists**
This guarantees that the named pipe creation won't fail when `readWritePipe()` is called.
> fix(tests): remove named pipe if it exists

- pkg/cmd/cobra/cobra.go
- pkg/cmd/cobra/helper.go
- pkg/cmd/flags/policy.go
- pkg/cmd/urfave/urfave.go
- pkg/config/config.go
- pkg/ebpf/tracee.go
- pkg/events/derive/symbols_collision_test.go
- pkg/policy/ebpf.go
- pkg/policy/equality.go
- pkg/policy/policies.go
- pkg/policy/policies_compute.go
- pkg/policy/policies_iterator.go
- pkg/policy/policies_test.go
- pkg/policy/policy_manager.go
- pkg/policy/snapshots.go
- pkg/policy/snapshots_test.go
- tests/integration/dependencies_test.go
- tests/integration/event_filters_test.go
- tests/testutils/policies.go
c0c711b28 **chore: disable snapshots tests**
da4b19f42 **chore: remove mutex from policies**
9a27046c4 **chore: hide type from the public API**
9f36a4f2e **chore: PolicyManager init refactoring**
c0c711b28 **chore: disable snapshots tests**
```
Snapshots is currently not used and will be revamped in the future.
```
da4b19f42 **chore: remove mutex from policies**
```
policies is now fully under the umbrella of PolicyManager, which already
has a mutex.
```
9a27046c4 **chore: hide type from the public API**
```
Policies -> policies
```
9f36a4f2e **chore: PolicyManager init refactoring**
```
This tidy up continues the work started in previous commits,
by refactoring the PolicyManager initialization code to receive a
Policy slice instead of the Policies object itself.
The changes to …
```
> Policies tidying more

- pkg/ebpf/c/common/common.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/logging.h
- pkg/ebpf/c/common/task.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/capture.go
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/controlplane/processes.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/processor_funcs.go
- pkg/ebpf/processor_proctree.go
- pkg/ebpf/tracee.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_procfs.go
- pkg/proctree/taskinfo.go
- pkg/time/normalizetime.go
- pkg/time/time.go
Tracee had an issue that all the times from the kernel were monotonic. However, many user-mode times like times in procfs are of boottime. As boottime is more accurate, change to use boottime if possible (mainly newer kernels).
If boottime is not available (old kernels), it's still possible to use the proctree option, but the proctree won't be built from procfs. Instead, it will be built from some events.
Fix https://github.com/aquasecurity/tracee/issues/4074
6be76aee5 **Enable time normalization for proctree**
9142b16ec **Enable time normalization for control plane**
0d4ea1022 **Check eBPF helper func symbol & Time normalization init**
aa68a61f5 **Time package**
51d562b5d **eBPF data plane - use boottime whenever possible**
6be76aee5 **Enable time normalization for proctree**
``` …
```
> fix(proctree): fix clock type differences

- cmd/tracee-rules/main.go
- pkg/capabilities/capabilities.go
- pkg/capabilities/capabilities_test.go
- pkg/containers/path_resolver_test.go
- pkg/ebpf/tracee.go
6bd0b3956 **feat(caps): base ebpf capabilities**
```
Add the ability to add the ebpf capabilities to the base ring, instead
of allocating a specific ring. When the feature is enabled, requests for
the eBPF ring will seamlessly avoid a ring switch, and the callback will
be called as is.
```
Stack addresses should remain working.
> feat(caps): base ebpf capabilities

- pkg/pcaps/common.go
- pkg/pcaps/interface.go
- tests/integration/capture_test.go
This PR adds context information to pcap files generated by Tracee. Based on the type of pcap, an interface description that contains various pieces of context information in JSON format is added.
Example of an interface description for a process pcap:
```
{"container":{"id":"c373adfdc4ac4c3a330c4fda09ad9398bcfb99c381b97cb044c813a397547def","name":"gallant_nightingale","image":"busybox:latest","imageDigest":"busybox@sha256:5eef5ed34e1e1ff0a4ae850395cbf665c4de6b4b83a32a0bc7bcb998e24e7bbb"},"kubernetes":{"podName":"","podNamespace":"","podUID":"","podSandbox":false},"hostName":"c373adfdc4ac","processName":"ping","process":{"threadStartTime":1716378637481073915,"processId":1,"cgroupId":526,"threadId":1,"parentProcessId":0,"hostProcessId":191684,"hostThreadId":191684,"hostParentProcessId":1916 …
```
> Packet capture context

- pkg/ebpf/tracee.go
- pkg/policy/event_flags.go
- pkg/policy/event_flags_test.go
- pkg/policy/policy_manager.go
- pkg/policy/policy_manager_test.go
19320445b **chore: introduce eventFlags to policy manager**
```
It replaces the inner eventState type being a holder for the flags of an
event with a proper API.
In next efforts, it will replace the event state map embedded in Tracee.
```
> chore: introduce eventFlags to policy manager

- pkg/capabilities/capabilities.go
93b17685d **chore(cap): check if cap is supported before set/unset**
```
set or unset a capability without proper checking can result in a panic.
```
Test the following code in an older kernel version <5.8.
```
err = capabilities.GetInstance().Specific(
func() error {
return nil
},
cap.BPF,
cap.PERFMON,
)
if err != nil {
return errfmt.WrapError(err)
}
```
If `CAP_BPF`+`CAP_PERFMON` is used on kernel version <5.8, we get a `panic: assignment to entry in nil map` when set/unset the map that was initialized. It happens because both cap are supported only on kernel version >=5.8.
> chore(cap): check if cap is supported before set/unset

- cmd/tracee-ebpf/main.go
- cmd/tracee/cmd/root.go
- pkg/cmd/cobra/cobra.go
- pkg/cmd/urfave/urfave.go
- pkg/config/config.go
- pkg/ebpf/events_enrich.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/signature_engine.go
- pkg/ebpf/tracee.go
- pkg/events/sorting/sorting.go
- tests/integration/tracee.go
236d33ef0 **feat(ebpf): configurable pipeline channel size**
236d33ef0 **feat(ebpf): configurable pipeline channel size**
```
Allow configuring the event channels in pipeline stages using the
`pipeline-channel-size` flag and config entry. Rigorous testing of the
effect of playing with this value has yet to be done, so the default
value is currently 10000 as hardcoded before.
Tentatitevely, reducing the size of this configuration value may help
reduce the mean memory usage, perhaps reduce channel contention, but may
be at the cost of a greater risk for event loss.
```
1. `tracee --pipeline-channel-size X`
2. Configure in a config file with `pipeline-channel-size: X` at the root level
> feat(ebpf): configurable pipeline channel size

- pkg/ebpf/c/tracee.bpf.c
0aa855cbf **chore(ebpf): optimize filldir64 program**
```
The filldir64 program runs very frequently, and as such incurs great
overhead. However, its usecase only requires the submission of events
from non 0 process inodes. Since this filter is faster than scope
evaluation, move this condition check before program data initialization
and scope evaluation.
Optimization reduces the average runtime to ~18% of the previous
overhead. Note, that even for more run amounts, the overall runtime is
now 27% from the previous version.
Before:
PROGRAM: filldir64 (type: kprobe, runtime: 61047110 ns, amount: 53135 times, average: 1148 ns)
After:
PROGRAM: filldir64 (type: kprobe, runtime: 16507056 ns, amount: 80350 times, average: 205 ns)
```
`hidden_inodes` event should work the same.
> chore(ebpf): optimize filldir64 program

- pkg/ebpf/controlplane/cgroups.go
613986ac5 **fix(controlplane): filter unnecessary enriches**
```
The condition for enrichment in the control plane was faulty. It relied
on the previous check for container relevant cgroups + not dead dirs.
This, however, is obviously not enough. Therefore the condition for
enrichment trigger now includes checking if the cgroup is a container's
root directory.
```
`tracee -o json`
`docker run --rm -d ubuntu`
Enrichment should work as before, with no new errors.
> fix(controlplane): filter unnecessary enriches

- pkg/events/core.go
The process_execute_failed event was not functioning correctly due to a missing dependency on the sys_enter probe.
This commit attaches the required probe, allowing the event to trigger as expected.
> fix: Ensure correct event dependency for process_execute_failed

- pkg/ebpf/tracee.go
Previously, tracee incorrectly assumed all tailcall indexes were syscall IDs, leading to unnecessary loading of syscall-specific BPF programs. This caused a resource leak due to unused tracepoint attachments. The issue is now fixed by only removing the code which attaches these programs, as we explicitly define it in the event dependencies.
Run tracee with
`sudo ./dist/tracee -e sched_process_exec`
Before this fix, sys_enter and sys_exit events were attached, after this fix they are not anymore.
Use the following command to verify:
`sudo bpftool link`
> fix: Prevent loading syscall-specific BPF programs for non-syscall events

- go.mod
- go.sum
- pkg/cmd/tracee.go
- pkg/ebpf/tracee.go
12c4a512a **chore: release bpf object memory**
```
These are the two references to the BPF object read from the file. Both
need to be set to nil for the Go garbage collector to reclaim the
memory.
```
To observe a real change in RSS, it's necessary to run Tracee with `GOGC=5` to trigger the GC cycle more frequently. This approach allows for a clearer view of the improvement in RSS size.
`sudo env GOGC=5 ./dist/tracee --events kill`
RSS size before this commit:
```
ps -p `pgrep tracee` -o pid,vsz,rss,cmd
PID    VSZ   RSS CMD
29655 2269948 101512 ./dist/tracee --events kill
```
RSS size in this commit:
```
ps -p `pgrep tracee` -o pid,vsz,rss,cmd
PID    VSZ   RSS CMD
26268 2265800 87796 ./dist/tracee --events kill
```
With this chore, we achieve around a 14MB reduction in RSS, which …
> chore: release bpf object memory

- pkg/ebpf/c/common/probes.h
Generic kretprobe macro was not updated with recent changes.
Update the macro to fix it.
> fix: TRACE_RET_FUNC macro

- pkg/events/parsers/data_parsers.go
- pkg/events/parsers/data_parsers_bench_test.go
- pkg/events/parsers/data_parsers_test.go
ae857dafa **chore(parsers): optimize ParseMmapProt**
```
Refactor ParseMmapProt to use mmapProtArgs slice.
- Introduced mmapProtArgs slice for cleaner and more maintainable code.
- Replaced multiple if statements with a loop and string builder.
- Improved performance: reduced allocs/op from 17 to 15, and B/op from
392 to 352.
- Execution time slightly improved from 1603 ns/op to 1536 ns/op
(benchmark file used included).
- Reduced function size from 1534 to 677 bytes (55.8% less), what
should improve locality and reduce cache misses.
```
> chore(parsers): optimize ParseMmapProt

- pkg/events/parse_args.go
- pkg/events/parse_args_bench_test.go
- pkg/events/parse_args_test.go
8d86c0c5d **chore(events): optimize ParseArgs for uintptr conv**
d4144ae50 **chore(events): improve flag parsing performance**
8d86c0c5d **chore(events): optimize ParseArgs for uintptr conv**
```
- Improved execution time by 20.78% and reduced byte operations by 55%.
- Changed loop to iterate by index for direct modification of
argument values instead of iterating again via SetArgValue.
- Replaced string concatenation with strconv.AppendUint for efficient
string construction.
Running tool: /home/gg/.goenv/versions/1.22.4/bin/go test -benchmem
-run=^$ -tags ebpf
-bench ^(BenchmarkParseArgs_Uintptr|BenchmarkParseArgs_Old)$
github.com/aquasecurity/tracee/pkg/events -benchtime=10000000x -race
goos: linux
goarch: amd64
pkg: github.com/aquasecurity/tracee/pkg/events
cpu: AMD Ryzen 9 7950X …
```
> improve flag parsing performance

- pkg/signatures/benchmark/benchmark_test.go
0d193c0bc **fix: set engine to nil - sig benchmark**
```
In order to avoid engine leak, set engine to nil and force GC.
```
Thanks to @geyslan for spotting the Engine leak in every benchmark iteration. When a large benchtime value is used, the tasks get stuck.
> fix: set engine to nil - sig benchmark

- pkg/ebpf/c/common/arch.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/task.h
- pkg/ebpf/c/vmlinux.h
Thanks @oshaked1 for writing this commit!
Tracee's `get_task_pt_regs` function mimics the logic of this helper, but relies on assuming some values defined in the kernel. This commit changes this function to use the helper if it is available. This helper must receive a task_struct with BTF info obtained from `bpf_get_current_task_btf`. From my experimentation, the verifier cannot determine whether a task_struct contains BTF info if it was stored outside of the stack. This means that this function cannot acutally retrieve the registers of any task except for the current one. The function name was changed to reflect this requirement, and it no longer receives a task_struct as a parameter.
./tracee
Closes #4239
> feat(ebpf): use bpf_task_pt_regs when available

- pkg/ebpf/c/common/probes.h
Add macros and functions to streamline syscall argument extraction in Tracee, supporting various architectures and syscall wrapping scenarios. Also enhance the TRACE_SYS_* macros for easier system call tracing.
> feat: add syscall helper macros

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/core.go
make security_socket_setsockopt not rely on sys_enter/exit
./tracee -e=security_socket_setsockopt
> feat(ebpf): make security_socket_setsockopt not rely on sys_enter/exit

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/core.go
make security_socket_accept not rely on sys_enter/exit
./tracee -e=security_socket_accept
Closes #4214
> feat(ebpf): make security_socket_accept not rely on sys_enter/exit

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/core.go
make mem_prot_alert not rely on sys_enter/exit
./tracee -e=mem_prot_alert
> feat(ebpf): make mem_prot_alert not rely on sys_enter/exit

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/core.go
make security_socket_bind not rely on sys_enter/exit
./tracee -e=security_socket_bind
> feat(ebpf): make security_socket_bind not rely on sys_enter/exit

- .github/actions/build-dependencies/action.yaml
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
b97098231 **chore: pin go tools versions**
> chore: pin go tools versions

- pkg/signatures/benchmark/benchmark_test.go
- pkg/signatures/benchmark/helpers_test.go
- pkg/signatures/benchmark/signature/golang/performance_static.go
cf550d1d3 **perf: benchmark improve sig GetMetadata**
```
In the signature interface, the GetMetadata method is frequently called.
Currently, every time the method is called, memory is allocated for
metadata. Two alternative methods were evaluated: using metadata 1) with
sync.Once and 2) statically.
```
> GOOS=linux CC=clang GOARCH=arm64 CGO_CFLAGS="-I/vagrant/dist/libbpf -I/vagrant/3rdparty/libbpf/include/uapi" CGO_LDFLAGS="-L/vagrant/dist/libbpf/obj -lbpf " go test -benchmem -run=^$ -bench ^BenchmarkEngineMultipleMethodsGetMetadata$ github.com/aquasecurity/tracee/pkg/signatures/benchmark -benchtime=10000x
```
current_method           	    10000            696962 ns/op          581334 B/op       5012 allocs/op
method_1_(sync.once)     	    10000            577382 ns/op          213181 …
```
> perf: benchmark improve sig GetMetadata

- .github/workflows/pr.yaml
- tests/e2e-inst-signatures/scripts/containers_data_source.sh
Close: #4248
69f4e4ec3 **chore: specify local Ubuntu version for consistency**
3f38168ab **chore: update AMI matrix images**
```
- Disable the ./test/e2e-install-deps.sh script as the AMIs are
already updated.
```
Thank you @geyslan for the help during this task.
> chore: update AMI matrix images

- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/types.h
cf34d1f4 **chore: improve save_args_to_submit_buf**
```
This replaces the switch case branches for a direct access to a type
size table and uses bitmasking to decide about the code path to take.
Improvements:
| dist/tracee.bpf.o     | Before (B) | After (B) | Diff (B) | (%)     |
|-----------------------|------------|-----------|----------|---------|
| Size in Bytes         | 14118048   | 14098024  | -20024   | -0.14%  |
| sys_exit_submit       | Before (B) | After (B) | Diff (B) | (%)     |
|-----------------------|------------|-----------|----------|---------|
| Interpr Size (xlated) | 25248      | 19200     | -6048    | -23.96% |
| JITed Size (jited)    | 16600      | 12161     | -4439    | -26.73% |
| Memlock               | 28672      | 20480     | -8192    | -28.57% |
| Metric (1k …
```
> Improve `save_args_to_submit_buf`

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/core.go
add path&ctime to module_load event
./tracee -e=module_load
> feat(ebpf): add path&ctime to module_load event

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/core.go
Use task registers to extract `argv` and `envp` instead of getting them from sys_enter.
> process_execute_failed: don't rely on sys_enter

- pkg/ebpf/c/common/arch.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/common/probes.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/probes/arch_amd64.go
- pkg/ebpf/probes/arch_arm64.go
- pkg/ebpf/probes/probe_group.go
- pkg/ebpf/probes/probes.go
- pkg/ebpf/probes/trace.go
- pkg/events/core.go
feat: Add syscall kprobe support
We currently use sys_enter/sys_exit tracepoints to trace syscalls.
These impact performance on hot paths.
This change introduces BPF program attachment to syscall entry/exit using kprobes,
offering a more efficient mechanism. 
It handles varying symbol prefixes across architectures and includes 32-bit compat support.
Close #4211
> Generic syscall kprobes

- docs/docs/advanced/data-sources/builtin/process-tree.md
- docs/docs/install/config/index.md
- docs/docs/policies/usage/cli.md
- examples/config/global_config.yaml
- pkg/cmd/cobra/config.go
- pkg/cmd/cobra/config_test.go
- pkg/cmd/flags/proctree.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_bench_test.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_test.go
4b896202e **fix: create a new fresh string for comm**
cb89e2f9f **perf: use proctree expirable lru cache**
976704fcf **perf: remove mutex, add concurrency tests**
36ca022df **chore: benchmark proctree**
4b896202e **fix: create a new fresh string for comm**
```
comm had the same inner address as the original string which it was
created from (basename). This caused the original underlying bytes to
be preserved and not garbage collected.
Converting it to a byte slice and then back to a string guarantees that
a new string is created releasing the original reference.
```
cb89e2f9f **perf: use proctree expirable lru cache**
```
hashicorp LRU increases RSS over time. This change uses the proctree
lru cache to an expirable one, which will remove entries after a
certain time.
Two flags/options …
```
> Proctree improvements (RSS/Performance)

- pkg/events/parsers/data_parsers.go
- pkg/events/parsers/data_parsers_bench_test.go
- pkg/events/parsers/data_parsers_test.go
d7fa48d0e **chore(parsers): add optionIsContainedInArgument**
c830bf91e **chore(parsers): opti optionsAreContainedInArgument**
b15d55997 **chore(parsers): impr OptionsAreContainedInArgument**
d7fa48d0e **chore(parsers): add optionIsContainedInArgument**
```
Currently all usages of the `optionsAreContainedInArgument` function
are using only one option. Then, `optionIsContainedInArgument` comes as
a simplification of the previous function.
Even though `optionsAreContainedInArgument` is not used anymore, it is
still being kept for now, since some parser might need to check for
multiple options in the future.
=== RUN   Benchmark_optionsAreContainedInArgumentWithOnlyOne
Benchmark_optionsAreContainedInArgumentWithOnlyOne
Benchmark_optionsAreContainedInArgumentWithOnlyOne-32            5000000 …
```
> optimize parser options check

- pkg/changelog/changelog.go
- pkg/changelog/changelog_benchmark_test.go
- pkg/changelog/changelog_test.go
8cee7a26f **perf(changelog): optimize enforceSizeBoundary**
3bc61a882 **chore(changelog): avoid unnecessary initialization**
8cee7a26f **perf(changelog): optimize enforceSizeBoundary**
```
These optimizations make the enforceSizeBoundary function more
efficient across various scenarios, leading to overall better
performance while maintaining the same behaviour (*).
Running tool: /home/gg/.goenv/versions/1.22.4/bin/go test -benchmem
-run=^$ -tags ebpf
-bench ^(BenchmarkEnforceSizeBoundaryOld|BenchmarkEnforceSizeBoundary)$
github.com/aquasecurity/tracee/pkg/changelog -benchtime=100000000x
goos: linux
goarch: amd64
pkg: github.com/aquasecurity/tracee/pkg/changelog
cpu: AMD Ryzen 9 7950X 16-Core Processor
| Test Case              | Old (ns/op) | New (ns/op) |   (%)  | …
```
> Changelog optimization

- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_bench_test.go
- pkg/bufferdecoder/eventsreader_test.go
Close: #4081 
28ec9535a **fix: improve performance of readStringVarFromBuff**
```
Optimize readStringVarFromBuff for better performance and memory usage.
- The optimizations were tested using new benchmarks:
- Short: 33.26% faster, 42.86% less memory usage, 1 fewer allocation.
- Medium: 28.34% faster, 54.55% less memory usage, 1 fewer allocation.
- Long: 26.90% faster, 73.42% less memory usage, 3 fewer allocations.
- Long: with Low Max: 19.12% faster, 48.15% less memory usage, 1 fewer
allocation.
The overall improvements show significant gains in both execution speed
and memory efficiency. For more check eventsreader_bench_test.go.
Changes:
- Preallocated the buffer with a reasonable initial capacity to avoid
repeated slice resizing.
- Removed TrimLeft call since conversion logic already …
```
> fix: improve performance of readStringVarFromBuff

- pkg/events/parse_args.go
- pkg/events/parse_args_bench_test.go
- pkg/events/parse_args_helpers.go
3adc191b0 **chore(events): parseSyscall with no lock**
```
Bypass the lock contention accessing the read-only map directly.
```
115a85c86 **chore(events): reduce ParseArgs complexity**
```
This reduces the complexity of the ParseArgs function by extracting
different parts of it into separate helpers. This makes the code
easier to read and understand and also makes it smaller.
Before:
1a080c0      14863 T github.com/aquasecurity/tracee/pkg/events.ParseArgs
After:
1a0cee0      11632 T github.com/aquasecurity/tracee/pkg/events.ParseArgs
It's a reduction of 21.73% in the size of the function what should also
improve cache locality and performance.
The benchmark tests also show a significant improvement in performance,
with a reduction of 6.4% in the time it takes to parse the arguments. …
```
> improve flag parsing performance continuation

- .gitignore
- Makefile
Close: #4253
9d4e5855e **fix(build): parallel build (libbpf wise)**
```
When running with -j option, the build was emitting bogus messages
related to the lack of libbpf.a. A variable was being evaluated out of
a rule and respective requirements were not being met.
```
> fix(build): parallel build (libbpf wise)

- .gitignore
- Makefile
a17f7ef6e **fix(build): cyclic dependency in makefile**
```
$(GOENV_MK) is a body level include, so using it as a prerequisite and
as a target dependency caused a cyclic dependency.
Use .eval_goenv rule (and placeholder file) to evaluate variables to be
stored in goenv.mk and use the placeholder as a prerequisite for the
targets that need the goenv.mk content.
```
> fix(build): cyclic dependency in makefile

- .gitignore
- Makefile
02adacf5c **fix(build): cyclic dependency in makefile**
```
$(GOENV_MK) is a body level include, so using it as a prerequisite and
as a target dependency caused a cyclic dependency.
Use .eval_goenv rule (and placeholder file) to evaluate variables to be
stored in goenv.mk and use the placeholder as a prerequisite for the
targets that need the goenv.mk content.
commit: dd763f4 (main), cherry-pick
```
> [v0.22.0] fix(build): cyclic dependency in makefile

- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.alpine-tracee-make
Close: #4270 
9e9852f54 **fix(build): set GOTOOLCHAIN="auto" for alpine**
```
This also refactors Dockerfile.alpine-tracee-make splitting it in stages
to improve caching and reduce image size.
Oportunistically, this also changes the previous and
Dockerfile.alpine-tracee-container to use TARGETARCH docker arg instead
of checking uname -m.
```
> fix(build): set `GOTOOLCHAIN="auto"` for alpine

- pkg/events/derive/process_execute_failed.go
- use the correct LRU (base events)
- remove unused LRU
fix: process_execute_failed use correct lru
- use the correct LRU (base events)
- remove unused LRU
> fix: process_execute_failed use correct lru

- pkg/ebpf/processor.go
- pkg/ebpf/processor_funcs.go
Uprobe events are created with the context of tracee's process, even though it is irrelevant for the event.
This PR removes such irrelevant context from the appropriate events, by resetting all context information.
This cloes #4285.
Generate any uprobe based event (e.g. hidden_kernel_module) and see how all context information is empty.
> Remove irrelevant context from uprobe based events

- pkg/containers/containers.go
- pkg/containers/runtime/containerd.go
- pkg/ebpf/controlplane/cgroups.go
- pkg/ebpf/events_enrich.go
49079a0 **feat(enrich): improve containerd image info enrich**
```
Make the image info query in containerd enrichment more robust.
Procedure now begins by first querying the containerd image service,
and only then using the cri directly as a fallback.
Additionally, fix a typo in the CRI query which appended the image name
as its digest, even when found.
```
cb72aed96 **fix(enrich): silence noncontainer cgroup errors**
```
In case enrichment is requested on a non container cgroup, return the
metadata struct with an empty container id instead. User is responsible
for handling this "not-found" case by themselves.
Apply this in locations where enrichment is called (pipeline and control
plane).
```
Deploy tracee on a containerd emv
Enrichment should work as usual
Digests should appear …
> container enrichment fixes and improvements

- pkg/events/core_amd64.go
- pkg/events/core_arm64.go
f1e531f75 **update syscall table: lookup_dcookie is removed**
```
Kernels 6.7 and above does not have lookup_dcookie syscall anymore
commit: 34238f1 (main), cherry-pick
```
> [v0.21.1] update syscall table: lookup_dcookie is removed

- pkg/containers/containers.go
- pkg/containers/runtime/containerd.go
- pkg/ebpf/controlplane/cgroups.go
- pkg/ebpf/events_enrich.go
3f810f7c7 **feat(enrich): improve containerd image info enrich**
```
Make the image info query in containerd enrichment more robust.
Procedure now begins by first querying the containerd image service,
and only then using the cri directly as a fallback.
Additionally, fix a typo in the CRI query which appended the image name
as its digest, even when found.
commit: 126133a (main), cherry-pick
```
8b74d3959 **fix(enrich): silence noncontainer cgroup errors**
```
In case enrichment is requested on a non container cgroup, return the
metadata struct with an empty container id instead. User is responsible
for handling this "not-found" case by themselves.
Apply this in locations where enrichment is called (pipeline and control
plane).
commit: e4215bd (main), cherry-pick
```
> [v0.22.1] container enrichment fixes and improvements

- docs/docs/install/config/index.md
- docs/docs/policies/usage/cli.md
- examples/config/global_config.yaml
- pkg/cmd/cobra/config.go
- pkg/cmd/cobra/config_test.go
- pkg/cmd/flags/proctree.go
- pkg/proctree/proctree.go
af231a69c **chore!: rollback proctree to simple LRU**
```
The expirable LRU cache is not intended to be used in the ProcessTree
type since the TTL would impact its correctness on some scenarios.
Despite TTL can be disabled by setting it to 0, it is not a good idea
due to the potential performance impact of its implementation. See the
comparison between the simple LRU and the expirable LRU below:
| Benchmark                              | Exp LRU |  Simple |    %   |
|                                        |  TTL 0  |   LRU   |  Impr. |
|                                        | (ns/op) | (ns/op) |    *   |
|----------------------------------------|---------|---------|--------|
| GetProcessByHash-Concurrency1          | 4.264   | 6.301   | -47.8% |
| GetProcessByHash-Concurrency2 …
```
> chore!: rollback proctree to simple LRU

- pkg/ebpf/c/common/buffer.h
Closes #4300 
Fix an off-by-one bounds check on an argument type array that resulted in `timespec_t` args not being submitted.
Run `tracee -e nanosleep,clock_nanosleep -s comm=sleep`, run `sleep 1` in the background and see if `request` and `remain` args are `nil` or have a value.
> Fix `timespec_t` args not being submitted to userspace

- pkg/cmd/cobra/cobra.go
- pkg/cmd/urfave/urfave.go
- pkg/config/config.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/hidden_kernel_module.go
- pkg/ebpf/hooked_syscall_table.go
- pkg/ebpf/ksymbols.go
- pkg/ebpf/processor_funcs.go
- pkg/ebpf/signature_engine.go
- pkg/ebpf/tracee.go
- pkg/events/definition_group.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_collision_test.go
- pkg/events/derive/symbols_loaded.go
- pkg/policy/ebpf.go
- pkg/policy/event_flags.go
- pkg/policy/policy_manager.go
- pkg/policy/policy_manager_test.go
- tests/integration/dependencies_test.go
- tests/integration/event_filters_test.go
4dfd7da92 **chore: inject deps manager into policy manager**
9aff9d2bb **chore(policy): introduce ManagerConfig**
443869ea7 **fix: validateKallsymsDependencies() nil deref**
4dfd7da92 **chore: inject deps manager into policy manager**
```
It makes the access to event flags be done through the policy manager,
which is responsible for setting up the dependencies manager.
This also:
- Turn the event flags access thread-safe.
- Renames manager and config types.
- Fix t.eventSignatures[eventId] logic, now accessible via policy
manager IsRequiredBySignature(), since the former was only flagging
the event as signature, but not as required by one.
```
This is a enabler for https://github.com/aquasecurity/tracee/issues/3987.
> Events flags embedding

- pkg/ebpf/processor_funcs.go
Currently, as part of capturing executed files, tracee tries to copy the file. In case the copy fails, tracee drops the event. This patch changes the behavior to log a debug message and continue the normal flow.
sched_process_exec: don't drop event in capture exec
./tracee -e=sched_process_exec -c exec
> sched_process_exec: don't drop event in capture exec

- tests/testutils/exec.go
Close: #4281 
6ce01b595 **fix(tests): possible goroutine leak**
```
Fix a possible goroutine leak in ExecCmdBgWithSudoAndCtx().
```
> fix(tests): possible goroutine leak

- tests/testutils/tracee.go
Continuation of https://github.com/aquasecurity/tracee/pull/4306.
The use of t.Fatal hid the real issue of timeout. In the future this should be managed to   rollback test execution gracefully and fail without fatal.
> chore(tests): increase Tracee startup timeout

- signatures/helpers/helpers.go
Reverts aquasecurity/tracee#4317
Since we are not going to use `CloneMetadataProperties` anymore, this PR should be reverted.
> Revert "chore: sig helper clone metadata"

- pkg/ebpf/signature_engine.go
5ee8cafcf **fix(ebpf): set pipeline chan size from config**
```
Make all pipeline channels have the size set from the config option.
```
> fix(ebpf): set pipeline chan size from config

- types/trace/trace.go
Requirement for https://github.com/aquasecurity/tracee/pull/4336
d40bc1f81 **chore(types): add Zero field to ArgMeta**
```
This is field for internal use which holds the zero value
of ArgMeta.Type.
```
> chore(types): add Zero field to ArgMeta

- go.mod
- go.sum
- pkg/bufferdecoder/decoder.go
- pkg/events/core.go
- pkg/events/definition_group.go
- pkg/events/parse/params.go
- signatures/helpers/go.mod
- signatures/helpers/go.sum
Close: #4335
2f31471ef **fix(events): setuid16 arg name typo**
473762535 **fix: handle zero-value types for unavailable fields**
41eeb29f2 **chore(go.mod): bump types to latest version**
2f31471ef **fix(events): setuid16 arg name typo**
```
'git log --grep old_old_uid_t' in Linux kernel code didn't return any
results.
```
473762535 **fix: handle zero-value types for unavailable fields**
```
Some event arguments, such as "interpreter_*" from sched_process_exec,
were not being populated because the kernel might not always provide
them. This was causing errors during the gRPC proto conversion, as
the values couldn't be asserted - they were nil.
With this change, ArgMeta now holds the Zero value of the type, ensuring
that assignment is always possible without requiring additional parsing
in …
```
> Handle zero-value types for unavailable fields - ArgMeta

- pkg/ebpf/processor.go
- pkg/ebpf/processor_funcs.go
Close: #4330
0b35baa4d **fix(ebpf): register processor conditionally**
```
Register SchedProcessFork processors, including normalizeTimeArg,
only if proctree is enabled.
```
206e16072 **fix(ebpf): try to assert only when it is not nil**
```
The normalizeTimeArg function was not checking if the value was nil
before asserting it as an uint64.
This also adds the type to the error message.
```
`sudo ./dist/tracee -e sched_process_fork`
`sudo ./dist/tracee --proctree source=both -e sched_process_fork` to have related args filled.
> register normalizeTimeArg processor only when proctree is on

- docs/docs/install/config/index.md
- docs/docs/policies/usage/cli.md
- examples/config/global_config.yaml
- pkg/cmd/cobra/config.go
- pkg/cmd/cobra/config_test.go
- pkg/cmd/flags/proctree.go
- pkg/proctree/proctree.go
d7083d7ce **chore!: rollback proctree to simple LRU (#4299)**
```
The expirable LRU cache is not intended to be used in the ProcessTree
type since the TTL would impact its correctness on some scenarios.
Despite TTL can be disabled by setting it to 0, it is not a good idea
due to the potential performance impact of its implementation. See the
comparison between the simple LRU and the expirable LRU below:
| Benchmark                              | Exp LRU |  Simple |    %   |
|                                        |  TTL 0  |   LRU   |  Impr. |
|                                        | (ns/op) | (ns/op) |    *   |
|----------------------------------------|---------|---------|--------|
| GetProcessByHash-Concurrency1          | 4.264   | 6.301   | -47.8% |
| GetProcessByHash-Concurrency2 …
```
> [v0.22.3] chore!: rollback proctree to simple LRU (#4299)

- pkg/events/core.go
- pkg/events/parse/params.go
7eafda0b2 **fix(core): ctx_id* types of io_* events typo**
```
io_destroy, io_getevents, io_submit and io_cancel were using an
inexistent type for ctx_id.
The same for io_setup's ctx_idp parameter.
```
2a3f0dd4c **fix(parse): correct types sizes**
```
This considers the size of the types based on vmlinux.h.
```
> Fix arg zero parse types and core typo

- pkg/server/grpc/event_data.go
dad7dae43 **fix: print err when parseArgument() fails**
```
When parseArgument() fails, error message should be printed to help
debugging.
```
> fix: print err when parseArgument() fails

- pkg/ebpf/c/tracee.bpf.c
f0c672d20 **feat(ebpf): restrict set_fs_pwd to (f)chdir syscall (#4359)**
```
commit: ab6344f (main), cherry-pick
```
> [v0.22.3] feat(ebpf): restrict set_fs_pwd to (f)chdir syscall (#4359)

- pkg/ebpf/hooked_syscall_table.go
When unable to locate a syscall symbol, instead of printing an error and terminate the hook checker goroutine, be more graceful: print a warning and skip hook check only for the specific syscall
When unable to locate a syscall symbol, instead of printing an error and terminate the hook checker goroutine, be more graceful: print a warning and skip hook check only for the specific syscall
./tracee -e=hooked_syscall
> feat(events): change log level in hooked_syscall

- pkg/events/derive/hidden_kernel_module.go
On startup, there could be a case where a kernel module is being loaded before the hidden kernel module initialization function is called and finished.
On startup, there could be a case where a kernel module is being loaded before the hidden kernel module initialization function is called and finished.
./tracee -e=hidden_kernel_module
> fix(events): check if init finished in hidden kernel module

- docs/docs/policies/rules.md
changed process filter to scope filters
> changed process filter to scope filters

- pkg/mount/mount.go
1. Deploy tracee to an EKS env
2. sh into it with `kubectl exec -it <pod_name> -- /bin/sh`
3. `cat /proc/self/mountinfo`
4. Confirm that an appropriate cgroupfs mount exists for cpuset or cgroup2
5. Importantly, if it is known that the deployed tracee instance has cgroupfs mounted via k8s or docker, there should be no additional mount for the relevant cgroup version (cgroup v2 may still be mounted by tracee in cgroupv1 envs)
6. `ls` that cgroupfs folder and confirm that `kubepods.slice` exists and other pods are visible
7. Optionally: check the debug logs at tracee's startup for info on the mount object and confirm it aligns with expected result per the environment.
Resolve #4311
> fix(mount): reintroduce root path requirement

- cmd/tracee/cmd/analyze.go
- cmd/tracee/cmd/list.go
- pkg/cmd/cobra/cobra.go
- pkg/cmd/initialize/sigs/sigs.go
- pkg/cmd/initialize/sigs/sigs_test.go
- pkg/ebpf/signature_engine.go
- pkg/events/findings/findings.go
- pkg/events/findings/findings_test.go
- pkg/signatures/engine/engine.go
df567ebc7 **fix(analyze): enable sigs consuming sigs**
ad56d06f8 **fix(findings): clone properties before rewriting**
84ceba74a **chore: move finding event conversion to a package**
3b3299707 **chore: decouple sig init from init**
df567ebc7 **fix(analyze): enable sigs consuming sigs**
```
Signatures consuming other signatures relied on the single binary
reprocessing finding events into the pipeline. This did not occur in
analyze mode. Introduce that mechanism so that it now works.
Co-authored-by: Asaf Eitani <asaf.eitani@aquasec.com>
```
84ceba74a **chore: move finding event conversion to a package**
```
Opportunistic refactor. Logic does not relate to eBPF and does relate to
event data. Also allows importing this logic without importing eBPF
related code.
```
3b3299707 **chore: decouple …
> analyze: enable sigs consuming sigs

- cmd/tracee/cmd/analyze.go
- pkg/signatures/engine/engine.go
1. Findings were previously wrongly fedback to the engine even after an error in converting to events. This issue was resolved.
2. Finding feedbacks in general are now restricted by the engine config being set to single-binary mode (which now logically includes analyze mode).
tracee-rules shouldn't crash or emit errors when using a signature plugin that relies on signature feedback. The signature will not work.
In analyze the signature will work just as before.
> fix(engine): restrict finding feedback

- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/filters/binary.go
- pkg/filters/bool.go
- pkg/filters/bool_test.go
- pkg/filters/processtree.go
- pkg/filters/processtree_test.go
- pkg/filters/string.go
- pkg/filters/string_test.go
- pkg/filters/uint.go
- pkg/policy/ebpf.go
- pkg/policy/equality.go
> Refactor filter matching

- pkg/ebpf/c/capture_filtering.h
- pkg/ebpf/c/common/common.h
- pkg/ebpf/c/tracee.bpf.c
Closes #4395 
There are 2 implementations for `has_prefix()`, one as a macro and one as a function (depending on the compiler version). They both behave differently in cases where no difference was found in `n` iterations - the macro returns 1 (true), which is an issue if the prefix is longer than `n`, while the function returns 0 (false) which is wrong if the prefix and string are identical. An additional check was added to `has_prefix()` to account for prefixes longer than `n`, while still returning true when the strings are equal.
Additionally, an `strncmp()` macro and function were added, because most uses of `has_prefix()` become clearer when using `strncmp()`.
Only a single usage of `has_prefix()` (in `filter_file_path()`) cannot use `strncmp()` because the prefix length can only be …
> fix(epbf): fix behavior of `has_prefix() ` and add `strncmp()`

- pkg/events/core.go
- signatures/golang/illegitimate_shell.go
- signatures/golang/illegitimate_shell_test.go
- signatures/golang/kernel_module_loading.go
- signatures/golang/kernel_module_loading_test.go
This PR removes the dependency of the default event set on sys_enter/sys_exit probes to improve performance when no specific event is selected.
To do that, update default event set and signatures that were depend on events that used these probes.
> perf: remove sys_enter/exit dependency from default event set

- signatures/helpers/helpers.go
def5b4582 **feat(helpers): net_packet_http request/response**
```
- Add `GetProtoHTTPRequestByName` to get http request header from the
event `net_packet_http_request`;
- Add `GetProtoHTTPResponseByName` to get http response header from the
event `net_packet_http_response`;
```
Signature helpers function necessary for https://github.com/aquasecurity/tracee/pull/4354.
> feat(helpers): GetProtoHTTPRequestByName/GetProtoHTTPResponseByName

- pkg/bufferdecoder/decoder.go
- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_test.go
- pkg/cmd/gptdocs.go
- pkg/cmd/initialize/sigs/sigs_test.go
- pkg/cmd/list.go
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/types.h
- pkg/ebpf/controlplane/signal.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/events/definition.go
- pkg/events/definition_group.go
- pkg/events/derive/derive.go
- pkg/events/derive/derive_test.go
- pkg/events/derive/process_execute_failed.go
- pkg/events/ftrace.go
- pkg/events/usermode.go
- pkg/filters/data.go
- pkg/policy/ebpf.go
- pkg/policy/policy_manager.go
- pkg/policy/v1beta1/policy_file.go
This PR renames the `parameters` field in event definitions to `fields`. This change reflects the evolving nature of Tracee, which now supports various event types beyond just syscalls.
The term "fields" more accurately describes the structured data within events, aligning with the concept of event schemas and the `data` section in the new event structure.
This renaming also avoids future confusion with the planned introduction of "event parameters," which will be configurable settings for modifying event behavior.
> refactor: Rename event parameters to fields

- go.mod
- go.sum
- pkg/server/grpc/event_data.go
- pkg/server/grpc/event_data_test.go
- pkg/server/grpc/tracee.go
- pkg/server/grpc/tracee_test.go
0f3a94c1b **chore(grpc): bump api to latest 715b629**
```
It also updates grpc proto conversion functions to use the new api.
```
> chore(grpc): bump api to latest 715b629

- Makefile
- go.mod
- go.sum
- performance/dashboard/docker-compose.yml
- performance/dashboard/provisioning/dashboards/tracee.json
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/perf_count.go
- pkg/ebpf/tracee.go
- pkg/metrics/collector.go
- pkg/metrics/event_collector.go
- pkg/metrics/stats.go
- pkg/server/grpc/diagnostic.go
- pkg/version/version.go
bae153278 **chore(performance): update tracee dashboard**
5a5c2e7ce **chore: add perfbuf metric per event (METRICS=1)**
5fe36d177 **chore(go.mod): bump api to latest 1f796cb**
5a5c2e7ce **chore: add perfbuf metric per event (METRICS=1)**
```
Enabled only when built with METRICS=1.
BPFPerfEventSubmitAttemptsCount and BPFPerfEventSubmitFailuresCount
count the number of events processed by the eBPF programs and written to
or attempted to be written to the perf buffer.
It is incremented right after the attempt of writing the event to the
perf buffer, making it possible to measure if the that event was
successfully written to the perf buffer or not.
This metric can be used to monitor the performance of individual eBPF
events and to detect potential bottlenecks.
```
`METRICS=1 make tracee` …
> Perf event writes metric

- tests/integration/event_filters_test.go
Close: #4255
5cf2d9d1b **fix(tests): use ExpectAtLeastOneForEach**
```
Two test cases were using ExpectAllInOrderSequentially helper function
and passing by luck, since they emit more events than expected only
beyond the expected events boundary.
For that cases we should use ExpectAtLeastOneForEach helper function
instead.
```
34be7e038 **fix(tests): possible out of range in integration**
```
ExpectAllInOrderSequentially might try to access an index out of range
depending on the number of events that are being checked.
More about in issue #4255.
``` in issue #4255.
```
> fix(tests): possible out of range in integration

- .github/workflows/pr.yaml
- go.mod
- go.sum
- tests/e2e-net-signatures/e2e-httprequest.go
- tests/e2e-net-signatures/e2e-httpresponse.go
- tests/e2e-net-signatures/export.go
- tests/e2e-net-signatures/scripts/httprequest.sh
- tests/e2e-net-signatures/scripts/httpresponse.sh
fix: #4346
f457c2bf6 **feat(test): e2e integration test for new helpers**
1. Duplicate the http.go signature file.
2. Update the event to `net_packet_http_request` or `net_packet_http_response`.
3. Use the appropriate helper: `GetProtoHTTPRequestByName` or `GetProtoHTTPResponseByName`.
> feat(test): e2e integration test for new helpers

- cmd/tracee/cmd/analyze.go
- pkg/analyze/analyze.go
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/output.go
- pkg/cmd/flags/tracee_ebpf_output.go
a4037e228 **feat(analyze): add legacy output**
97f335a2b **feat(analyze): implement printer outputs**
3a372d0de **chore(analyze): move analyze to pkg**
72b0427ef **chore(output): split printer config procedure**
a4037e228 **feat(analyze): add legacy output**
```
Add output format for flag marked as "legacy". The output will be the
same format as given for findings in the rawjson.tmpl template in
tracee-rules.
```
97f335a2b **feat(analyze): implement printer outputs**
```
Add rudimentary support to more complex outputs via tracee printers.
```
Resolve #4369
> Analyze legacy output

- .github/actions/build-dependencies/action.yaml
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- builder/Makefile.checkers
Close: #4416 
9b8d817ee **fix(build): fix build checkers for goimports**
```
It also align goimports version to v3.8.2 in different environments.
```
> fix(build): fix build checkers for goimports

- Makefile
- go.mod
- go.sum
- performance/dashboard/docker-compose.yml
- performance/dashboard/provisioning/dashboards/tracee.json
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/perf_count.go
- pkg/ebpf/tracee.go
- pkg/metrics/collector.go
- pkg/metrics/event_collector.go
- pkg/metrics/stats.go
- pkg/server/grpc/diagnostic.go
- pkg/version/version.go
32721cfde **chore(performance): update tracee dashboard**
```
commit: bae1532 (main), cherry-pick
```
09df0991b **chore: add perfbuf metric per event (METRICS=1)**
```
Enabled only when built with METRICS=1.
BPFPerfEventSubmitAttemptsCount and BPFPerfEventSubmitFailuresCount
count the number of events processed by the eBPF programs and written to
or attempted to be written to the perf buffer.
It is incremented right after the attempt of writing the event to the
perf buffer, making it possible to measure if the that event was
successfully written to the perf buffer or not.
This metric can be used to monitor the performance of individual eBPF
events and to detect potential bottlenecks.
commit: 5a5c2e7 (main), backport
[backport]
- changed countPerfEventSubmissions to use eventsState.
``` …
> [v0.22.5] Perf event writes metric

- pkg/ebpf/c/tracee.bpf.c
The sys_enter raw tracepoint always provides direct access to pt_regs,
regardless of the architecture's use of a syscall wrapper. This PR removes
the redundant conditional check and simplifies the logic for extracting system
call arguments.
> fix: Remove unnecessary check for syscall wrapper in sys_enter tracepoint

- .github/workflows/pr.yaml
8c14f78d4 **chore(GH): pin ubuntu (22.04) version for gh runners**
```
Currently, ubuntu:latest uses Ubuntu version 24.04, which includes
kernel 6.8. Since Tracee needs to be tested with kernel 6.8, it is
better to pin the version of the Ubuntu runners.
After testing Tracee with kernel 6.8 and confirming that everything
works correctly, this commit can be reverted.
```
> chore(GH): pin ubuntu (22.04) version for gh runners

- .github/workflows/pr.yaml
d4524045e **chore: add kernel 6.8 and 6.10 in matrix images**
```
- Add kernel 6.8 and 6.10, both for x86_64 and aarch64;
- Both kernels are based on Ubuntu 24.04 LTS (codename Noble).
```
> chore: add kernel 6.8 and 6.10 in matrix images

- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- Makefile
- builder/Dockerfile.alpine-tracee-container
- builder/Makefile.release
- builder/Makefile.tracee-container
- builder/Makefile.tracee-make
Close: #4154
Close: #4443
1517687da **chore(ci): use new make snapshot rule**
7e3eab7bb **chore(builder): version format & quicker snapshot**
feca8a5da **fix(builder): avoid static binary clobbering**
1517687da **chore(ci): use new make snapshot rule**
```
This also removes INSTANCE_TYPE from the snapshot workflow, as it is
expected to be not so resource intensive now.
```
7e3eab7bb **chore(builder): version format & quicker snapshot**
```
This changes the version format (details on #4154).
Also, this makes the snapshot (dev daily) building quicker by not
embedding the BTF files in the tracee binaries.
As daily images are not meant for production, this should not be a
problem, also considering that the majority of the contributors are
running latest kernels.
```
`make -f …
> fix release tarball static binaries & make daily building faster

- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/c/vmlinux_flavors.h
b54f498f4 **fix(ebpf): adjust inode struct to kernel v6.11**
```
- Add support for three different ranges of kernel versions.
- For kernel 6.11 and newer, struct inode uses the fields
i_ctime_sec and i_ctime_nsec for time.
- For kernels 6.6 to 6.10, struct inode uses __i_ctime.
- For kernels 6.5 and older, struct inode uses i_ctime.
- Align struct inode to the kernel 6.11 structure and mock
the inode struct for kernels older than 6.11.
```
Thank you, @agalauner-r7, for providing such a detailed issue report and proposing various solutions to address this issue.
fix: #4391
> fix(ebpf): adjust inode struct to kernel v6.11

- tests/integration/event_filters_test.go
ed57c0016 **chore(test): use cat cmd to trigger magic_write event**
```
- On newer kernels, the cp command no longer uses vfs_write. As
a result, using cp to trigger magic_write will not work.
```
> chore(test): use cat cmd to trigger magic_write event

- .github/workflows/pr.yaml
- tests/integration/event_filters_test.go
9e6e4d4fd **chore(test): use more cmd to trigger magic_write event**
e442ebd73 **Revert "chore(GH): pin ubuntu (22.04) version for gh runners"**
e442ebd73 **Revert "chore(GH): pin ubuntu (22.04) version for gh runners"**
```
This reverts commit ad74ef5a637b5c6fd1830b12f58a9cb897643762.
```
The GitHub runner currently uses ubuntu:latest (Ubuntu 24.04 LTS), which includes kernel 6.8. Initially, the version of the Ubuntu runner was pinned because Tracee needed to be tested with kernel 6.8.
After conducting tests on kernel 6.8 and confirming that everything worked as expected, the pinning was reverted.
The reason for pinning and later reverting the version was due to two failing integration tests. These tests relied on the command `cp /etc/netconfig /tmp/netconfig` to generate a `magic_write` …
> chore: pin ubuntu:latest for gh runners / trigger magic_write event

- .github/workflows/pr.yaml
d0cd0a473 **chore: add kernel 6.11 and 6.12 in matrix images**
```
- Add kernel 6.11 and 6.12, both for x86_64 and aarch64;
- Both kernels are based on Ubuntu 24.04 LTS (codename Noble).
```
> chore: add kernel 6.11 and 6.12 in matrix images

- .github/workflows/codeql.yaml
9f92aaf01 **chore(ci): add codeQL as workflow file**
```
- Using CodeQL as a workflow file allows us to customize the
configuration, such as installing the libbpf library.
```
fix: https://github.com/aquasecurity/tracee/issues/4439
> chore(ci): add codeQL as workflow file

- go.mod
- go.sum
35d303a60 **chore(go.mod) bump api to 4cdea40d**
> chore(go.mod) bump api to 4cdea40d

- pkg/events/parse_args_helpers.go
- pkg/events/parse_args_helpers_test.go
- fix issue #3892 
- fix the empty result of failed parse helper argument
- add test to parse_args_helper.go
`make check-pr`:
1cbdc3d1dc **tests: add argument parsers tests**
69d55cbe77 **fix: empty arguments resolution**
69d55cbe77 **fix: empty arguments resolution**
```
When tracee tries to resolve a numeric argument to a string (e.g. cmd value of
bpf syscall), if the resolution fails, the event field will contain an empty
string.
Return the raw value as a string in case of a failed resolution.
```
In order to test you can run the test in the file with this command 
``` bash
GOOS=linux CC=clang GOARCH=amd64 CGO_CFLAGS="-I/tracee/dist/libbpf -I/tracee/3rdparty/libbpf/include/uapi" CGO_LDFLAGS="-L/tracee/dist/libbpf/obj -lbpf" \
go test \
-tags ebpf \
-v \
-short \
-race \ …
```
> fix empty arguments resolution

- docs/man/scope.1
526c4eec5 **fix(man): missing rebuild**
```
Somehow the lack of a rebuild step passed unnoticed by CI. This change
is the result of `make -f builder/Makefile.man man-run`.
```
> fix(man): missing rebuild

- go.mod
- go.sum
- pkg/ebpf/tracee.go
23d8ea16d **chore(go.mod): bump libbpfgo**
16d1e190a **fix: clock time detection**
16d1e190a **fix: clock time detection**
```
- The clock time detection was rework since the libbpfgo func
BPFHelperIsSupported changed;
- Unless it is explicitly marked as unsupported (supported=false),
it will default to BOOTTIME.
```st case the helper is not supported so the monotonic is set.
```
fix: #4505 
Most of the change is located in libbpfgo, but I've inverted the order of the checking since most of the time we support boottime.
What changed and why in the libbpfgo: https://github.com/aquasecurity/libbpfgo/blob/45a155ff1a362156b5c7d1b75bc3db5f8cb5e526/libbpfgo.go#L104-L116
> fix: clock time detection

- go.mod
- go.sum
- pkg/ebpf/tracee.go
cbb258198 **fix: clock time detection**
```
* chore(go.mod): bump libbpfgo
commit: aeca328 (main), backport
[backport]
- point go.mod to libbpfgo branch with the helper fix
* fix: clock time detection
- The clock time detection was rework since the libbpfgo func
BPFHelperIsSupported changed;
- Unless it is explicitly marked as unsupported (supported=false),
it will default to BOOTTIME.
commit: f5cb740 (main), cherry-pick
```
> [v0.22.4-1] fix: clock time detection

- pkg/filters/binary.go
- pkg/filters/data.go
Takes care of some of #4481. 
4bef591ce **fix(filters): int conversion without check**
```
This silences some CodeQL "Incorrect conversion between integer types"
warnings.
```
> fix(filters): int conversion without check

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/event_parameters.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/hooked_syscall_table.go
- pkg/ebpf/ksymbols.go
- pkg/ebpf/probes/trace.go
- pkg/ebpf/processor_funcs.go
- pkg/ebpf/tracee.go
- pkg/events/derive/hooked_seq_ops.go
- pkg/events/derive/hooked_syscall.go
- pkg/utils/environment/kernel_symbols.go
- pkg/utils/environment/kernel_symbols_test.go
- pkg/utils/symbol_table.go
- pkg/utils/symbol_table_test.go
- pkg/utils/utils.go
- tests/e2e-inst-signatures/e2e-set_fs_pwd.go
The previous ksymbols implementation used a lazy lookup method, where only symbols marked as required ahead of time were stored. Trying to lookup a symbol that was not stored resulted in `/proc/kallsyms` being read and parsed in its entirety.
While most symbols being looked up were registered as required ahead of time, some weren't (in particular symbols needed for kprobe attachment) which incurred significant overhead when tracee is being initialized.
This new implementation stores all symbols, or if a `requiredDataSymbolsOnly` flag is used when creating the symbol table (used by default), only non-data symbols are stored (and required data symbols must be registered before updating). Some additional memory usage optimizations are included, for example encoding symbol owners as an index …
> feat(ksymbols): reimplement ksymbols

- signatures/helpers/go.mod
- signatures/helpers/go.sum
- signatures/helpers/helpers.go
This is part of #4541 to make possible to merge #4544.
ed62bef6a **feat(helpers): unparsed flag helpers**
```
flag helpers previously took a string argument to test against possible
flag configurations. New implementation takes the integer form and
makes the test with the bit flag directly.
It makes use of syscall package to get constants for the flags instead
of Tracee's parsers package.
Co-authored-by: Geyslan Gregório <geyslan@gmail.com>
```
> feat(helpers): reapply: unparsed flag helpers

- pkg/ebpf/c/common/memory.h
The previous check resulted in false positives for regular mmap allocations (without explicit address hints), resulting in random test failures for `suspicious_syscall_source` (VMA type was detected as golang heap instead of anonymous).
Continuation of https://github.com/aquasecurity/tracee/pull/4403.
> fix(ebpf): fix insufficiently accurate detection of golang heaps

- pkg/ebpf/events_pipeline.go
- tests/e2e-inst-test.sh
This is an attempt to debug these:
- https://github.com/aquasecurity/tracee/actions/runs/12894481676/job/35953248480#step:4:1186
- https://github.com/aquasecurity/tracee/actions/runs/12916037607/job/36027976370#step:6:526
- https://github.com/aquasecurity/tracee/issues/3878
64a4221c3 **chore: improve e2e and pipeline for debuggability**
> chore: improve e2e and pipeline for debuggability

- pkg/ebpf/event_parameters.go
If an event that uses parameters is enabled but not present in all policies, a nil access occurs and tracee panics. This fix makes sure the event is present in each policy before accessing its parameters.
> fix(events): fix incorrect handling of event parameters

- .github/workflows/pr.yaml
Close: #4560 
3a828b80a **fix(ci): remove runners collision**
```
When more than one PR is opened at the same time, the runners were
colliding with each other, due to identical names.
```
> fix(ci): remove runners collision

- tests/e2e-inst-signatures/scripts/ds_writer/ds_writer.go
Detected while debugging https://github.com/aquasecurity/tracee/actions/runs/12953849577/job/36134460471#step:4:1268
66dbdb4a2 **fix(e2e): treat corner cases in ds_writer.go**
> fix(e2e): treat corner cases in ds_writer.go

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux_missing.h
- pkg/ebpf/events_pipeline.go
Close: #4558
cccaf7f83 **fix(ebpf): treat sched_process_exit corner cases**
```
The sched_process_exit event may be triggered by a standard exit, such
as a syscall, or by alternative kernel paths, making it unsafe to assume
that it is always associated with a syscall exit.
do_exit and do_exit_group, while typically invoked by the exit and
exit_group syscalls, can also be reached through internal kernel
mechanisms such as signal handling. A concrete example of this occurs
when a syscall returns, enters signal handling, and subsequently calls
do_exit after get_signal. Both get_signal and do_exit involve
tracepoints.
A real execution flow illustrating this scenario in the kernel is as
follows:
entry_SYSCALL_64
├── do_syscall_64
├── syscall_exit_to_user_mode
├── …
```
> fix(ebpf): treat sched_process_exit corner case

- pkg/ebpf/processor.go
- pkg/ebpf/processor_funcs.go
- pkg/events/core.go
- pkg/events/parse_args.go
- tests/e2e-inst-signatures/e2e-stack_pivot.go
- tests/e2e-inst-signatures/e2e-suspicious_syscall_source.go
Since signatures now receive unparsed event arguments, conversion of syscall IDs to names became an issue since the signature has no way to know whether the event was generated on an x86_64 or ARM64 system. To solve this, we convert the syscall ID argument to its name at the event processing stage, so it happens regardless of argument parsing. This is applied to the `suspicious_syscall_source` and `stack_pivot` events.
> feat(events): convert syscall arg to name at processing stage

- pkg/ebpf/c/common/task.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/controlplane/processes.go
- pkg/ebpf/controlplane/processes_bench_test.go
- pkg/ebpf/processor_proctree.go
- pkg/ebpf/processor_proctree_bench_test.go
- pkg/events/core.go
- pkg/proctree/proctree_feed.go
- pkg/server/grpc/event_data_test.go
a13d497a4 **fix: get exit code and signal values**
```
When a process exits normally via exit(n), the exit code is
stored in the upper byte (exit_code << 8). The lower byte is
used for signal information if the process was terminated by
a signal.
Also, align the type of exit_code used at struct task_struct.
```
Use the following code to trigger:
```
gcc -o trigger trigger.c
```
```c
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <signal.h>
int main() {
printf("Forking process...\n");
pid_t pid = fork();
if (pid == 0) {
printf("Child process running, PID: %d\n", getpid());
sleep(10);
printf("Child process exiting normally\n");
exit(1);
} else if (pid > 0) {
// Parent process
sleep(1);
printf("Parent sending SIGKILL to child …
```
> fix(ebpf): correct value of exit and signal code for sched_process_exit

- pkg/ebpf/c/common/memory.h
- pkg/ebpf/c/tracee.bpf.c
Identifying thread stacks by a VMA is unreliable because VMA splitting and joining may cause the searched VMA to not align nicely with the thread stack VMA.
Instead, we can identify a thread stack by an address, making the identification straight-forward.
> fix(ebpf): revise thread stack identification logic

- pkg/events/derive/net_tcp.go
- tests/integration/event_filters_test.go
The code attempted to cast "type" as a string, which caused issues when the actual value was of a different type. So this PR changes the type to int32, aligning it with parsers.SOCK_STREAM.Value(), and adds an integration test.
8845c70a1 **test: add test for event net_tcp_connect**
3ff256021 **fix: type parsing net_tcp_connect**
3ff256021 **fix: type parsing net_tcp_connect**
```
The code attempted to cast "type" as a string, which caused issues
when the actual value was of a different type. So this commit changes
the type to int32, aligning it with parsers.SOCK_STREAM.Value().
```
cmd:
```
nc -zv localhost 7777
```
Tracee:
```
sudo ./dist/tracee -e net_tcp_connect
16:12:03:441124 …
```
> Fix: `net_tcp_connect` event

- pkg/changelog/changelog_test.go
- pkg/ebpf/tracee.go
- pkg/filters/binary.go
- pkg/proctree/datasource.go
- pkg/proctree/fileinfo.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_output.go
- pkg/proctree/proctree_procfs.go
- pkg/proctree/taskinfo.go
- pkg/utils/proc/exe.go
- pkg/utils/proc/formatters.go
- pkg/utils/proc/ns.go
- pkg/utils/proc/ns_bench_test.go
- pkg/utils/proc/ns_test.go
- pkg/utils/proc/parsers.go
- pkg/utils/proc/readfile.go
- pkg/utils/proc/readfile_bench_test.go
- pkg/utils/proc/readfile_test.go
- pkg/utils/proc/stat.go
- pkg/utils/proc/stat_bench_test.go
- pkg/utils/proc/stat_test.go
- pkg/utils/proc/status.go
- pkg/utils/proc/status_bench_test.go
- pkg/utils/proc/status_test.go
- pkg/utils/tests/helpers.go
- pkg/utils/utils.go
- tests/integration/tracee.go
Ran these in `main` and `procfs-work` branches:
`dist/tracee --metrics --pyroscope --pprof -s tree=2609608 -e sched_process_exec,sched_process_fork,sched_process_exit --proctree source=both  --proctree disable-procfs -o none`
`dist/tracee --metrics --pyroscope --pprof -s tree=2241901 -e sched_process_exec,sched_process_fork,sched_process_exit --proctree source=both  -o none`
Stressor details:
Details
`8 threads with 1_000_000 ops each` running on:
cpu: AMD Ryzen 9 7950X 16-Core Processor
MemTotal: 64923992 kB (64GB)
```
| Metric        | NO procfs (%) | WITH procfs  (%) |
|---------------|--------------:|-----------------:|
| CPU avg       | -2.65%        | -28.46%          |
| Malloc avg    | -1.56%        | -22.60%          |
| Heap avg      | -1.94%        | +5.65%           |
| Heap …
```
> Procfs improvements

- docs/docs/events/builtin/extra/sched_process_exec.md
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/controlplane/processes.go
- pkg/ebpf/controlplane/processes_bench_test.go
- pkg/ebpf/processor_proctree.go
- pkg/ebpf/processor_proctree_bench_test.go
- pkg/events/core.go
- pkg/proctree/datasource.go
- pkg/proctree/fileinfo.go
- pkg/proctree/fileinfo_test.go
- pkg/proctree/process.go
- pkg/proctree/process_test.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_feed_test.go
- pkg/proctree/proctree_output.go
- pkg/proctree/proctree_procfs.go
- pkg/proctree/taskinfo_test.go
- pkg/proctree/thread.go
- pkg/proctree/thread_test.go
- pkg/utils/proc/ns_test.go
Continuation of https://github.com/aquasecurity/tracee/pull/4540
Close: #4546
Ran these in `main` and `proctree-the-third` branches:
`dist/tracee --metrics --pyroscope --pprof -s tree=2609608 -e sched_process_exec,sched_process_fork,sched_process_exit --proctree source=both  --proctree disable-procfs -o none`
`dist/tracee --metrics --pyroscope --pprof -s tree=2241901 -e sched_process_exec,sched_process_fork,sched_process_exit --proctree source=both  -o none`
Stressor details:
Details
`8 threads with 1_000_000 ops each` running on:
cpu: AMD Ryzen 9 7950X 16-Core Processor
MemTotal: 64923992 kB (64GB)
```
| Metric       | main              | proctree-the-third | % Diff (main vs. work)  |
|--------------|-------------------|--------------------|-------------------------|
| malloc avg   | …
```
> Proctree improvements (cont)

- .clang-format
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
12a7e77bb **chore(ebpf): format apply based on the latest fix**
d3fc3e14e **fix: remove duplicate entry in .clang-format**
d3fc3e14e **fix: remove duplicate entry in .clang-format**
```
PenaltyReturnTypeOnItsOwnLine was duplicated in the .clang-format file.
It was crashing the clangd server.
Since the value of PenaltyReturnTypeOnItsOwnLine was being wrongly
interpreted, this opportunistically changes the other Penalty* values.
```
> Fix clang format

- deploy/helm/tracee/Chart.yaml
- deploy/kubernetes/tracee/tracee.yaml
- go.mod
- go.sum
- pkg/ebpf/tracee.go
8b58a2cf5 **chore(k8s): prepare v0.22.6 release**
```
commit: ffab7a0 (main), cherry-pick
```
10616e3d9 **chore: bump 3rdparty/libbpf to v1.5.0 (#4530)**
```
| Metric          | Difference (%)       |
|-----------------|----------------------|
| CPU Avg (%)     | -0.34%  (negligible) |
| Heap Avg (MB)   |  0.00%               |
commit: 409b3cc (main), cherry-pick
```
19ba04216 **fix: clock time detection**
```
* chore(go.mod): bump libbpfgo
commit: aeca328 (main), backport
[backport]
- point go.mod to libbpfgo branch with the helper fix
* fix: clock time detection
- The clock time detection was rework since the libbpfgo func
BPFHelperIsSupported changed;
- Unless it is explicitly marked as unsupported (supported=false),
it will default to BOOTTIME.
commit: f5cb740 (main), cherry-pick
```
> [v0.22.6] clock time fix and libbpf/libbpfgo bumps

- pkg/cmd/printer/printer.go
- pkg/counter/counter.go
- pkg/events/ftrace.go
- pkg/events/trigger/context.go
- pkg/metrics/event_collector.go
- pkg/metrics/stats.go
- tests/perftests/metrics_test.go
- tests/testutils/tracee.go
Close: #4485 
Close: #4486 
Close: #4487
Close: #4593
@ShohamBit if some somehow still happen after 0abfcabf6, please reopen the respective one.
0abfcabf6 **fix(perftests): make Tracee stop gracefully**
c2d41507c **fix(metrics): ignore bpf submit stats when METRICS=0**
c2d41507c **fix(metrics): ignore bpf submit stats when METRICS=0**
```
This also:
- Prints Stats as json.
- Pass Counter as pointer instead of value.
```
Stats output:
`{"Stats":{"EventCount":122,"EventsFiltered":0,"NetCapCount":0,"BPFLogsCount":0,"ErrorCount":0,"LostEvCount":0,"LostWrCount":0,"LostNtCapCount":0,"LostBPFLogsCount":0}}`
`{"Stats":{"EventCount":122,"EventsFiltered":0,"NetCapCount":0,"BPFLogsCount":0,"ErrorCount":0,"LostEvCount":0,"LostWrCount":0,"LostNtCapCount":0,"LostBPFLogsCount":0,"BPFPerfEventSubmitAttemp …
> fix(metrics): ignore bpf submit stats & gracefully stop tracee

- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- Makefile
- builder/Dockerfile.alpine-tracee-container
- builder/Makefile.release
- builder/Makefile.tracee-container
- builder/Makefile.tracee-make
02ffd2505 *** fix(builder): avoid static binary clobbering**
```
commit: a96a3ea (main), cherry-pick
---
* chore(builder): version format & quicker snapshot
This changes the version format (details on #4154).
Also, this makes the snapshot (dev daily) building quicker by not
embedding the BTF files in the tracee binaries.
As daily images are not meant for production, this should not be a
problem, also considering that the majority of the contributors are
running latest kernels.
commit: a1030f8e (main), cherry-pick
---
* chore(ci): use new make snapshot rule
This also removes INSTANCE_TYPE from the snapshot workflow, as it is
expected to be not so resource intensive now.
commit: 7e0d70e1 (main), cherry-pick
```
From PR #4444
> [v0.22.6] fix release tarball static binaries & make daily building faster

- go.mod
- go.sum
15c5730dc **chore(go.mod): bump api to latest 6968a8b**
> [v0.22.6] chore(go.mod): bump api to latest 6968a8b

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/controlplane/processes.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/net_capture.go
- pkg/ebpf/processor.go
- pkg/ebpf/processor_funcs.go
- pkg/ebpf/processor_proctree.go
- pkg/events/core.go
- pkg/events/derive/net_packet_helpers.go
- pkg/events/parse_args.go
- pkg/events/parse_args_helpers_test.go
- pkg/events/parse_args_test.go
- pkg/proctree/proctree.go
- pkg/proctree/proctree_feed.go
- pkg/proctree/proctree_output.go
- pkg/proctree/proctree_procfs.go
- tests/e2e-inst-signatures/e2e-proctree_data_source.go
- tests/e2e-inst-test.sh
Close: #4580
Close: #3878
f2e413059 **chore(proctree): mov hash computation to userspace**
5d943de68 **chore(proctree): add debug comment**
71bb922af **fix(proctree): exec event already brings data**
0ed6a1a3a **fix(proctree): treat kthread as special case**
fa4bc3283 **fix(proctree): time normalization momentum**
0e9065f8f **fix(tests): kill only tracee (-x exact match)**
ab4e18441 **chore(proctree): add exittime to debug**
71bb922af **fix(proctree): exec event already brings data**
```
Populate Process TaskInfo with data from sched_process_exec event.
Without it, the ProcessTree when set as source=events will contain
entries with no relevant data.
```
0ed6a1a3a **fix(proctree): treat kthread as special case**
```
kthread was being added only as parent, so its taskinfo was not being …
```
> Fix ProcessTree rogue entries

- .github/actions/build-dependencies/action.yaml
- Vagrantfile
- api/go.mod
- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- builder/Makefile.checkers
- docs/contributing/building/building.md
- go.mod
- pkg/cmd/list.go
- signatures/helpers/go.mod
- tests/e2e-install-deps.sh
- types/go.mod
5fd885f16 **fix(build): abort on code-check error**
dceee6286 **chore(lint): apply go vet rule**
93d2f2c9b **chore(build): bump Go to 1.24**
5a6afaba3 **chore(go): bump Go to 1.24**
5a6afaba3 **chore(go): bump Go to 1.24**
```
Upgrading to Go 1.24 brings performance improvements due to the new
Swiss Tables hash map implementation. With the same
deterministic/intensive proctree stress test, it was observed
significant reductions in CPU usage, heap memory, and object allocation.
Performance comparison:
| Metric       | Go 1.22.3 | Go 1.24.0 | Improvement |
|--------------|----------:|----------:|------------:|
| CPU avg      | 17.7%     | 13.5%     | -23.73%     |
| Heap avg     | 211MB     | 176MB     | -16.59%     |
| Heap obj avg | 1,156,562 | 730,153   | -36.86%     |
More details: …
```
> Bump Go to 1.24

- go.mod
- go.sum
- signatures/helpers/go.mod
- signatures/helpers/go.sum
3d4b390e0 **chore(go): bump go.mod to use latest pkgs**
```
Bump main and signatures/helpers go.mod to use latest api and types pkg.
```
> chore(go): bump go.mod to use latest pkgs

- go.mod
- go.sum
b89f4d2f5 **chore(go): bump to use latest signatures/helpers**
```
Bump main go.mod to use latest asignatures/helpers.
```
> chore(go): bump to use latest signatures/helpers

- pkg/ebpf/perf_count.go
Close: #4614
d55202c5d **fix(ebpf): profile only common events**
`METRICS=1 make tracee`
`sudo ./dist/tracee -e security_file_open,anti_debugging,net_packet_tcp -o none --metrics --pyroscope --pprof`
Outputs only common events metrics.
```json
{"level":"info","ts":1740578919.9102988,"msg":"Event submit attempts","net_packet_base":0,"net_packet_tcp_base":1108,"security_file_open":76195,"ptrace":0,"total":77303}
{"level":"info","ts":1740578919.9103284,"msg":"Event submit failures","net_packet_tcp_base":0,"security_file_open":0,"ptrace":0,"net_packet_base":0,"total":0}
```
The same can be observed in grafana:
> fix(ebpf): profile only common events

- Makefile
9f30e0b1c **fix(Makefile): typos**
24dfacdbc **chore(build): add bear rule**
24dfacdbc **chore(build): add bear rule**
```
To generate compilation database for Clang tooling, one can run
`make bear`.
This adds some development cmds to the Makefile help.
```
> Add bear rule to Makefile

- go.mod
- go.sum
- pkg/containers/containers.go
- pkg/containers/datasource.go
- pkg/containers/path_resolver.go
- pkg/containers/runtime/containerd.go
- pkg/containers/runtime/crio.go
- pkg/containers/runtime/docker.go
- pkg/containers/runtime/runtime.go
- pkg/containers/runtime/service.go
- pkg/ebpf/capture.go
- pkg/ebpf/controlplane/cgroups.go
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/events_enrich.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/tracee.go
- pkg/events/derive/container_create.go
- pkg/events/derive/container_remove.go
- pkg/events/usermode.go
- pkg/policy/ebpf.go
- pkg/policy/equality.go
- pkg/policy/policy_manager.go
7e600b6d1 **refactor(containers): split cgroup to container map**
```
Some general refactors to the containers package.
Containers and cgroup data is split up so that querying and maintaining
container data can managed "offline", without a cgroup fs backend.
```
Nothing breaks
> refactor(containers): split cgroup to container map

- tests/e2e-inst-test.sh
- tests/e2e-kernel-test.sh
- tests/e2e-net-test.sh
a75e4a479 **fix(tests): handle tracee pids correctly**
```
Passing it as a single quoted variable fails when there are multiple
pids:
./tests/e2e-inst-test.sh: line 241: kill: 18731 19343: arguments must be process or job IDs
Handle it as an array instead so each pid element is expanded correctly.
```
https://github.com/aquasecurity/tracee/actions/runs/13903229340/job/38899944478?pr=4583
> fix(tests): handle tracee pids correctly

- .github/dependabot.yaml
b52078308 **chore(ci): dependabot gomod for sec updates only**
```
Dependabot is now set to run daily for Go modules, but it will only
create pull requests for security-related updates. Version bumps for
gomod non-security updates will be handled manually, as we have many
dependencies that require thorough testing.
It also adds a prefix to the commit message to make it easier to
identify the purpose of the commit.
```
> chore(ci): dependabot gomod for sec updates only

- api/go.mod
- types/go.mod
3587efe59 **chore(api): align go toolchain**
448ef2779 **chore(types): bump toolchain to go1.24.1**
448ef2779 **chore(types): bump toolchain to go1.24.1**
```
go1.24.1 (released 2025-03-04) includes security fixes to the net/http
package, as well as bug fixes to cgo, the compiler, the go command, and
the reflect, runtime, and syscall packages.
https://github.com/golang/go/issues?q=milestone%3AGo1.24.1%20label%3ACherryPickApproved
```
> chore(go): bump toolchain to go1.24.1 - 1st

- signatures/helpers/go.mod
- signatures/helpers/go.sum
7b0abdab8 **chore(signatures/helpers): bump toolchain to go1.24.1**
```
go1.24.1 (released 2025-03-04) includes security fixes to the net/http
package, as well as bug fixes to cgo, the compiler, the go command, and
the reflect, runtime, and syscall packages.
https://github.com/golang/go/issues?q=milestone%3AGo1.24.1%20label%3ACherryPickApproved
```
> chore(go): bump toolchain to go1.24.1 - 2nd

- go.mod
- go.sum
Close: #4678 
fd2186731 **fix(deps): bump psx to v1.2.76-rc1**
fa56872e2 **fix(deps): bump to libbpfgo using libcap v1.2.75**
7fd451953 **fix(deps): bump libcap to v1.2.75**
fd2186731 **fix(deps): bump psx to v1.2.76-rc1**
```
- https://github.com/aquasecurity/tracee/pull/4688#issuecomment-2764255447
- https://web.git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?h=psx/v1.2.76-rc1&id=07d8ce731d5fe9063abfef4a77306e273b18b5f3
```
7fd451953 **fix(deps): bump libcap to v1.2.75**
```
The regression introduced in v1.2.72
https://bugzilla.kernel.org/show_bug.cgi?id=219687
was fixed since 1.2.74
https://web.git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=025f28ca4fe085fbcbf7933d53a42d335744e553
Nevertheless, this bumps libcap to v1.2.75 to match with the upstream
libbpfgo version. …
```
> fix(libcap): bump libcap to v1.2.75 & libpsx to v1.2.76-rc1

- go.mod
- go.sum
- pkg/ebpf/perf_count.go
2ea27b575 **PR #4688: fix(deps): bump libcap to v1.2.75 & libpsx to v1.2.76-rc1**
5fdc7f3a8 **PR #4631: fix(ebpf): profile only common events**
2ea27b575 **PR #4688: fix(deps): bump libcap to v1.2.75 & libpsx to v1.2.76-rc1**
```
fix(deps): bump libcap to v1.2.75
The regression introduced in v1.2.72
https://bugzilla.kernel.org/show_bug.cgi?id=219687
was fixed since 1.2.74
https://web.git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=025f28ca4fe085fbcbf7933d53a42d335744e553
Nevertheless, this bumps libcap to v1.2.75 to match with the upstream
libbpfgo version.
commit: main@7fd451953, backport
---
fix(deps): bump psx to v1.2.76-rc1
- https://github.com/aquasecurity/tracee/pull/4688#issuecomment-2764255447
- https://web.git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?h=psx/v1.2.7 …
```
> Release v0.23.1

- types/trace/trace.go
- types/trace/trace_test.go
> feat(trace): data field decoding types

- cmd/traceectl/go.mod
4762acf45 **fix: add toolchain**
I was getting this error when compiling Tracee. So after adding the toolchain the compilation get back to normal.
```
make -C cmd/traceectl all
cp cmd/traceectl/dist/traceectl ./dist/
echo "Moved traceectl binary to ./dist"
mkdir -p dist
go build \
-ldflags "-X main.version=v0.23.0-84-gd87b15186" \
-o dist/traceectl \
main.go 
go: downloading go1.24 (linux/amd64)
go: download go1.24 for linux/amd64: toolchain not available
make[1]: *** [Makefile:12: build] Error 1
Moved traceectl binary to ./dist
rm .check_pkg-config
```
> fix: add toolchain

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/controlplane/controller.go
- pkg/ebpf/heartbeat/heartbeat.go
- pkg/ebpf/probes/probe_group.go
- pkg/ebpf/probes/probes.go
- pkg/events/core.go
- pkg/server/http/server.go
Fixes: #3123 
This change introduces a heartbeat event in Tracee to enhance health monitoring and improve /healthz endpoint readiness/liveness. The heartbeat is generated every second by a Go function, which is then captured by a uprobe in the eBPF layer. This ensures that Tracee is actively processing events and functioning correctly.
Key changes:
* Introduced a periodic heartbeat event using a Go function running every second.
* Attached a uprobe to capture the heartbeat when the function is invoked.
* Ensures tracee is processing events generated at bpf layer
1. run tracee command by enabling healthz flag
`tracee --healthz --http-listen-addr=:8080`
expectations: heartbeat_event are generated 
2.  `curl http://localhost:8080/healthz`
expectations: status should return OK
> feat: add heartbeat event

- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_bench_test.go
- pkg/bufferdecoder/eventsreader_test.go
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/common.h
- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
Close: #4219
Close: #1129
71b9d2d6 **fix(decoder): treat abstract socket in decoder**
```
Abstract sockets were being ignored by readSunPathFromBuff() - former
readStringVarFromBuff() - in the decoder.
```
c883776c **fix(ebpf): correct sockaddr_un size handling**
```
In security_socket_connect, sun_path may not be NUL-terminated.
Therefore, sockaddr_un should be read based on the addrlen argument
provided, rather than assuming a fixed size.
```
e3b085df **fix(ebpf): read sockaddr_un members individually**
```
- Read sockaddr_un members individually to prevent offset issues,
especially since the destination struct (on the stack) may not be
aligned with the source struct (from the kernel).
This also:
- Treat len member as the sun_path length, not the struct size.
- Change all related …
```
> fix(ebpf): sockaddr_un length

- api/go.mod
- cmd/traceectl/go.mod
- go.mod
- signatures/helpers/go.mod
- types/go.mod
33ed7fbbd **chore(deps): bump go toolchain to 1.24.2**
https://go.dev/doc/devel/release#go1.24.minor
> chore(deps): bump go toolchain to 1.24.2

- signatures/helpers/go.mod
- signatures/helpers/go.sum
f661492c4 **chore(go): bump to use latest types**
```
Bump signatures/helpers go.mod to use latest types.
```
> chore(go): bump to use latest types

- pkg/ebpf/c/tracee.bpf.c
If the current version of Tracee is compiled with `METRICS=1`, we should get a error during run. Tested on x86-64.
> fix: ebpf max inst limit

- pkg/ebpf/processor_funcs.go
- types/trace/trace.go
ef15d765f **types: fix trace.Pointer type alias**
89a93fe1b **fix(ebpf): process memdump argument parsing**
ef15d765f **types: fix trace.Pointer type alias**
```
Was accidentally set to a type equivalence in d87b151864.
This caused code which meant to apply only to the nominal type to also
apply to uint64 types in general (for example hex formatting when parsing
data fields).
```
89a93fe1b **fix(ebpf): process memdump argument parsing**
```
Processor function of print_mem_dump unwrapped into uintptr instead of the new trace.Pointer
```
> Decode fixes

- cmd/traceectl/pkg/cmd/printer/printer.go
traceectl printer had references to an old grpc api which brought up compilation errors.
compiling traceectl will emit no errors
> fix(traceectl): fix printer process field access

- pkg/ebpf/capture.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/events_pipeline_bench_test.go
- pkg/ebpf/processor_funcs.go
- pkg/utils/utils.go
- pkg/utils/utils_bench_test.go
- pkg/utils/utils_test.go
3b8c0f615 **perf(ebpf): improve NUL byte trimming**
```
Introduce utils.TrimTrailingNUL function to handle NUL byte trimming
in a more efficient manner.
Running tool: /home/gg/.goenv/versions/1.24.0/bin/go test -benchmem
-run=^$ -tags ebpf -bench
^(BenchmarkBytesTrimRight_WithNUL|BenchmarkBytesTrimRight_NoNUL|
BenchmarkTrimTrailingNUL_WithNUL|BenchmarkTrimTrailingNUL_NoNUL)$
github.com/aquasecurity/tracee/pkg/utils -benchtime=200000000x -count=5 timeout=5m
goos: linux
goarch: amd64
pkg: github.com/aquasecurity/tracee/pkg/utils
cpu: AMD Ryzen 9 7950X 16-Core Processor
| Benchmark               | Avg Time (ns/op) | Improvement vs TrimRight |
|-------------------------|------------------|--------------------------|
| TrimTrailingNUL_WithNUL | 1.980 ns         | 17.1% faster             |
| …
```
> perf(ebpf): improve decodeEvents

- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_bench_test.go
- pkg/bufferdecoder/eventsreader_test.go
This reverts commit 71b9d2d6046bdcd81254e10cfdaba278990a31d2.
Commit introduced errors decoding some security_socket_connect events in the internal e2e tests. We leave aside the eBPF fixes done in the including PR.
> Revert "fix(decoder): treat abstract socket in decoder"

- pkg/cmd/initialize/kernelconfig.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/utils/environment/kernel_config.go
- pkg/utils/environment/osinfo.go
Close: #4649 
23c4855cd **fix(ebpf): check kprobe and uprobe support**
4c24eb205 **fix(environment): update comments**
ad668f628 **fix(initialize)!: add CONFIG_UPROBE_EVENTS as needed**
ad668f628 **fix(initialize)!: add CONFIG_UPROBE_EVENTS as needed**
```
BREAKING CHANGE: missing kconfig output changed.
```
Tested by @TrueBad0ur. https://github.com/aquasecurity/tracee/issues/4649#issuecomment-2848657935
> Check probes support

- .github/workflows/codeql.yaml
0be708fe6 **fix(ci): github actions do not support yaml anchor**
```
The anchor was introduced in 8d9ba5d.
```
> fix(ci): github actions do not support yaml anchor

- Makefile
b061915f3 **chore(build): use multiarch dir when available**
> chore(build): use multiarch dir when available

- .github/workflows/pr.yaml
393677d33 **feat(ci): add ref option to PR action**
```
This turns the PR action more flexible by allowing it to use a specific
ref (branch, tag, or commit) instead of always using the current branch.
```
> feat(ci): add ref option to PR action

- pkg/analyze/analyze.go
- pkg/cmd/cobra/cobra.go
- pkg/ebpf/events_pipeline.go
- pkg/signatures/engine/engine.go
5fdc7f3a8 **PR #4803: fix(engine):disable feedback**
```
fix(engine):disable feedback (#4803)
commit: 77d211e79996f (main), cherry-pick
```
> [v0.23.2] PR #4803: fix(engine): feedback deadlock issues

- Makefile
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
9d2c1b2d3 **chore(build): introduce BUILD_TYPE_FLAG**
```
This makes use of x-macros to make extendable build types.
```
> chore(build): introduce BUILD_TYPE_FLAG

- Makefile
- pkg/pcaps/common.go
- pkg/utils/files.go
- tests/integration/capture_test.go
- tests/integration/dependencies_test.go
- tests/integration/event_filters_test.go
- tests/integration/tracee.go
- tests/testutils/logger.go
Close: #4799
Close: #4782 
Close: #4192
Relate: #4068
33bcc1a9c **chore(tests): disable pid 0 swapper (sched_switch)**
711da2f77 **fix(tests): pid 0 event from swapper**
651f5ff85 **fix(tests): pidToCheck special pids**
c16b7dd09 **fix(tests): dependencies and logger**
4a60cabfd **chore(tests): increase integration test timeout**
54df2c847 **fix(tests): fix a container events test case**
78dd6257d **fix(pcaps): replace slashes in ProcessName**
33bcc1a9c **chore(tests): disable pid 0 swapper (sched_switch)**
```
Even though the failure rate has been reduced, the test still
occasionally fails in specific environments. See:
https://github.com/aquasecurity/tracee/issues/4799#issuecomment-3018918112
```
711da2f77 **fix(tests): pid 0 event from swapper**
```
This also adds a command-line flag …
```
> fix integration tests and related

- pkg/utils/proc/ns.go
- pkg/utils/proc/ns_test.go
Improve and extend namespace handling functionality in ns.go.
- Fix grammar in function documentation comments
- Add GetAnyProcessInNS function to find processes in specific namespaces
- Add GetNamespaces function to list all namespace IDs for a given type
> feat(utils/proc): enhance namespace utilities

- cmd/tracee/cmd/root.go
- tests/integration/tracee.go
The 1024 default for `--perf-buffer-size` and `--blob-perf-buffer-size` assumes a 4KB page size to give 4MB of contiguous memory per perfbuffer. But Arm and Powerpc architectures can have page sizes of 64KB and that could require a lot of memory on servers with many cores as perfbuffers are per cpu. Fix by calculating the defaults to give 4MB per perfbuffer.
Close: #4817
> Set default buffer pages apprioprate for page size

- cmd/tracee-rules/main.go
- pkg/analyze/analyze.go
- pkg/cmd/cobra/cobra.go
- pkg/ebpf/tracee.go
- pkg/signatures/benchmark/benchmark_test.go
- pkg/signatures/engine/engine.go
- pkg/signatures/engine/engine_test.go
Fix and optimize signature loading
First commit:
```
fix: optimize signature loading by filtering based on policy requirements
Previously, Tracee would start goroutines for ALL available signatures
during initialization, regardless of whether they were actually needed
based on the configured policies. This led to unnecessary resource usage
when many signatures were available but only a subset was required.
Changes:
- Introduce AvailableSignatures vs SelectedSignatures distinction in engine.Config
- Add selectSignaturesBasedOnPolicies() function to filter signatures based on policy event requirements
- Update engine.Init() to only load SelectedSignatures instead of all available signatures
- Ensure only policy-required signatures get goroutines started via loadSignature()
Performance …
```
> Fix signature loading

- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/common.h
- pkg/ebpf/c/tracee.bpf.c
First commit:
```
ebpf: fix update_min macro to properly modify original variable
The update_min macro was broken because it lacked output constraints in its
inline assembly, causing it to only work on a register copy without writing
back to the original variable.
Add the missing '+r' output constraint to [size] parameter so the macro can
actually modify the original variable instead of just working on a register copy.
This fix is needed for the macro to work correctly with struct fields like
buf->offset, not just local variables.
```
Second commit:
```
ebpf: fix buffer bounds checking for clang 15 compatibility
Replace explicit bounds checks with the fixed update_min macro in buffer
functions to help the BPF verifier understand memory access safety with
newer clang versions.
The issue …
```
> Fix clang issue

- pkg/ebpf/c/capture_filtering.h
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/common.h
- pkg/ebpf/c/common/filesystem.h
- pkg/ebpf/c/common/memory.h
- pkg/ebpf/c/tracee.bpf.c
efad07cde **chore(ebpf): use bounded loop**
```
Replaced multiple unrolled loops with bounded loops, resulting in a
notable reduction of the final object file size. For example, the
`tracee.bpf.o` file shrank from 15.5 MB to 14.2 MB (~8.6% / ~1.28 MB).
The actual size improvement may be greater, as this reduction reflects
only the current build artifact and likely applies across several BPF
programs.
```
Related: #474
> Use bounded loops

- cmd/tracee/cmd/root.go
- docs/docs/install/config/index.md
Reduces memory usage when pipeline channels are full, from ~8.4MB to ~840KB per channel. Also enables faster backpressure detection when consumers cannot keep up with event rates.
> perf: reduce pipeline-channel-size default from 10000 to 1000

- pkg/bufferdecoder/decoder.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/signature_engine.go
- pkg/events/derive/container_create.go
- pkg/events/derive/container_remove.go
- pkg/events/derive/derive.go
- pkg/events/derive/derive_test.go
- pkg/events/derive/hidden_kernel_module.go
- pkg/events/derive/hooked_seq_ops.go
- pkg/events/derive/hooked_syscall.go
- pkg/events/derive/net_flow.go
- pkg/events/derive/net_packet.go
- pkg/events/derive/net_tcp.go
- pkg/events/derive/process_execute_failed.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_collision_test.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/symbols_loaded_test.go
- pkg/events/parse_args.go
- pkg/events/parse_args_bench_test.go
- pkg/events/parse_args_helpers_test.go
- pkg/events/parse_args_test.go
- pkg/filehash/cache.go
- pkg/filehash/hash.go
- pkg/signatures/engine/engine.go
> Optimize events pipeline

- .gitignore
Add .clangd to .gitignore to exclude clangd language server cache files from version control.
> gitignore: add clangd files

- Makefile
- builder/Makefile.release
- Add STRIP_BPF_DEBUG option (default: disabled) to strip debug symbols
- When enabled, reduces BPF object size from 12MB to 9MB (25% reduction)
> build: add BPF debug stripping option to reduce object file size by ~3MB

- pkg/ebpf/c/tracee.bpf.c
The probes logic return if a reset fails.
However, a reset fails for event not chosen.
This cause a bug that tests fail if not all test events are chosen.
> fix(ebpf): fix exec_test probe reset logic

- pkg/containers/path_resolver.go
- pkg/containers/path_resolver_test.go
- pkg/ebpf/processor_funcs.go
- pkg/events/derive/symbols_loaded.go
- pkg/filehash/cache.go
- pkg/filehash/key.go
- pkg/utils/sharedobjs/shared_object.go
- Add ResolveLink() method for single symlink resolution with loop detection
- Add ResolveAllLinks() method for comprehensive path component resolution
- Add GetProcMounts() method to find accessible mount info in namespaces
- Implement LRU cache (1024 entries) for symlink resolution performance
- Add security validation to prevent symlink traversal outside mount boundaries
- Change mount namespace type from int to uint32 for consistency
- Add comprehensive input validation for all new methods
- Update related types and interfaces for type consistency
- Add extensive test coverage for new functionality and edge cases
This enables tracee to properly resolve symlinks within container mount namespaces while maintaining security and performance.
> containers: add symlink resolution support to path resolver

- Makefile
Stop testing on first failure to make debugging easier. This prevents having to scroll through multiple test failures to find the root cause of issues.
> build: add -failfast flag to test-unit target

- pkg/ebpf/processor_funcs.go
- pkg/ebpf/tracee.go
- pkg/events/core.go
- pkg/events/definition_test.go
- pkg/events/derive/hooked_seq_ops.go
- pkg/events/derive/hooked_syscall.go
Remove SYSLOG from base capabilities of hooked_syscall, hooked_seq_ops, hooked_proc_fops, and print_mem_dump events. Add proper capability elevation when kallsyms access is actually needed.
Fixes #3079
> fix: remove unneeded SYSLOG capability from base capabilities

- cmd/tracee-ebpf/main.go
- cmd/tracee/cmd/man.go
- cmd/tracee/cmd/root.go
- embedded-man.go
- pkg/cmd/cobra/cobra.go
- pkg/cmd/flags/capture.go
- pkg/cmd/flags/capture_test.go
- pkg/cmd/flags/containers.go
- pkg/cmd/flags/errors.go
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/output.go
- pkg/cmd/flags/output_test.go
- pkg/cmd/flags/tracee_ebpf_output.go
- pkg/cmd/flags/tracee_ebpf_output_test.go
- pkg/cmd/printer/printer_test.go
Fixes #4869
- Replace broken '--flag help' suggestions with working 'tracee man <flag>' commands
- Embed manual pages in binary using Go embed for distributed binaries
- Fix 'tracee man cri' command to correctly reference containers.1 file
- Update all flag error messages (output, capture, containers, errors, logger)
- Update test expectations to match new error message format
- Ensure help system works without requiring local docs directory
The previous help system was broken for users of distributed binaries, providing misleading '--output help' style suggestions that don't work. Now all error messages suggest the working 'tracee man <flag>' commands.
> fix: improve error messages and embed manual pages in binary

- deploy/helm/tracee/templates/daemonset.yaml
- deploy/helm/tracee/values.yaml
Remove old way of configuring webhook. One should now use the configfile -> https://github.com/aquasecurity/tracee/pull/3832
> helm: remove old webhook config

- pkg/ebpf/probes/compatibility.go
- pkg/ebpf/probes/compatibility_test.go
- pkg/errfmt/errfmt.go
Support map type requirement in probes compatibilities.
This allow the usage of a map of a type which is not supported in all kernel versions by a program.
Currently, unsupported maps will still fail to be created upon bpf module load, but I will address it in a follow-up PR.
This PR is a simpler version of #4892
I have tested it manually by creating a requirement of an arena map which my system doesn't support, and seeing the debug logs of failure.
It will be easier to test once we have events that use this feature.
-->
> feat(probes): add map type compatibility requirement

- .github/workflows/pr.yaml
- .gitignore
- Makefile
- codecov.yml
- docs/contributing/testing-coverage.md
- mkdocs.yml
- Add -covermode=atomic to unit and integration tests for concurrent safety
- Configure GitHub Actions to upload coverage reports to Codecov
- Add codecov.yml with appropriate targets (75% project, 80% patch)
- Create new Makefile targets: 'coverage' and 'coverage-html' for local development
- Add comprehensive developer documentation for coverage workflows
- Exclude type definitions from coverage (focus on business logic)
- Support separate coverage tracking for unit vs integration tests
Fixes #152
> feat: add comprehensive code coverage with Codecov integration

- go.mod
- go.sum
- pkg/ebpf/tracee.go
This is a follow-up PR for #4892.
Add a check of bpf maps support in the system before creating them in the bpf module load.
This will allow together with the bpf map compatibility requirement of the probes to use new types of bpf maps in bpf programs while supporting older kernel versions. Together with the fallback mechanism, it will allow to create efficient programs that use new bpf map types in newer kernels and fallback programs for older versions, allowing an event to be both efficient and support all environments.
As the map type and program type compatibility requirements have been merge, this PR resolves #1653
Tested it manually by creating an arena map and seeing the log of failing to create it, while still running Tracee normally.
> Load infra/map autocreate

- pkg/ebpf/c/common/buffer.h
d2ffc826d **fix:(ebpf): 'and' bitwise bug in save_bytes_to_buf**
> fix:(ebpf): 'and' bitwise bug in save_bytes_to_buf

- go.mod
- go.sum
The common module has been merged into the main branch and is now available as a published module. Remove the local replace directive to use the official published version.
> build: remove local common module replace directive

- pkg/ebpf/c/common/buffer.h
d6f648727 **fix(ebpf): use u32 for read_size in save_bytes_to_buf**
```
The save_bytes_to_buf function expects a u32 size parameter to match
bpf_probe_read's signature, but was using size_t internally which creates
a type mismatch on 64-bit systems (size_t: 8 bytes vs u32: 4 bytes).
This ensures consistent 32-bit sizing throughout the storing operation.
```
> fix(ebpf): use u32 for read_size in save_bytes_to_buf

- pkg/events/data/decode.go
Fix type mismatch where TIMESPEC_T arguments were decoded as time.Time but had ArgMeta.Type='float64', causing issues for JSON consumers.
- Update 20 TIMESPEC_T fields in core.go to use 'time.Time' type
- Add time.Time JSON unmarshaling support with nanosecond precision
- Add comprehensive tests with floating-point precision handling
Affects syscalls: clock_nanosleep, nanosleep, futex, poll, select, etc.
> fix(events): correct TIMESPEC_T decoded as time.Time instead of float64

- .github/actions/test-go-module/action.yaml
- .github/workflows/pr.yaml
Followup to previous conditional module testing implementation that had critical issues preventing the intended CI time savings.
Fixes:
- Make expensive jobs (integration, kernel matrix, ARM64) job-level conditional
- Add missing ARM64 module testing capability
- Centralize change detection logic (eliminate duplication)
- Clean up dependency chains
> ci: fix conditional module testing to actually skip expensive jobs

- docs/contributing/adding-events.md
- docs/contributing/checkpatch.md
- docs/contributing/guidelines.md
- docs/contributing/overview.md
- docs/contributing/performance.md
- docs/docs/install/healthz.md
- docs/docs/install/prerequisites.md
- docs/docs/install/prometheus.md
- docs/docs/policies/usage/cli.md
Updates documentation to reflect current Tracee architecture and improves contributor experience:
**Technical Updates:**
- Update CAP_NET_ADMIN description from tc programs to cgroup_skb BPF programs
- Fix protoc makefile references (Makefile.man → Makefile.protoc)
- Remove deprecated cache configuration 
- Update to unified server configuration format
**Documentation Reorganization:**
- Streamline contributing guides to eliminate redundancy across 3 pages
- Create clear hierarchy: overview (workflows) → guidelines (standards) → checkpatch (tools)
- Consolidate all development commands and troubleshooting in one place
> docs: fix outdated references and reorganize contributing guides

- common/bitwise/bitwise_test.go
- common/digest/cache.go
- common/digest/hash_test.go
- common/elf/analyzer_test.go
- common/environment/amount_test.go
- common/environment/osinfo_test.go
- common/fileutil/fileutil_test.go
- common/logger/callerinfo_test.go
- common/logger/filter_test.go
- common/logger/logger_test.go
- common/mount/mount_test.go
- common/murmur/murmur_test.go
- common/parsers/data_parsers_test.go
- common/set/set_test.go
- common/sharedobjs/host_symbols_loader_test.go
- common/stringutil/stringutil.go
- common/stringutil/stringutil_test.go
- common/tests/helpers_test.go
- common/timeutil/time_test.go
- bitwise: 0.0% → 100.0%
- murmur: 0.0% → 100.0%
- set: 0.0% → 100.0%
- logger: 0.0% → 92.9%
- tests: 0.0% → 91.7%
- digest: 13.0% → 94.8%
- sharedobjs: 50.0% → 89.2%
- fileutil: 6.1% → 81.6%
- elf: 18.4% → 78.1%
- timeutil: 0.0% → 70.9%
- mount: 9.9% → 66.7%
- stringutil: 44.4% → 100.0%
- parsers: 41.4% → 58.6%
- environment: 61.8% → 77.3%
> test: improve common module test coverage across 14 packages

- common/timeutil/time_test.go
Remove test that fails intermittently in CI due to unreliable boot time calculation in containerized environments
> test: remove flaky EpochToBootTimeNS test

- builder/Makefile.performance
The performance dashboard checks were still looking for the old -pyroscope and -pprof flags. Updated to detect the new unified --server flag with pyroscope/pprof values.
> fix(performance): update dashboard detection for new --server flag format

- pkg/signatures/engine/engine.go
```
fix(engine): remove duplicate channel close causing panic
The signature engine was closing the output channel twice:
1. In signature_engine.go via 'defer close(engineOutput)'
2. In engine.go via 'close(engine.output)'
Since engineOutput and engine.output are the same channel, this caused
a 'close of closed channel' panic during shutdown.
The fix follows Go channel ownership principle: only the creator
(signature_engine.go) should close the channel.
Fixes panic: close of closed channel at engine.go:218
```
```
fix(engine): prevent send-on-closed-channel race in matchHandler
Uses context-based protection to prevent 'send on closed channel' panics
during shutdown. Works regardless of signature Close() implementations.
```
Fix: #4679
> Fix sig engine close chan

- pkg/ebpf/c/tracee.bpf.c
f66de1598 **fix(ebpf): use sockaddr workaround in arm64**
```
Workaround was previously limited to x86 due to verifier limitations in ARM64.
These have likely since been fixed, and the workaround therefore works just as well in ARM64.
```
1. Run tracee on arm64 filtering for `security_socket_connect`
2. Connect with ssh to the machine running tracee
3. There should be no event where the value `remote_addr` of is `<nil>`
Compare with #1129
> fix(ebpf): use sockaddr workaround in arm64

- 3rdparty/btfhub.sh
- Makefile
- scripts/btfhub.sh
Close: #4456 
Realized that for Tracee case the sparse clone tool provided in btfhub repo is not enough, then this sparse clones setting the filters manually.
40b7c10bb **refactor(btfhub): relocate btfhub script**
```
Move the btfhub script to the scripts directory for better organization.
```
7c4f39129 **refactor(btfhub): improve script structure and ...**
```
... add sparse checkout for BTF files
- Implement sparse checkout for efficient BTF file downloads,
reducing unnecessary data transfer.
- Add logic to handle existing archive directories intelligently,
ensuring updates are managed correctly.
- Improve user feedback throughout the script (lib.sh).
```
`make btfhub BTFHUB=1`
> Improve btfhub.sh to download only the required

- scripts/btfhub.sh
9d785e42a **feat(btfhub): BTF generation with parallel jobs**
```
- Pass to use multiple jobs in btfgen.
- Introduce logic to calculate optimal parallel job count based on
available CPU cores.
```
This depends on https://github.com/aquasecurity/btfhub/pull/150.
> feat(btfhub): BTF generation with parallel jobs

- tests/integration/event_filters_test.go
f4958874a **fix(integration): specify ls pathname filters**
da2bdee40 **chore(integration): print actual mismatched event**
f4958874a **fix(integration): specify ls pathname filters**
```
Some tests would expect triggers related to the ls binary.
Since '*ls' is a not very specific ending, change those filters to include a '/' before.
```
Integration tests remain green
> ARM64 integration fixes

- .github/dependabot.yaml
c0fa6c040 **chore: re-add Dependabot config file**
```
This time without go modules management.
```
> chore: re-add Dependabot config file

- .github/dependabot.yaml
df9208a78 **chore(ci): disable dependabot gomod updates**
```
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#disabling-dependabot-version-updates
```
> chore(ci): disable dependabot gomod updates
