- start.py
- test_container_tracer.py
- tracee/container_tracer.py
Add `-e`/`--events-to-trace` option allowing user to specify the syscalls and events to be shown in the trace. 
For example: `tracee -e cap_capable,execve` shows only cap_capable and execve events in the output
Default is to include all events (can also be explicitly specified with `-e all`)
> Add event filter

- README.md
- start.py
- tracee/event_monitor_ebpf.c
- tracee/tracer.py
Remove BPF code replacement each time tracee is started.
By doing that, we will be able to compile Tracee's BPF code once per node.
Adding config map to communicate userspace configuration to BPF code.
> dynamic configuration of the bpf code

- tracee/argprinters.go
- tracee/tracee.go
migration of https://github.com/aquasecurity/tracee/pull/44 to go
> print sockaddr common families in go

- tracee/argprinters.go
- tracee/consts.go
- tracee/tracee.go
migration of https://github.com/aquasecurity/tracee/pull/45 to go
> print prctl and ptrace options in go

- tracee/printer.go
before: 
```json
"arguments":["/usr/bin/dirname",["dirname","/home/itaysk/.asdf/asdf.sh"]]
```
after:
```json
"arguments": {"p0": "/usr/bin/dirname", "p1": "[dirname, /home/itaysk/.asdf/asdf.sh]"}
```
> fix json arguments formatting to match python version

- go.mod
- go.sum
- main.go
- test/loader.sh
- tracee/printer.go
- tracee/tracee.go
- handle lost events (count and print them). uses https://github.com/iovisor/gobpf/pull/235
- support customizable buffer size. uses https://github.com/iovisor/gobpf/pull/218
- add a simple load test to test lost events
related: https://github.com/aquasecurity/tracee/issues/49
> handle lost events and support configurable buffer size

- .gitignore
- Dockerfile
- Makefile
- README.md
- test/loader.sh
- tracee/tracee.go
this PR builds tracee distributable binary, in preparation to start releasing tracee.
it also embeds the ebpf c code in the binary.
additionally it removes the multi-os support from the makefile since tracee is linux only
fix: https://github.com/aquasecurity/tracee/issues/67
related: https://github.com/aquasecurity/tracee/issues/69
> build distributable binary

- start.py
- tracee/tracer.py
https://github.com/aquasecurity/tracee/pull/73 broke events selection in the python version. the PR fixes that. Also, it renames the flag in python to `events` because it accepts multiple entries unlike the go version which accepts one at a time and therefore is called `event`
> fix events flag in python

- tracee/tracee.go
Tracee go version was using excessive memory. The leak was correlated with multiple calls to `bpf.GetSyscallFnName`. The python version [does the same thing](https://github.com/aquasecurity/tracee/blob/master/tracee/tracer.py#L904) but in gobpf there's an issue where the symbol cache is not being reused as in python, and also not being released. I'm working on fixing this upstream, but in the meantime it's easy to work around this issue in tracee with this PR.
> work around gobpf memory leak

- main.go
- start.py
- tracee/consts.go
- tracee/event_monitor_ebpf.c
- tracee/tracee.go
- tracee/tracer.py
option to log all syscalls invocations, including syscalls which were not fully traced by tracee
adds support for tracepoint attachment which at this point is limited to "sys_enter" only
> add support for tracepoints and implement raw_syscalls tracepoint

- main.go
- tracee/printer.go
- tracee/tracee.go
if we want to treat the "tracee" package as a library, it should never print to stdout directly.
> decouple tracee package from main (cli) package

- main.go
- test/gob.go
- tracee/printer.go
- tracee/tracee.go
this allows tracee to communicate with another golang consumer using [gob encoding](https://golang.org/pkg/encoding/gob/) which is efficient binary encoding and avoids needless serialization when the consumer is a go program
> add output gob output format

- tracee/tracee.go
is it's not known just print the id
> fix raw_syscall printing if syscall is not known to tracee

- tracee/tracee.go
if the user specify `--capture-files` but didn't `-e write_vfs` or `-e security_bprm_check` appropriately, capture files will not work. This PR makes sure to trace these events, but in order to hide them from the output (the user didn't ask to trace them), I register them as essential events which achieve the same behavior. In a future PR we might rename essential events to something like hidden events and integrate it with EventConfig
> fix file capture when dependent event is missing

- tracee/tracee_test.go
https://github.com/aquasecurity/tracee/pull/131/ broke the test for ptrace printing, this PR fixes that
> fix test for ptrace printing

- tracee/event_monitor_ebpf.c
Not in all cases elements were removed from these maps when no longer
necessary.
This patch fixes this issue
> Fix "memory leaks" in bin_args_map and args_map

- tracee/event_monitor_ebpf.c
before this fix the `Protection changed from W+E to E!` alert would print a capture message even if `--capture` was not set to `mem`
> fix mem alert when not capturing

- tracee/tracee.go
`--capture exec ` for `memfd_create`d files was trying to get the file from the filesystem which failed. In the future we might want to get the file using it's device/inode but for now just suppress the error
> fix capture exec for non-filesystem files

- tracee/event_monitor_ebpf.c
- tracee/printer.go
- tracee/tracee.go
I didn't add it to the table output after all, only to the json/gob outputs. In future PR we can maybe make the printer aware of "container mode" change the output format accordingly
> add host pids to context

- main.go
- tracee/consts.go
- tracee/event_monitor_ebpf.c
- tracee/printer.go
- tracee/tracee.go
This patch changes the way we attach to syscalls.
Instead of using a kprobe for each syscall, we use raw_syscalls
tracepoint as an entry point, and dispatch to the relevant syscall
handler using tail calls.
We first try to use the newer raw tracepoints (kernel ver >= 4.17), as
it is more performant, and fallback to "regular" tracepoint otherwise.
This change has the following advantages:
1. Stability between kernel versions
2. Better performance (see https://lwn.net/Articles/748352 for
comparison)
3. Faster start time and stopping of tracee as there are less probes
(only one for all syscalls)
4. It will allow us to support 32 bit userspace programs without adding
additional probes
> Use tracepoints instead of kprobes for syscalls

- tracee/tracee.go
another process can lookup this file in the output directory to know when tracee is ready, meaning all the initialization was complete. especially useful for tests
> signal readiness using a file in output dir

- tracee/tracee.go
improve capture executed files and fix a bug if the container is sharing pid namespace. instead of caching the pid 1 of every mntns (sensitive to pid namespace and lost events), we will cache the first 5 (by default) pids of every mount namespace. like before, it will always include pid1 in the container.
note that I didn't implement the pid cache cleanup since this turned out to be tricky. this is not a "leak" problem because the pid cache is limited in size. In a future PR we can implement it in order to be able to add new pids to the cache.
> fix capture exec when sharing pidns

- tracee/event_monitor_ebpf.c
This PR moves kernel pointers reads to a dedicated section in the code.
By adding getters for reading kernel data structures, it should be easier to port tracee to other kernel versions.
This patch also removes some of BCC's "magic" for reading kernel memory.
By doing these reads directly (instead of counting on bcc's rewriter), we can move to non-bcc bpf libraries in the future (e.g. libbpf, and gobpf/elf)
To do that, explicitly use bpf_probe_read() to derefernce pointers.
Wrap the calls with KERN_READ() macro.
> Improve bpf code portability and genericness

- tracee/tracee.go
instead of `tracee.${pid}`, will be `tracee.pid` with the ${pid} written in it
> change readiness file format

- .gitignore
- .gitmodules
- 3rdparty/include/stdarg.h
- Makefile
- README.md
- bpfwrap/libbpf_perf_cb.go
- bpfwrap/libbpf_wrapper.go
- tracee/event_monitor_ebpf.c
- tracee/tracee.go
This PR replaces gobpf as the bpf library used by Tracee with bpfwrap.
bpfwrap is a wrapper to libbpf, which is written in C.
The advantages of using bpfwrap over gobpf are the following:
- no bcc dependancy - only clang is required to compile the code
- compile once - compilation can take place during installation
on a given node. Then, the compiled object is used in future runs.
This have the advantage that Tracee will not have unnecessary delays
on start.
- libbpf is being developed as part of the linux kernel. This means it
will always get the latest features, and that it is well maintained.
- the move to libbpf will allow us to add support for CO-RE in the
future. With CO-RE, bpf object is Compiled Once, and can then
Run Everywhere without the need to compile the code again for …
> Move from gobpf to bpfwrap (libbpf)

- tracee/event_monitor_ebpf.c
Commit d58cd29cba127702f05ddd5e39d7f00eb67e6a0c (fix kernel 4.14) inadvertently introduced a bug in send bin chunk size.
When sending last commit, we now perform bitwise AND operation on the chunk size with (MAX_PERCPU_BUFSIZE >> 1).
This means that the chunk size can't be bigger than this value, which is not the case.
Set chunk size to this value to avoid corrupted data
> Fix send bin chunk size

- tracee/pipeline.go
- tracee/printer.go
Errors were incorrectly positioned with adjacent event. tailing newline should not be part of the message, it should be handled by the printer
> fix error printing line break

- main.go
- tracee/printer.go
- tracee/tracee.go
To resolve #214, provided the `-o go-template=<path>` option.
> Output formatting via gotemplate

- Dockerfile
- test/gob/go.mod
Updated docker file to use build for golang 1.15 as 1.13 is now EOL as of 11thAug 2020
> updated to golang 1.15

- go.mod
no sure exactly what happened but https://github.com/aquasecurity/tracee/pull/248 changed everything but the main go.mod file
> update go version to 1.15

- tracee/tracee.go
Using int32, string size can be negative, and crash Tracee when trying to allocate a byte slice which is huge (when unsigned).
Fix by using uint32
> Fix bad string size type

- Dockerfile
- Makefile
- release.Dockerfile
I also took the opportunity to upgrade the base image to ubuntu focal.
note that the builder image version will need to change to go 1.15 when libbpf is merged with master (currently libbpf is still on 1.13)
> fix docker builds for libbpf

- tracee/consts.go
- tracee/tracee.bpf.c
Add sched_process_exit event and set it as essential. Also set do_exit event as non essential.
As tracepoints are considered a more stable API, and as there are environments where tracepoints are enabled but kprobes are not, it is preferable to use sched_process_exit and not do_exit as an essential event.
Keep do_exit event as it has the process exit code, which is not available for the sched_process_exit event
> Add sched_process_exit event

- .github/workflows/build-test.yaml
Added tests as a job in the GitHub Actions workflow. Related to #254.
We can also alternatively add a new section in the `Makefile` and run tests in a container. However, could not detect failing tests with that approach.
```makefile
.PHONY: test-docker
test-docker: clean
img=$$(docker build --target builder -q .) && \
cnt=$$(docker create $$img); \
docker run -a stdout $$cnt make test; \
docker rm $$cnt ; docker rmi $$img
```
> feat: Add tests to CI/CD workflow

- main.go
- tracee/consts.go
- tracee/tracee.bpf.c
- tracee/tracee.go
_(I marked this as a draft because of a verifier issue, see context below)_
This adds a `--filter` flag to tracee. Currently the only supported value to filter by is `uid`. In this proposed solution users can specify filters of the form `<field>=<value>`, or multiple by using a comma separated list or specifying the flag multiple times:      `--filter <field>=<value1>,<value2>` or `--filter <field>=<value1> --filter <field>=<value2>`
In the case of uid filtering, the way I've implemented this is by parsing passed values, and sharing two values between user and kernel space: an array of the uids in their own BPF_ARRAY and a field in the BPF_HASH `config_map` for the length of this array. 
The issue is that the verifier complains about the loop in bpf which reads from the array of uids. …
> Add a `--filter` flag and support for filtering of events by uid

- .dockerignore
- .github/workflows/build-test.yaml
- Dockerfile
- Makefile
- README.md
- main.go
This PR is re-organizing the build in docker code, improving the build targets user experience, and adding visibility into the build progress. it also bumps the required llvm version from 7 to 9, as we found issues with 7.
> improve building in docker

- Dockerfile
- Makefile
1. make clean tried to read from a file after deleting it
2. libbpf headers target was `libbpf/usr/include`, but some targets required `libbpf/usr/include/bpf`, and there's no recipe for this target. This happened to work so far because usually some other rule tried to build `libbpf/usr/include` before the rule that needed `/bpf` run. but if the `/bpf` is called directly before the parent rule is called, which happens with `make release`, then it will try to build `libbpf/usr/include/bpf` which has no recipe. the solution is to change the libbpf headers target point to the specific desired path, (`/bpf`). another approach could be to specify exactly which headers files are needed whic I could do if you think it's better. another alternative is to define the `/bpf` as a target but since …
> fix a couple of issues with the makefile

- Dockerfile
- Dockerfile.builder
- Makefile
- entrypoint.sh
Use docker alpine image instead of ubuntu.
This change reduces the attack surface and shrinks the image sizes.
Image sizes (before compression in dockerhub):
- Fat: 327MB
- Slim: 15MB
Close #335 
Close #329
> Use alpine image instead of ubuntu

- tracee/tracee.bpf.c
> Fix bpf compilation on redhat and centos with kernel 4.18

- README.md
- main.go
- tracee/consts.go
- tracee/tracee.bpf.c
This PR adds a new tracing mode called process:follow. It enables tracing a specific binary in an easy way.
Today if we want to trace a binary, we can use process:new mode, and filter according to the process name (e.g. using the 'comm' filter). The problem with that approach is that if the process then executes a binary with a different name, it will not be tracced (as it will be filtered out). Removing the filter will enable tracing all new processes, however, there will also be noise from other new processes.
Using the new process:follow mode, a filter can be given, and Tracee will only trace processes according that filter. The difference, however, is that the children of the filtered process will be traced as well.
For example, say we want to trace a process named "example", which …
> Add process follow mode

- test/gob/go.mod
- test/gob/gob.go
- tracee/printer.go
when tracee writes into a file, and something else read from this file, we can't rely on EOF to know when the producer has finished sending events. For example if the producer doesn't yet have events to report, the consumer will hit EOF immediately, or if the consumer is consuming events faster than the producer.
The solution is to explicitly signal end of transmission, using a special even that seals the events stream. For now I'm adding it by default for gob output, but in the future we should 1) make it optional and 2) add it to every output that can be consumed in "streaming" fashion
> signal end of transmission for gob output

- tracee-rules/engine/engine.go
- tracee-rules/main.go
- tracee-rules/output.go
- tracee-rules/signature.go
- tracee-rules/signatures/golang/example.go
- tracee-rules/types/types.go
in rego signatures, metadata and eventSelectors are queries at runtime so we need to be able to return an error
> improve signature error handling

- main.go
- main_test.go
- tracee/consts.go
- tracee/tracee.bpf.c
- tracee/tracee.go
This PR introduces the changes as described in #377:
1. Tracing modes are simplified to: new/all/follow/pidns
2. pidns mode keeps the "container:new" semantics from before, meaning, tracing when "new container" is started. This name better describes how we traced new containers in the past - by looking for the creation of new pid namespaces (execution of pid 1).
3. Boolean container filter is added. Opposed to pidns (which is equivalent to container:new), filtering by container (with default 'new' trace mode) will trace all new processes created in any container, including existing containers. Using container filter with 'all' trace mode is equivalent to the old "container:all" mode.
4. move "--events" "--exclude-events" and "--set" flags into "--filter" flag
> Change trace modes and filter UX

- tracee/tracee.go
* Monitors `vfs_write` and `vfs_writev` events
* Records file path, writes a file in the form `write.dev-#.inode-#` to the output directory
* Output directory is indexed by the source file's path
Resolves #213
> Add indexing of written files by path

- main.go
- main_test.go
- tracee/tracee.bpf.c
In a previous commit we changed max string filter size from 16 to 32.
This made comm filter to stop working.
The reason for this, is the way we check for filter equality in the kernel, which is by treating the string as a key to a map (and not by comparing character by character)
In the linux kernel, comm char array has a length of 16. This made the comparison not to work, as the next 16 bytes doesn't belong to the comm field.
Fix this by changing string_filter max size back to 16 in the bpf code.
In the user space, we can remove the string size limit, as when updating a bpf map, the number of bytes taken are exactly as defined in the map, which make long strings trimmed to the size of the map.
> Fix comm filter

- tracee/consts.go
- tracee/tracee.bpf.c
- tracee/tracee.go
Remove trace "mode" from bpf code and use filters instead.
The "new" and "pidns" modes are changed to NEW_PID_FILTER and NEW_PIDNS_FILTER in bpf code.
This PR does **not** change anything in the flags UX, but it will allow us to easilly move these two trace modes (and the "all" mode as well) to the filter flag if we decide to do so.
> Use filters instead of modes in bpf code

- go.mod
- go.sum
- main.go
- tracee/consts.go
- tracee/external/external.go
- tracee/pipeline.go
- tracee/printer.go
- tracee/tracee.bpf.c
- tracee/tracee.go
eBPF Has the ability to capture stack traces at the location the program was called. This PR adds the ability to capture the stack traces into the outputted event JSON.
As this can have a performance impact, this feature is behind a `--capture-stack-traces` cli flag.
The PR has had to add or alter a number of different parts of tracee:
- Adding a new eBPF map of type `BPF_MAP_TYPE_STACK_TRACE`, to keep track of the stack traces
- Adding a new config option `CONFIG_CAPTURE_STACK_TRACES` to track if we wish to capture stacks or not
- A new function in `libbpfgo` to lookup a value from an eBPF Map
- Altering the `Event` struct to have a `StackTrace` param
Where necessary I've tried to make sure to be architecture-agnostic, e..g when calculating pointer sizes, etc.
By eBPF's design, the Stack …
> Add ability to capture stack traces

- main.go
- main_test.go
- tracee/pipeline.go
- tracee/printer.go
- tracee/tracee.go
related: https://github.com/aquasecurity/tracee/issues/397
this also fixes a small issue with --capture documentation 
There are a few practices here that if approved I think we should implement in the other preparers in the future.
> refactor output flag

- .github/workflows/release.yaml
by default GH actions does a shallow clone of just the latest commit. we need all history to build the changelog.
> fix release workflow for github actions

- libbpfgo/libbpfgo.go
Add function for printing out debug info written by the BPF helper bpf_trace_printk()
> feat: add TracePrint to libbpfgo

- Makefile
- tracee-ebpf/Dockerfile
- tracee-ebpf/Makefile
- tracee-ebpf/Readme.md
- tracee-rules/Makefile
close: #465 
this doesn't address repackaging the container which will be done in a followup PR. this just "fixes" the release process to reflect the repo restructure
- rename tracee to tracee-ebpf
- adds a root level makefile 
- extracts release from the original tracee makefile (now tracee-ebpf) into root level makefile
- fix a few small issues with the makefile
> update release process after restructure

- tracee-rules/Readme.md
- tracee-rules/input.go
- tracee-rules/input_test.go
- tracee-rules/main.go
- tracee-rules/output.go
This addresses some of the points in #499. In particular:
1) Removes the `--trace-file`, and `--stdin-as` flags.
1) Adds a new flag called `--input-trace` that allows the user to specify the input file and input format for events to tracee-rules.
Still need to address:
1) ~Need to add unit tests for the above parsing logic~
1) What should the default options be?
1) ~https://github.com/aquasecurity/tracee/issues/499#issuecomment-771927000~
> Refactor flags in tracee-rules

- tracee-rules/main.go
Small change but this will make output look like this:
> Rename signatures and add spacing to printing of them with --list flag

- tracee-ebpf/Makefile
Small PR to fix a clang option
Fixes https://github.com/aquasecurity/tracee/issues/504
> fix: trace-ebpf: Fix typo in clang option

- tracee-rules/signatures/golang/export.go
- tracee-rules/signatures/golang/stdio_over_socket.go
- tracee-rules/signatures/golang/stdio_over_socket_test.go
export the signature so it will be loaded by tracee-rules.
fix FD assignment to int32 rather than int, because it causes panic.
> Fix stdio over socket

- Makefile
- tracee-ebpf/go.mod
- tracee-ebpf/main.go
- tracee-ebpf/main_test.go
- tracee-ebpf/test/gob/go.mod
- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/pipeline.go
- tracee-ebpf/tracee/printer.go
- tracee-ebpf/tracee/tracee.go
- tracee-rules/engine/engine.go
- tracee-rules/engine/engine_test.go
- tracee-rules/go.mod
- tracee-rules/input.go
- tracee-rules/input_test.go
- tracee-rules/output.go
- tracee-rules/signatures/golang/examples/example.go
- tracee-rules/signatures/golang/helpers.go
- tracee-rules/signatures/golang/stdio_over_socket.go
- tracee-rules/signatures/golang/stdio_over_socket_test.go
- tracee-rules/signatures/rego/regosig/traceerego.go
- tracee-rules/signatures/rego/regosig/traceerego_test.go
closes: https://github.com/aquasecurity/tracee/issues/497
The restucture changed the paths in main but didn't
effect the Go import paths which looks for a given tag. This commit
updated the import paths in preparation for the release (which will
create the tag)
> update import paths after restructure

- Readme.md
- tracee-ebpf/Readme.md
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
As described in #452 , there are many things that were changed between kernel version 4.14 to 4.18, and keeping support for kernels <4.18 will force us to keep too many compilation flags and kernel version checks.
These changes include the following:
1. bpf_get_current_cgroup_id() helper function that was added in 4.18 will allow us to better distinguish between different containers (we currently use pid namespace for that, which is far from ideal)
2. raw tracepoints vs "regular" tracepoint - today we support both, but there is no good reason to use the "regular" tracepoints.
3. attach_Xprobe() vs attach_legacyXprobe() - X={u,k}
4. syscall arguments passing was changed in 4.17, and now it is save in pt_regs struct indirectly. We already support both in the code, but it makes the code less …
> tracee-ebpf: update minimal kernel version to 4.18

- Readme.md
- docker-mac.md
Added information how to run Tracee on Docker for Mac (which does not come with Kernel headers).
This fixes issue #570
> Added information how to run Tracee on Docker Mac

- Readme.md
- tracee-rules/main.go
- tracee-rules/signature.go
- tracee-rules/signature_test.go
- tracee-rules/signatures/golang/stdio_over_socket.go
- tracee-rules/signatures/rego/anti_debugging_ptraceme.rego
- tracee-rules/signatures/rego/anti_debugging_ptraceme_test.rego
- tracee-rules/signatures/rego/code_injection.rego
- tracee-rules/signatures/rego/code_injection_test.rego
- tracee-rules/signatures/rego/dynamic_code_loading.rego
- tracee-rules/signatures/rego/dynamic_code_loading_test.rego
- tracee-rules/signatures/rego/examples/example1.rego
- tracee-rules/signatures/rego/examples/example1_test.rego
- tracee-rules/signatures/rego/examples/example2.rego
- tracee-rules/signatures/rego/examples/example2_test.rego
- tracee-rules/signatures/rego/fileless_execution.rego
- tracee-rules/signatures/rego/fileless_execution_test.rego
- tracee-rules/signatures/rego/kernel_module_loading.rego
- tracee-rules/signatures/rego/kernel_module_loading_test.rego
- tracee-rules/signatures/rego/ld_preload.rego
- tracee-rules/signatures/rego/ld_preload_test.rego
- tracee-rules/signatures/rego/regosig/traceerego.go
- tracee-rules/signatures/rego/regosig/traceerego_test.go
- tracee-rules/types/types.go
This PR intends to introduces the following:
> feat: Add IDs to Signature Metadata.

- .github/workflows/pr-rules.yaml
- tracee-ebpf/Dockerfile.builder
- tracee-rules/Dockerfile.builder
- tracee-rules/Makefile
There aren't docs around to use this action but looking at the yaml, I was able to understand it. https://github.com/petroprotsakh/opa-test-action/blob/master/action.yml
Saves us the hassle from building our own setup each time (clone OPA binary, etc.)
In theory it should run this (from the tracee-rules dir):
```
$ opa test . --verbose --ignore="examples"
data.main.test_match_1: PASS (3.399054ms)
data.main.test_match_wrong_request: PASS (114.405µs)
--------------------------------------------------------------------------------
PASS: 2/2
```
Fixes https://github.com/aquasecurity/tracee/issues/491
Requires: https://github.com/aquasecurity/tracee/pull/567
> feat: Add OPA tests to Github Actions

- libbpfgo/libbpf_cb.go
- libbpfgo/libbpfgo.go
- libbpfgo/selftest/ringbuffers/.gitignore
- libbpfgo/selftest/ringbuffers/Makefile
- libbpfgo/selftest/ringbuffers/go.mod
- libbpfgo/selftest/ringbuffers/go.sum
- libbpfgo/selftest/ringbuffers/main.go
- libbpfgo/selftest/ringbuffers/run.sh
- libbpfgo/selftest/ringbuffers/self.bpf.c
This adds support for ringbuffers to libbpfgo. A good reference for ringbuffers can be found [here](https://nakryiko.com/posts/bpf-ringbuf/). There is not much difference in userspace between ringbuffers and perfbuffers besides the fact that ringbuffers API does not support a callback for lost events. That will have to be handled in kernel space for consumers of libbpfgo, like Tracee. 
I have a separate PR awaiting this which I can open as a draft seeing how it would be consumed in Tracee.
> feat: Add ringbuffer support to libbpfgo

- .github/workflows/pr-rules.yaml
- libbpfgo/go.mod
- libbpfgo/selftest/ringbuffers/go.mod
- tracee-ebpf/Dockerfile.builder
- tracee-ebpf/go.mod
- tracee-ebpf/test/gob/go.mod
- tracee-rules/Dockerfile.builder
- tracee-rules/go.mod
This is in preparation for https://github.com/aquasecurity/tracee/issues/434
> feat: Bump up to go1.16

- libbpfgo/libbpfgo.go
fix: rb.stopped should be set in the Stop method
This cleans up the design of a solution to an issue where Stop()
could be called after the sole consumer of the rb.stop channel
has closed but rb.stopped has not yet been set. This removes
the need to have a non-blocking channel write with `select` as
it turns out we really don't need this channel at all.
> Cleanup ringbuffer stop logic

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
Adding a new event named magic_write. This event is triggered when a file header is written (currently set to the first 16 bytes).
This event can then be used to detect when a file of some given type is written (e.g. an ELF file).
To support the addition of this event, a new argument type is introduced: bytes.
When submitting an argument of this type, it is possible to transfer an arbitrary number of bytes as an argument
> tracee-ebpf: add magic_write event

- tracee-rules/Readme.md
- tracee-rules/goldens/broken.tmpl
- tracee-rules/main.go
- tracee-rules/output.go
- tracee-rules/output_test.go
- tracee-rules/templates/csv.tmpl
- tracee-rules/templates/simple.tmpl
- tracee-rules/templates/xml.tmpl
This PR aims to add the following:
- Formatting webhook payloads with supplied templates
- Using a user supplied template for formatting payload
- Additional refactoring & testing
Fixes: https://github.com/aquasecurity/tracee/issues/539
Sample usage:
```
tracee-rules --input-tracee format:json --webhook="http://foo.local" --webhook-template="templates/simple.tmpl" --content-type="application/json"
```
> Webhook message formatting using go templates

- tracee-rules/main.go
- tracee-rules/main_test.go
```
ID         NAME                                VERSION DESCRIPTION
TRC-1      Standard Input/Output Over Socket   0.1.0   Redirection of process's standard input/output to socket
TRC-2      Anti-Debugging                      0.1.0   Process uses anti-debugging technique to block debugger
TRC-3      Code injection                      0.1.0   Possible code injection into another process
TRC-4      Dynamic Code Loading                0.1.0   Writing to executable allocated memory region
TRC-5      Fileless Execution                  0.1.0   Executing a precess from memory, without a file in the disk
TRC-6      kernel module loading               0.1.0   Attempt to load a kernel module detection
TRC-7      LD_PRELOAD                          0.1.0   Usage of LD_PRELOAD to allow hooks on …
```
> Adding version string to --list output

- entrypoint.sh
- entrypoint_test.bats
- test/mocks/mock
- tracee-ebpf/Dockerfile
- tracee-ebpf/entrypoint.sh
Since we now moved to perf based kprobes instead of the legacy debugfs probes, we can remove the mount of debugfs
> Remove debugfs mount

- Readme.md
- tracee-ebpf/Makefile
Add the flag to add the submodules.
Suggest a way to get missing libbpf code if the original checkout
didn't specify the submodules.
Also remove extra tab character from Makefile.
Signed-off-by: Icarus Sparry <Icarus Sparry tracee@icarus.freeuk.com>
> Better help message for missing libbpf

- libbpfgo/libbpfgo.go
Fixes RingBuffer's Stop to do a clean exit.
Adds a polling 300ms timeout to check for stop condition.
The Stop() method waits for the polling goroutine to exit
before returning to the caller.
Fixes #619
> Fix RingBuffer shutdown

- Dockerfile
- tracee-ebpf/Dockerfile
fix: #608
(a forced docker pull would have worked as well in this case but better to make the version explicit to avoid potential mistakes like this)
> fix tracee-ebpf dockerfile for go 1.16

- tracee-rules/main.go
Also fixes documentation to use --rules flag.
Fixes: https://github.com/aquasecurity/tracee/issues/610
> feat: Print loaded rules info at runtime

- Makefile
- Readme.md
- tracee-ebpf/Makefile
- tracee-ebpf/Readme.md
- tracee-rules/Makefile
Fix "make clean".
- Use '-C' rather than '-c' to enter subdirectory
- Check for existence of files before reading from them, fixes empty
args to docker rmi.
Document Gnu Make 4.3 or better is required, Makefiles uses grouped targets.
Signed-off-by: Icarus Sparry <Icarus Sparry tracee@icarus.freeuk.com>
> Fix some of the toplevel "make clean" errors.

- tracee-rules/Readme.md
- tracee-rules/signatures/golang/stdio_over_socket.go
- tracee-rules/signatures/helpers/helpers.go
This moves both the rego and go helper functions into their own package, updates usage and Makefile accordingly. (#599) 
It also adds notes in the README about them (#538).
> fix: move and document the signature helpers 

- libbpfgo/helpers/argParsers.go
- libbpfgo/helpers/example_tracelisten_test.go
- libbpfgo/libbpfgo.go
Please note, after consulting with @itaysk , we decided that is better to close this issue with a two-phase commit.
In the first commit (this one) we will simply copy functions in libbpfgo so that tests will pass. In the second commit we will use libbpfgo funcs (under linuxhelpers package) and remove not relevant functions under tracee package (argprinters.go).
> copying argprinters funcs under libbpfgo

- Readme.md
Currently the "quickstart" relative link doesn't do anything since the target section has changed
> fix relative link to quickstart-with-docker

- Dockerfile
- Makefile
Related https://github.com/aquasecurity/tracee/issues/391
Adding labels to Docker image
> Adding labels to Docker image

- libbpfgo/helpers/argumentParsers.go
- libbpfgo/helpers/tracelisten.go
- libbpfgo/libbpfgo.go
- libbpfgo/selftest/ringbuffers/go.mod
- libbpfgo/selftest/ringbuffers/go.sum
- tracee-ebpf/main.go
- tracee-rules/main.go
This PR handles the following small things (not associated with issues)
- moves the libbpfgo helpers function `TracePrintListen` into it's own file and renames the other helpers file.
- remove go.mod/go.sum file from the selftest package in libbpfgo, no need for them.
- fixes small linter errors in libbpfgo, and adds `-lbpf` to link libbpf (mostly just for gopls).
- fix importing of the `urfave/cli` package
> Group of small fixes

- tracee-rules/output.go
- tracee-rules/output_test.go
- tracee-rules/signatures/golang/examples/example.go
- tracee-rules/signatures/golang/stdio_over_socket.go
- tracee-rules/signatures/rego/regosig/traceerego.go
- tracee-rules/types/types.go
This PR changes the `types.Finding` struct to use SignatureMetadata field instead of Signature field.
> types.Finding interface update

- libbpfgo/libbpfgo.go
- libbpfgo/selftest/perfbuffers/.gitignore
- libbpfgo/selftest/perfbuffers/Makefile
- libbpfgo/selftest/perfbuffers/go.mod
- libbpfgo/selftest/perfbuffers/go.sum
- libbpfgo/selftest/perfbuffers/main.go
- libbpfgo/selftest/perfbuffers/run.sh
- libbpfgo/selftest/perfbuffers/self.bpf.c
This is anlogous to 09b2b47c (which fixed RingBuffer).
It does a clean PerfBuffer stop by waiting for the
polling goroutine to finish its work.
Fixes #640
> Fix PerfBuffer shutdown

- tracee-rules/output.go
- tracee-rules/output_test.go
- tracee-rules/templates/falcosidekick.tmpl
This PR removes Falcosidekick specific code and reuses the templating logic to build the same.
Fixes https://github.com/aquasecurity/tracee/issues/627
> refactor: Remove falcosidekick specific code and reuse templating

- libbpfgo/libbpfgo.go
- libbpfgo/selftest/perfbuffers/main.go
- libbpfgo/selftest/ringbuffers/Makefile
- libbpfgo/selftest/ringbuffers/main.go
While it's convenient to specify map sizes in BPF C file,
sometimes the right size is only known at runtime.
With Resize(), it's possible to instantiate the module
and resize the maps before they're loaded into the kernel.
Fixes #655
> Add Resize() and GetMaxEntries() to BPFMap

- tracee-ebpf/main.go
- tracee-ebpf/tracee/printer.go
fix: #618 
printers were closing their stdout/stderr although they didn't create
those. this caused initBPF errors for example to get unseen
> fix error handling

- libbpfgo/helpers/rwArray.go
- libbpfgo/helpers/rwArray_test.go
- libbpfgo/libbpf_cb.go
- libbpfgo/libbpfgo.go
Fixes eventsChannels and lostChannels accesses
- Both were accessed without a mutex
- The acceeses in polling goroutine are frequent,
locks are undesired in this path
- Use a sparse array (implemented as a two level tree)
to provide lock-free read-only access.
Fixes #648
> Fix eventsChannels race

- .dockerignore
Related the issue https://github.com/aquasecurity/tracee/issues/681
> Adding a dockerignore

- .github/workflows/pr-ebpf.yaml
I hosted a VM in azure where i'm running a github actions runner
#685
```
[*] uname -a
Linux gh-action-tracee-centos-8.2 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
> feat: add testing envrionment matrix that includes self hosted runner

- tracee-ebpf/Makefile
- tracee-ebpf/main.go
- tracee-ebpf/main_test.go
- tracee-ebpf/tracee/tracee.go
Related issue https://github.com/aquasecurity/tracee/issues/560
- Using switch and validateOutputFormatValue method to validate the default output format values("table", "table-verbose", "json", "gob","gotemplate=").
> fix: trace-ebpf flag output

- tracee-ebpf/tracee/tracee.go
This is to handle #690 
The "EOF" error is printed as a result of the File Write Channel sending empty raw data. I believe the reason for this has to do with allocating memory for []byte{} that'd be send over the file_write channel, but nothing ever being written, leading it to being drained in this way. 
This will skip over empty raw data that's been sent. Alternatively we can add a check for `err == io.EOF` and ignore it specifically.
> Add check for empty bytes being written by file write channel 

- Readme.md
The link to the minimum requirements was broken. It has been corrected to the correct link.
> Fix minimum requirements link

- libbpfgo/libbpfgo.go
Although LSM is attached via BPF_RAW_TRACEPOINT_OPEN, using
AttachRawTracepoint is not possible since the tp_name argument
to bpf_program__attach_raw_tracepoint must be NULL.
Partially addresses #365
> libbpfgo: Add AttachLSM() method

- libbpfgo/Makefile
- libbpfgo/libbpfgo.go
- libbpfgo/libbpfgo_test.go
- libbpfgo/selftest/perfbuffers/main.go
- libbpfgo/selftest/ringbuffers/main.go
- libbpfgo/selftest/run.sh
- libbpfgo/test/.gitignore
- libbpfgo/test/test.bpf.c
Some libbpf functions fail and return an -errno
encoded inside the pointer. Therefore checking
for NULL is not enough.
Checks the returned pointers for NULL or ERR_PTR
encoding and converts the errno (if available)
to an error message.
Fixes #708 
Fixes #691
> libbpfgo: Check for ERR_PTR return values

- libbpfgo/libbpfgo.go
Closes https://github.com/aquasecurity/tracee/issues/723
This appears to work for my use case, I'll contribute fixes should I notice any bugs with this as is. It's mostly modeled after what libbpf-rs does.
@yanivagman @grantseltzer
> libbpfgo: Add map iterator support

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
Add the following events to tracee-ebpf:
- security_bpf: allows bpf() syscall command to be traced.
- security_bpf_map: called from bpf() BPF_MAP_GET_FD_BY_ID command.
The first is important for generic bpf syscall tracing while the later
is triggered whenever some process tries to get an eBPF MAP fd in order
to read or update MAP contents: an important feature for tampering
prevention.
Signed-off-by: Rafael David Tinoco <rafaeldtinoco@gmail.com>
> tracee-ebpf: add security_bpf{,_map} events (#617)

- tracee-ebpf/Readme.md
The link was coming up as 404 for me, modified to use the link from the docs site, which seems to be working ok.
> Update Prerequisites Link in READMe

- tracee-ebpf/main.go
> tracee-ebpf: ignore kernel config check when init fails

- tracee-ebpf/tracee/tracee.bpf.c
Since the large loop gets unrolled, the various variable
allocations caused programs to exceed the stack limit.
> Optimize save_path_to_str_buf in tracee.bpf.c

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
Add sched_process_exec to catch user mode process creations from the kernel. This event will monitor any sched_process_exec - including such that were invoked from the user space.
In order to check if the function was invoked from the kernel - the parent name should start with "kworker/".
This is also backup up with tracee-rules rego helper `is_process_kernel`.
> add sched_process_exec event

- tracee-ebpf/tracee/tracee.bpf.c
Prior to the fix Tracee failed to run:
After the fix Tracee succeeds loading the BPF program.
> Fix error that caused eBPF code not to be loaded

- tracee-ebpf/tracee/tracee.bpf.c
This PR fixes a regression caused by the recent merge of the initial CO-RE
support to match the fix in 85cf5b
Fixes #786
> tracee-ebpf: fix compilation on ubuntu

- tracee-ebpf/tracee/pipeline.go
- tracee-ebpf/tracee/tracee.go
This commit includes: 
- a Broker API with the Streamer interface and implementation of IOStreamer (aka printer).
- the creation of Consume() API exposed by Tracee.
> implemented broker and consume API for tracee-ebpf

- tracee-rules/benchmark/README.md
- tracee-rules/benchmark/signature/golang/code_injection.go
```console
$ go test -race -bench=EngineWithCodeInjection/golang -benchmem
goos: darwin
goarch: amd64
pkg: github.com/aquasecurity/tracee/tracee-rules/benchmark
cpu: Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
BenchmarkEngineWithCodeInjection/golang-4         	==================
WARNING: DATA RACE
Write at 0x000001f61f40 by goroutine 20:
github.com/aquasecurity/tracee/tracee-rules/benchmark/signature/golang.(*codeInjection).Init()
/Users/dpacak/go/src/github.com/aquasecurity/tracee/tracee-rules/benchmark/signature/golang/code_injection.go:36 +0xb8
github.com/aquasecurity/tracee/tracee-rules/engine.NewEngine()
/Users/dpacak/go/src/github.com/aquasecurity/tracee/tracee-rules/engine/engine.go:56 +0x738
github.com/aquasecurity/tracee/tracee-rules/benchmark.BenchmarkEngineWithCodeInjection.func1() …
```
> fix(benchmark): Unprotected global variable processMemFileRegexp in golang.codeInjection.Init()

- tracee-ebpf/tracee/tracee.bpf.c
1. Fix container id when cgroup starts with "docker-"
2. Fix container id not shown in sched_process_exit event
> tracee-ebpf: fix container id issues

- tracee-ebpf/tracee/tracee.bpf.c
fix #811 
Bug introduced in #758
> tracee-ebpf: fix incomplete path

- tracee-ebpf/external/external.go
- tracee-ebpf/external/external_test.go
- tracee-ebpf/external/go.mod
the external package was originally created for consuming tracee-ebpf events without having to import and build entire tracee-ebpf project, but since it was under the same module that defeated the purpose of a separate package. this commit is a preperation for a future commit which will import external package as a go module from this commit (after which we can remove the old external package).
> add external package as a module

- tracee-ebpf/external/external.go
- tracee-ebpf/external/external_test.go
- tracee-ebpf/external/go.mod
- tracee-ebpf/external/go.sum
ToUnstructured returns a JSON compatible map which can
be used as a parsed input with OPA Go SDK to avoid
relatively expensive JSON encoding round trip.
Looking at benchmarks it's not a game changer, but we can observer a slight improvement:
```
➜  benchmark git:(main) go test -bench=EngineWithNSignatures/rego -benchtime=100x -benchmem
goos: darwin
goarch: amd64
pkg: github.com/aquasecurity/tracee/tracee-rules/benchmark
cpu: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
BenchmarkEngineWithNSignatures/rego/2Signatures-16         	     100	  14135044 ns/op	11575729 B/op	  245983 allocs/op
BenchmarkEngineWithNSignatures/rego/4Signatures-16         	     100	  22670464 ns/op	23365947 B/op	  494621 allocs/op
BenchmarkEngineWithNSignatures/rego/8Signatures-16         	     100	  44750550 ns/op …
```
> feat: Add ToUnstructured method to Event

- tracee-ebpf/external/external.go
- tracee-ebpf/main.go
- tracee-ebpf/tracee/pipeline.go
- tracee-ebpf/tracee/printer.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
This PR sets the default timestamp to be the realtime (wall) timestamp.
In addition, it is possible to use a monotonic timestamp relative to tracee start time using a new output option.
The format of the timestamp is changed to accommodate these changes.
> tracee-ebpf: use wall and relative timestamps

- tracee-ebpf/tracee/tracee.bpf.c
> tracee-ebpf: Adjust MAX_PATH_COMPONENTS limit for kernels >= 5.2

- tracee-ebpf/tracee/tracee.bpf.c
Extending the number of bytes sent by the magic_write event. This is required for the analysis of ELF headers.
> tracee-ebpf: extend magic_write bytes

- tracee-ebpf/tracee/tracee.go
Handle SIGTERM  to display the epilogue message, instead of abruptly stop. 
eg:
```
End of events stream
Stats: {eventCounter:7531 errorCounter:0 lostEvCounter:0 lostWrCounter:0 lostNtCounter:0}
```
> tracee-ebpf: add SIGTERM support

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
using kprobe tcp_connect, in order to capture tcp SYN and SYN-ACK packets. 
this internal kernel function is a good place to identify outgoing tcp connections:
- this function is called both for ipv4 and ipv6. 
- this function is called after the kernel assigns a local port to the socket.
- this function is called before the first SYN packet is sent.
we no longer have use of the tcp states TCP_SYN_SENT and TCP_ESTABLISHED in the inet_sock_set_state tracepoint - this is because these states were only used to capture outgoing tcp connections.
TCP_LISTEN is still needed because it is used to capture incoming tcp connections.
TCP_CLOSE is now used for both outgoing and incoming tcp connections, but we have to update sock_ctx_map in tcp_connect, so we can remove this network flow from …
> use tcp_connect kprobe to get tcp handshake packets

- tracee-ebpf/tracee/tracee.go
Refactor to avoid doing `strings.Split(k, ".")` twice. Let me know if you okay with simple refactorings like this.
> tracee-ebpf: refactor to avoid two strings.Split

- tracee-rules/Readme.md
Fix minimum requeriments links, it uses the link from the [tracee-ebpf/Readme.md](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/Readme.md#quickstart)
> tracee-rules: fix minimum requirements link

- tracee-ebpf/tracee/argprinters.go
- tracee-ebpf/tracee/argprinters_test.go
Adding test coverage to [argprinters.go](https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/argprinters.go)
```
tracee-ebpf/tracee/argprinters.go:10:	PrintUint32IP		100.0%
tracee-ebpf/tracee/argprinters.go:18:	Print16BytesSliceIP	100.0%
tracee-ebpf/tracee/argprinters.go:24:	PrintAlert		100.0%
```
> tracee-ebpf: improve argprinters test coverage

- tracee-rules/main.go
1. You can run Tracee-rules with `--pprof` and `--pprof-addr :7777` flags to enable (remote) profiling:
```
sudo ./tracee-ebpf --output=format:gob --security-alerts | ./tracee-rules \
--pprof --pprof-addr:7777 \
--input-tracee=file:stdin --input-tracee=format:gob
```
2. Profile **cpu** for **60 seconds** and access Graph or Flame Graph visualisation in your web browser:
```
go tool pprof -http=0.0.0.0:6060 http://localhost:7777/debug/pprof/profile?seconds=60
```
3. Profile **goroutine** stack traces of all current goroutines:
```
go tool pprof -http=0.0.0.0:6060 http://localhost:7777/debug/pprof/goroutine
```
Check all available profiles on https://golang.org/doc/diagnostics#profiling.
> tracee-rules: enable pprof endpoints

- tracee-ebpf/tracee/tracee.go
- tracee-ebpf/tracee/tracee_test.go
Add tests for `OutputConfig.Validate()`:
```
=== RUN   TestOutputConfigValidate
=== RUN   TestOutputConfigValidate/format:table
=== RUN   TestOutputConfigValidate/format:table-verbose
=== RUN   TestOutputConfigValidate/format:json
=== RUN   TestOutputConfigValidate/format:gob
=== RUN   TestOutputConfigValidate/format:gotemplate=tmpl
=== RUN   TestOutputConfigValidate/invalid_format
```
I also refactored the code in a way I consider more readable than the huge `if`, but I can revert it if you prefer the previous version.
> tracee-ebpf: add output validate test

- Dockerfile
Fixes https://github.com/aquasecurity/tracee/issues/736. If adding a dependency is not a problem, [tini](https://github.com/krallin/tini) is a very common solution to handle signals properly on containers.
The image size doesn't  change:
```
tracee:with_tini         446MB
tracee:without_tini      446MB
```
Testing:
```
docker build  -t tracee:with_tini .
docker run -v /boot/config-$(uname -r):/boot/config-$(uname -r) --name tracee --rm --privileged -it tracee:with_ini
docker kill --signal=SIGINT tracee
docker kill --signal=SIGTERM tracee
```
> tracee: add tini tracee docker image

- tracee-ebpf/main.go
- tracee-ebpf/main_test.go
Fixes https://github.com/aquasecurity/tracee/issues/502
To validate:
```
tracee-ebpf -o help  2>/dev/null
tracee-ebpf -c help  2>/dev/null
tracee-ebpf -t help  2>/dev/null
```
> tracee-ebpf: fix help flag to print to stdout

- tracee-ebpf/tracee/tracee.bpf.c
Fixes: #851
For the kprobe security_sb_mount, the save_path_to_str_buf() complexity
is too big with the unroll logic + MAX_PATH_COMPONENTS of 80, even on
higher kernels (like 5.4 in Ubuntu). Reducing to 64 did NOT help.
Reducing to 48 DID help and it worked.
Ubuntu kernel contains c04c0d2b968a ("bpf: increase complexity limit and
maximum program size") commit with no reversions. The commit states
that:
BPF_COMPLEXITY_LIMIT_INSNS is the kernel internal limit
and success to load the program no longer depends on program size,
but on 'smartness' of the verifier only.
which might indicate that the eBPF verifier in older kernels, like 5.4,
is not smart enough to consider an unroll of 80 iterations, in the path
resolution function, a logic less complex than it should.
> tracee-ebpf: turn MAX_PATH_COMPONENTS down to 48

- tracee-rules/signature.go
When an error occurs in rego rule - the error message used to print the first 20 bytes - effectively cropping the full name of the rules for rule names longer than 20 bytes.
This PR should fix it.
> fix rule name partially cropped in error message

- tracee-ebpf/Makefile
- tracee-ebpf/tracee/co_re_missing_definitions.h
This PR fixes CO:RE support in `tracee-ebpf` on RHEL 8 and its derivatives.
RedHat kernel support was added some time ago by #351 but additional changes are now needed to make that fix work for CO:RE since this mode doesn't use actual RedHat Linux kernel header files and some definitions are missing.
> Fix CO:RE support for RHEL 8 and derivatives

- tracee-ebpf/tracee/co_re_missing_definitions.h
- tracee-ebpf/tracee/tracee.bpf.c
Changed the way tracee-ebpf detects invocation of a user mode process from the kernel.
Now uses the `PF_KTHREAD` flag in the parent task struct flags.
Will detect userland process creation from kworker or kthread.
> change invoked_from_kernel detection method

- tracee-ebpf/tracee/tracee.bpf.c
We originally created this filter (only tracing security_file_open that was originated from open/openat syscalls) as we've noticed there were times it was called not from open/openat context (e.g. during execve), and we wanted to reduce the amount of events triggered by it. As such events frequency is low (which are not originating from open/openat), and as users might expect to get an event for every time that security_file_open is triggered, we can remove this filter.
> tracee-ebpf: don't filter security_file_open for open/openat

- tracee-ebpf/main.go
Fixes https://github.com/aquasecurity/tracee/issues/585
> tracee-ebpf: print help for invalid arguments

- tracee-ebpf/Makefile
- tracee-rules/Makefile
Allowing external flags to `go test`. This simplify getting coverage reports or running single tests. Eg:
```
make test GOTEST_FLAGS="-run Test_updateFileSHA"
make test GOTEST_FLAGS="-cover"
...
```
> tracee-ebpf: add flags support for make test

- tracee-ebpf/tracee/tracee.bpf.c
PR #897 caused a regression in kernel 4.19 - program instruction count was too big.
Seems like using `__builtin_memcpy` uses more instructions that bpf_probe_read().
Change back to use bpf_probe_read() to fix this regression
> tracee-ebpf: fix regression - program too large in kernel 4.19

- tracee-ebpf/tracee/co_re_missing_definitions.h
Fix #900 
Specifically, the problem was that THREAD_SIZE was defined as follows:
`#define THREAD_SIZE (2*PAGE_SIZE)`
While it should have been:
`#define THREAD_SIZE (PAGE_SIZE << 2)`
I also took the opportunity to highlight the fact that some of these constants are architecture specific, and remove some x32 specific definitions
> tracee-ebpf: fix get syscall id from regs

- tracee-ebpf/go.mod
- tracee-ebpf/go.sum
- tracee-ebpf/main.go
- tracee-ebpf/tracee/tracee.go
1. start using libbpfgo initial btfinfo helper
2. allow external BTF files through TRACEE_BTF_FILE env variable
3. execution decisions based on available environment
4. update to libbpfgo with initial btfinfo
> tracee: support external BTF files

- tracee-ebpf/tracee/containers.go
- tracee-ebpf/tracee/tracee.go
Fixes: #862
Initialize pid_to_cont_id_map during tracee startup so that already
running containers can have their container_id resolved when being
traced.
Instead of traversing cgroups filesystem, like tracee eBPF code does, I
have preferred to rely in wrapped 'docker cli' commands to discover
container ids and tasks running in each active container. This made the
code cleaner and easier to be maintained.
Note: There is a small window of opportunity for a container to be
started while this logic is running. I could have made 'Containers'
logic to run in a go coroutine but that would also create another race
window: userland adding a pid to the map that has already been removed
by the - now active - trace event handler.
> tracee.go: initialize pid_to_cont_id_map during startup

- tracee-ebpf/tracee/printer.go
Fixes https://github.com/aquasecurity/tracee/issues/752
> tracee-ebpf: fix error printing to be always text

- tracee-ebpf/external/external.go
As a preparation to taking printer out of the tracee package and moving it into main package, we need to export Stats.
Doing this, we will also be able to export Stats to other consumers of tracee-ebpf.
The exported struct will expose statsStore as defined in tracee.go:
```
type statsStore struct {
eventCounter  counter
errorCounter  counter
lostEvCounter counter
lostWrCounter counter
lostNtCounter counter
}
```
> tracee-ebpf: add stats to external

- tracee-rules/main.go
This code probably made sense at some point, but it doesn't anymore. The test for an empty event source returns `err`, but all the calls before check `if err != nil { return err}`, so if somehow the code entered inside the if it would `return nil`.  But it doesn't seem like that [inputs](https://github.com/aquasecurity/tracee/blob/main/tracee-rules/main.go#L91-L94) will be empty, it will either have a source or return [error](https://github.com/aquasecurity/tracee/blob/ceece80d347ef5e23777a4f8888cfd3fca9b4447/tracee-rules/input.go#L33)
> tracee-rules: refactor non used code

- tracee-ebpf/go.mod
Currently, when we make changes that also require changing the external package, we first have to commit the changes in external, wait for it to be merged, fetch the new package and update go.mod, and only then submit the other changes. 
This is annoying, and can be avoided by replacing external in go.mod with a relative path
> tracee-ebpf: use replace for the external package

- tracee-ebpf/Makefile
CO-RE allows eBPF objects to be portable among different kernel
versions. This commit allows tracee-ebpf to be statically compiled so it
is also portable. By being a static binary, we avoid portability issues
such as:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_XXX' not found
----
This has been discussed and agreed upon https://github.com/aquasecurity/tracee/pull/873 but I accidentally closed that merge request. I'm opening this one with the proposal we had: to make it optional.
> tracee-ebpf: add static build support for portability

- tracee-ebpf/tracee/tracee.go
According to  https://lore.kernel.org/bpf/CAMy7=ZXTiaX9xzNi5aOavwsf+mziJ=w-EcHH2f=cJmCGr3EPQA@mail.gmail.com/T/#u, getting an EEXIST error can happen when a qdisc already exists, and we should explicitly check for it - this PR does exactly that.
Note: We will still get the printed error message from libbpf. To remove it, we will need to figure out how to ignore it from libbpfgo libbpf_print_fn function.
Fix #947
> tracee-ebpf: fix network capture with latest libbpf

- tracee-ebpf/go.mod
- tracee-ebpf/go.sum
- tracee-ebpf/main.go
- tracee-ebpf/main_test.go
- tracee-ebpf/printer.go
- tracee-ebpf/tracee/events_pipeline.go
- tracee-ebpf/tracee/tracee.go
- tracee-ebpf/tracee/tracee_test.go
This PR moves the printer logic out of the tracee package into the main package, and decouples events generation from printing.
This will also allow a consumer of tracee-ebpf as a library to use channels to get stdout,stderr and tracee stats on close.
> tracee-ebpf: move printer to main package

- tracee-ebpf/tracee/consts.go
This fix is required for proper json unmarshalling in tracee-rules of the sched_process_exec event
> tracee-ebpf: fix sched_process_exec argument types

- tracee-ebpf/tracee/tracee.bpf.c
Fixes: #851
This commit removes a conditional branch from the logic of
raw_syscalls:sys_enter tracepoint. This solves issues with
dead code detection and CO-RE optimizations (most likely).
Bug: https://github.com/aquasecurity/tracee/issues/851
Reference: https://github.com/aquasecurity/tracee/issues/851#issuecomment-903074596
Reference: https://x-lore.kernel.org/stable/20210821203108.215937-1-rafaeldtinoco@gmail.com/#t
> tracee-ebpf: mitigate deadcode optimization issue for 5.4 and less

- tracee-ebpf/tracee/consts.go
> tracee-ebpf: fix sched_process_fork arg names

- tracee-rules/benchmark/benchmark_test.go
- tracee-rules/benchmark/signature/wasm/signatures.go
- tracee-rules/engine/engine.go
- tracee-rules/engine/engine_test.go
- tracee-rules/main.go
Adds a new flag `--rego-enable-parsed-events` which enables parsed events.
```
benchmark                                                              iter         time/iter    bytes alloc             allocs
---------                                                              ----         ---------    -----------             ------
BenchmarkEngineWithCodeInjectionSignature/rego-8                        100    12760.62 μs/op   5807573 B/op   123602 allocs/op
BenchmarkEngineWithCodeInjectionSignature/rego_+_prepared_events-8      100     8942.85 μs/op   6026101 B/op   112120 allocs/op
BenchmarkEngineWithCodeInjectionSignature/golang-8                      100      991.93 μs/op    441537 B/op     3004 allocs/op
BenchmarkEngineWithCodeInjectionSignature/golang_+_prepared_events-8    100 …
```
> feat: Add flag for prepared events

- tracee-rules/benchmark/signature/rego/signatures.go
- tracee-rules/main.go
- tracee-rules/signature.go
- tracee-rules/signature_test.go
- tracee-rules/signatures/rego/regosig/traceerego.go
- tracee-rules/signatures/rego/regosig/traceerego_test.go
Adds a new flag `--partial-eval` that can be passed in for turning on partial evaluation of rego rules.
> feat: Add flag for Partial Eval

- tracee-rules/benchmark/signature/rego/signatures.go
- tracee-rules/main.go
- tracee-rules/signature.go
- tracee-rules/signature_test.go
- tracee-rules/signatures/rego/regosig/traceerego.go
- tracee-rules/signatures/rego/regosig/traceerego_test.go
Adds a new flag `--rego-runtime-target` that can be specified with potential runtime targets for rego rules: `rego` or `wasm`.
Requires: https://github.com/aquasecurity/tracee/pull/979
Signed-off-by: Simar simar@linux.com
> feat: Add flag for Runtime Target

- tracee-ebpf/Makefile
Modify the readlink in the Makefile file so that it works properly with relative softlinks in CentOS.
My test procedure on CentOS 7 is as follows：
```bash
$ cd tracee-ebpf && make build DOCKER=1 --just-print
....
Step 3/3 : WORKDIR /tracee
---> Using cache
---> 5e8a792b8117
Successfully built 5e8a792b8117
Successfully tagged tracee-builder:latest
docker run --rm -v /root/tracee/tracee-ebpf:./ -v /root/tracee/tracee-ebpf:/tracee/tracee-ebpf -w /tracee/tracee-ebpf --entrypoint make tracee-builder KERN_BLD_PATH=/usr/src/kernels/5.4.132-1.el7.elrepo.x86_64 KERN_SRC_PATH=build dist/tracee-ebpf VERSION=v0.6.1-1-gce65764
docker: Error response from daemon: invalid volume specification: '/root/tracee/tracee-ebpf:./': invalid mount config for type "bind": invalid mount path: './' mount path must …
```
> Fix `readlink` bug with relative softlinks

- tracee-ebpf/Makefile
This attempts to fix #942 
My rationale here is that this is only to make centos8 and rhel8 work, so I normalize the content of /usr/lib/os-release (even this has variance from centos to rhel) and only set RHEL_RELEASE_CODE if the value of VERSION_ID is rhel or centos. 
This isn't necessary for fedora as all supported versions have kernel version 5.8+ 
> Check os-release file for rhel or centos string

- tracee-ebpf/tracee/tracee.bpf.c
The change is incomplete, because the check in startup is if there is a 64
bytes of hexadecimal number in the cgroup dirname.
The reason for the incomplete change is that more accurate check will
be much heavier in performance.
> Fixed inconsistency in processes containerID value between startup and runtime

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/events_decoder.go
- tracee-ebpf/tracee/events_pipeline.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
- tracee-ebpf/tracee/tracee_test.go
Instead of sending the type of every argument in an event,
we can use the argument index to figure out the type.
This saves sending an extra 1 byte per each argument of any given event.
> tracee-ebpf: don't send argument type

- .gitignore
- Vagrantfile
This patch allows using Vagrant with VirtualBox or any
compatible provider to bootstrap tracee project.
It provisions Ubuntu 20.4 LTS with all dependencies to
compile and run tracee.
git clone https://github.com/aquasecurity/tracee.git
cd tracee
$ vagrant up && vagrant ssh
vagrant@ubuntu-focal:~$ cd /vagrant && make
vagrant@ubuntu-focal:/vagrant$ sudo ./dist/tracee-ebpf
> chore: Add Vagrantfile to easily get started with tracee

- Dockerfile
We use tini as the init process in our main dockerfile,
this causes an issue if we set the pid namespace to the host
because the kernel won't re-parent zombie children to this
proc. As a result, tini fails if it's not pid 1 or if TINI_SUBREAPER
is not set to true.
> Set TINI_SUBREAPER env variable in dockerfile

- tracee-rules/go.mod
- tracee-rules/go.sum
This upgrades the tracee-ebpf/external module to
a recent commit which fixes #1009
> tracee-rules: Upgrade external package dependency

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
1. In some cases, we did not delete pid/tid from map when should_trace() returned 0. Handle this by always trying to remove from map when a thread exits.
2. Add exit_code as an argument of sched_process_exit
> tracee-ebpf: improve sched_process_exit

- tracee-rules/engine/engine_test.go
This test will currently fail intermittently as seen here:
We need to ignore the order of elements received as its not important to assert. 
> fix: Ignore order of elements in engine_test.go

- tracee-ebpf/tracee/argprinters.go
- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/events_processor.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
create a new event to indicate a dup of socket.
in order to do that, we need to know that the file that is being 'dup'ed is of type socket.
we can get the 'struct file' of the duplicated FD, and we have to compare to file_operations of this file to the file_operations of a socket file. this is why i probe into the return of the 'socket' syscall. the return value of this syscall is the FD of the syscall in the current task. then i can go to the file descriptor table of the current task, and get the 'struct file' of this FD that i know to be a socket. i save the socket file_operations in a map, and then i use it in the 'dup*' events.
> add socket_dup event

- deploy/kubernetes/tracee-postee/tracee.yaml
Adds the resource limits and tolerations in to the Postee based manifest to bring it in line with the falco sidekick manifest. Fixes https://github.com/aquasecurity/tracee/issues/1059
> update postee manifest with tolerations and  resource limits

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
- tracee-ebpf/tracee/write_capture.go
Add init_module capture.
Split `send_bin` to helper and calling tail bpf programs for `raw_tracepoint` and `kprobe`.
The split was needed because a tail call cannot be called to a different type bpf program.
> init_module capture

- Makefile
- docs/Dockerfile
- docs/install/prerequisites.md
Also adding a convenient Make target to preview the documentation on http://localhost:8000 before it's published:
```console
$ make mkdocs-serve
docker build -t aquasec/mkdocs-material:tracee -f docs/Dockerfile docs
[+] Building 0.1s (7/7) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                           0.0s
=> => transferring dockerfile: 36B                                                                                                                                            0.0s
=> [internal] load .dockerignore                                                                                                                                              0.0s
=> => …
```
> docs: fix formatting on prerequisites page

- docs/tracee-ebpf/output.md
- entrypoint.sh
- tracee-ebpf/main.go
- tracee-ebpf/main_test.go
- tracee-ebpf/tracee/argprinters.go
- tracee-ebpf/tracee/tracee.go
This handles #461 
Based on conversation with Yaniv/Rafael we decided to make raw arguments opt-in, so they're parsed into strings by default (for all output formats). Raw arguments can be received by specifying `--output option:raw-arguments`. 
> Add option for raw arguments from various event flags

- tracee-ebpf/tracee/tracee.bpf.c
> tracee-ebpf: fix events sent in parallel to raw_sys_exit event

- tracee-ebpf/tracee/tracee.bpf.c
add READ_USER to allow reading of user buffers in raw_tracepoints.
bpf_probe_read_user and bpf_core_read_user depending if CORE is defined.
> add READ_USER

- tracee-ebpf/external/external.go
- tracee-ebpf/tracee/argprinters.go
- tracee-ebpf/tracee/argprinters_test.go
- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/events.go
- tracee-ebpf/tracee/events_decoder.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
Not too long ago we had "security-alerts" as part of tracee-ebpf (until #1114 removed it).
"alerts" where messages sent by an eBPF event as an extra argument, to pass some information about a security alert.
Introduce MemProtAlert in the external package, so it can be used by tracee-ebpf consumers
This will also allow us to expose "alerts" as raw arguments (related #1123 )
> tracee-ebpf: add MemProtAlert type to external package

- tracee-ebpf/printer.go
- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/containers.go
- tracee-ebpf/tracee/events.go
- tracee-ebpf/tracee/events_processor.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
This PR changes the way we extract container id for events.
The current solution has several problems:
1. Container id is saved per process, wasting memory.
2. Container id is only 12 chars long, while the full container id (64 chars long) might be required.
3. Bpf code is responsible for extracting container id from a cgroup name (we now check, for example, if cgroup name has "docker-" prefix, but this doesn't always work, e.g. with podman)
4. Regexes used during container id map initialization don't match the container ids we extract in runtime (as bpf code can't handle regexes)
To solve these problems, let's move to use cgroup id to get a container id:
1. In the context of every event, send task's cgroup id (instead of 12 chars container id)
2. Add a new map in userspace that maps …
> tracee-ebpf: use cgroup id for container id resolution

- tracee-ebpf/tracee/containers.go
- tracee-ebpf/tracee/events.go
- tracee-ebpf/tracee/events_processor.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
Currently, to filter a container in the bpf code we use "pid != host_pid", and to identify a NEW container we look for pid 1 in a new pid namespace.
These checks are not always true (e.g. pid=host or containers that share pid namespace).
This PR introduces a new way to identify containers in the bpf code using cgroup ids.
To do this, the following algorithm is used:
1. Introduce a new (bpf) containers_map with a key of cgroup_id (lower 32 bits) and value of CONTAINER_EXISTED, CONTAINER_CREATED, CONTAINER_STARTED
2. Update containers_map on init with existing containers (CONTAINER_EXISTED)
3. Update containers_map when a new cgroup is created (CONTAINER_CREATED)
4. If a cgroup path is not of a new container (checked by userspace when a cgroup_mkdir event is received) - remove it from the …
> tracee-ebpf: filter containers using cgroup id

- Readme.md
- docs/index.md
- docs/integrations.md
- docs/tracee-ebpf/index.md
- tracee-ebpf/Dockerfile
- tracee-ebpf/Readme.md
To identify existing containers, `--cgroupns=host` should be provided to the `docker run` command
> docs: add cgroupns=host docker option

- tracee-rules/signatures/golang/export.go
- tracee-rules/signatures/golang/kubernetes_api_connection_test.go
- tracee-rules/signatures/golang/stdio_over_socket_test.go
- tracee-rules/signatures/rego/regosig/aio_test.go
- tracee-rules/signatures/rego/regosig/common_test.go
- tracee-rules/signatures/rego/regosig/traceerego_test.go
- tracee-rules/signatures/signaturestest/signaturestest.go
The signaturetest.SigTest struct doesn't support meaningful assertions
because it has only boolean properties to indicate findings.
Use signaturetest.FindingHolder instead that keeps all findings
in memory and along with helper methods allows flexible
assertions (with testify).
Resolves: #925
> refactor: tests for Go signatures

- .github/workflows/mkdocs-dev.yaml
- .github/workflows/mkdocs-latest.yaml
- docs/Dockerfile
- mkdocs.yml
the repo was renamed according to mkdocs-macros recommendation (macro->macros) and also to better reflect the variable (any version, not just semver)
can be used like `{{ git_tag_version }}`
> update mkdocs version dependency

- docs/Dockerfile
- docs/index.md
- docs/install/ebpf-compilation.md
- docs/install/headers.md
- docs/install/kubernetes.md
- docs/integrations.md
- docs/tracee-ebpf/index.md
To preview changes run `make mkdocs-serve` and open http://localhost:8000 in you web browser.
> docs: use mkdocs macros plugin to specify version of tracee release artifacts

- tracee-ebpf/go.mod
- tracee-ebpf/go.sum
- tracee-ebpf/tracee/tracee.go
- tracee-rules/go.mod
- tracee-rules/go.sum
This upgrades:
- libbpf to v0.5.0
- libbpfgo to v0.2.2-libbpf-0.5.0 (and fixed breaking change)
- tracee-ebpf/external to v0.6.4
> Upgrade dependencies

- tracee-ebpf/tracee/tracee.bpf.c
* tracee-ebpf: reformat suggestions for better readability
* tracee-ebpf: remove unneeded asm_inline clang mitigation
because of type checks, recently introduced in tracee.bpf.c, we
currently need at least clang-12 for building tracee. asm_inline()
mitigation, used so far with base on:
https://github.com/iovisor/bcc/commit/2d1497cde1cc9835f759a707b42dea83bee378b8
does not seem to be needed for clang >= 12. no build issues happen
without it, so let's go ahead and remove it.
> tracee-ebpf: reformat suggestions for better readability

- tracee-ebpf/tracee/consts.go
- tracee-ebpf/tracee/tracee.bpf.c
Add ctime of the opened file to `security_file_open`.
The type was fixed from `unsigned long` to `u64` because it resulted in parsing errors of following argument.
This issue wasn't noticed because there are no arguments after the `ctime` argument of `sched_process_exec`.
> add ctime to security_file_open and fix variable type

- tracee-ebpf/tracee/co-re/struct_flavors.h
- tracee-ebpf/tracee/tracee.bpf.c
The following comment: https://github.com/aquasecurity/tracee/issues/1171#issuecomment-985966743 summarizes the whys of this PR.
---
commit bf6ff44 (HEAD -> 418corefixes, rafaeldtinoco/418corefixes)
Date:   Fri Dec 3 11:27:09 2021
tracee-ebpf: turn CO-RE v4.18 and beyond compatible
Fixes: #1171
For the VANILLA v4.18 (and beyond) kernels, we need the following 3
commits backported, together with this patch, in order to have tracee
eBPF object loaded correctly.
commit 0962590e5533
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Wed Oct 31 23:05:52 2018
bpf: fix partial copy of map_ptr when dst is scalar
commit e4f8d81c738d
Author: Steven Rostedt (VMware) <rostedt@goodmis.org>
Date:   Mon Jul 9 21:48:54 2018
cgroup/tracing: Move …
> 418corefixes

- docs/tracee-ebpf/output.md
- tracee-ebpf/main.go
in the help string it is mentioned that several output flags can be provided in sequence, specifically the out-file and err-file flags:
```
Examples:
--output json                                            | output as json
--output gotemplate=/path/to/my.tmpl                     | output as the provided go template
--output out-file:/my/out err-file:/my/err               | output to /my/out and errors to /my/err
--output none                                            | ignore events output
Use this flag multiple times to choose multiple output options
```
Although it states that the flag should be provided multiple times the example shows differently.
> fix help on output flags

- .github/workflows/pr.yaml
- Makefile.one
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- builder/Makefile.docker
- builder/README-containers.md
- builder/README.md
- embedded-ebpf.go
- tracee-ebpf/Makefile
- tracee-ebpf/main.go
- tracee-rules/engine/engine.go
- tracee-rules/input_test.go
- tracee-rules/regosig/aio_test.go
**tracee: a new makefile is born**
Original Makefile will be kept until all targets, release process and
docker container functionalities are in place. The new Makefile(s) are
meant to be used by:
$ make -f Makefile.new <target>
> **Note:** DO NOT mix usage of ./Makefile, ./tracee-ebpf/Makefile &
> ./tracee-rules/Makefile with ./Makefile.one. Make sure to wipe all
> "dist" directories before using Makefile.one.
The new Makefile targets are: (fix this)
$ make all                  # build tracee-ebpf, tracee-rules & rules
$ make env                  # show makefile environment/variables
$ make reqs                 # verify build requirements
$ make core                 # build ./dist/tracee.bpf.core.o
$ make non-core             # build ./dist/tracee.bpf.XXX.o
$ make tracee-ebpf          # …
> tracee-ebpf: a new Makefile

- tracee-ebpf/tracee/tracee.bpf.c
related to #1237
@yanivagman and i did some investigating on the bug.
we understood that the order of the variables on the stack solves the issue.
there's probably a bug somewhere with CORE+clang that creates some overflow or stack override.
changing the order of the variables avoids the override.
> reorder variables on stack

- cmd/tracee-ebpf/printer.go
- tracee-ebpf/tracee/tracee.bpf.c
This PR fixes two bugs:
1. table-verbose printer printed an incorrect value of the host ppid
2. host ppid should be `real_parent->tgid` (pid in userspace) and not `real_parent->pid` (tid in userspace)
> tracee-ebpf: fix ppid

- tracee-ebpf/tracee/events_config.go
- tracee-ebpf/tracee/tracee.bpf.c
added a event for alerting about hidden process.
in case of inode number that is 0 in dir file of process in /proc - Glibc will ignore it and wont show it
the event is checks if the inode is zeroed and it is - its alerting in tracee console (or the asked output)
example of alerting in json format about porcess hidden with pid 1:
{"timestamp":1638302644352381023,"processId":4393,"threadId":4393,"parentProcessId":4286,"hostProcessId":4393,"hostThreadId":4393,"hostParentProcessId":4286,"userId":1000,"mountNamespace":4026531840,"pidNamespace":4026531836,"processName":"top","hostName":"itamar-VirtualB","containerId":"","eventId":"1032","eventName":"hidden_inodes","argsNum":1,"returnValue":0,"stackAddresses":null,"args":[{"name":"process_hidden","type":"char*","value":"1"}]}
> added Hidden inodes event

- tracee-ebpf/tracee/events_arm64.go
commit ce77ccc8470e ("Feature/support 32 bit syscalls (#1196)") added
events that did not exist for arm64 architecture. This commit adds those
events to the list of undefined, to arm64, syscalls list.
> tracee-ebpf: fix arm64 compilation due to inexisting events

- tracee-ebpf/tracee/events_config.go
- tracee-ebpf/tracee/tracee.bpf.c
Fixes: 1208
Mitigates: 1129
- Remove Dup2EventID from the default set (unsupported by arm64)
- Revert fix made by 48654aa ("fix sockaddr struct overflow and change
error message") only in arm64, as its verifier isn't passing that
change. Added as a TODO to fix issue: #1129.
> tracee-ebpf: enable apple M1

- tracee-ebpf/tracee/argprinters.go
- tracee-ebpf/tracee/events.go
- tracee-ebpf/tracee/events_processor.go
As a preparation for having higher level events, this PR moves events processing methods to the end of processEvents function. 
In addition, events sorting (#1103) can then be placed before the events are being processed, which might be required for some features.
> tracee-ebpf: reorder events processing

- tracee-ebpf/tracee/tracee.bpf.c
> tracee-ebpf: fix missing sched_process_exit with pid=new

- pkg/containers/containers.go
- tracee-ebpf/tracee/events_pipeline.go
- tracee-ebpf/tracee/events_processor.go
This PR adds cgroup ctime information which can be used to track containers start time.
Instead of using the WalkDir function to find a specific cgroup, this PR implements a recursive function that is more efficient as it
only stats a directory if its name has a given suffix. By doing so, performance is 5 times better than the use of WalkDir for this specific case.
In addition, this PR fixes the following issue (thanks @rafaeldtinoco for spotting this):
When container filter is set, we might treat essential events such as cgroup_mkdir as "false container positives".
Such events should be processed before checking for false positives.
This PR fixes this by placing the check for false positives after processing the events
> tracee-ebpf: add container cgroup ctime

- tracee-ebpf/tracee/events_definitions.go
- tracee-ebpf/tracee/tracee.bpf.c
We noticed that the flag could have `true` value for multiple `sched_process_exit` events if they happen at almost the same because of concurrency issue (value used in the `do_exit` function in an atomic way, but we use the value afterwards so we are vulnerable to concurrent changes in the value).
> Bugfix: Add warning docs for group exit flag about race conditions

- cmd/tracee-ebpf/main.go
To fix misleading error message, e.g., when the BPF object cannot
be loaded from the /tmp/tracee directory.
> tracee-ebpf: handle error when BPF object cannot be loaded

- tracee-ebpf/tracee/tracee.go
mem_prot_alert event no longer depends on mmap and mprotect events as we now save syscall args anyway.
Remove these dependencies
> tracee-ebpf: remove mem_prot_alert dependencies

- pkg/containers/containers.go
The function used to recompile a constant regex, now it is precompiled on module load and reused for matching.
> containers: optimize getContainerIdFromCgroup

- tracee-ebpf/tracee/process_tree.go
solves #1366 
by changing the return to continue while error occurs .
if you want i can also remove the error check in the creation of Tracee to verify it never crush on that case
> change to conitine instead exit while error occurs

- tracee-ebpf/tracee/events_definitions.go
- tracee-ebpf/tracee/tracee.go
Some events depend on other events to function properly.
Add a new field to event definition to declare those dependencies.
When an event is chosen by the user, set its dependencies essential.
This change will also help with the introduction of higher level events (#1310),
that are derived from other events received in userspace.
> tracee-ebpf: introduce event dependencies

- cmd/tracee-ebpf/main.go
- go.mod
- go.sum
- tracee-ebpf/tracee/argprinters.go
- tracee-ebpf/tracee/events_decoder.go
- This is needed bump to solve https://github.com/aquasecurity/tracee/issues/295
- It contains fixes to breaking changes related to parseArgs
- https://github.com/aquasecurity/libbpfgo/issues/108 was discovered during this PR (should be resolved in the next libbpfgo version)
> Bump to libbpfgo v0.2.3-libbpf-0.6.1 with libbpf 0.6.1

- Makefile.one
- tracee-ebpf/Makefile
We already have code under pkg that requires CGO flags
to compile and run. Therefore, we run them in the
test-tracee-ebpf target.
Resolves: #1369
> chore: run tests in the pkg subdirectories

- builder/Makefile.tracee-container
- builder/Makefile.tracee-make
- cmd/tracee-ebpf/main.go
After commit a5bc030, tracee-make stopped being able to run tracee-ebpf because the lack of '/sys/kernel/security' dir inside the container. That also happened to any other system not providing that file.
Exit only if lockdown mode is explicitly set to CONFIDENTIALITY, otherwise ignore it.
Fix: #1396
> main.go: fix missing security lockdown sysfs file

- go.mod
- go.sum
libbpfgo recently added 2 needed fixes:
commit 5e89006 ("libbpfgo: use perf_buffer__new new API and fix style") and commit 5d2336e ("kprobe: remove legacy kprobes and unneeded includes").
Together they fix a panic happening in main branch:
$ sudo ./dist/tracee-ebpf
TIME             UID    COMM             PID     TID...
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=...
whenever libbpf executes perf_buffer__new() using the old, and deprecated, prototype. This change makes sure that libbpfgo will always call perf_buffer__new() using the new prototype.
Fix: #1383
> libbpfgo: bump to commit 5e89006 to include fixes

- tracee-ebpf/tracee/events_processor.go
Hi this PR solves #1400 by creating a new helper function that fix the type bug and change the process context assignment in the sched_process_fork_event and sched_process_exec_event
> fixed type mismatch with the processCtx

- tracee-ebpf/tracee/filters.go
Remove buggy casting of inequality_filter value to uint32.
Correct type expected for map's value is uint64.
Fix #1417
> tracee-ebpf: fix inequality filter

- 3rdparty/btfhub.sh
btfhub-archive caching will be performed by github actions. Allow a way to skip the initial fetching logic (unneeded for the PR checks).
@danielpacak let me know if this suits our needs for the PR checks. I can make changes if you need something else.
> btfhub.sh: allow skipping initial fetch

- tracee-ebpf/tracee/co-re/missing_definitions.h
- tracee-ebpf/tracee/tracee.bpf.c
Add missing cap_opts definition in CO-RE to fix cap_capable event which
didn't monitor the requested capabilities correctly.
Fix #1341
> tracee-ebpf: fix cap_capable when using CO-RE

- cmd/tracee-ebpf/internal/flags/flags-filter.go
- cmd/tracee-ebpf/main.go
- pkg/containers/containers.go
- tracee-ebpf/tracee/filters.go
- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
Add container id filter by mapping the container id to cgroup id and
using it to filter in kernel.
Close #255
> tracee-ebpf: introduce container id filter

- cmd/tracee-rules/main.go
- tracee-rules/benchmark/benchmark_test.go
- tracee-rules/engine/engine.go
- tracee-rules/engine/engine_test.go
During the performance testing that @mtcherni95 and I are doing, we've found that one of tracee-rule's bottlenecks (especially when running with low cpu constraints) is blocked channels on sending and receiving. We've also measured high times spent in `runtime.futex`, which is related to the channel blocking as I will demonstrate.
This PR enables configuring the event channels buffers that stream to signatures in tracee-rules. The default value set in the CLI is 1000. This should decrease the channel blocking overhead when some signatures receive many events, and reduce time in context switching between the signature go routines.
The PR also introduces a `Config` struct for the tracee-rules engine.
First, the case of unbuffered channels: 
Currently, signatures in the rules engine are …
> Buffered signature channels

- .github/workflows/pr.yaml
- .github/workflows/publish-tracee-tester.yaml
- .github/workflows/scheduled-signatures-test.yaml
- tests/Makefile
We've already published aquasec/tracee-tester:latest to [DockerHub](https://hub.docker.com/r/aquasec/tracee-tester) so we can just use it for testing.
> chore(ci): skip building aquasec/tracee-tester:latest container image

- .github/workflows/pr.yaml
- .github/workflows/scheduled-signatures-test.yaml
- tests/tracee_test.go
Gives some insights into (failing) tests run in the CI workflow
```console
$ go test -v -run "TestTraceeSignatures" ./tests/tracee_test.go \
-tracee-image-ref "tracee-nocore:latest" \
-tracee-tester-image-ref "aquasec/tracee-tester:latest" \
-tracee-signatures "TRC-2"
=== RUN   TestTraceeSignatures
=== RUN   TestTraceeSignatures/tracee-nocore:latest/TRC-2
2022/02/04 14:23:41 Starting container id: eb7dfe6d44e3 image: testcontainers/ryuk:0.3.3
2022/02/04 14:23:41 Waiting for container id eb7dfe6d44e3 image: testcontainers/ryuk:0.3.3
2022/02/04 14:23:41 Container is ready id: eb7dfe6d44e3 image: testcontainers/ryuk:0.3.3
2022/02/04 14:23:41 Starting container id: 3c40da3e1a92 image: tracee-nocore:latest
2022/02/04 14:23:41 Waiting for container id 3c40da3e1a92 image: tracee-nocore:latest …
```
> test(smoke): follow tracee container logs and print them out to error log

- cmd/tracee-ebpf/internal/flags/flags-filter.go
- cmd/tracee-ebpf/main_test.go
- tracee-ebpf/tracee/events_pipeline.go
Currently we don't trace existing container processes when a container
filter is set. This behavior is due to using the NewPidFilter when
a container filter is set. As we now use cgroups to identify
containers (and not by checking that pid != host_pid like we used to),
we can remove this extra filter to trace existing container processes
as expected by the filter.
While at it, fix the "!container" filter which currently doesn't work as the events are identified as false container positives.
Fix #1436
> tracee-ebpf: fix container filters

- .github/workflows/pr.yaml
- .github/workflows/scheduled-signatures-test.yaml
- builder/Dockerfile.alpine-tracee-container
- builder/Makefile.tracee-container
- builder/entrypoint.sh
- cmd/tracee-ebpf/main.go
- docs/building/containers.md
- tests/tracee_test.go
```
This commit is the result of a broader discussion regarding how we
should distribute tracee and how CO-RE and non CO-RE feature, and wording,
should be handled.
We, now, will have the following container images:
- tracee:latest
- tracee:full
And they are generated by:
- make -f builder/Makefile.tracee-container build-tracee
- make -f builder/Makefile.tracee-container build-tracee-full
And might be tested by:
- make -f builder/Makefile.tracee-container run-tracee
- make -f builder/Makefile.tracee-container run-tracee-full
Obs: images need to be built before run targets are executed.
Both images can run:
- tracee-eBPF with CO-RE
- tracee-eBPF with CO-RE + BTFHub (tailored BTF files)
- tracee-eBPF non CO-RE (from /tmp/tracee non CO-RE eBPF obj)
So, one may built the non CO-RE object by …
```
> builder: container images: slim and full

- .github/workflows/release.yaml
- builder/Dockerfile.alpine-tracee-container
- builder/Makefile.release
- builder/Makefile.tracee-container
This PR:
- Creates a new `Makefile.release` which has two targets:
- Snapshot
- Builds tracee-ebpf, tracee-rules, rules
- Builds an archive of build artifacts along with license
- Takes checksum of archive
- Builds container images
- Publish
- Pushes container images to dockerhub
- Creates github release with the build artifact archive 
For both of these targets the main environment variables to set are:
PUSH_DOCKER_REPO (default: aquasec/tracee)
SNAPSHOT_VERSION - the tag or SHA to label the release/snapshot as (default: latest git SHA)
This PR also does the following:
- Updates the github action for releasing to use this new makefile
- Fixes existing Makefile to cleanup intermediate images
> New release workflow

- tracee-ebpf/tracee/tracee.bpf.c
- tracee-ebpf/tracee/tracee.go
string_store map is no longer necessary (used as a workaround for compilation errors on older clang/libbpf versions)
Remove it.
> tracee-ebpf: remove string store map

- builder/entrypoint.sh
- cmd/tracee-ebpf/main.go
- cmd/tracee-ebpf/printer.go
- cmd/tracee-rules/main.go
- docs/integrations.md
- go.mod
- go.sum
- pkg/counter/counter.go
- pkg/counter/counter_test.go
- pkg/external/external.go
- tracee-ebpf/metrics/prometheus.go
- tracee-ebpf/metrics/stats.go
- tracee-ebpf/tracee/events_pipeline.go
- tracee-ebpf/tracee/events_processor.go
- tracee-ebpf/tracee/net_events.go
- tracee-ebpf/tracee/tracee.go
- tracee-ebpf/tracee/write_capture.go
- tracee-rules/engine/engine.go
- tracee-rules/metrics/prometheus.go
- tracee-rules/metrics/stats.go
* Adds prometheus metrics endpoint to tracee-ebpf cli enabled by flag (defaults to `:3366/metrics`)
* Adds prometheus metrics endpoint to tracee-rules cli enabled by flag (defaults to `:4466/metrics`)
* Adds engine stats
* Moves tracee-ebpf counter to it's own package (reused in engine stats)
* Adds metrics package which registers tracee-ebpf and tracee-rules stats to prometheus
* Move stats definition to metrics package (as part of stabilization #1250)
As part of #887
> Prometheus support

- .gitmodules
Changed `libbpf` submodule link to use HTTPS instead of SSH so the `tracee` git repository can be cloned recursively even on machines that do not have an SSH public key registered on Github.
> Use HTTPS link instead of SSH link for git submodules

- tracee-ebpf/tracee/argprinters.go
Simply change the way in which pointer arguments are parsed into a hex string in `parseArgs`. `fmt.Sprintf`, due to it's need to support many types of operations, can be less performant than using more specific operations. In this case, simply replacing `Sprintf` with a string concatenation conversion functions removes this code path bottleneck.
First a flame graph comparison:
With Sprintf:
Without:
Note the cpu percentage decrease in processEvents at the top of the screenshots (which should translate to gains in other places, hopefully in more time for event processing and signature handling).
In addition i've performed a benchmark between these two functions:
```
package tohex
import (
"fmt"
"strconv"
)
func SprintFToHex(val uintptr) string {
return fmt.Sprintf("0x%X", val)
}
func …
```
> parseArgs: replace Sprintf with string concat

- deploy/kubernetes/tracee-postee/tracee.yaml
- docs/install/kubernetes.md
the Postee k8s was updated to use the http port with [8082](https://github.com/aquasecurity/postee/blob/main/deploy/kubernetes/postee.yaml#L97)
> fix: k8s tracee manifests

- docs/rules-authoring.md
#1489 reported a few different issues with broken links in documentation. #1497 fixed some of them, this fixes the rest.
> Fix links in documentation

- types/protocol/protocol.go
- types/protocol/protocol_test.go
In continuation of this from #1482:
> > In addition:
> > 
> > 1. in protocol.go we are exposing functions like `Origin`, `ContentType`, `Header` but the fields of `Event` and `EventHeaders` are also exported. What am I missing?
> > 2. in particular, `EventHeaders.Custom` is exported and a user might use the library wrongly and addressing to a `nil` `Custom` field causing a program crash/panic.
> 
> 1. The functions are there to ensure an abstracted access to those headers. IMO I'm perfectly fine with unexposing the headers and providing access only through receivers. However, that would complicate event building so maybe we can suffice using just the suggestion below (2)
> 2. Then as part of what I wrote above, at a minimum we could unexpose the`Custom` field and expose a `SetHeader` …
> protocol: encapsulate custom event headers

- Makefile
Solves #1509
This PR:
1. Adds a script(`test-types`) to test the `types` module since it was missing from tests.
2. Adds `test-types` to `make test`.
3. Adds a job to verify types in the PR github workflow.
> Makefile: add types module testing

- go.mod
- go.sum
Hi 
I just added to `libbpfgo` a helper that enables to hold all the kernel symbols.
This update will help #1508, #1222, and #1195 
I just update `go.mod` and `go.sum` files to use the last commit of `libbpfgo`
solves #1520
> change the libbpfgo to latest

- cmd/tracee-ebpf/internal/flags/flags-capture.go
- docs/tracee-ebpf/capture.md
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/events_definitions.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/net_events.go
- pkg/ebpf/tracee.go
- pkg/procinfo/procinfo.go
add options to separate captured pcap files by their process context.
two output options were added: 
- separating by hostPid
- separating by containerId
in tracee output folder, the captured pcaps would be captured under the containerId folder ("host" is used when containerId from process context is empty), in this format:
- separating by hostPid:
<tracee_out>/host/<process_name>_<process_id>_<process_start_time>.pcap
- separating by containerId:
<tracee_out>/<containerId>/captured.pcap
- user didn't choose separating the pcaps:
<tracee_out>/host/captured.pcap
more details about how we separate:
instead of have one pcapWriter for tracee, we now have a map of pcapWriters, where the key is packetContext. packetContext is generated for each packet, and depends on whether the user chose to …
> Separate pcaps

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/initialization/kconfig.go
- pkg/ebpf/tracee.go
Changed kconfig loading to be expandable, and added kconfigs which are required in the future to calculate page address.
Fix #1504
> Load expened kconfig to BPF

- pkg/bufferdecoder/eventsreader.go
This fixes an issue with gob encoding where `trace.SlimCred` was registered but when we parse the SlimCred argument it's parsed as `bufferdecoder.SlimCred`.
The fix simply adds a cast after the decoding, which should break on compile time if either of the contracts change.
> decoding: cast SlimCred to trace.SlimCred

- tests/tracee_test.go
Tests always fail with:
`error creating Tracee: could not read /boot/config-5.11.0-1028-azure: stat /boot/config-5.11.0-1028-azure: no such file or directory\n`
Fix this
> tests: mount /boot for smoke tests

- pkg/ebpf/initialization/kconfig.go
#1532 fixed always failing tests issue, however, it didn't fix the root cause of the problem.
#1512 mistakenly returned an error when it failed to load kconfig values, instead of assuming values as was done before.
This PR fixes this.
> tracee-ebpf: fix boot mount error

- pkg/ebpf/net_events.go
- pkg/ebpf/tracee.go
solves #1529.
introducing new struct `netPcap` to hold both the writer, and the file object. this way, on netExit, we can access the file object and close it (note: flushing the ngWriter is adviced before closing the underline file).
also, changed name of Tracee struct field: netPcap to netCapture.
> close pcap files instead of just deleting from mapping

- pkg/containers/containers.go
- pkg/ebpf/events_definitions.go
- pkg/ebpf/tracee.go
- pkg/ebpf/user_mode_events.go
This PR adds existing_containers event that lists all the containers which were present once tracee started.
Using this information in combination of the runtime `container_create` event it is now possible to have the complete picture of the containers running in the system, which can then be used by tracee-rules.
Once #1278 will be completed, we can remove this event and pass this information as part of the new tracee-ebpf to tracee-rules protocol.
> tracee-ebpf: add existing_containers event

- go.mod
- go.sum
- pkg/ebpf/c/tracee.bpf.c
This currently causes a bunch of deprecated API warnings, so keeping this as a draft until I fix those issues, and mark libbpfgo v0.2.5-libbpf-v0.7.0 as an official release.
Info on the deprecated `bpf_map_def`:
- https://github.com/libbpf/libbpf/commit/d788cd57b54c179a657f823cbe56c868f6974924
- https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#drop-support-for-legacy-bpf-map-declaration-syntax
> Upgrade libbpfgo and libbpf for v0.7.0

- pkg/ebpf/events_processor.go
- pkg/ebpf/net_events.go
fixes #1544.
in `cgroup_rmdir` event, get the container id from the tracee Containers map. use this container id to get the pcap context, and close properly.
this approach forces getting the pcap context using the `container id`, and not the `hostTid` - therefore, created `getContainerPcapContext` func (and also `getProcessPcapContext`, `getHostPcapContext`) and generalized `getPcapContext`.
> fix container pcaps not being closed

- pkg/ebpf/c/tracee.bpf.c
SEC("classifier") is now deprecated: See https://github.com/libbpf/libbpf/wiki/Libbpf-1.0-migration-guide#bpf-program-sec-annotation-deprecations
> switch to "tc" instead of "classifier"

- cmd/tracee-rules/output.go
- tests/tracee_test.go
To mitigate loosing detections when tracee-ebpf is not
ready when we trigger detection.
> test(smoke): wait for tracee pid file before sigs are triggered

- pkg/containers/containers.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
Container removal didn't take into account cgroup hierarchy id, unlike
cgroupMkdir (container creation).
Under cgroup v1 environments, this might cause running containers to be
removed before they are actually removed. In case another container has
the same cgroup id, but in another cgroup hierarchy, the removal of such
a container will also remove the first one.
Fix this by updating the container maps for only one cgroup hierarchy (cpuset).
Close #1534
> tracee-ebpf: fix container removal in cgroup v1

- cmd/tracee-rules/output_test.go
- cmd/tracee-rules/templates/rawjson.tmpl
Some users have reported a breaking change when we changed `Finding.Context` to `Finding.Event.Payload`.
This PR updates the `rawjson.tmpl` to be backwards compatible with to the previous struct(from 0.6.5). Later json templates need to be versioned appropriately (A discussion on this will be opened in the near future).
> templates: change rawjson.tmpl to be backwards compatible

- Makefile
- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- packaging/Dockerfile.fedora-packaging
- packaging/Dockerfile.ubuntu-packaging
We've declared OPA v0.35.0 in go.mod, but we are
using v0.33.1 throughout builder config files.
> fix(deps): use OPA v0.35.0 in builder config files

- pkg/containers/containers.go
This PR fixes the first case described in #1563
I've confirmed this works in a relevant local environment by tracing `cgroup_mkdir` and `container_create` events.
> containers: add missing detection for containerd

- Makefile
@rafaeldtinoco 
This is in preparation for container enrichment, the issue arised when importing `containerd`'s runtime SDK, compilation would fail due to relocations, as I understand it most go modules are compiled with position independence by default but clang doesn't do so, and so conflicts sometimes happens with libbpf.
This flag should solve those issues.
> Makefile: add "-fPIC" to libbpf compilation flags

- Makefile
Resolves #1542
Although checking the availability of a package in `checklib` rules,
the `pkg-config --libs` command should be used instead of hardcoded
`-lelf -lz` flags to support edge cases (for example,
when the libraries aren't located in the default directories).
cc @rafaeldtinoco
> Call pkg-config --libs to get dynamic package libs flags

- Vagrantfile
Running make -f builder/Makefile.mkdocs on macOS doesn't really work.
With this patch to Vagrantfile we can run MkDocs server in Vagrant
guest machine and forward it to macOS host on http://localhost:8000.
> chore(docs): preview mkdocs on macOS

- builder/Makefile.release
> Remove 'v' from git tag used in image tags

- pkg/ebpf/c/tracee.bpf.c
@grantseltzer this fix could land in this release as it is the only thing blocking tracee-ebpf to work in arm64 currently.
In order to have tracee-ebpf AND tracee-rules working (at least the events needed by existing signatures), I have opened https://github.com/aquasecurity/tracee/issues/1588.
@AnaisUrlichs I believe that with this one you may start playing with tracee-ebpf and tracee-rules in arm64 VMs.
> arm64: fix compilation error by removing undefined cast

- .github/workflows/release.yaml
- RELEASING.md
- builder/Makefile.release
- builder/Makefile.tracee-make
The new release workflow has a flaw where the tar file asset does not contain the tracee-ebpf and tracee-rules binaries. This appears to be because the actual build is done in a docker container but that container is invoked with the `-it` flag, causing the build to fail. This PR removes those flags.
See failing command here: 
https://github.com/aquasecurity/tracee/runs/5631481033?check_suite_focus=true#step:4:1277
This also adds a RELEASING markdown file consistent with other Aqua projects.
> Remove interactive tty flags from docker run when building, RELEASING.md

- cmd/tracee-ebpf/main.go
This PR:
* Document the potential breaking behavior if enabling the debug flag
* Debug protects the `--metrics` init flag print
Close #1581
> tracee-ebpf: debug protect `--metrics` stdout prints

- .github/workflows/mkdocs-latest.yaml
To avoid automatically publishing release candidates on https://aquasecurity.github.io/tracee/v0.7.0-rc-1/
> chore: skip publishing documentation for release candidates

- deploy/grafana/README.md
- deploy/grafana/tracee.json
- docs/tutorials/deploy-grafana-dashboard.md
Adds a json for importing a tracee metrics dashboard (for both tracee-ebpf and tracee-rules).
An example of the dashboard:
This provides a simple demonstration of the usage for the prometheus metrics feature.
> add grafana dashboard for tracee metrics

- cmd/tracee-ebpf/internal/flags/flags-capture.go
- cmd/tracee-ebpf/internal/flags/flags-filter.go
- cmd/tracee-ebpf/main.go
- docs/tracee-ebpf/trace-options.md
- pkg/bufferdecoder/net_decoder.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
- pkg/ebpf/filters.go
- pkg/ebpf/net_events.go
- pkg/ebpf/tracee.go
Hi 
this PR solves #1514 
by separate the `net_packet` to new numbering of events which will be only for network events and adding the `net` option flag to the `-trace`  flag
> enable tracing net_packet event

- pkg/ebpf/events_derived.go
- pkg/ebpf/tracee.go
This PR refactors the `deriveEvent` function and mechanism so that it is:
1. More declarative in syntax
2. Takes less cpu time (reduced by 3.91% of overall time in code path)
The `Tracee` object now initializes a map on startup of type `map[int32]map[int32]deriveFn`, this represents a map of a derived EventID to its possible derivations and their corresponding deriving functions.
Then `deriveEvents` can simply check if the current event has any derivations to be done and get the map of all it's derivative functions, instead of calculating that map on each `deriveEvents` call which causes unnecessary GC work due to the map and function variable assignments.
This improves CPU usage in runtime and allows a more declarative approach to defining event derivatives through the map initialization …
> Refactor event derivation mechanism

- pkg/ebpf/net_events.go
- pkg/ebpf/tracee.go
using lru.Cache as the map of the opened pcapWriters. a callback is called whenever a key is removed from this cache (due to LRU, or specifically remove due to process/container exit), enabling us to close the FD.
i set the limit to be 512 - just an arbitrary number that seems to me as good enough to let tracee use 1024-512 FDs, and also not having the overhead of opening an already existing pcap too many times.
if there are any other things to consider here - please let me know!
> limit number of open pcap using lru.Cache

- pkg/ebpf/tracee.go
on the user space part, if the network interface chosen by the user has the `FlagLoopback` set on it - attach only to the ingress of this interface.
solves #1418
> capture packets on loopback device only on ingress to avoid duplications

- docs/install/prerequisites.md
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
- pkg/ebpf/initialization/ksymbols.go
- pkg/ebpf/tracee.go
Load symbols from /proc/kallsyms to BPF map.
The first commit is a patch until the loading of kallsyms will be merged into libbpfgo, so please only review the second commit.
This is a first step needed for #1357.
Fix #1505
> Load kallsyms values

- pkg/ebpf/tracee.go
The conditions to load load were not matching types used.
The conditions to attach net events were missing.
> bugfix: pkg/ebpf: fix bug of loading net events when not required

- cmd/tracee-ebpf/internal/flags/debug.go
- cmd/tracee-ebpf/internal/flags/debug_test.go
- cmd/tracee-ebpf/main.go
The debug settings is now defined in the `flags` package.
The PR also uses Tracee's internal debug setting instead of the previous global var where it was needed.
This was done so flags can access the debug status without passing it as an arg.
> refactor: move debug setting to flags package

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
Hi 
Sometimes malware try to create a secret backdoor to communicate with the user-space, which could be done by creating a file under /proc with a special file operation that handles that the malware tasks.
This PR on of 2 that will solve #1613 which is the about this problem around the entire the Linux kernel (not just under /proc).
Its added an event that trace calls of `proc_create` that communally used by malwares to deploy files under /proc in order to create a commination between the kernel space to the user space.
> add proc_create event

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
Hello 
This PR solves #1565 by adding kprobe to `call_usermode_helper()`.
`call_usermode_helper` is a function that is commonly used by kernel rootkits to interact with the user space from the kernel.
Here is the function man page:
[https://www.kernel.org/doc/htmldocs/kernel-api/API-call-usermodehelper.html](https://www.kernel.org/doc/htmldocs/kernel-api/API-call-usermodehelper.html
)
And This is an example of using this function to get container escape:
[https://xcellerator.github.io/posts/docker_escape/](https://xcellerator.github.io/posts/docker_escape/ )
> Adding call_usermode_helper event

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
Hi 
This PR is the second PR (2nd out of 3) that will solve #1613 .
It adds to Tracee a kprobe event that traces calls to 'debugfs_create_file' which is a kernel function that is used to create a file under the debug filesystem (under /sys/fs/debug).
BTW this is the main page of the function:
[https://www.kernel.org/doc/htmldocs/filesystems/API-debugfs-create-file.html](https://www.kernel.org/doc/htmldocs/filesystems/API-debugfs-create-file.html
)
The event's arguments will be the file name, its path, mode, and the file operations pointer in the memory
> added debugfs_create_file event

- cmd/tracee-ebpf/main.go
- pkg/bufferdecoder/decoder.go
- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/protocol.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_amd64.go
- pkg/ebpf/events_arm64.go
- pkg/ebpf/events_definitions.go
- pkg/ebpf/events_derived.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
Hi
this is a fixed version of #1222 PR, 
Its solves #1257 
I put it now as Draft until it will pass a CR  (:
**how it works:**
A special ioctl cmd is executed during tracee initialization. This
special ioctl cmd tells eBPF kprobe function that it should look the
syscalls table for a list of given syscalls and their addresses.
By checking runtime syscall handlers addresses, it is possible to know
if the handlers were hijacked by a kernel module, for example. They way
way it works is this: if the syscall handler address is not in kernel
text segment boundaries, it means it is not part of running kernel
(likely a hook somewhere else).
> tracee-ebpf: add event to detect hooked syscalls

- Makefile
- pkg/events/sorting/sorting_test.go
- pkg/rules/engine/engine.go
- pkg/rules/engine/engine_test.go
Adds quality gate to test that code and tests are written
without race conditions. This allows catching issues similar
to #1629 and #1630.
Resolves: #623
> test: run unit tests with -race flag

- types/protocol/protocol.go
- types/trace/trace.go
- types/trace/trace_test.go
This is in preparation for PR 3 in #1644.
Matches the default headers of `protocol.Event` to the selector fields defined in `detect.SignatureEventSelector`.
> types: match EventHeaders to SignatureEventSelector

- cmd/tracee-rules/output_test.go
- go.mod
- go.sum
- pkg/rules/engine/engine.go
- pkg/rules/engine/engine_test.go
- pkg/rules/regosig/traceerego_test.go
As described in #1644 
This implements the header changes in #1645 
With this PR the engine signature selection will be decoupled from tracee-ebpf's events, and will be able to process any `protocol.Event` which existing signatures can support.
This will be in draft until #1645 is merged.
> engine: use the matching headers for signature selection

- pkg/rules/regosig/traceerego.go
- pkg/rules/regosig/traceerego_test.go
1. Removes the validation for trace.Event casting
2. In case of an irrelevant payload to a rego signature, no error will be returned, the document will simply not match
3. Adds relevant tests for invalid event payloads, where the finding is nil
> rules: allow generic protocol.Events in rego signatures

- Readme.md
- builder/entrypoint.sh
- docs/index.md
Fixes: #1658
This change re-creates the "trace" subcommand to our tracee:latest (future) docker image. Users may be able to execute `docker run tracee trace`, like they used to do before v0.7.
Fixes: #1658 
Please pick one and delete the others:
- Bug fix (non-breaking change which fixes an issue)
This change doesn't have a unit test but we're able to test if it is effective by not having failures in the PR workflow (on container building) and then generating the container locally and trying out multiple execution types:
```
$ make -f builder/Makefile.tracee-container build-tracee
```
It does not break current behavior:
```
$ docker run --rm --pid=host --privileged -v /etc/os-release:/etc/os-release-host:ro -v /sys/kernel/security:/sys/kernel/security:ro -e …
```
> entrypoint: restore trace subcommand for docker image

- pkg/rules/engine/engine.go
- pkg/rules/engine/engine_test.go
Fix an issue where events with a partial `Selector` headers without a `Source` field of value `"tracee"` would be unaccounted for in event dispatching.
Adds comments to explain event selection process.
Bug fix (non-breaking change which fixes an issue)
This shouldn't be a breaking change, unit tests were locally run to validate and a test path with a partial selector was added to `TestEngine_ConsumeSources`.
> engine: Accept partial non tracee source selectors

- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_test.go
Add support for `loff_t` in the `eventsreader.go` file.
Fixes: #1674 
- New feature (non-breaking change which adds functionality)
> add support for "loff_t" event argument type

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
- pkg/ebpf/events_derived.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/net_events.go
- pkg/ebpf/tracee.go
It is required to differentiate between different events configurations.
When an event is chosen, its bpf programs need to be loaded.
Some bpf programs might be used by different events, so it is required to know which events should be submitted to userspace, and which shouldn't.
In addition, not every event that is submitted to userspace needs to be emited to the user. For example, when a derived event such as container_create is chosen, the cgroup_mkdir event should be submitted to userspace, however, if the user didn't choose the cgroup_mkdir event, it shuoldn't be emitted as part of the output.
This PR dynamically creates the required configuration for each event according to the chosen events and their dependencies.
> tracee-ebpf: handle event configuration

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
Hi 
This PR is the third of 3 PR that solve #1613 .
It adds to Tracee a kprobe event that trace calls to `debugfs_create_dir`, which is a kernel function that is used by the kernel module to create directories under /sys/kernel/debug.
Here is the man page of the function from the kernel docs:
[https://www.kernel.org/doc/htmldocs/filesystems/API-debugfs-create-dir.html](https://www.kernel.org/doc/htmldocs/filesystems/API-debugfs-create-dir.html
)
The event will print the name of the dir and its path, here's s an example for output:
`04:33:27:509621  0      insmod           3426    3426    0                debugfs_create_dir   name: malware_poc, path: /sys/kernel/debug/
`
> add debugfs_create_dir event

- cmd/tracee-ebpf/internal/flags/flags-filter.go
- cmd/tracee-ebpf/main.go
- cmd/tracee-ebpf/main_test.go
- pkg/ebpf/events_definitions.go
for some events we need the ability to pass information to the user mode.
this results in internal events being exported to the user.
this commit marks those events as internal and makes them unfiltered
and doesn't print them to the user in the --list message.
This is a feature that will improve #1583 and #1561 .
- New feature (non-breaking change which adds functionality)
> Add internal event feature

- 3rdparty/btfhub.sh
- Makefile
"Smoke Test CO-RE" has issues when executing btfhub.sh during build
time:
HEAD is now at 83e0916 Documentation fix (#32)
Branch 'main-200' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main-200'
Deleted branch main (was 83e0916).
btfhub-archive not a repo dir
make[1]: *** [Makefile:503: btfhub] Error 1
go: downloading github.com/aquasecurity/libbpfgo v0.2.5-libbpf-0.7.0
That happens because of a bad existing sanity check. The "tracee-ebpf"
Makefile target should also place btfhub target as a dependency so the
files are always included in the resulting tracee-ebpf binary.
Please pick one and delete the others:
- Bug fix (non-breaking change which fixes an issue)
$ BTFHUB=1 make tracee-ebpf
The error has been observed from: …
> btfhub: fix compilation for when BTFHUB is enabled

- pkg/ebpf/events_definitions.go
Fix the naming convention of some events.
- Bug fix (non-breaking change which fixes an issue)
> fix event constants wrong convention

- pkg/ebpf/c/tracee.bpf.c
Change constants in the C code which are enumerating values to enums.
Fixes: #1678 
- Bug fix (non-breaking change which fixes an issue)
**Manual Test Setup**:
In Manjaro with kernel 5.10.101 compiled and run multiple events to check sanity.
> pkg/ebpf: use enums for enumerating defines

- pkg/ebpf/c/tracee.bpf.c
if dup failed, we returned without deleting syscall data from map.
fix not deleting syscall data on all cases in socket_dup
Fixes: #1717 
tested locally
- command 01: ./dist/tracee-ebpf -t e=socket_dup
> fix: delete syscall data on socket dup

- pkg/ebpf/events_definitions.go
- pkg/ebpf/tracee.go
Currently, in order to define which probes are required for an event to
function correctly, we either define the probes explicitly or use an
event dependency, which will load and attach the required probes.
This other method of defining the probes implicitly should be used only
when the event is a real dependency, and not just as a mechanism to load
and attach the other event's bpf program.
This commit explicitly defines which probes are required for an event to
function correctly, and always submit an event to userspace when it is
defined as a dependency of another event. In addition, it sets tracee to
always load all the bpf programs that exists on the BPF object file.
This is required to break the coupling between an event and the probes
used by it. It will also be required to support …
> tracee-ebpf: flatten event probe dependencies

- pkg/ebpf/events_derived.go
- pkg/ebpf/events_pipeline.go
- pkg/events/sorting/sorting.go
This PR:
1. Removes the sinking and derivation of events from processEvents
2. Adds a new event sinking pipeline stage
3. Adds a new event derivation pipeline stage
4. Makes the out channel buffer uniform across the pipeline stages (10000)
Relevant to #1684
This was done in order to have an enrichment stage (see #1572) in the pipeline, after the process stage but before deriving and sinking.
- Refactor (non-breaking change which adds functionality)
Unit tests were ran locally.
Manual testing:
In order to check that event derivation was working correctly I have done the following test:
1. Build tracee
2. Run it as such:`./dist/tracee-ebpf --trace event=cgroup_mkdir,container_create`
3. In parallel, start a container as such `docker run --rm redis`
4. A container_create event should be …
> pipeline: split process and sink stages

- pkg/ebpf/argprinters.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/events_definitions.go
- pkg/ebpf/events_derived.go
The shared_object_loaded event indicates a shared object was loaded to a process.
It relies on `security_mmap_file` kprobe.
The event is only generated if the calling syscall to `security_mmap_file` is `mmap` and if the requested protection has `EXEC`.
The other events are a memory protection lsm events that are meant to provide a debugging interface for research purposes.
> add shared_object_loaded and memory protections lsm events

- Readme.md
Previous `Readme.md` file change removed the documentation session because it was just a literal copy of `docs/index.md`. I'm bringing it back after @yanivagman requested saying there are users that couldn't find documentation and asked us about it.
Checking markdown translation in my repo.
> readme: bring the documentation session back

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
Event implementation uses a symbol which was introduced only in kernel version 5.8.
Fixed the bug using it and a bug of using the `get_symbol_addr` helper (global values are not supported in older kernels),
Also prevent event analyzing if splice failed, just to reduce overhead and wrong analyze of kernel's data.
This PR has a problem that old Manajro kernels don't have the `do_splice` symbol for some reason in `kallsyms` file, which make the event unloadable in these versions. Ubuntu 4.18 was fine though. I don't see a way to bypass it so it will be suffice for now.
fix #1659 
fix #1691
> bugfix: support dirty_pipe_splice in unexploited kernels

- pkg/containers/containers.go
- pkg/ebpf/events_enrich.go
- pkg/ebpf/tracee.go
@NDStrahilevitz is out for the next days and we needed the enricher merged before the next release. I have spoken with him about this fixes needs before he was out and I'm addressing issues observed in https://github.com/aquasecurity/tracee/pull/1572.
commit 109f5249
Date:   Tue May 17 02:20:12 2022
events_enrich: make sure queue flushing is ordered
Events enricher needs to make sure event is not sent to the out channel
before emptying the cache, for the same cgroupId, entirely. This commit
creates a "per cgroupId cache flush" transaction, guaranteed by a mutex.
Fixes: https://github.com/aquasecurity/tracee/pull/1572#discussion_r874024076
commit cc150850
Date:   Mon May 16 22:43:39 …
> Enrich container events review fixes

- cmd/tracee-ebpf/capabilities.go
- cmd/tracee-ebpf/main.go
- pkg/ebpf/events_definitions.go
- pkg/ebpf/probes/probes.go
- pkg/ebpf/tracee.go
This replaces the fix proposed in #1707
```
Date:   Thu Jun 2 12:41:49 2022 +0000
probes: add required dependency field
This is done through the following steps:
1. Split the probes into a separate module
2. Probes are handled implicitly through handles
3. Events have probe dependencies which includes
a handle and a required field
4. Attaching failure is handled according to the required field
```
Fixes: #1622
Testing is done through the TRC-9 test in a tracee-tester image running on GKE. Some PR jobs were temporarily removed in this PR to test it faster. They will be added back.
When the tests are passed this checkbox will be filled. This PR shouldn't be merged until then. …
> [REFACTOR] Separate probes and add new required field for probe dependencies

- pkg/ebpf/c/tracee.bpf.c
output dns events which are on top of tcp, not just udp.
supporing DNS events over TCP
Fixes: #1806
- command 01
- command 02
> dns events: support dns events over tcp

- deploy/kubernetes/tracee-falcosidekick/tracee.yaml
- deploy/kubernetes/tracee-postee/tracee.yaml
When caching was added to entrypoint the limits were not increased from
the deployment recipes, making tracee to fail with OOM in real
environments.
The default memory consumption shall be in between 768M and 1GB of ram
by default. That might be changed in a near future when performance
increases and less caching is needed.
Fixes: #1798
By the same user who reported the issue (while talking to me in Slack).
> k8s deployment: increase needed limits because of caching

- pkg/containers/containers.go
- pkg/containers/service.go
If an enrichment request is received with an unknown runtime
the enrichment service will try to enrich from all known registered
runtimes before failing.
This is done in order to fix repeated "unknown runtime" errors and failed
enrichments in kubernetes environments such as microk8s and k3s.
```
Date:   Wed Jun 8 10:47:02 2022 +0000
containers: add enrichment logic for unknown runtime
If an enrichment request is received with an unknown runtime
the enrichment service will try to enrich from all known registered
runtimes before failing.
This is done in order to fix repeated "unknown runtime" errors and failed
enrichments in kubernetes environments such as microk8s and k3s.
```
Fixes: #1786
Fixes: #1789
Tested manually through …
> [FIX] containers: add enrichment logic for unknown runtime

- pkg/ebpf/argprinters.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_definitions.go
- pkg/ebpf/probes/probes.go
create new event indicating process name change
using `__set_task_comm` kprobe to indicate event of process name change
Fixes: #1810
- command 01
- command 02
> event: set_task_comm

- pkg/events/derive/hooked_seq_ops.go
This event was broken in a recent refactor. This is a mix up fix.
issue: #1860
Fixes: #1860 
> fix: hooked_seq_ops bug

- pkg/ebpf/c/tracee.bpf.c
delete elements from module_init_map after done using them
delete elements from `module_init_map` after done using them in `kretprobe`.
Fixes: #1862
tested locally.
- run tracee: `./dist/tracee-ebpf -t e=do_init_module`
- load a kernel module: `insmod hello.ko`
- look whats in the map: `bpftool map dump name module_init_map` (should be empty now).
> do_init_module: delete from map after used

- signatures/rego/disk_mount.rego
- signatures/rego/disk_mount_test.rego
don't trigger signature TRC-11 if the process is runc
check if `processName` starts with `runc:` and if `threadId == 1` - if so, don't trigger the signature because it is expected behavior for `runc` process to mount devices upon container startup.
Fixes: #1611
tested locally.
- command 01 (on 1st shell): `./dist/tracee-ebpf -t e=security_sb_mount -o format:gob | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:gob`
- command 02 (on 2nd shell): `docker run --rm -it ubuntu:latest`
shouldn't trigger TRC-11 signature after this PR.
> signatures: fix runc false-positive on TRC-11

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/events.go
The inode mode (aka i_mode member of the inode) contains information
regarding the file's privileges and type.
Thus, it is interesting from security point of view to know its value
for executed files.
Fixes: #1888
> pkg/ebpf: add inode mode to sched_process_exec args

- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
commit 04efaaa6022837297d78c2060d7793d67ceb6963 (HEAD -> fix-panic-finit-module-event, pfork/fix-panic-finit-module-event)
Date:   Tue Jun 28 10:29:16 2022 -0400
Surface more errors and validate the newly created symbols map
Fixes: #1843
`sudo ./dist/tracee-ebpf -t e=finit_module` and loading a kmod
> Surface more errors and validate the newly created symbols map

- pkg/ebpf/c/tracee.bpf.c
exit tail calls for dup weren't called
- command 01
- command 02
> fix: dup exit tail calls not called

- pkg/ebpf/events_enrich.go
This PR solves two potential mutex locks that can occur in the enrichment pipeline. It also increases the queue sizes as a backup buffer.
```
Date:   Tue Jun 28 09:26:54 2022 +0000
enrich: read queue only once at enrich start
This commit includes two fixes:
1. In the enrichment receiving part of this pipeline stage,
the relevant queue is read with a mutex acquire at multiple points.
To avoid unnecessary points of failure with that I've moved this
queue acquisition to the top of the loop.
2. In the enrich sending routine, the enrich is sent to a queue while
a lock is acquired. If the queue is full the send will be stuck and
the lock will not be unlocked. The queue is now read before sending the
enrichment so the lock will always …
```
> enrich: fix enrichment queue locks

- builder/entrypoint.sh
- cmd/tracee-ebpf/capabilities.go
- cmd/tracee-ebpf/main.go
- cmd/tracee-rules/main.go
- docs/install/prerequisites.md
Enable tracee-ebpf and tracee-rules to keep running with high
capabilities if dropping capabilities failed, if configured to do so
by the user.
This will allow tracee to run in environment that don't allow
capabilities dropping.
Fixes: #1874 
> Bugfix: cmd: enable running with high capabilities by flag

- pkg/events/events.go
Fix wrong doc path of the events `setsockopt` and `security_socket_setsockopt`.
> bugfix: pkg/events: fix setsockopt doc mismatch

- docs/install/prerequisites.md
- pkg/containers/containers.go
- pkg/containers/utils.go
```
Date:   Mon Jul 4 15:29:33 2022 +0000
containers: mount cpuset on cgroupsv1
When cgroupsV1 is used, the cgroup controller is located at the host
/sys/fs/cgroup/cpuset. However, this fs is duplicated to the container's
filesystem and used instead of it when running tracee-ebpf
from a container. As a result, a different root cgroupId is given,
and existing cgroups are not detected for population on startup.
This fix makes tracee create a local mountpoint for the host's cpuset
if it detects usage of cgroupsV1.
```
Fixes: #1900
Fixes: #1338
You can test with either of these ways:
1. Add the log described in #1900, build tracee to a container and run. The log should be empty of the repeated cgroup 1 checks.
2. I. Start a redis …
> containers: mount cpuset on cgroupsv1

- pkg/containers/containers.go
This fixes the logic of creating the cgroup mount when in a container using cgroupv1. It adds an error check and creates the mount in tmpfs instead of the src directory. 
commit 04af9297f788782231e58cc831148f4f275a30e1 (HEAD -> breakup-capabilities-check-and-drop, pfork/breakup-capabilities-check-and-drop)
Date:   Wed Jul 13 18:17:08 2022 -0400
containers: move cpuset cgroup mount to tmpfs
commit d10100f36c7c0a64f762d7f5619d87436d5ecb45
Date:   Wed Jul 13 10:33:55 2022 -0400
Add error check to cpuset mkdir call
Fixes  #1945 
#1945 contains reproduction instructions
> capabilities: mount cpuset in tmpfs when in a container

- .github/workflows/release.yaml
The github actions runner isn't picking up the git tag for some reason 
commit d0a2b005cc219ce57cbc04520e8efdbad7a648f3 (HEAD -> manual-release-trigger, pfork/manual-release-trigger)
Date:   Thu Jul 14 11:38:56 2022 -0400
release: add manual trigger to workflow
> release: add manual trigger to workflow

- .github/workflows/mkdocs-dev.yaml
This adds a button to release dev documentation
commit d69dee9e73c067526b095f45724f489672abbfd8 (HEAD -> manual-dev-doc, pfork/manual-dev-doc)
Date:   Thu Jul 14 13:37:51 2022 -0400
docs: add manual trigger to dev docs
> docs: add manual trigger to dev docs

- pkg/containers/containers.go
- pkg/ebpf/tracee.go
```
Date:   Mon Jul 18 12:05:06 2022 +0000
containers: add Close function for cleanup
Currently Close() performs cleanup logic for the cpuset mounting done
on cgroupv1 environments.
```
Fixes: #1945
Test is done to ensure the cpuset mounting logic still works as expected on cgroupv1 environments.
1. Build tracee as container on a cgroupv1 environment.
2. Run some arbitrary container, for the sake of this example:
`docker run --rm redis`
3. Run tracee as such:
```
docker run \
--name tracee --rm \
--pid=host --cgroupns=host --privileged \
-v /etc/os-release:/etc/os-release-host:ro \
-e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host \
-e ALLOW_HIGH_CAPABILITIES=0 \
tracee trace -t event=existing_container
```
Expected output: an …
> containers: add Close function for cleanup

- pkg/ebpf/c/tracee.bpf.c
exit and exit_group syscall are always submitted to userspace even when not chosen by the user.
Only submit these events when required.
Manually 
- command 01
- command 02
> Should submit exit

- pkg/ebpf/events_enrich.go
If container is already running and a cgroup rmdir event happens,
enrichment code might try to close a nil channel. Check if channel
exists before trying to close it.
Fixes: #1999
Same test as the reproducer given in the issue.
> events_enrich: do not try to close nil channel

- pkg/ebpf/initialization/ksymbols.go
When reading `/proc/kallsyms` file, a symbol address is checked to
identify if the file was read correctly.
The "current_task" symbol is not available on ARM, so it had to be
changed to a symbol supported on all architectures.
Fixes: #2034
> pkg/ebpf: change authentication symbol for kallsyms

- docs/events/security_alerts/symbols_loaded.md
Fix wrong description of the event arguments in the event documentation
Fixes: #2052
> docs: fix `symbols_loaded` event doc

- builder/entrypoint.sh
When running tracee with the trace subcommand, a few seconds are wasted while probing for tracee-ebpf capabilities.
This is not required when the user is about to run tracee-ebpf anyway.
When running tracee with the trace subcommand, a few seconds are wasted while probing for tracee-ebpf capabilities.
This is not required when the user is about to run tracee-ebpf anyway.
Fixes: #1765 
> builder: Remove cap probing for trace subcommand

- tests/integration/tracee.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
delete minor unreachable code caused by t.FailNow
see https://go.dev/play/p/3AtpQLkd8t- for example:
```go
package main
import (
"testing"
)
func TestLastIndex(t *testing.T) {
t.Errorf("this line will print and exit")
t.FailNow()
t.Errorf("this line can't print")
}
/* output:
=== RUN   TestLastIndex
prog.go:8: this line will print and exit
--- FAIL: TestLastIndex (0.00s)
FAIL
Program exited.
*/
```
- command 01
- command 02
> delete minor unreachable code caused by t.FailNow

- cmd/tracee-ebpf/internal/printer/printer.go
- cmd/tracee-rules/input.go
- pkg/events/events.go
a bug was introduced in #2031 regarding the output of `map[string]HookedSymbolData`
fix: register gob map[string]HookedSymbolData and fix hooked_seq_ops argument type
> fix hooked_seq_ops output bug

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_processor.go
- pkg/ebpf/tracee.go
- pkg/events/derive/container_create.go
- pkg/events/derive/container_remove.go
- pkg/events/derive/derive.go
- pkg/events/derive/derive_test.go
- pkg/events/derive/detect_hooked_syscall.go
- pkg/events/derive/hooked_seq_ops.go
- pkg/events/derive/net_packet.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/trigger.go
- pkg/events/events.go
Retains the event context of the triggering event
(e.g. hooked_syscall gets the context of the insmod that preceded it)
Fixes: #2019
- `tracee-ebpf -t e=hooked_syscalls`
- load a kernel module with `insmod`
- the `hooked_syscall` event should have `insmod` as it's process name
> retain context of triggering event to the triggered event

- pkg/ebpf/events_derived.go
- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/symbols_loaded_test.go
Symbols loader make many errors, and by returning them from the
derive function it causes too much noise.
Change it so excess errors will be visible only while debugging.
Fixes: #2036
> pkg/events/derive: prevent spam errors with symbols_loaded

- builder/entrypoint.sh
- cmd/tracee-ebpf/capabilities.go
- cmd/tracee-ebpf/flags/capabilities.go
- cmd/tracee-ebpf/flags/capabilities_test.go
- cmd/tracee-ebpf/main.go
- docs/deep-dive/dropping-capabilities.md
- pkg/capabilities/capabilities.go
Add options to bypass capabilities dropping partly or entirely
in tracee-ebpf.
This will help to solve locally capabilities issues for developers or
users which face capabilities bug.
Fixes: #1996
> cmd/tracee-ebpf: add capabilities dropping bypasses

- cmd/tracee-ebpf/capabilities.go
- docs/installing/prerequisites.md
As the kernel documentation doesn't document any value above 2 for `/proc/sys/kernel/perf_event_paranoid`,
distributions are allowed to interpret any value above 2 as they want. To ensure that Tracee runs in a maximum
number of environment, Tracee should only drop CAP_SYS_ADMIN when perf_event_paranoid is lesser or equal to 2,
in order to avoid any distribution-dependent behavior.
Fixes: #2077 
> Lowering the thresold to drop CAP_SYS_ADMIN

- deploy/helm/tracee/Chart.yaml
This introduces tweaks and fixes for Postee UI for Tracee users.
This introduces tweaks and fixes for Postee UI for Tracee users.
See the following PRs:
- https://github.com/aquasecurity/postee/pull/441
- https://github.com/aquasecurity/postee/pull/435
- https://github.com/aquasecurity/postee/pull/419
> feat(deps): Bump up Postee Helm chart version.

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/events.go
```
Date:   Sun Aug 28 13:31:21 2022 +0000
tracee.bpf.c: optimize sys_enter and sys_exit
Optimize these hot path probes by moving the logic of event init and
submit to run conditionally in a tail call.
Only the following logic will run if no event submission is needed:
1. Storing task's current syscall
2. Storing syscalls arguments in task
```
Currently tested with this script (credits to @rafaeldtinoco):
```
#!/bin/bash
bpftool prog show > /tmp/progshow.$$
checkfile() {
prognum=$(echo $line | cut -d' ' -f1)
progname=$(echo $line | cut -d' ' -f2)
runtime=$(cat /tmp/progshow.$$ | grep ^$prognum | awk '{print $9}')
amount=$(cat /tmp/progshow.$$ | grep ^$prognum | awk '{print $11}')
if [[ $runtime -eq 0 ]]; then …
```
> ebpf: optimize SysEnter and SysExit probes

- pkg/events/derive/symbols_loaded.go
- pkg/events/derive/symbols_loaded_test.go
The errors received from the symbols loaded are expected to happen.
Thus, until we have a logger which enables us to declare this as a
warning, we need to silence the error so it won't be counted as an
error.
Fixes: #2036
> pkg/events/derive: silence symbols loaded errors

- pkg/ebpf/c/missing_definitions.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
```
Date:   Wed Aug 31 12:49:38 2022 +0000
ebpf: add get_task_syscall_id helper
This is used in events supporting the detect-syscall option, in order to
decouple them from the syscall_data_t struct tracking mechanism.
This decoupling is required for these events to function in the future
without calling sys_enter and sys_exit logic for every syscall.
security_file_open is intentionally left as is, because it will have
syscall tail call dependencies in the near future.
```
Fixes: #2133
Test by running:
`./dist/tracee-ebpf -o option:detect-syscall -t e=task_rename`
Wait for an event output and confirm a valid syscall is printed.
> ebpf: add get_task_syscall_id helper

- cmd/tracee-ebpf/capabilities.go
- cmd/tracee-ebpf/capabilities_test.go
- go.mod
- go.sum
- pkg/ebpf/probes/probes.go
- pkg/ebpf/tracee.go
- pkg/events/parse_args.go
After some e2e tests gone wrong, and broader discussion, a rollback to
previous libbpfgo version was decided to keep v0.8.2 stable. This commit
reverts recent changes:
- Revert "libbpf: upgrade to v1.0.0"
This reverts commit 911d01b70e5cd362472c283c2ab8184d1d3ec734.
- Revert "libbpfgo: update to latest (1.0.0+)"
This reverts commit eb1fe11db143e98bd1c3b8bcaed6056ff4c17589.
- Revert "parse_args: fix {get,set}sockopt new parse option"
This reverts commit fdacd945953feb6b97f1bcba3a6c52889cc3cdf3.
- Revert "capabilities: fix usage of kernel version interface"
This reverts commit 9001dbc8dd9b04ae36ff4ebbdd18329f9b315d45.
- Revert "deprecation: adjust deprecation warnings"
This reverts commit afa634764995681aad33d2c3cfb78e6a04fd41a6.
> release: prepare for 0.8.2 by reverting libbpfgo bump

- pkg/events/parse_args.go
- pkg/events/parse_args_test.go
libbpfgo currently parse the socket option argument in some cases to include "or" in the middle between to consts names. The reason is that the kernel has 2 consts with the same name. According to the context we know which constant is relevant. This PR fix the parsed option name to be the one we expect it to be.
Fixes: #2156
> pkg/events: fix socket option parse args edge cases

- cmd/tracee-ebpf/main.go
- cmd/tracee-rules/main.go
- docs/deep-dive/healthz.md
- docs/integrating/prometheus.md
- docs/tutorials/deploy-grafana-dashboard.md
- mkdocs.yml
- pkg/server/server.go
- pkg/server/server_test.go
Adds /healthz endpoint to both tracee-ebpf and tracee-rules.
The endpoints will be used for testing if a process is up
in a k8s liveness probe.
```
commit c8ad38db7c54706960fa179069a911edb502a94f (HEAD -> add-healthz-endpoint, origin/add-healthz-endpoint)
Date:   Fri Aug 26 21:54:03 2022 -0300
feat: add healthz endpoint
Adds /healthz endpoint to both tracee-ebpf and tracee-rules.
The endpoints will be used for testing if a process is up
in a k8s liveness probe.
```
Fixes: #2113
```
curl --head localhost:3366/healthz
curl --head localhost:4466/healthz
``` …
> feat: add healthz endpoint

- pkg/ebpf/tracee_test.go
- pkg/events/events.go
These missing events were causing invalid parses for the syscall_pathname argument.
```
Date:   Wed Sep 14 12:12:45 2022 +0000
events: add execve and execveat to security_file_open syscalls
These missing events were causing invalid parses for the
syscall_pathname argument.
```
Fixes: #2165
run `tracee-ebpf -t e=security_file_open -t security_file_open.pathname=/usr/bin* -o option:detect-syscall`
events with `syscall=execve` will have their `syscall_pathname` argument empty as expected.
> [FIX] events: add execve and execveat to security_file_open syscalls

- pkg/bufferdecoder/net_decoder.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/net_events.go
- pkg/ebpf/tracee.go
- pkg/events/events.go
net_events: remove current net debugging mechanism
Preparation for moving away from the TC eBPF program types for ingress
and egress. The current net_debug is also interefering in the normal
debug output. A similar (or not) debugging approach will be made if/when
needed.
Related: #2152
General CI/CD tests.
> Remove net debug

- pkg/ebpf/tracee.go
Currently debug mode enables TC (and net related probes) automatically because net_debug was in place. Now, that net_debug has been removed, there is no need for that.
This also solves the permission problems when no net_event was given to debug (and it would fail without correct permissions for loading net probes).
> tracee: debug mode: only enable net probes if needed

- cmd/tracee-ebpf/main.go
- cmd/tracee-rules/main.go
- pkg/server/server.go
- pkg/server/server_test.go
Moves pprof to server (DRY) and add it to tracee-ebpf.
Fixes: #2137
> Move pprof to server

- cmd/tracee-rules/main.go
- cmd/tracee-rules/main_test.go
This is a minor cleanup on `tracee-rules/main.go`:
- check for commands vs flags first
- fix errors returned for the flag `rego-runtime-target` because the var `target` is empty
- change `listSigs` signature, `error` return not used
- minor change for redability
> refactor: clean up tracee-rules/main.go

- Readme.md
Analysising -> Analysing
commit 6f5f9f244c01cac85ed9520fc021f7b2ea35e9d0 (HEAD -> patch-1)
Author: Margarita Manterola <margamanterola@gmail.com>
Date:   Wed Sep 28 18:03:24 2022 -0300
README: Fix typo
Analysising -> Analysing
I haven't tested this as it's fixing a typo in the Readme file.
"Bug Fix" (Maybe? It's a typo fix)
> Fix typo in README file

- tests/kerneltest.sh
This is a quick fix as the tests might be facing false positives without it.
> [MAINT] kerneltest: fix test name variable

- cmd/tracee-ebpf/main.go
- pkg/events/amd64.go
- pkg/events/arm64.go
- pkg/events/events.go
This fixes a bug where 32 bit syscalls were out of range for the sys_enter/exit tail call indexes, which caused a crash when tracing them.
```
Date:   Sun Oct 9 12:39:23 2022 +0000
events: include 32bit syscalls in syscall event range
This fixes a bug where 32 bit syscalls were out of range for the
sys_enter/exit tail call indexes, which caused a crash when tracing them.
```
Fixes: #2202
On an amd64 system run:
`tracee-ebpf -t e=waitpid`
Confirm that no crash occurs.
> events: include 32bit syscalls in syscall event range

- pkg/bufferdecoder/eventsreader.go
- pkg/ebpf/c/tracee.bpf.c
In `tracee.bpf.c` we use arg types to determine syscall arguments. Recent feature changed arguments types enum values, causing bug in argument parsing of syscalls.
This commit fix this issue and add unsupported basic types should be supported in parsing.
Fixes: #2227
> pkg/ebpf: fix bug in support for arg types

- pkg/ebpf/c/tracee.bpf.c
Fixes the issue that multiple tracee instances are all invoking the uprobe trigger events for each instance.
Fixes: #2225
commit e5a6bf84285bd812f517cdd6fdfc1124a0835fee (HEAD -> fix_uprobe, origin/fix_uprobe)
Date:   Wed Oct 12 18:28:32 2022 +0300
uprobe: fix uprobe trigger triggered from multiple tracee instances
Fixes the issue that multiple tracee instances are all invoking the uprobe
trigger events for each instance.
Fixes: #2225
Fixes: #2225
- running 2 instances of tracee-ebpf with `hooked_syscalls,hooked_seq_ops` events and loading a kernel module.
> uprobe: fix uprobe trigger triggered from multiple tracee instances

- cmd/tracee-ebpf/main.go
- cmd/tracee-rules/main.go
- pkg/server/server.go
- pkg/server/server_test.go
minor refactor, remove debug flag from server using `logger.Debug`
> refactor: remove debug flag from pkg/server

- pkg/ebpf/c/missing_definitions.h
- pkg/ebpf/c/missing_noncore_definitions.h
- pkg/ebpf/c/struct_flavors.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/vmlinux.h
- pkg/ebpf/probes/probes.go
- pkg/events/events.go
- pkg/events/parse_args.go
this event indicates an ebpf program being attached to a perf event.
this event includes arguments describing the bpf program,
and arguments describing the perf event.
an example event:
`14:18:52:018729  0      bpftrace         30743   30743   0                bpf_attach           prog_type: BPF_PROG_TYPE_KPROBE, prog_name: do_nanosleep, perf_symbol: do_nanosleep, perf_addr: 0, prog_write_user: false, perf_type: kretprobe`
this event indicates an ebpf program being attached to a perf event.
this event includes arguments describing the bpf program,
and arguments describing the perf event.
Fixes: #2003 
more details about this PR:
bpf program can be attached to a perf event in the system in two methods.
in both this methods, the attach is between an already loaded bpf program to the already …
> events: add bpf_attach event

- deploy/helm/tracee/values.yaml
- deploy/kubernetes/tracee/kustomization.yaml
- deploy/kubernetes/tracee/tracee.yaml
Fix https://github.com/aquasecurity/tracee/issues/2267
- postee optional on helm
- k8 tracee.yaml without posted or falco
> k8s: make postee optional

- .github/workflows/mkdocs-latest.yaml
Fix for https://github.com/aquasecurity/tracee/issues/2273
Based on https://github.com/aquasecurity/trivy/pull/2824
> docs: stop creating docs for patch versions

- docs/contributing/overview.md
- docs/docs/overview.md
Add basic overview for sections docs, and contributing. Let me know if you want to add something, or we can keep it simple for now, just to make the release with some information, instead of blank pages.
> docs: add overview to docs, contributing sections

- pkg/ebpf/events_processor.go
- pkg/ebpf/initialization/ksymbols.go
- pkg/ebpf/tracee.go
Right before releasing v0.9.0, e2e tests failed because of the lack of capabilities of some events that are not being tested in github. 
Example on how to reproduce the issue:
```
sudo TRACEE_LOGGER_LVL=debug ./dist/tracee-ebpf --containers --output format:json --output option:parse-arguments --output option:detect-syscall --trace event=do_init_module,hooked_syscalls
...
{"level":"debug","ts":1666391078.532682,"msg":"capabilities change","pkg":"capabilities"}
{"level":"debug","ts":1666391078.532827,"msg":"capabilities change","pkg":"capabilities"}
{"level":"debug","ts":1666391078.5328455,"msg":"enabling","pkg":"capabilities","cap":"cap_sys_resource"}
{"level":"debug","ts":1666391078.532858,"msg":"enabling","pkg":"capabilities","cap":"cap_bpf"} …
```
> capabilities: raise caps ring for some privileged operations

- pkg/ebpf/tracee.go
This is a temporary mitigation, so cgroupv1 directory can be mounted during docker container initialization. The full code, mounting cgroupv1, cgroupv2 and unmounting them at the end of the execution is
being worked at PR: #2233.
> caps: raise privileges for cgroupv1 mount

- pkg/ebpf/c/tracee.bpf.c
change bpf_attach_map key to prog_id only,
so we won't have context mismatches and loose the event
use only `prog_id` as the key for `bpf_attach_map`, to avoid mismatches of the context, and therefore loosing the event.
Fixes: #2294
- command 01
- command 02
> event fix: bpf_attach map key

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_processor.go
commit 7b9e6f35ae48ad76c76a9765e5491ca0bd795e45 (HEAD -> fix_fops, origin/fix_fops)
Date:   Tue Oct 25 17:22:16 2022 +0300
hooked_proc_fops: remove redundant struct check and handle null pointer
Fixes: #2300
> hooked_proc_fops: remove redundant struct check and handle null pointer

- cmd/tracee-ebpf/flags/filter.go
- docs/docs/tracing/event-filtering.md
Only accept equality and inequality expressions for mntns and pidns. There's no real use cases for greater and less filtering.
Their removal is a step of performance improvement for multi-scope feature.
**P.S.: changes related to mntns and pidns minimum and maximum will happen through https://github.com/aquasecurity/tracee/pull/2238** 
194f8af2 filters: flags: fail mntns and pidns greater/less
Fixes: #2301 
```shell
❯ sudo ./dist/tracee-ebpf -t comm=uname -t 'mntns>10'
{"level":"fatal","ts":1666703509.1801474,"msg":"app","error":"invalid filter expression: >10"}
tracee on  2301-remove-greater-less [$!?] via 🐹 v1.19.2 via ⍱ v2.3.0 
❯ sudo ./dist/tracee-ebpf -t comm=uname -t 'mntns<10'
{"level":"fatal","ts":1666703516.6671994,"msg":"app","error":"invalid …
```
> filters: flags: change mntns and pidns filter expressions

- types/trace/trace.go
UnmarshalJson isn't supporting u8 type currently, even though it is used by the `do_sigaction` event.
Add support to it and to other types names missing.
Fixes: #2311
Ran tracee with signature using the `do_sigaction` event which parse both the `bool` and `u8` types.
> Bugfix: types/trace: add u8 type support to UnmarshalJson

- tests/integration/integration_test.go
- tests/integration/tester.sh
This is a change to the integration tests so that the commands which are meant to trigger events that the tests look for, are actually picked up by tracee. In order for this to happen, the events can't be the same PID as tracee. This is accomplished using syscall.ForkExec() which runs functions in a shell script.
Fixes #2073 
`sudo make test-integration`
> Run integration test triggers in own PID

- deploy/helm/tracee/Chart.yaml
- deploy/kubernetes/tracee-falcosidekick/tracee.yaml
- deploy/kubernetes/tracee-postee/tracee.yaml
- deploy/kubernetes/tracee/tracee.yaml
Update kubernetes tags to reflect latest release: https://github.com/aquasecurity/tracee/releases/tag/v0.9.3
> k8s: update tags to 0.9.3

- pkg/ebpf/c/tracee.bpf.c
We use a single buffer from buffer map per CPU to store strings in eBPF programs between inner functions.
This expose us to bug like the current one - double use of the buffer overwrite previous string there before it has been used. Now get second string only after sending the first one to different buffer.
Fixes: #2344
> pkg/ebpf: fix multi use of string buf in seched_process_exec

- pkg/logger/logger.go
72c38284 logger: enrich debug level logs
ffa109a0 logger: refactor
Fixes: #2248 
```shell
❯ sudo TRACEE_LOGGER_LVL=debug ./dist/tracee-ebpf -t comm=ls
{"level":"debug","ts":1666192669.9143562,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"BUILD_ID","OS_KERNEL_RELEASE":"rolling"}
{"level":"debug","ts":1666192669.9146245,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"PRETTY_NAME","OS_KERNEL_RELEASE":"\"Manjaro Linux\""}
{"level":"debug","ts":1666192669.9146755,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"KERNEL_RELEASE","OS_KERNEL_RELEASE":"5.15.74-3-MANJARO"}
{"level":"debug","ts":1666192669.9147034,"msg":"osinfo","pkg":"main","file":"main.go","line":85,"OSReleaseField":"ARCH","OS_KERNEL_RELEASE":"x86_64"} …
```
> [FEAT] logger: debug output enrichment

- pkg/cgroup/cgroup.go
- pkg/cgroup/errors.go
- pkg/containers/containers.go
- pkg/ebpf/tracee.go
- pkg/mount/errors.go
- pkg/mount/mount.go
- pkg/utils/files.go
- tests/kerneltest.sh
This is a refactor triggered by comment https://github.com/aquasecurity/tracee/pull/2200#discussion_r990781388. Tracee needs to always initialize cgroupv1 and/or groupv2 when needed. Cgroupv2 is always needed for cgroup ebpf programs.
```
sudo ./dist/tracee-ebpf --install-path /tmp/tracee --cache cache-type=mem --cache mem-cache-size=512 --output format:json --output option:parse-arguments --output option:detect-syscall --containers --trace container --trace comm=bash --trace follow --capabilities bypass=false | jq -c
```
Note: Set bypass to false so capabilities are applied:
```
CapInh: 0000000000000000
CapPrm: 000001ffffffffff
CapEff: 0000000000000000
CapBnd: 0000000000000000
CapAmb: 0000000000000000
```
> [REFACTOR] Cgroup Interface (cgroupv1 and cgroupv2 initialization)

- pkg/events/derive/derive.go
- pkg/events/derive/derive_test.go
Until now, we had a function to support derivation of a single event from a single base event.
However, sometimes a single base event can trigger multiple instances of a single derived event (aka, one derive function that should derive multiple events in a single call).
We add support for it, and unite the two APIs to use the same code.
Fixes: #2383 
> pkg/events: add API to derive multiple events from single function

- pkg/procinfo/procinfo.go
The procfs read errors might be too frequent as processes may vanish during tracee initialization. They're important for debugging, though, so turn info into debug level.
Fixes: #2393
> pkg/procinfo: procfs errors are too frequent

- pkg/ebpf/tracee.go
Last merge had wrong permissions and there are still errors reading procfs when dropping capabilities. This commit fixes the issue.
> pkg/ebpf/tracee: fix capabilities for procfs reads

- types/detect/detect.go
Fix for https://github.com/aquasecurity/tracee/issues/2407
Add `EventName` to `detect.SignatureMetadata`. The new field will be used to definite the event name used when loading rules to the `events.Definitions` table.
More context for this issue can be found on the POC implementation: https://github.com/aquasecurity/tracee/pull/2374
> types: add EventName to SignatureMetadata

- Makefile
- builder/Dockerfile.alpine-tracee-container
- cmd/tracee/main.go
Fix https://github.com/aquasecurity/tracee/issues/2388
```
commit 10590adbd28b81b004a4c022a035334e9a16f8e2 (HEAD -> add-tracee-binary, origin/add-tracee-binary)
Date:   Wed Nov 30 16:36:50 2022 -0300
tracee: add new binary
Adds new binary tracee, which will join the experience of tracee-ebpf,
and tracee-rules, where everything will be treated as an event.
```
The PR adds the binary as a copy of the existing `tracee-ebpf`. The duplication of flags here is intentional, the new binary will later diverge from the existing binaries on the flags it will expose, with new names and also features. So I prefer not to extract the flags to a common place for now. 
The PR also adds the new binary to the Docker image. 
For extra context, please check: …
> tracee: add new binary

- pkg/utils/proc/ns.go
- Change Info to Debug to avoid errors such as:
{"level":"warn","ts":1669930709.794133,"msg":"Failed in fetching process
mount namespace","pid":3861386,"error":"could not open ns dir: open
/proc/3861386/ns: no such file or directory"}
{"level":"warn","ts":1669930709.7942631,"msg":"Failed in fetching
process mount namespace","pid":3861387,"error":"could not open ns
dir: open /proc/3861387/ns: no such file or directory"}
{"level":"warn","ts":1669930709.7942793,"msg":"Failed in fetching
process mount namespace","pid":3861390,"error":"could not open ns
dir: open /proc/3861390/ns: no such file or directory"}
If processes have vanished while tracee is trying to read their namespaces during initialization.
> pkg/utils/proc: log errors as debug only

- signatures/golang/dropped_executable.go
- signatures/golang/export.go
Fixes https://github.com/aquasecurity/tracee/issues/2444
Configures the Origin to be the same we used for rego: https://github.com/aquasecurity/tracee/blob/main/signatures/rego/dropped_executable.rego#L20
I've tested it on GKE and DO, adding the context to be containers fixes the false positives.
Note, I want to use this signatures+nginxrat malware to do the new tracee get started tutorial example -> https://github.com/aquasecurity/tracee/issues/2353
> rules: reenable dropped_executable

- pkg/cmd/urfave/urfave.go
```commit 691dd00ed10eed01146a2c4cc5ce3fe051a87f61 (HEAD -> fix-ignored-error, origin/fix-ignored-error)
Date:   Sat Nov 12 14:35:35 2022 -0300
ebpf: fix error handling
The error returned by kernel.Lockdown() was ignored.
```
ps: in case where we actually want to ignore the error, we should instead do `lockdown, _ := kernel.Lockdown()`
> ebpf: fix error handling

- pkg/utils/sharedobjs/host_symbols_loader.go
- pkg/utils/sharedobjs/host_symbols_loader_test.go
When changed the capabilities package usage, we didn't check capabilities callback return value (error).
This caused usage of open-failed files, which meant null pointer dereference.
Fixes: #2442
> pkg/utils/sharedobjs: check open failure

- pkg/cgroup/cgroup.go
- pkg/containers/containers.go
- pkg/events/derive/container_create.go
- pkg/events/derive/container_remove.go
```
Date:   Thu Dec 8 11:08:17 2022 +0000
derive: fix cgroupv1 hid false derives
In cgroupv1 systems, cgroup_mkdir events come from many different
hierarchies, some existing outside of cpuset, where we query for the
container cgroups.
Because these cgroup_mkdir events would go through a derive process
anyway, for each controller in the system there would be a failed derive
searching through the entire cpuset controller with no results.
This fix adds a check in v1 systems to see if the hierarchy id is
the default one, otherwise derivation is skipped.
```
Tested with sonobuoy performance tests.
This bug:
1.  caused loss of events
2. a bottleneck in deriveEvents and subsequently decodeEvents due to missing …
> derive: fix cgroupv1 hid false derives

- signatures/golang/process_vm_write_code_injection.go
- signatures/golang/process_vm_write_code_injection_test.go
Refactor signature name, it was too big for typing.
> rules: refactor signature name

- tests/e2e-net-test.sh
commit 83121848 (HEAD -> no-e2e-tests-419, rafaeldtinoco/no-e2e-tests-419)
Date:   Thu Dec 8 15:06:55 2022
network: do not run e2e-net-test for vanilla v4.19
Network code isn't ready yet for v4.19, do not run the network tests for
those kernels. The RHEL8 kernel, despite being v4.18, supports all the
code and features (because of their backports).
> [FIX] network: do not run e2e-net-test for vanilla v4.19

- pkg/rules/signature/signature_test.go
- signatures/rego/anti_debugging_ptraceme.rego
- signatures/rego/cgroup_release_agent_modification.rego
- signatures/rego/code_injection.rego
- signatures/rego/disk_mount.rego
- signatures/rego/dropped_executable.rego
- signatures/rego/dynamic_code_loading.rego
- signatures/rego/fileless_execution.rego
- signatures/rego/illegitimate_shell.rego
- signatures/rego/k8s_service_account_token.rego.disabled
- signatures/rego/kernel_module_loading.rego
- signatures/rego/kubernetes_certificate_theft_attempt.rego
- signatures/rego/ld_preload.rego
- signatures/rego/proc_fops_hooking.rego
- signatures/rego/syscall_table_hooking.rego
Fixes https://github.com/aquasecurity/tracee/issues/2411. This is not a mandatory change, because we are not using the rego signatures, though I would like to keep it consistent with the changes done on the golang signatures here -> https://github.com/aquasecurity/tracee/issues/2409
> rules: add event name to rego signatures

- pkg/ebpf/probes/probes.go
- pkg/ebpf/tracee.go
Capabilities were being raised 2 times when tcProbes were enabled (because NET_ADMIN was being added as a required capability). Add NET_ADMIN as a required capability outside the escalation so no nested calls occur (which causes dead lock with capabilities package big lock).
Fixes: #2433
```
sudo ./dist/tracee-ebpf --install-path /tmp/tracee --cache cache-type=mem --cache mem-cache-size=512 --output format:json --output option:parse-arguments --output option:detect-syscall --capabilities bypass=false --trace net=docker0 --trace event=net_packet_ipv4
```
> probes: fix lockup when nested raising privileges

- pkg/ebpf/events_pipeline.go
When the cmdline has arg filters for derived events, for example, they are never filtered (Equal, NotEqual, Contains, NotContains) as their Event ID comes from the functions DeriveSingleEvent & DeriveMultiple Events, and not from the perfbuffer event, like regular events.
Their filtering stage should be done in a later stage in the pipeline, when derivatives (derived events) are obtained, and not in the decodeEvents phase. This patch fixes the issue by running all filters for the derived event being processed.
Fixes: #2462
After the patch is applied, the network events can be filtered by "src" and "dst" (at least, need to check other args). This makes it easier to check the events as network events sometimes can be too noisy.
```
$ sudo ./dist/tracee-ebpf --install-path /tmp/tracee …
```
> events_pipeline: run filters for derived events

- go.mod
- go.sum
commit 7aeabea2
Date:   Mon Dec 12 21:09:20 2022
libbpfgo: bump to v0.4.5-libbpf-1.0.1
Fixes for tracee:
* 6070c0d - Add parsing function for mmap flags argument. (#267) <Alon Zivony>
* aa91d8b - libbpf: fix access violation in libbpf_print_fn. <Hao Xiang>
* 1161940 - libbpf: mitigate libbpf_print_fn issues for tracee. <Rafael David Tinoco>
> Bump libbpfgo to v0.4.5-libbpf-1.0.1

- cmd/tracee-ebpf/main.go
- cmd/tracee/main.go
- cmd/tracee/main_test.go
- pkg/cmd/flags/flags_test.go
- pkg/cmd/flags/help.go
- pkg/cmd/flags/rego.go
- pkg/cmd/tracee.go
- pkg/ebpf/events_engine.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/finding.go
- pkg/ebpf/rule_engine.go
- pkg/ebpf/tracee.go
- pkg/events/events.go
- pkg/events/events_test.go
- pkg/rules/engine/engine.go
- pkg/rules/rego/rego.go
- pkg/rules/signature/signature.go
- pkg/rules/signature/signature_test.go
This PRs adds the rule engine to the events pipeline.
Fixes: https://github.com/aquasecurity/tracee/issues/2441
```
make
./dist/tracee --trace event=anti_debugging
./dist/tracee --trace event=anti_debugging --output format:json
./dist/tracee --trace event=anti_debugging,execve
./dist/tracee --trace event=ptrace,anti_debugging
./dist/tracee  --trace event=anti_debugging,aslr_inspection,cgroup_notify_on_release,cgroup_release_agent,core_pattern_modification,default_loader_mod,disk_mount,docker_abuse,dynamic_code_loading,fileless_execution,hidden_file_created,illegitimate_shell,k8s_api_connection,k8s_cert_theft,kernel_module_loading,ld_preload,process_vm_write_inject,proc_fops_hooking,proc_kcore_read,proc_mem_access,proc_mem_code_injection,ptrace_code_injection,rcd_modification,sched_debug_re …
```
> Add rules to the pipeline

- deploy/helm/tracee/templates/daemonset.yaml
- deploy/helm/tracee/values.yaml
Fixes https://github.com/aquasecurity/tracee/issues/2436
depends on https://github.com/aquasecurity/tracee/pull/2439
```
helm install tracee ./deploy/helm/tracee    --namespace tracee-system --create-namespace   --set everythingIsAnEvent=true
```
> tracee: add flag to install new tracee

- pkg/ebpf/c/tracee.bpf.c
commit a907a655 (HEAD -> fix-arm64-unused-vars, rafaeldtinoco/fix-arm64-unused-vars)
Date:   Tue Dec 13 18:28:38 2022
tracee.bpf: arm64: fix var warning for bpf-nocore
./pkg/ebpf/c/tracee.bpf.c:4663:10: warning: unused variable 'addr_len'
[-Wunused-variable]
uint addr_len = (uint) PT_REGS_PARM3(ctx);
^
./pkg/ebpf/c/tracee.bpf.c:4743:10: warning: unused variable 'addr_len'
[-Wunused-variable]
uint addr_len = (uint) PT_REGS_PARM3(ctx);
Fixes: #2467
> tracee.bpf: arm64: fix var warning for bpf-nocore

- pkg/ebpf/events_pipeline.go
- pkg/filters/args.go
commit 4c047682 (HEAD -> arg-filter-fixes, rafaeldtinoco/arg-filter-fixes, main)
Date:   Wed Dec 14 03:45:45 2022
filters: if arg is missing do not process it
When filtering an event for an argument that might not exist (because
the eBPF code might not send it), the events missing the argument
being filtered were being sent.
One exampe is when openat filters for openat.args.pathname of
/etc/passwd. Some openat events missing pathname might be sent out
through printer.
Do not process the event when an argument being filtered for does not
exist in the event.
Fixes: #2487
commit cbc79bba
Date:   Wed Dec 14 03:44:14 2022
filters: add []string type to args filters
SymbolsLoaded event has …
> Arg filter fixes

- pkg/ebpf/bpf_error.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/tracee.go
- pkg/logger/logger.go
- pkg/metrics/stats.go
commit cfd8611d
pkg/ebpf: make string copy work in focal 4.19
commit ea4cac9b
logger: warn event loss
Due ChanErrors removal #2403, warn about it.
commit ff4c077b
logger: ebpf errors
Introduce EBPF error control mechanism - submission via perf buffer.
EBPF errors are aggregated before being submitted and are later
processed and logged by the processBPFErrors() go routine.
This starts the use of bpf error mechanism through some type checking
like BPF_ERR_MAP_UPDATE_ELEM, BPF_ERR_GET_CURRENT_COMM and
BPF_ERR_INIT_CONTEXT.
Fixes: #2174 
Toggled a checking (falsed an error) in the ebpf side to be able to send the error and get it in user space.
```shell
❯ TRACEE_LOGGER_LVL=debug sudo -E ./dist/tracee-ebpf -t comm=who
[sudo] password for gg: …
```
> [FEAT] log ebpf errors

- docs/tutorials/everything-is-an-event.md
- mkdocs.yml
Fix https://github.com/aquasecurity/tracee/issues/2454
if you want to follow up and test this tutorial locally, keep in mind the helm chart wasn't published yet because we didn't release, so you can try the version to install locally:
```
helm install tracee ./deploy/helm/tracee --namespace tracee-system --create-namespace  --set everythingIsAnEvent=true --set image.repository=josedonizetti/tracee --set image.tag=new1
```
It uses the local helm chart, with an image with the latest tracee I've pushed to my docker hub.
> docs: add everything is an event tutorial

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/derive/net_packet_dns.go
Fixes:
1. need to memset 0 the event struct in stack not to have garbage in comm
2. need to pass the object instead of a pointer as argument, the same as dns_request and dns_response events had.
3. only send dns_request event if there are no responses.
----
IN A
IN MX
(the old event dns_request has trashed command names, I solved that in the new one as well)
(looks like the old dns_response event did not pick the correct MX response, while the new one did)
IN NS
----
PS: For the "IN A" tests I have emulated 2 things:
1. pktlen from the new events is always 14 bytes shorter (that is because the new events only consider L3 layer and beyond, being agnostic to L2 type). 
2. the interface name was used as "docker0"
just to check if old and new events were the same.
----
@roikol FYI, could you …
> network: fix net_packet_dns_request and response

- types/trace/trace.go
Add to the error message when there is an unrecognized type the type
and the argument it is relevant to.
This way it is way easier to identify problems with this function.
> types/trace: improve unmarshalJson error message

- pkg/events/events.go
Change `shared_object_loaded` to use the `security_mmap_file` probe instead of event dependency, as only the probe is required to submit this event (which is originated in kernel space).
Fixes: #2528
> events: remove unnecessary dependency in security_mmap_file

- pkg/ebpf/events_processor.go
- pkg/ebpf/ksymbols.go
- pkg/ebpf/tracee.go
whenever kernelSymbols are updated, also update the ksymbols_map. this way bpf progs will use up-to-date kernel symbols.
i've moved the ksymbols.go out of `initialization` package because these methods are no longer used only in the initialization phase. they are now used also whenever an update the kernelSymbols is invoked. 
```
Date:   Wed Dec 28 16:09:15 2022 +0200
ebpf: update ksymbols_map when updating kernelSymbols
whenever kernelSymbols are updated, also update the ksymbols_map.
this way bpf progs will use up-to-date kernel symbols
```
Fixes: #2530
this has been tested locally using a kernel module that changes a required kernel symbol by the `dirty_pipe_splice` event.
- command 01: …
> ebpf: update ksymbols_map when updating kernelSymbols

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/events_processor.go
- pkg/events/derive/detect_hooked_syscall.go
- pkg/events/derive/hooked_seq_ops.go
- pkg/events/events.go
Optimize the rootkit events to have the text segment check done in kernel.
Surprisingly in my testing this also decreased the average runtime of the uprobes (from ~60k ns to 49k ns), but since these aren't common events it's not that relevant.
More relevant is that `security_file_permission`'s average runtime (which `hooked_proc_fops` uses) was significantly reduced (to ~910ns from ~3750ns), probably due to skipping more submissions.
Mainly the purpose of this refactor was to reduce the amount of submissions of `hooked_proc_fops` (which is about 10% of most event profiles), and simplify the code around checking text segments in userspace (this is possible due to #2531).
commit 02df765ed7c0a9eafeff09cc6cece90529e75556
```
Date: …
```
> ebpf: move event text segment checks to kernel

- cmd/tracee-rules/main.go
commit fd13ead9caae67785101a0402bb9c164be7aefd1 
tracee-rules: use logger instead of Printf
Fixes: #2532 
```shell
./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json < <(cat /etc/passwd) 2>&1 | head -n 3
{"level":"info","ts":1673034598.8414884,"msg":"Signatures loaded","total":30,"signatures":["TRC-101","TRC-1013","TRC-109","TRC-1024","TRC-1019","TRC-1027","TRC-107","TRC-106","TRC-1012","TRC-1028","TRC-1029","TRC-1031","TRC-1010","TRC-1026","TRC-1011","TRC-1021","TRC-1023","TRC-1015","TRC-102","TRC-103","TRC-1025","TRC-1014","TRC-104","TRC-105","TRC-1016","TRC-1017","TRC-1018","TRC-1020","TRC-1030","TRC-1022"]}
{"level":"error","ts":1673034598.8416545,"msg":"invalid json in root:x:0:0::/root:/bin/bash: invalid character 'r' looking for beginning of value"} …
```
> tracee-rules: use logger instead of Printf

- pkg/ebpf/events_pipeline.go
Each event has 2 time related values - the timestamp and thread start time.
The timestamp is changed in usermode to be since epoch, so it is expected that the thread start time will change in the same manner.
Fixes: #2539
> ebpf: change thread start time to be since epoch

- pkg/cmd/tracee.go
commit 488e0a77eb07dad769a14fd696f41cd54a3ece2a
cmd/tracee: fix go routine order
The preamble was getting printed before the tracee was fully initialized
what was causing intertwined logs.
This reorders the go routine that prints the preamble and starts the
event channel reception.
Fixes: #2485 
```shell
sudo ./dist/tracee-ebpf -t uid=1000 -t event=execve -t pid=new --log debug
{"level":"debug","ts":1673038239.7655802,"msg":"osinfo","KERNEL_RELEASE":"5.15.85-1-MANJARO","ARCH":"x86_64","PRETTY_NAME":"\"Manjaro Linux\"","ID":"manjaro","ID_LIKE":"arch","BUILD_ID":"rolling","pkg":"urfave","file":"urfave.go","line":53}
{"level":"debug","ts":1673038239.7656102,"msg":"RuntimeSockets: failed to register default","socket":"containerd","error":"failed to register runtime socket stat …
```
> cmd/tracee: fix event channel go routine order

- pkg/ebpf/c/tracee.bpf.c
Currently event data is stored on the stack using a struct named
event_data_t. This has the drawback of consuming 120 bytes
(sizeof(event_data_t)) out of the available 512 bytes before we even
begin considering the required logic of the event. By moving this struct
into a map, not only we save this space on the stack, but we can then
also add a buffer to save the event's arguments instead of having a
dedicated submit buffer. This allows us to place the buffer right after
the context of the event, and send it to userspace without having to do
an extra copy of the context to the submit buffer.
In addition to the above benefits, this also sets the ground to split
our bpf programs into several programs linked by tail calls and keeping
the event's state on the event data map.
Tests being …
> Store event data in a map

- docs/docs/tracing/event-filtering.md
- pkg/cmd/flags/filter.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/filters.go
- pkg/filters/binary.go
- pkg/filters/errors.go
- pkg/utils/proc/ns.go
Currently the binary filter can not differentiate between binaries that have the same path but reside in different mount namespaces. Having the mount namespace is required to identify a specific binary to filter by.
Enable the user to provide the mount namespace in addition to the binary path and keep support of providing a binary without specifying a mount namespace.
To filter by path, the following syntax is used::
--trace binary=/some/binary/path
To filter by path and a specific mount namespace (e.g. 4026532448), use:
--trace binary=4026532448:/some/binary/path
Specifying the host mount namespace can be done using the "host" alias:
--trace binary=host:/some/binary/path
Fixes: #2516
> filters: expand binary filter to support mount ns

- Readme.md
As dicussed in the task https://github.com/aquasecurity/tracee/issues/2489. We will be removing the tracee video from the Readme for now.
> docs: remove outdated video from Readme

- builder/Makefile.release
Fixes https://github.com/aquasecurity/tracee/issues/2508
> chore: add go signatures to the tar release

- cmd/tracee-rules/input.go
- go.mod
- go.sum
- pkg/cmd/printer/printer.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/tracee.go
- pkg/events/derive/net_packet_dns.go
- pkg/events/derive/net_packet_helpers.go
- pkg/events/derive/net_packet_http.go
- pkg/events/derive/net_packet_icmp.go
- pkg/events/derive/net_packet_icmpv6.go
- pkg/events/derive/net_packet_ipv4.go
- pkg/events/derive/net_packet_ipv6.go
- pkg/events/derive/net_packet_tcp.go
- pkg/events/derive/net_packet_udp.go
- pkg/events/events.go
made by @roikol and approved by me.
network: add HTTP events
Introduce the new HTTP, HTTP request and HTTP response events.
- event retval now encodes more than just layer3 protocol types.
- BPF logic for HTTP events and L7 parsing in kernel (reduce num of events)
- derivation logic for HTTP events.
- generic layer 7 parsing function used by DNS and HTTP now.
> network: add HTTP events

- cmd/tracee-ebpf/main.go
- cmd/tracee-rules/main.go
- cmd/tracee/main.go
- pkg/cmd/tracee.go
- pkg/ebpf/rule_engine.go
- pkg/rules/benchmark/benchmark_test.go
- pkg/rules/engine/engine.go
- pkg/rules/engine/engine_test.go
To process signals we use a done channel which is passed down as an argument. But it would be best to use a Context. To fix it we are using `signal.NotifyContext` which returns a context that will be closed in case the expected signals are sent.
This refactor was discussed on https://github.com/aquasecurity/tracee/issues/2355
Task: https://github.com/aquasecurity/tracee/issues/2355
> tracee: refactor signals done channel

- .gitignore
- Makefile
- Vagrantfile
- builder/Dockerfile.alpine-tracee-container
- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- packaging/Dockerfile.fedora-packaging
- packaging/Dockerfile.ubuntu-packaging
commit e49dc500 (HEAD -> clang-format-12, rafaeldtinoco/clang-format-12)
Date:   Sun Jan 15 04:38:15 2023
builder: adjust OPA version to latest in remaining
commit 53acf4b0
Date:   Sun Jan 15 04:30:12 2023
builder: adjust tracee-make docker files
- ubuntu: allow fix-fmt makefile rule to work inside tracee-make img
- ubuntu: install multiple llvm/clang/clangd/clang-format versions
- ubuntu & alpine: update opa to latest version to tracee-make img
- ubuntu & alpine: add binaries for testing within tracee-make img
commit 06296884
Date:   Sun Jan 15 04:28:48 2023
git: update .gitignore
- add temp files related to development
> Clang format 12

- pkg/ebpf/c/tracee.bpf.c
Newer LLVM versions might fail to optimize the has_string() loop unrolling with the following error:
./pkg/ebpf/c/tracee.bpf.c:2487:5: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
By replacing the has_string() inline function with a macro compound statement, it is possible to mitigate that issue and make the eBPF binary properly optimized.
Compile Tracee with clang-12, clang-13, and clang-14. Check if all tests pass and no compiler warnings happen.
> ebpf: turn has_prefix() to macro using compound expr

- types/trace/trace.go
Add a PodSandbox field to indicate wether the event is coming from a kubernetes sandbox container or not.
> types/trace: add PodSandbox field

- docs/contributing/events/kprobes/kallsyms_lookup_name.md
- docs/docs/deep-dive/caching-events.md
- docs/docs/deep-dive/ordering-events.md
- docs/docs/deep-dive/performance.md
- docs/docs/detecting/go-cel.md
- docs/docs/detecting/golang.md
- docs/docs/detecting/index.md
- docs/docs/detecting/rego.md
- docs/docs/tracing/output-formats.md
- docs/docs/tracing/output-options.md
- pkg/cmd/flags/flags_test.go
- pkg/cmd/flags/output.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/tracee.go
- tests/e2e-net-test.sh
- tests/integration/tracee.go
- tests/kerneltest.sh
Always evict the originated syscall argument for internal hooks events.
Remove the `detect-syscall` output option that was used to make it available.
Fix documentation to match new format.
Fixes: #2391 
> events: always detect originated syscall

- pkg/cmd/flags/filter.go
- pkg/ebpf/filters.go
- pkg/ebpf/tracee.go
- pkg/events/derive/net_packet_helpers.go
- pkg/events/events.go
- types/trace/network_trace.go
network: remove leftovers from previous code
There is no reason to filter network interfaces anymore.
Remove some extra constants as well.
> network: remove leftovers from previous code

- tests/e2e-net-test.sh
commit: c11a39ce has accidentally commented the script responsible for te initial setup for the e2e network tests. This commit fixes it.
Fixes: #2491 (together with that commit)
> network: uncomment e2e network tests config script

- types/trace/trace.go
MatchedScopes is a requirement for the multiscope effort #2238.
Since types is a different module this needs to enter first to make e2e happy.
> chore: add MatchedScopes to Event

- docs/docs/capturing/index.md
- pkg/cmd/flags/capture.go
- pkg/cmd/flags/flags_test.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/net_capture.go
- pkg/ebpf/tracee.go
- pkg/pcaps/pcaps.go
1. Tracee would capture any network packet independently of given event filters. That wouldn't allow users to specify a single protocol to be captured, for example. Now, consider the following command:
tracee-ebpf --output none \
--trace event=net_packet_dns,net_packet_icmp \
--capture network
Tracee is able to capture ICMP and DNS packets only, for example.
2. Tracee would capture all PCAP files using the entire packet payloads. That would lead a situation where the user wouldn't be able to run tracee, with the capturing option, for too long in a higher data transfer environment, as the PCAP file would grow in a very fast pace.
Considering the following command:
tracee-ebpf --output none \
--trace event=net_packet_dns,net_packet_icmp \
--capture network
--capture pcap:command
--capture …
> network: adjust capturing packets in many fronts

- pkg/cmd/flags/capture.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/net_capture.go
commit e0267e71 (HEAD -> pcap-fixes, rafaeldtinoco/pcap-fixes)
Date:   Fri Jan 27 01:44:30 2023
network: adjust capture length for known protocols
The capture payload length (snaplen) for:
- net_packet_icmp
- net_packet_icmpv6
- net_packet_dns
does not make much sense. Keep snaplen for:
- net_packet_ipv4
- net_packet_ipv6
- net_packet_udp
- net_packet_tcp
- net_packet_http
commit 129b7ce4
Date:   Fri Jan 27 00:35:45 2023
network: capture underlying layers correctly
----
For testing:
```
sudo rm -rf /tmp/tracee/out/pcap && sudo ./dist/tracee-ebpf --log debug --install-path /tmp/tracee --output option:parse-arguments --capabilities bypass=false --trace event=net_packet_udp --output …
```
> pcap fixes before the release

- docs/docs/tracing/event-filtering.md
- pkg/ebpf/filters.go
- pkg/filters/binary.go
- pkg/utils/proc/exe.go
- tests/integration/integration_test.go
- tests/integration/tester.sh
commit ebe6dc2436f8022e70aceb15cc678eda1df743c1
```
Date:   Wed Jan 11 12:59:02 2023 +0000
integration: add test for binary filter
Test confirms that `docker run` commands output with a filter on
dockerd's binary path will include events with it's own PID.
You can confirm this does not work by running the test without
the previous commit.
```
commit 307b0fab783924d4419b7c9e2ddc96d32fddafe3
```
Date:   Tue Jan 10 12:45:36 2023 +0000
filters: populate proc_info_map with filtered binaries
Previously, the binary filter could only practically filter new
sub-processes of processes running before tracee has started.
This is due to binary paths being enriched in eBPF code only …
```
> filters: populate proc_info_map with filtered binaries

- docs/docs/tracing/scopes.md
- fix example command
- add new to intertwined category
- move wrong one to detached category
> fix: doc: mscope: examples

- pkg/ebpf/c/tracee.bpf.c
- pkg/events/trigger/context.go
As it's a self-triggered event, matchedScopes must be set to all leaving the matching to the user land.
Context: db12e661e
Test:
```shell
sudo ./dist/tracee-ebpf -t 4:e=hooked_seq_ops -o format:table-verbose
TIME             SCOPES            UTS_NAME          CONTAINER_ID  MNT_NS       PID_NS       UID    COMM             PID     TID     PPID    RET              EVENT                ARGS
11:11:43:092225  0000000000000008                                 0            0            0                       0       0       0       0                hooked_seq_ops       hooked_seq_ops: map[]
^C
End of events stream
Stats: {EventCount:1 EventsFiltered:0 NetEvCount:0 NetCapCount:0 BPFLogsCount:0 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCount:0 LostNtCapCount:0 LostBPFLogsCount:0}
```
> ebpf: set context seq ops scopes to always on

- pkg/events/events.go
Some events
```
ContainerCreate
ContainerRemove
ExistingContainer
```
can't be mixed with `container=new`.
This fixes integration tests failures like:
`--- FAIL: Test_EventFilters/trace_only_events_from_new_containers`
Context:
- #2636
> chore: fix: default set container conflict

- pkg/events/events.go
- tests/integration/integration_test.go
#2645 removed all container set events from the default set because they broke integration tests (in particular `existing_container`).
This PR brings back `container_create` and `container_remove`.
> events: bring back container create/remove events

- docs/contributing/events/format.md
- docs/docs/detecting/golang.md
- pkg/bufferdecoder/eventsreader.go
- pkg/bufferdecoder/eventsreader_test.go
- pkg/ebpf/events_pipeline.go
- pkg/rules/benchmark/signature/golang/anti_debugging.go
- pkg/rules/benchmark/signature/golang/code_injection.go
- pkg/rules/celsig/wrapper/wrapper.go
- signatures/helpers/arguments_helpers.go
- signatures/helpers/helpers.go
- tests/integration/integration_test.go
Not passing arguments when they are missing from the eBPF payload proved to be problematic, because of parsing errors and database tables building.
Now we always pass all arguments, with default `nil` value if they are missing.
Fixes: #2261
> events: pass uninitialized arguments

- pkg/ebpf/c/tracee.bpf.c
Clean the arguments buffer after `security_bpf` submission. This will prevent double arguments sent to the user-mode
- command 01
- command 02
> ebpf: clean arguments after security_bpf

- pkg/cmd/printer/printer.go
Since we changed the default set to include some security_socket_xxx events, it is now required to expand the space reserved for the event name or it gets trim.
Expand space from 20 to 25 chars.
- command 01
- command 02
> fix: don't trim event names in table printer

- signatures/golang/disk_mount.go
- signatures/golang/disk_mount_test.go
instead use the ContainerStarted context flag
```
Date:   Tue Jan 31 12:50:02 2023 +0200
disk_mount: don't whitelist runc process
instead use the ContainerStarted context flag
```
Fixes: #1611
- command 01: `./dist/tracee-ebpf -t e=security_sb_mount -o format:json | ./dist/tracee-rules --input-tracee file:stdin --input-tracee format:json`
- command 02: `docker run --rm -it ubuntu:latest`
> disk_mount: don't whitelist runc process

- deploy/helm/tracee/Chart.lock
The chart lock wasn't update, which failed the last publish: https://github.com/aquasecurity/tracee/actions/runs/4054901241
> k8s: update helm chart lock

- pkg/filters/uint.go
Return error in case of uint compared as less than zero.
Fixes: #450 
```shell
sudo ./dist/tracee  -t 3:e=sched_process_fork,sched_switch -t 3:comm=kthreadd -t 3:'pid<0'
{"level":"fatal","ts":1675274360.603387,"msg":"app","error":"invalid filter expression: <0"}
```
```
sudo ./dist/tracee  -t 3:e=hooked_syscalls,sched_process_fork,sched_switch -t 3:comm=kthreadd -t 3:pid=2
21:00:00:000000  0                       0       0       0                hooked_syscalls           hooked_syscalls: []
14:58:36:217564  0      kthreadd         2       2       0                sched_process_fork        parent_tid: 2, parent_ns_tid: 2, parent_pid: 2, parent_ns_pid: 2, …
```
> fix: filters: uint can't be less than 0

- pkg/containers/path_resolver.go
- pkg/utils/proc/ns.go
5a7dbb21 containers: resolve relative path of ns with legit root
ef716be0 utils: fix wrong stat file parsing
Fixes: #2670
Manually saw it fixed the first mount ns processes and emitted warnings no longer
> Fix processes root directory access

- docs/getting-started/installing/prerequisites.md
Update prerequisites permission section with required docker flags '--pid=host --cgroupns=host --privileged'.
Fixes: #1211 
```shell
make -f builder/Makefile.mkdocs mkdocs-build
docker build \
-f builder/Dockerfile.mkdocs \
-t tracee-mkdocs:latest \
.
Sending build context to Docker daemon  42.35MB
Step 1/2 : FROM squidfunk/mkdocs-material:8.3.0
---> 585d64194fff
Step 2/2 : RUN pip install --upgrade pip &&     pip install mike &&     pip install mkdocs-macros-plugin
---> Using cache
---> de4b86c1ce83
Successfully built de4b86c1ce83
Successfully tagged tracee-mkdocs:latest
```
> docs: update required docker flags

- pkg/ebpf/c/common/context.h
- pkg/ebpf/c/tracee.bpf.c
When more than one event is being submitted in the same BPF program it may be required to reset the arguments buffer of the event. 
Create a function to handle this.
- command 01
- command 02
> refactor: reset event args

- builder/Makefile.checkers
- pkg/ebpf/c/missing_definitions.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/events/derive/net_packet_ipv4.go
- pkg/events/derive/net_packet_ipv6.go
network: fix retval for IPv6 packets
The event retval value works, for networking events, as a value to
tell userland (derivation) tips about what to do. Initial usecase was
to differentiate layer 3 protocols (IPv4 vs IPv6), but it gained more
meaning with http events.
This patch fixes the retval value for IPv6 packets, fixing issues seen
with net_packet_ipv6 events having zeroed values.
> network: fix IPv4 packets being treated as IPv6 (net_packet_ipv6 only traced)

- docs/docs/capturing/index.md
- pkg/cmd/flags/capture.go
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/tracee.go
- pkg/pcaps/common.go
- pkg/pcaps/pcap.go
- pkg/pcaps/pcaps.go
network: default to capturing all network traffic
- Before this change, only network traffic that was explicitly being traced by the user was captured.
- This change makes it so that all network traffic is captured by default and adds a command line option:
--capture pcap-options:[none,filtered]
to allow the old behavior, of capturing only traffic from the given filters, to still exist if "filtered" option is given.
Fixes: #2683
> network: default to capturing all network traffic

- signatures/golang/dropped_executable.go
- signatures/golang/dropped_executable_test.go
Got a trigger for this signature on a personal cluster, and without the path of the dropped executable not easy to understand what to check on the container:
before:
```
*** Detection ***
Time: 2023-02-08T22:06:22Z
Signature ID: TRC-1022
Signature: New executable dropped
Data: map[]
Command: curl
Hostname: app-8bf6f79d9-q
```
after:
```
*** Detection ***
Time: 2023-02-08T22:13:59Z
Signature ID: TRC-1022
Signature: New executable dropped
Data: map[path:/minikube-linux-amd64]
Command: curl
Hostname: app-8bf6f79d9-q
```
> signatures: add path to dropped_executable data

- docs/docs/tracing/output-formats.md
- pkg/metrics/stats.go
Remove the old net event stats from the `Stats` struct so the table printer epilogue won't include it.
> metrics: remove old net event stats

- cmd/tracee/main.go
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/logger_test.go
- pkg/cmd/urfave/urfave.go
- pkg/logger/logger.go
flags: introduce log unit tests
logger: flush logs periodically
logger: add aggregate option to --log
Fixes: #2570
```shell
sudo ./dist/tracee -t comm=uname -log debug               
{"L":"DEBUG","T":"2023-02-03T20:51:43.131-0300","M":"osinfo","BUILD_ID":"rolling","KERNEL_RELEASE":"5.15.89-1-MANJARO","ARCH":"x86_64","PRETTY_NAME":"\"Manjaro Linux\"","ID":"manjaro","ID_LIKE":"arch","pkg":"urfave","file":"urfave.go","line":53}
{"L":"DEBUG","T":"2023-02-03T20:51:43.131-0300","M":"RuntimeSockets: failed to register default","socket":"containerd","error":"failed to register runtime socket stat /var/run/containerd/containerd.sock: no such file or directory","pkg":"flags","file":"containers.go","line":47}
{"L":"DEBUG","T":"2023-02-03T20:51:43.131-0300","M":"RuntimeSockets: failed to register …
```
> fix: make inner aggregated logs usable

- 3rdparty/btfhub.sh
Add support for the following distros:
- CentOS 7       (5.4 kernel)
- CentOS 8       (4.18 kernels)
- RHEL 8         (4.18 kernels)
- SLES 15.3      (5.3 kernels)
- Oracle Linux 7 (5.4 kernels)
- Oracle Linux 8 (5.4 kernels)
- Debian 10      (5.10 kernels)
- Fedora 28      (5.0 kernels)
- Fedora 29      (5.3 kernel)
- Fedora 30      (5.0 and 5.6 kernels)
- Fedora 31      (5.3 kernel)
- Ubuntu Bionic  (5.0, 5.3, 5.4 kernels)
- Ubuntu Focal   (5.4, 5.8, 5.11 kernels)
> btfhub: sync new kernels recently added

- cmd/tracee-rules/main.go
Fix https://github.com/aquasecurity/tracee/issues/2718
The [PR](https://github.com/aquasecurity/tracee/pull/2580) fixed a bug when `tracee-rules` was executed with `sudo`, though it introduced a bug for when `tracee-rules` is executed without `sudo`, it fails because it can't raise capabilities.
This PR fixes this bug. 
```
make
./dist/tracee-rules --list-events
sudo ./dist/tracee-rules --list-events
```
> tracee-rules: bypass capabilities if user not root

- pkg/cmd/flags/flags_test.go
- pkg/cmd/flags/output.go
- pkg/cmd/printer/printer_test.go
- pkg/cmd/urfave/urfave.go
Simplify output logic in order to add multiple printer support in a follow-up pr. Also increase test coverage. 
compile `tracee`, and test --output
This is a refactor in order to add multiple printers supported, required by the new binary.
https://github.com/aquasecurity/tracee/issues/2355
> refactor: simplify output flags

- cmd/tracee/main.go
- cmd/tracee/main_test.go
Fixes TODO for https://github.com/aquasecurity/tracee/issues/2355
The unified binary create events for all signatures by default (add events to Definitions). The enabling of such events is handled by `tracee` default filtering logic. With this strategy we can support use cases like: 
--trace e=anti_debugging
--trace set=signatures
--trace set=signatures --trace e!=anti_debugging
```
tracee --trace e=anti_debugging
tracee --trace set=signatures
tracee --trace set=signatures --trace e!=anti_debugging
```
> tracee: fix filters

- pkg/cmd/flags/output.go
`tracee --output help` list an option for `cache-events` which the code ignores, this probably is an old flag that was replaced by higher level flag `tracee --cache help`
```
tracee --output help
```
> flags: remove cache-events from output help

- pkg/filters/containers.go
- pkg/filters/string.go
- pkg/filters/uint.go
Fixes: #2589
swap uint and containers equality order
Make them have the same equality precedence as string and binary.
> swap uint and containers equality order

- docs/contributing/events/security_alerts/bpf_attach.md
- pkg/ebpf/c/missing_definitions.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/events/events.go
- pkg/events/parse_args.go
add argument to the bpf_attach event indicating whether the bpf_override_return helper function is used.
this is to be used later on in the signatures phase.
```
Date:   Tue Jan 10 15:29:23 2023 +0200
ebpf: add prog_override_return arg to bpf_attach
add argument to the bpf_attach event indicating whether the
bpf_override_return helper function is used
```
Fixes: #2558
locally using my own sample of BPF program that uses the `bpf_override_return` helper.
- command 01: `./dist/tracee-ebpf -t e=bpf_attach`
> ebpf: add prog_override_return arg to bpf_attach

- pkg/cmd/flags/filter.go
- pkg/cmd/flags/flags_test.go
- pkg/ebpf/tracee.go
- pkg/filterscope/errors.go
- pkg/filterscope/filterscope.go
- pkg/filterscope/filterscopes.go
filterscopes: create a filterscopes pkg
A filterscopes pkg is needed so that the it can be used outside of the ebpf pkg. This is needed for the upcoming refactors such as the one that will allow the filterscopes to be used by the "load objects" and "symbols collision" events.
@geyslan please check if this brakes your current work too much, and, if you can accept it and rebase your code, I'll be able to continue a refactor proposal to "ld SO symbols collision" (https://github.com/aquasecurity/tracee/pull/2053/) PR so the derivation table initialization does not get specific event initialization at its top.
> filterscopes: create a filterscopes pkg

- .github/workflows/release.yaml
- builder/Makefile.release
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
This PR aims to sign tracee container images with cosign using the keyless approach, which avoids the hassle of securely keeping our private keys.
PTAL @itaysk @dlorenc
> Thanks to @marcofranssen for helping me to fix the makefile; I've appealed to his wisdom about makefiles ! 
Fixes: #2115
> sign container images with cosign

- pkg/cmd/flags/filter.go
- pkg/containers/path_resolver.go
- pkg/containers/path_resolver_test.go
- pkg/ebpf/tracee.go
- pkg/events/derive/symbols_collision.go
- pkg/events/derive/symbols_collision_test.go
- pkg/events/derive/symbols_loaded.go
- pkg/utils/sharedobjs/container_symbols_loader.go
commit edd80f47 (HEAD -> symbols_coll_refactor, rafaeldtinoco/symbols_coll_refactor, main)
Date:   Sun Feb 19 14:25:27 2023
symbols_collision: refactor and comment extension
1. containers/path_resolver: return a pointer
2. ebpf/tracee:
- cleanup derivation table init function
- move symbols_collision initialization to the correct place
3. events/symbols_loaded:
- extend init function with code from derivation table init
- adjust formatting for readability
4. events/symbols_collision:
- extend init function with code from derivation table init
- adjust formatting for readability
- add comments to explain the logic
- rename variables for meaning clarity
5. events/symbols_collision_test:
- adjust test to reflect the new init function …
> adjust recently merged symbols_collision event and better document it

- cmd/tracee-ebpf/main.go
- cmd/tracee/main.go
- go.mod
- go.sum
commit f965b789dde7a42f92919ae241a14e5434bc66e3
libbpfgo: bump to 8f83f25
From this hash, libbpfgo publicizes its log callback API.
commit f14050d2e9ec81013afd2388d27111729be14d54
chore: set libbpfgo logger callback
- https://github.com/aquasecurity/libbpfgo/pull/284
- https://github.com/aquasecurity/tracee/pull/2600
Fixes: #2417
> logger: set libbpfgo logger callback

- pkg/bufferdecoder/eventsreader.go
- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/c/vmlinux.h
print the seconds of struct timespec instead of pointer address
issue: #2711 
```
Date:   Sun Feb 12 17:13:17 2023 +0200
events: print seconds of timespec
print the seconds of struct timespec instead of pointer address
```
terminal 1: `./dist/tracee-ebpf -t e=clock_nanosleep`
terminal 2: `sleep 1`
> events: print seconds of timespec

- types/trace/trace.go
This PR adds support to Metadata to `trace.Event`. At first this will be used to add `SignatureMetadata` when a signature event is created from a detection. Instead of adding `SignatureMetadata` directly, we have a more generic approach allowing for future use by events that are not signatures (eg: derivations, ebpf)
The `Metadata` field is a pointer and marked as `omitempty` so we only print it if there are metadata. 
This PR is part of https://github.com/aquasecurity/tracee/issues/2355
Test the PR using this change to add signature metadata to signature events https://github.com/aquasecurity/tracee/pull/2753
The [first implementation](https://github.com/aquasecurity/tracee/pull/2744) was using a more dynamic approach, but after discussion we decide to have a structure for the specific …
> types: add event metadata

- go.mod
- go.sum
- pkg/ebpf/finding.go
- pkg/ebpf/finding_test.go
This PR uses the new [Metadata](https://github.com/aquasecurity/tracee/pull/2752) field from `trace.Event` to add the Signature Metadata from the detection into the signature event. Because `SignatureMetadata` contains a few specific fields that don't fit on the `trace.Event` metadata, we are adding them as properties (`SignatureID`, and `SignatureName`)
We add extra signature metadata information, because it is used by internal services, though once we finish the new architecture where sigantures raise events, instead of findings we will remove it. https://github.com/aquasecurity/tracee/issues/2541
```json
{"timestamp":1676925283242804700,"threadStartTime":1676925283242676500,"processorId":4,"processId":1514163,"cgroupId":700736,"threadId":1514163,"parentProcessId":1514161,"hostProcessId" …
```
> Add signature event metadata

- pkg/ebpf/finding.go
- pkg/ebpf/finding_test.go
- pkg/ebpf/signature_engine.go
- pkg/events/events.go
- pkg/filters/args.go
This PR changes signature events to use `finding.Data` as arguments instead of the original event arguments. 
Also, it fix the filtering based on such arguments for signature events.
This PR is part of epic: https://github.com/aquasecurity/tracee/issues/2355
The simplest way to test is to change an existing signature to include same [output data](https://github.com/aquasecurity/tracee/blob/main/signatures/golang/anti_debugging_ptraceme.go#L70), recompile tracee, and test out the feature, eg:
```
tracee --trace event=anti_debugging --trace anti_debugging.args.arg1=test
```
> tracee: fix args on signatures events

- cmd/tracee-ebpf/main.go
- cmd/tracee/main.go
- go.mod
- go.sum
- pkg/cmd/initialize/callbacks.go
- tests/integration/tracee.go
commit 0a83bf085508b3a58abad01723ae77d9fe506816
libbpfgo: set libbpfgo callbacks
This brings to Tracee the libbpfgo filtering logic that was removed from
libbpfgo.
- https://github.com/aquasecurity/libbpfgo/pull/294
This also changes libbpfgoKprobePerfEventRegexp to match:
'trace_utimes_common' progs.
commit 29b5090afa69e9abffbc8832df654159186172fb
bump libbpfgo to v0.4.6
Compile and run, the libbpf output should remain as silent as ever.
Fixes: #2756 #2754
Context:
- https://github.com/aquasecurity/libbpfgo/pull/284#issuecomment-1437170456
- #2756
- #2754
> libbpfgo: set libbpfgo callbacks

- builder/entrypoint.sh
This PR changes docker image entrypoint to use the new tracee binary. It removes the use of the older binaries `tracee-ebpf` and `tracee-rules`.
```
make -f builder/Makefile.tracee-container build-tracee
docker run  --name tracee --rm -it  --pid=host --cgroupns=host --privileged  -v /etc/os-release:/etc/os-release-host:ro      -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host  tracee:latest
docker run  --name tracee --rm -it  --pid=host --cgroupns=host --privileged  -v /etc/os-release:/etc/os-release-host:ro      -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host  tracee:latest --output json
docker run  --name tracee --rm -it  --pid=host --cgroupns=host --privileged  -v /etc/os-release:/etc/os-release-host:ro      -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host  tracee:latest --filter …
```
> tracee: make it the default binary

- cmd/tracee-ebpf/main.go
- cmd/tracee/main.go
- pkg/cmd/flags/flags_test.go
- pkg/cmd/flags/help.go
- pkg/cmd/flags/output.go
- pkg/cmd/flags/tracee_ebpf_output.go
- pkg/cmd/printer/broadcast.go
- pkg/cmd/printer/printer.go
- pkg/cmd/printer/printer_test.go
- pkg/cmd/tracee.go
- pkg/cmd/urfave/urfave.go
This PR add support for multiple printers to new `tracee` binary. The old binary `tracee-ebpf` maintain the previous syntax, and the change is only implemented for the new binary, for such I have first created a commit where I rename the previous `output` flag in order to simplify the deletion once we deprecate and remove `tracee-ebpf`. 
The new syntax was discussed on a previous PR https://github.com/aquasecurity/tracee/pull/2709
This PR is part of https://github.com/aquasecurity/tracee/issues/2355
Close https://github.com/aquasecurity/tracee/issues/2231
Please check the help commands:
```
tracee-ebpf --output help
tracee --output help
```
Multiple printers will be the base of the webhook implementation for the new binary, where webhooks will be a printer like stdout, etc.
> Add multiple printers

- pkg/cmd/flags/flags_test.go
- pkg/cmd/flags/output.go
- pkg/cmd/printer/printer.go
This PR adds a webhook printer. The webhook is used to send events to postee or falcosidekiq so users can configure alerting or actions on top of it. 
Start a simple http server and point the webhook to it. An example of this feature working with postee:
For now the printer is not implementing `template`, it only supports `json`. Templating is coming on a different PR.
> Add webhook printer

- deploy/helm/tracee/templates/daemonset.yaml
- deploy/helm/tracee/values.yaml
This flag was used for users who wanted to try the new experience when it was beta, but the new experience will now be the default option.
This PR removes the helm flag `everythingIsAnEvent` which was used to enable the new experience while it was beta. With the next release this experience will be the default option. 
This is part of https://github.com/aquasecurity/tracee/issues/2355
```
helm repo add aqua https://aquasecurity.github.io/helm-charts/
helm dependency update ./deploy/helm/tracee
helm install tracee ./deploy/helm/tracee \
--namespace tracee-system --create-namespace \
--set hostPID=true
```
> k8s: remove flag everythingIsAnEvent from helm

- pkg/cmd/printer/broadcast.go
This PR is changing the printer broadcast to block instead of drop events. The use of nonblocking here is dropping a lot of events, we could use a timeout to give some or increase the size of the buffer, but this needs to be investigated deeper. 
The previous solution was a blocking one, based on the fact that tracee core is ready to hold events, with a buffer 10 times bigger than the buffers for the printers -> https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_pipeline.go#L102
we will test it on the e2e to validate it fixes the flaky tests created
I will create a issue to investigate it further, but considering we have a release this week, blocking is the best solution
> printer: block instead of drop events for broadcast

- deploy/helm/tracee/templates/NOTES.txt
- deploy/helm/tracee/templates/daemonset.yaml
- deploy/kubernetes/kustomize/base/tracee.yaml
- deploy/kubernetes/kustomize/falcosidekick/kustomization.yaml
- deploy/kubernetes/kustomize/postee/kustomization.yaml
- deploy/kubernetes/tracee-falcosidekick/tracee.yaml
- deploy/kubernetes/tracee-postee/tracee.yaml
- deploy/kubernetes/tracee/tracee.yaml
This PR updates the kubernetes templates to use the new release, with the unified binary. 
This is part of https://github.com/aquasecurity/tracee/issues/2355
```
kubectl apply -f deploy/kubernetes/tracee/tracee.yaml 
kubectl edit ds/tracee # this opens an yaml, update the image: with `josedonizetti/tracee:0.12.0`
kubectl logs -f ds/tracee
```
Depends on https://github.com/aquasecurity/tracee/pull/2782
Tracee base, Tracee with Postee are working, but Tracee with Falcosidekiq is not, this is expected, because it depends on templates on the printer, a PR to fix it is on the way.
> k8s: fix templates to use unified binary

- cmd/tracee-gptdocs/main.go
- pkg/cmd/gptdocs.go
- pkg/cmd/urfave/urfave.go
This is a fix to tracee-gptdocs (currently dead locked due to a last min addiction).
> gptdocs: add option to generate docs for a list of events

- pkg/cmd/flags/filter.go
- pkg/cmd/initialize/callbacks.go
- pkg/events/events.go
Commit 0601f099 added network events to the default set but, since the default set is used for all versions, this broke v419 runs, as that version does not support network events.
commit a8a0d377 (HEAD -> v419-fix, rafaeldtinoco/v419-fix)
Date:   Wed Mar 1 01:59:53 2023
filter: mitigate v4.19 lack of network events
The default event set includes some net_packet events, but they're
not supported in vanilla v4.19 kernels. This patch mitigates this
issue by adding all the network related events to an exclusion list
during the filter events preparation phase.
Fixes: #2771
Note: This mitigation should be removed as soon as tracee has the
feature probe mechanism in place.
commit e2d52ad5 …
> sets: default set can't have network events v419

- .github/workflows/pr.yaml
- Since Jenkins do not support parallel jobs with the same AMI, use 2 similar AMIs for CO-RE and non CO-RE work, so we can speed up the testing total time.
> workflow: turn github node jobs paralell

- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
builder: add goimports to tracee-make docker imgs
`make -f builder/Makefile.tracee-make ubuntu-prepare`
`make -f builder/Makefile.tracee-make ubuntu-shell`
`make check-fmt`
`make fix-fmt`
Complement of:
- #2815
> builder: add goimports to tracee-make docker imgs

- .github/workflows/mkdocs-dev.yaml
- .github/workflows/mkdocs-latest.yaml
- .github/workflows/pr.yaml
- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/test-daily.yaml
- .github/workflows/test-os-packaging-daily.yaml
Get rid of the following warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: ...
> chore: fix deprecated nodejs warning for github action

- .github/workflows/pr.yaml
Looks like github login actions does not work when using "pull_request" event. Remove it from pr.yaml. Seems like we're not blocked by docker hub limits currently. Will have to find a way to overcome that in the "on: pull_request" workflow.
> workflow: fix: github login action not working

- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/probes/probes.go
- pkg/events/events.go
issue: #2793
```
Date:   Thu Mar 2 11:58:33 2023 +0200
feat: add inotify_find_inode event
add the inotify_find_inode event to indicate an inotify watch being
added to a file
```
command 1: `./dist/tracee-ebpf -f e=inotify_find_inode`
command 2: `inotifywatch /tmp/test.txt`
> feat: add inotify_find_inode event

- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- remove the extra tag from the AMI names because of jenkins limits
> workflow: snapshot labels for jenkins are too long

- types/trace/trace.go
This a prior step demanded by #2845.
Rename Event matchedScopes to matchedPolicies to be more consistent with the rest of the codebase.
This field will be replaced by matchedPoliciesNames in future PRs, but for now we just rename it to avoid confusion.
> types: matchedScopes -> matchedPolicies

- pkg/ebpf/c/common/buffer.h
- pkg/ebpf/c/common/filtering.h
- pkg/ebpf/c/common/probes.h
- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/c/types.h
- pkg/ebpf/tracee.go
The recently introduced events_map should carry all the configuration data required for the event. Currently it has only one value specifying for which scopes the event should be submitted. However, we can also use it to store the encoded event's parameter types which is currently being done using the params_type_map. This has two advantages - First, it removes the params_type_map which reduces memory footprint and complexity. Second, it saves an extra map lookup in the params_type_map, which is located in syscalls submit hotpath.
> ebpf: remove params_type_map and use events_map instead

- pkg/ebpf/c/maps.h
- pkg/ebpf/c/tracee.bpf.c
Use event_data_map to store bin_args_t and remove bin_args_map. This also has the benefit of reducing instruction count and complexity of the send_bin_helper() function.
Use the `--capture` write flag to verify functionality still works as expected
> ebpf: remove bin_args_map

- Makefile
Disabling the cache allows us to run the cache multiple times and detect non-deterministic anomalies.
Run `sudo make test-integration` more than one time and see that it no longer caches.
> tests: disable cache for integration tests

- pkg/ebpf/events_pipeline.go
Event filters for events which derive other events didn't work. For example:
`./dist/tracee -f e=sched_process_exec -f sched_process_exec.context.uid=0` didn't filter uid as expected.
Base event filtering was skipped in order to derive its derivatives, however, it shouldn't have been. This PR fixes this issue by computing matched policies first, and breaking the pipeline only if the event doesn't have derivatives. Anyway, even if it does have derivatives but it should have been filtered out, it won't be emitted since we computed its matched policies to be 0.
Fix #2868 
`./dist/tracee -f e=sched_process_exec -f sched_process_exec.context.uid=0`
before this patch the above uid filter didn't work, with the patch it does
> fix: base event filters

- pkg/ebpf/c/tracee.bpf.c
For almost all of the syscalls, we submit an event at sys_exit hook point. Execve, however, is a special case since we can't use the provided pointers at exit time as they are invalid. For this reason, we currently have two hookpoints for execve syscall - one at syscall entry, and the other one at syscall exit. The latter is called only when execve fails and returns an error.
Align the timestamp used by a failed execve call to the timestamp used by the syscall entry hook.
Simply start tracee with only execve event and watch for some failed execve call:
`./dist/tracee -f e=execve`
The timestamp should now be aligned.
> ebpf: align execve enter and exit timestamps

- pkg/events/parse_args.go
set type correctly for bpf helpers arg of the bpf_attach and security_bpf_prog events, so json unmarshalling will be done correctly
```
Date:   Thu Mar 23 12:22:01 2023 +0200
fix: use correct type for bpf helpers
set type correctly for bpf helpers arg of the bpf_attach and 
security_bpf_prog events, so json unmarshalling will be done correctly
```
> fix: use correct type for bpf helpers

- pkg/ebpf/events_processor.go
- pkg/filters/args.go
commit 2d3094ce22e11186c96e3eea808a3f378b8114d8
filters: args: skip arg filtering for PrintMemDump
PrintMemDump event must not be filtered out by arguments filter, as it
a special case that uses "args" as a way to pass "params" to the event.
commit 595ebeaca3a515a6cf1a891f0b42ae6ca45615d6
ebpf: assign processPrintMemDump args values
Instead of appending new args to processPrintMemDump event, assign
values to its existing args. More on that in #2617.
```shell
sudo ./dist/tracee -f e=print_mem_dump -f print_mem_dump.args.symbol_name=system:security_file_open
```
Fixes: #2902
> skip arg filtering for PrintMemDump

- types/trace/trace.go
- types/trace/trace_test.go
Split the Container and Pod fields into separate Containers and Kubernetes struct fields.
Add an ImageDigest field to the Container struct which represents the container image's SHA digest.
Types PR required for #2760
> types: add container and kubernetes context fields

- pkg/ebpf/tracee.go
add support to syscalls for the `print_mem_dump` event.
`tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=execve`
see the event pop up.
> add syscall support for print_mem_dump

- types/trace/trace.go
This adds the MatchedPoliciesNames field to the event struct. This field will be used to store the name of the policy that matched the event.
It also omits the MatchedPolicies bitmask from the event struct marshalling.
This is required by #2923
> types: event policy name

- pkg/containers/containers.go
- pkg/events/derive/container_create.go
Following changes are introduced:
1. New CgroupInfo field `ContainerRoot` is introduced to signify the directory being the root cgroup directory of a container (this solves podman container_create event duplication and is used to ensure no duplication in existing_container)
2. ContainerID from a cgroup path is now parsed by the last container id and runtime found.
This means for example that kind, a development kubernetes cluster deployed through docker and using containerd internally, will report its node containers as docker containers with their own ID and their internal pod containers as containerd containers with their ID, whereas before all containers would share the node container's runtime and ID.
How to test:
1. `tracee-ebpf -f e=container_create -o json`
2. `docker run …
> containers: parse ContainerID by inner cgroup

- tests/integration/integration_test.go
- tests/integration/tester.sh
This re-enables the integration tests for policies, adding a new test based on `PrepareFilterMapFromPolicies()`.
This doesn't make efforts to improve integration tests, since we have a plan to rework them in the future (#2688).
`sudo make test-integration`
It's part of #2665.
> tests: re-enable integration for policies

- pkg/events/derive/symbols_collision.go
The current `events_collisions` event might corrupt in some cases the cache map, as it is now returned from the loader class as a reference. Change the event to copy on change the map.
Fix #2930
> events: prevent symbols map cache corruption

- .github/workflows/release.yaml
- builder/Makefile.release
crane workflow logic did not work for v0.13.0. Remove it so tracee can be released. Revert this with plausible fix after the release.
> release: crane is buggy, remove until fixed

- pkg/ebpf/c/tracee.bpf.c
Fix wrong return value in process_execute_failed event
The return value needs to pass as int (32 bit) otherwise the value shown in the event is wrong.
> events: fix return value of process_execute_failed event

- pkg/cmd/flags/policy.go
- pkg/cmd/flags/policy_test.go
- pkg/ebpf/events_pipeline.go
- pkg/ebpf/signature_engine.go
commit 57fcacdc (HEAD -> policy-issues, rafaeldtinoco/policy-issues)
Date:   Mon Apr 3 23:43:23 2023
policy: cmd/flags: fix incorrect mntns filter name
- .. orelse when used, the following error is returned:
{"level":"fatal","ts":1680575946.4342806,"msg":"App","error":
"invalid filter option specified (mntNS!=100), use '--filter
help' for more info"}
- Update test to also try to create the Policies based on test data.
commit d1fdfc04
Date:   Tue Apr 4 00:50:19 2023
fix: fix segfaults when ctrl+c is too fast
When aborting tracee right in the beginning, user might face segfaults:
panic: runtime error: invalid memory address or nil pointer dereference
...
goroutine 71 [running]: …
> Policies mntns issue and Segfault fix

- pkg/ebpf/signature_engine.go
This is needed because later modification of the event (in particular of the matched policies) can affect engine stage.
Fixes: #2970
> sig: engine: copy event before engine processing

- cmd/tracee-ebpf/main.go
- cmd/tracee-rules/main.go
- cmd/tracee/main.go
- pkg/cmd/flags/logger.go
- pkg/cmd/flags/logger_test.go
- pkg/events/derive/symbols_loaded_test.go
- pkg/logger/callerinfo.go
- pkg/logger/logcounter.go
- pkg/logger/logger.go
- pkg/signatures/engine/engine_test.go
- tests/integration/integration_test.go
- tests/integration/tester.sh
Removed the option for configuring the logger from environemnt variables in favor of programmatic configuration.
This further exposes the option of supplying your own logger implementation and replacing tracee's default implemenation for library consumers of tracee.
Clean up the package to separate files for the utilities (log counters and caller info).
Fix #2475
> logger: refactor logger configuration

- types/trace/trace.go
this change will make unmarshalling for signatures much straight forward
```
Date:   Thu Mar 30 18:19:20 2023 +0300
feat: support unmarshalling trace types
unmarshal trace structs to the correct type
```
> feat: support unmarshalling trace types

- builder/Dockerfile.alpine-tracee-make
- builder/Dockerfile.ubuntu-tracee-make
- cmd/tracee-rules/input.go
- cmd/tracee-rules/main.go
- docs/classic-docs/docs/deep-dive/dropping-capabilities.md
- docs/docs/deep-dive/dropping-capabilities.md
- docs/getting-started/installing/prerequisites.md
- pkg/capabilities/capabilities.go
- pkg/cmd/flags/capabilities.go
- pkg/containers/containers.go
- pkg/containers/path_resolver.go
- pkg/ebpf/events_processor.go
- pkg/ebpf/ksymbols.go
- pkg/ebpf/tracee.go
- pkg/events/derive/hidden_kernel_module.go
- pkg/events/events.go
- pkg/events/usermode.go
- pkg/filters/binary.go
- pkg/mount/mount.go
- pkg/signatures/celsig/config.go
- pkg/signatures/signature/signature.go
- pkg/utils/files.go
- pkg/utils/sharedobjs/host_symbols_loader.go
**STILL MISSING**
But reviews can be made I believe.
commit b07efe93 (HEAD -> policies-rebased, rafaeldtinoco/policies)
Date:   Tue Mar 28 17:14:11 2023
capabilities: change ring names and create base cap
Instead of ring names such as Required, Requested, create simple names
for the rings:
Full         // All capabilties are effective
EBPF         // eBPF needed capabilities are effective
Specific     // Specific requested capabilities are effective
Base         // Capabilities that are always effective
The idea is: Tracee will always be running with **at least** the
capabilities from "Base" ring as **effective**. If developer raises
the ring to "Specific", then Tracee will have capabilities from the
"Base" ring PLUS a specific …
> capabilities: drop capabilities by default

- Makefile
- pkg/cmd/tracee.go
- pkg/ebpf/tracee.go
- pkg/signatures/engine/engine.go
- pkg/signatures/engine/engine_test.go
consume remaining tracee events after ctx is done
This also extracts the dispatch logic into the function processEvent
to reuse it in the drain loop.
Tests has also been updated reordering object creation and had the race
detector, "-race" flag, disabled. It must be re-enabled in the
one binary test suite effort.
---
drain and print events after tracee ctx is done
Fixes: #1377
Fixes: #2171
> consume remaining events after ctx is done

- pkg/ebpf/c/common/network.h
- pkg/ebpf/c/tracee.bpf.c
- pkg/ebpf/net_capture.go
- pkg/ebpf/probes/probes.go
- pkg/ebpf/tracee.go
- pkg/events/derive/net_packet_helpers.go
- pkg/events/derive/net_packet_icmp.go
- pkg/events/derive/net_packet_icmpv6.go
- pkg/events/derive/net_packet_ipv4.go
- pkg/events/derive/net_packet_ipv6.go
- pkg/events/derive/net_packet_tcp.go
- pkg/events/derive/net_packet_udp.go
- pkg/events/events.go
The exact problem is described at:
https://github.com/aquasecurity/tracee/issues/2739#issuecomment-1503605814
And a "prove" that this PR fixes the issue is at:
https://github.com/aquasecurity/tracee/issues/2739#issuecomment-1507142356
```
$ sudo cp /usr/bin/nc /usr/bin/othernc
$ sudo ./dist/tracee-ebpf --output format:json --filter event=net_packet_ipv4 --filter comm=othernc
$ othernc -4 -l 8080 &
$ dd if=/dev/zero bs=1024 count=1 | nc -i 5 -q 2 localhost 8080
```
And observe the pacotes in both: wireshark and tracee output. Each existing packet in wireshark should be described as one net_packet_ipv4 event in tracee output.
commit 5b082b40 (HEAD -> rafaelchanges, rafaeldtinoco/rafaelchanges)
Date:   Tue Apr 11 14:57:57 2023
network: …
> Important Network Fixes for Tracee

- .github/workflows/debug-shell.yaml
- tests/remotessh.sh
commit 8913fc09 (HEAD -> debug-shell, rafaeldtinoco/debug-shell)
Date:   Tue Apr 18 10:15:10 2023
workflow: introduce distro image debug shell
This commit introduces a workflow that makes possible triggering a VM
debug shell, to be ssh'ed to, that allows a developer to debug
development issues happening on specific kernel versions. With that,
the developer has the same environment used on PR tests, provisioned
so they can fix issues more easily.
The workflow shall be triggered manually whenever a debug shell is
needed, and the provisioned VM should be shutdown at the end of its
usage. Provisioning VMs require repository write access so, engineers
that have only triage permissions should ask maintainers for debug
shells.
> Enable a Debug Shell for Test Runners

- go.mod
- go.sum
This is needed after Tracee types JSON unmarshalling fixes.
> types: update tracee to use latest types

- pkg/ebpf/tracee.go
Fix a bug related to the context saved on the `print_mem_dump` event.
fix #2993 
run `dist/tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=execve,kill` and see if there are errors
> fix multiple symbols prints bug
